__tests__/cookie-functions.test.js, src/javascripts/cookie-functions.js
Closes #1615.
Why
---
If we are likely to move to a sub-domain consent approach in the future, we will need to 'reset' the cookie banner and consent cookie for users who have previously consented as what they have consented to has now
changed. This also applies if in the future we add a new cookie category or important new cookie.
What
-----
This PR adds a version number as a property to the cookie preferences object, and the function `resetCookies`.
The theory is that consumers of this code will check the cookie preferences object version on load, and if the version is incorrect, delete all cookies using `resetCookies`.
=> Add versioning to consent cookie

package-lock.json, package.json
Closes #1730.
Bumps [govuk-frontend](https://github.com/alphagov/govuk-frontend/) from 3.12.0 to 3.13.0:
- [Release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v3.13.0)
- [Changelog](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md)
- [Commits](https://github.com/alphagov/govuk-frontend/compare/v3.12.0...v3.13.0)
=> Bump govuk-frontend from 3.12.0 to 3.13.0

src/styles/page-template/index.md.njk
Fixes [#1709](https://github.com/alphagov/govuk-design-system/issues/1709).
This PR adds a `scriptNonce` option to the [options table in our Page template guidance](https://design-system.service.gov.uk/styles/page-template/#options).
We've added this option because users need to know what else to use, if they cannot follow our recommended approach and [include the SHA hash in their Content Security Policy (CSP)](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#select-and-initialise-part-of-a-page).
This PR also adds content to remind users they should provide nonces that are hard to guess. Otherwise, hostile actors can easily bypass the nonce.
=> Add `cspNonce` option to Page template guidance

src/components/checkboxes/index.md.njk, src/components/checkboxes/with-none-option-in-error/index.njk, src/components/checkboxes/with-none-option/index.njk
This updates the GOV.UK Design System website with guidance on the use of a "None of these" option for the Checkboxes component.
➡️ [Preview of the Checkboxes component with new guidance](https://deploy-preview-1535--govuk-design-system-preview.netlify.app/components/checkboxes/)
Uses a pre-release version of `govuk-frontend`, currently open as [PR #2151](https://github.com/alphagov/govuk-frontend/pull/2151).
NOTE: Do not merge until the `govuk-frontend` PR has been merged and released, and then update this PR to use the released version.
=> Add guidance for divider and "none of these" to Checkboxes component

src/javascripts/components/tabs.js, src/stylesheets/components/_tabs.scss, views/partials/_example.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/1653
- Removes the `role="tab"` attribute from the code example "tabs" (actually more of an accordion) on mobile
- Progressively enhances the mobile accordion links into buttons when JavaScript is available
- Replace CSS element selectors with classes for the mobile accordion links/buttons
When running the Lighthouse accessibility audit, the tabs for HTML and Nunjucks on mobile were flagged because they
used `role="tab"` without being nested within a parent element with `role="tablist"`.
The 'tabs' on mobile actually behave more like an accordion and it's not possible to nest them within `ul` and `li` elements,
so it made more sense to remove `role="tab"`.
Because the 'tabs' on mobile don't actually link anywhere when JavaScript …
=> Remove role="tab" from mobile tabs and progressively enhance to button

src/index.njk, src/stylesheets/components/_masthead.scss, src/stylesheets/main.scss, views/partials/_whats-new.njk
Add a what's new banner and a sign-up form journey to the GOV.UK Design System homepage. Replaces pull request #1670
=> Add sign up journey

views/partials/_whats-new.njk
Replace straight apostrophe with curly apostrophe.
This doesn't happen automatically here because smart quotes are handled by the Markdown parser in our pipeline, which treats this block as HTML and doesn't touch it.
Thanks to @joelanman for spotting this bug.
=> Fix apostrophe in what's new

views/partials/_whats-new.njk
This change constrains the Whats new section to a 2/3 column, which follows the [guidance we recommend for main content](https://design-system.service.gov.uk/styles/layout/#grid-system).
> Your main content should always be in a two-thirds column even if you’re not using a corresponding one-third column for secondary content.
=> Change width of what's new column

src/accessibility.md.njk
Update accessibility statement, after research and added guidance to mitigate issues with conditional reveals.
Added guidance in:
- [checkboxes component](https://design-system.service.gov.uk/components/checkboxes/#conditionally-revealing-a-related-question)
- [radios component](https://design-system.service.gov.uk/components/radios/#conditionally-revealing-a-related-question)
=> Remove conditional reveals as a WCAG 2.1 non-compliance

src/styles/typography/index.md.njk
email.com is a real domain, so shouldn't be used in documentation, as any example email address could actually be real. example.com is reserved for documentation, per https://www.iana.org/domains/reserved. name@example.com is already used on the email addresses pattern page
=> Replace example email address

src/stylesheets/components/_phase-banner.scss
Closes https://github.com/alphagov/govuk-design-system/issues/1595
Remove left and right padding from the phase banner on mobile.
The content within the phase banner on mobile has left and right padding applied. This means the content within the banner does not line up with other content on the page that is within an app-width-container element.
The app-width-container class means the padding isn't actually needed, so we can remove it on mobile. There is already no padding on desktop.
=> Align the phase banner content to app-width-container on mobile

src/javascripts/cookie-functions.js
We want to support IE10 and below, which do not support the ES6 `const` keyword.
I thought our uglifier (metalsmith-uglify) would remove const, but it does not. We would need an additional tool to do so.
So rather than making our system more complicated, lets just get rid of the const declarations.
Thanks to @vanitabarrett for flagging this up.
=> Replace const with var

src/components/checkboxes/conditional-reveal/index.njk, src/components/error-summary/linking/index.njk, src/components/fieldset/address-group/index.njk, src/components/radios/conditional-reveal/index.njk, src/get-started/labels-legends-headings/legend-h1/index.njk, src/get-started/labels-legends-headings/legend-m-s/index.njk, src/patterns/bank-details/default/index.njk, src/patterns/equality-information/date-of-birth/index.njk, src/patterns/equality-information/error-date-of-birth/index.njk, src/patterns/question-pages/date-of-birth/index.njk, src/patterns/question-pages/postcode/index.njk, src/styles/spacing/input-width/index.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/1151
Audit of the following components in examples in the design system, to make sure they have appropriate autocomplete attributes:
- govukInput
- govukTextarea
- govukDateInput
We recommend using the `autocomplete` attribute in our [guidance](https://design-system.service.gov.uk/components/text-input/#use-the-autocomplete-attribute), so we should use it (where appropriate) in our examples.
=> Audit autocomplete attribute use in examples

src/patterns/equality-information/error-ethnicity/index.njk, src/patterns/equality-information/ethnic-group/index.njk
**What**
Fixed typo in the spelling of `Caribbean` on the Equality Information page
**Why**
Because it is a typo.
=> Updated a typo in the spelling of Caribbean

src/styles/layout/common-two-thirds-one-third/index.njk, src/styles/layout/index.md.njk
Closes https://github.com/alphagov/govuk-design-system/issues/741
Changes "Row 2: Two-thirds / One-third" to "Row 2: Two-thirds / one-third"
It should be sentence case to be consistent with other instances on the page and generally with other Design System content
=> Fix title case on layout page

src/index.njk, src/stylesheets/components/_phase-banner.scss, views/partials/_banner.njk
The bottom border on the banner ends up butting up against the top of the masthead on the homepage at the mobile viewport. As it’s inset with the grid gutter it does not span the full width of the masthead, so this looks a bit odd.
Remove the bottom border from the phase banner from the homepage page only, by setting a `masthead` boolean in the frontmatter.
Fixes #1612
=> Remove border from banner on homepage

__tests__/mobile-navigation.test.js, src/javascripts/components/mobile-navigation.js, src/stylesheets/components/_mobile-navigation.scss, views/partials/_mobile-navigation.njk, views/partials/_subnav.njk
Restructure the sub navigation and mobile navigation heading structure so that it still makes sense with the addition of a cookie banner to the site (being added in https://github.com/alphagov/govuk-design-system/compare/cookie-banner?expand=1)
This PR:
- Changes the existing sub navigation and mobile navigation headings from `h4` to `h3` - there is no visual change
- On desktop, add a visually hidden `h2` so that the sub navigation `h3` headings are nested beneath it. 
- On mobile with JavaScript enabled, the existing mobile navigation has links which expand to reveal more content underneath (including `h3` headings). Wrap the mobile navigation link text within a `h2` heading.
- On mobile with JavaScript disabled, the existing mobile navigation does not expand to reveal more content - it …
=> Add headings to subnav and mobile navigation

src/javascripts/components/tabs.js
Replaces one instance of `classlist = ` with `classlist.add()` in tabs.js
Assignment to read-only properties is not allowed in strict mode
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
=> Make sure we use classlist.add

src/community/backlog/index.md.njk
Fixes [#1778](https://github.com/alphagov/govuk-design-system/issues/1778).
This PR adds a link from the [Design System site's Community Backlog page](https://design-system.service.gov.uk/community/backlog/) to [our Community Backlog board on GitHub](https://github.com/alphagov/govuk-design-system-backlog/projects/1).
Hopefully, this will make it easier for users to navigate between both of these places.
=> Link Backlog page to GitHub Community Backlog

src/cookies.njk
Add a sentence to the cookies page that is only shown when users visit the page using IE8 or below
The cookie banner and cookies form is hidden on IE8 and below. We want to add a sentence to the cookies page when users are using these versions, to explain that the information on the page doesn't apply to them.
Note: we're hiding the cookie banner and cookies form on IE8 and below, because the Google Tag Manager script is officially not supported on these versions.
=> Add IE8 sentence to cookies page

src/components/checkboxes/index.md.njk, src/patterns/question-pages/index.md.njk
Add a sentence to Checkboxes components to tell service teams to consider alternatives to the 'None of these' component, as it may not be the best option for some questions.
1/7/2021: Decision to add an explanation of a 'guard' question and link to it as part of this message.
Community and working group says that it is important to acknowledge that there are several ways of dealing with the 'none of the above' case and we ought to urge designers to consider different options.
Content designer, Designer
Discussions in the backlog for [Checkboxes](https://github.com/alphagov/govuk-design-system-backlog/issues/37) component.
=> Mention alternatives to 'none' checkbox option

src/accessibility.md.njk
Fixes [#1792](https://github.com/alphagov/govuk-design-system/issues/1792).
Following the [release of the latest version of the Tech Docs Template](https://github.com/alphagov/tech-docs-gem/blob/master/CHANGELOG.md#240), there is only one remaining issue making our Frontend docs site non-compliant with WCAG:
- When a user searches, the search results dialogue hides the main page region from assistive technology. This fails [WCAG 2.1 success criterion 2.4.3 Focus Order.](https://www.w3.org/TR/WCAG21/#focus-order) and [WCAG 2.1 success criterion 3.2.2 - On Input](https://www.w3.org/TR/WCAG21/#on-input).
This PR updates our [accessibility statement](https://design-system.service.gov.uk/accessibility/#non-accessible-content) to say:
- there is a non-compliant issue (instead of issues)
- when …
=> Update accessibility statement re last TDT issue

__tests__/cookie-functions.test.js, package.json, src/cookies.njk, src/javascripts/components/cookie-functions.js, src/javascripts/components/cookies-page.js
There are a couple of related changes included in this PR:
- Make sure all code that deletes cookies sets the expiry to `Thu, 01 Jan 1970 00:00:00 GMT` rather than using `new Date()` which does not consistently work
- Move the above logic for cookie deletion to the `deleteCookie()` function, to be consistent
- Refactor `COOKIE_CATEGORIES` to lookup via category (e.g: 'analytics') rather than by cookie name (see individual commit for more details)
- Add `_gat_UA` cookies to the allow list
- Fixes to test setup to support the above changes: setting the testURL to a value other than localhost; making the logic which deletes cookies in the `afterEach` more generic so we don't need to manually update it each time a new cookie is added to the allow list.
Analytics cookies were being set to …
=> Analytics cookies are deleted and disabled when consent removed

__tests__/cookie-banner.test.js, __tests__/cookies-page.test.js, src/javascripts/components/cookies-page.js
The [MDN page for FormElement.elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/elements) states that it is fully supported by IE. However, in IE, FormElement.elements returns a HTMLCollection rather than a RadioNodeList, which means we can't use RadioNodeList.value to check or set the radio button values.
This was leading to a bug where the radio buttons in the cookies forms were not being preselected, and the values were not being correctly set.
Instead of relying on the elements being returned as a RadioNodeList:
- use `querySelector` and the `:checked` selector to find radio buttons which have been selected already
- use `querySelector` and the `[name]` and `[value]` selectors to find the right radio button to select
=> Replace use of FormElements.elements and RadioNodeList.value to support IE

src/accessibility.md.njk, src/community/resources-and-tools/index.md.njk, src/components/character-count/index.md.njk, src/components/checkboxes/index.md.njk, src/components/table/index.md.njk, src/design-system-team.md.njk, src/get-started/extending-and-modifying-components/index.md.njk, src/patterns/bank-details/index.md.njk, src/patterns/contact-a-department-or-service-team/index.md.njk, src/privacy-policy.md.njk
We should try and use relative URLs in links where possible, so that review apps don't send users to the production app.
A few absolute links to the Design System website have snuck in over time, this PR replaces them with relative links by removing the `https://design-system.service.gov.uk` part.
=> Replace absolute links to self with relative links

__tests__/accessiblity_audit.test.js
Fixes the accessibility audit tests so we can exclude multiple different selectors from tests. Previously the selector
`.app-phase-banner__wrapper` was in the list of things to exclude, but was not being excluded (see [comment from @hannalaakso in PR #784][1]).
This change is needed to be able to bump `axe-core` or `@axe-core/puppeteer`.
It isn't clear from the `axe-puppeteer` documentation, but `AxePuppeteer.exclude` accepts only one argument, which is either a string or a list of strings. If a list of strings is provided, this is used to select an element within an iframe [[2]]. So to exclude several different elements, we need to call `.exclude` multiple times.
The easiest way to call `.exclude` multiple times for each test is to create a function (replacing the `thingsToExclude` …
=> Fix excludes for accessibility audit tests

views/partials/_cookie-banner.njk
Add app-width-container to cookie confirmation to ensure that the confirmation message lines up with the crown in the header. The app-width-container class has already been applied to the cookie message
=> Add app-width-container to cookie confirmation

src/components/radios/index.md.njk
Clarified that 'inline' means horizontal arrangement and 'stacked' means vertical arrangement.
Clarified that description of horizontal arrangement in guidance is not a recommendation to use it for a single question.
Clarified that setting for horizontal arrangement will not be respected in mobile view or narrow page view.
=> Update guidance on radios

views/layouts/_generic.njk
The [addition of an inline script](https://github.com/alphagov/govuk-design-system/pull/1775/commits/6858861f4f599176160359cd5927420fd0cc0e2a) to the `cookie-banner.njk` file to help with Cumulative Layout Shift means that the banner is still being shown in Internet Explorer 8 and below.
This PR wraps the inline script in a conditional which checks the browser is Internet Explorer 9 or above before running the inline script, to hide the banner on IE8 and below. This uses a "downlevel" conditional comment ([read more here](https://www.sitepoint.com/internet-explorer-conditional-comments/)) which means the HTML content inside the conditional is revealed to browsers that don’t support conditional comments, because the conditional statements - and only the conditional statements - are …
=> Wrap the cookie banner inline script in an IE conditional

src/cookies.njk
Correct the name of our design_system_cookies_policy cookie on the cookies page.
=> Correct the cookie consent name on /cookies

src/patterns/telephone-numbers/index.md.njk
A UK country code cannot be followed by zero. Number has now been corrected. The standard followed by BT is https://www.itu.int/rec/T-REC-E.123-200102-I/en
=> Corrected phone number

__tests__/cookie-banner.test.js, __tests__/cookie-functions.test.js, __tests__/cookies-page.test.js, src/javascripts/components/cookie-functions.js
Changes the deleteCookie function to handle deleting cookies with and without the domain specified. This is to make sure the deleteCookies function continues to work even if changes are made to the way we set cookies (for example: in Google Tag Manager - see below)
Cookies need to be deleted in the same level of specificity in which they were set.
You can't tell if a cookie was set with a domain attribute or not, so try both options
Previously, we set the Google Analytics cookieDomain property to 'auto' which caused
an issue in Internet Explorer where the cookies were set on service.gov.uk. We then set
the cookieDomain property to 'design-system.service.gov.uk' or the output of {{Page Hostname}}
in Google Tag Manager for preview apps. However, this actually means the analytics cookies are …
=> Delete cookies with and without domain

src/components/index.md.njk
Fixes [#1810](https://github.com/alphagov/govuk-design-system/issues/1810).
This PR adds info to the [Components page on the main Design System site](https://design-system.service.gov.uk/components/).
It tells users:
- that our code is public and available under an MIT license
- where they can find our repos
I also replaced some instances of the passive voice, to make the text more direct.
We're adding this info because a user reported they'd had to dig around before they found out we use MIT. See [#1810](https://github.com/alphagov/govuk-design-system/issues/1810) for full details.
Other gov teams have previously added similar info to their sites. For example, [data.gov.uk](https://guidance.data.gov.uk/support/contribute/) and [Verify](https://www.docs.verify.service.gov.uk/open-component …
=> Add MIT license and GitHub info to Components page

src/styles/colour/index.md.njk
Fixes [#1816](https://github.com/alphagov/govuk-design-system/issues/1816).
This PR removes mentions of "graphs" from our [Colour guidance](https://design-system.service.gov.uk/styles/colour/).
We've also given examples (illustrations, custom components) of what users should use colour for.
A user (see [#1814](https://github.com/alphagov/govuk-design-system/issues/1814)) asked if we designed the palette with graphs in mind. The guidance suggests we have:
> Use these colours for graphs and supporting material.
> For example, if you wanted to use red to represent some data in a graph you should use govuk-colour("red")` rather than `$govuk-error-colour`.
It is possible to use the colours for graphs, but we have not provided them for that purpose.  That's why they do not have enough contrast …
=> Remove graph mentions from Colour guidance

src/design-system-team.md.njk
- Update my role
- Mark Vanita as the tech lead 🎉 
- Tweak Tim's role description for consistency
- Ensure the GDS acronym is defined before it's used in Tim's role
=> Update team page with recent changes

.github/ISSUE_TEMPLATE/tech-debt.yaml
Adds a GitHub issue form [[1]] for tracking tech debt in the manner encouraged by the GDS Way [[2]].
The form YAML is copied from alphagov/govuk-frontend#2302.
This should make it slightly easier to add tech debt tickets to the repo.
[1]: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
[2]: https://gds-way.cloudapps.digital/standards/technical-debt.html#example
=> Add tech debt issue form

src/components/accordion/index.md.njk
Fixes [#747](https://github.com/alphagov/govuk-design-system/issues/747).
In the [Accordion, tabs and details section of our accordion guidance](https://design-system.service.gov.uk/components/accordion/#accordions-tabs-and-details), we've changed:
> The details component might be better if you only have one or 2 sections of content.
to
> The details component might be better if you only have one or two sections of content.
The ['Numbers' section of the style guide](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#numbers) states:
> Write all other numbers in numerals (including 2 to 9) except where it’s part of a common expression like ‘one or two of them’ where numerals would look strange.
=> Write out accordion guidance numbers in full

src/patterns/addresses/index.md.njk, src/patterns/equality-information/explainer-screen/index.njk, src/patterns/question-pages/index.md.njk
This PR is (probably) the last instalment in my quest to rid Design System content of negative contractions.
We avoid negative contractions in content because [some users struggle with them](https://readabilityguidelines.co.uk/grammar-points/contractions/#1-avoid-negative-contractions).
=> Replace negative contractions in Patterns guidance

__tests__/search.test.js, src/javascripts/components/search.js, src/javascripts/components/search.tracking.js
Adds search tracking back into the Design System website, as we have now fixed the issue around consent that necessitated its removal in #1106.
This reverts commit 86cc4493549f4d97edfd1680d634e17b6fe09939.
=> Add search tracking

src/patterns/check-answers/index.md.njk, src/styles/layout/index.md.njk
Fixes [#1290](https://github.com/alphagov/govuk-design-system/issues/1290).
This PR updates:
- our [check answers guidance](https://design-system.service.gov.uk/patterns/check-answers/) with advice to help users choose the right page-width.
- our [Layout guidance](https://design-system.service.gov.uk/styles/layout/) to specify what layout and line length we recommend
[A user reported they have services where using a full width page would work better.](https://github.com/alphagov/govuk-design-system-backlog/issues/36#issuecomment-619137375) They also shared other users' feedback, which has informed the content in this update.
=> Add width layout advice to Check answers guidance

src/styles/colour/index.md.njk
Addresses [#1304](https://github.com/alphagov/govuk-design-system/issues/1304).
We've replaced a link to an external site with a link to our [Sass API Reference docs](https://frontend.design-system.service.gov.uk/sass-api-reference/).
Three users on Slack (convo now unavailable) told us they'd had difficulty navigating to our Sass docs from the Design System site.
They also pointed out that the link from the text "[Sass variables](https://sass-lang.com/guide#topic-2)" is to Sass' own content on variables - and not, as they'd expected, to our Sass docs.
=> Link Colour guidance to Frontend Sass docs

src/index.njk
Replaces email address on homepage with link to 'Get in touch' page
=> Remove email address from homepage

src/components/back-link/index.md.njk
Fixes [#1847](https://github.com/alphagov/govuk-design-system/issues/1847).
This PR tells users why they should use a back link component, even though browsers already contain a back button.
=> Add user need to Back link page

src/styles/typography/index.md.njk
Fixes [#1076](https://github.com/alphagov/govuk-design-system/issues/1076).
This PR adds a 'When not to use the GDS Transport font' heading to our [Typography content](https://design-system.service.gov.uk/styles/typography/#font). It also replaces an old link with a more helpful link.
Currently, if users want to find out about restrictions, we direct them to the [Service Manual's 'Making your service look like GOV.UK' guidance](https://www.gov.uk/service-manual/design/making-your-service-look-like-govuk). However, the correct location is actually the same page's ['If your service isn't on GOV.UK' subsection](https://www.gov.uk/service-manual/design/making-your-service-look-like-govuk#if-your-service-isnt-on-govuk). Several users have struggled to find this info.
=> Tell users when not to use GDS Transport font

package-lock.json, package.json
Changelog from govuk-frontend:
> Fixes
> We’ve made fixes to GOV.UK Frontend in the following pull requests:
> 
> #2264: Improve focus state for radio and checkbox controls in forced colors mode (for example, Windows High Contrast Mode) – thanks to @adamliptrot-oc for reporting this issue
> #2265: Do not remove focus outline from disabled link buttons in forced colors mode
> #2273: Fix invisible footer on Open Government Licence logo in forced colors mode – thanks to @oscarduignan for reporting this issue
> #2277: Fix invisible start button chevron in forced colors mode
> #2290: Improve support for Internet Explorer 11 with Windows High Contrast Mode
> #2306: Add max-width to file upload component
> #2312: Remove padding-right from details component
=> Update to govuk-frontend 3.13.1

.github/workflows/ci.yaml
Should close https://github.com/alphagov/design-system-team-internal/issues/446 (hopefully).
We want to make sure only merges to main can deploy to PaaS, so we've created a [GitHub Actions environment][1] that contains the production secrets with the necessary protection rules.
This commit sets the job environment to the new `production` environment, so the job can use the new secret.
[1]: https://docs.github.com/en/actions/reference/environments
=> Update deploy job to use production environment

package.json
I missed this from #1865 :disappointed:
We need to also bump and relax the constraint on Node in the package.json file, to avoid command line warnings.
=> fixup! Bump default Node.js to 14.17.6

src/patterns/equality-information/error-date-of-birth/index.njk
Fixes [#1867](https://github.com/alphagov/govuk-design-system/issues/1867).
This PR updates the error message's text in the 'What is your date of birth?' example on our [equality information page](https://design-system.service.gov.uk/patterns/equality-information/).
We're replacing the previous text, "Enter a real date of birth, or leave it blank," because:
- a user pointed out that any valid date would be accepted, even if it was not the user's actual date of birth
- referring to the entry boxes as "it" is vague
=> Fix error message text in equality info example

CODEOWNERS
Part of https://github.com/alphagov/design-system-team-internal/issues/455
We need to make sure only staff can access secrets and/or deploy to production.
This commit adds a [CODEOWNERS file] to ensure that any changes to our GitHub Actions are reviewed by a developer, to avoid the (unlikely) scenario where a PR that changes our GitHub Actions is approved by someone who isn't a developer and doesn't spot the significance of the change.
[CODEOWNERS file]: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners
=> Add CODEOWNERS file to protect secrets

src/components/notification-banner/index.md.njk
Fixes [#1411](https://github.com/alphagov/govuk-design-system/issues/1411).
This PR updates our [notification banner guidance](https://design-system.service.gov.uk/components/notification-banner/) to:
- give examples of what we mean by 'page content'
- specify what we mean when we say the notification banner should be the same width as the page content
- include a link to our [layout guidance](https://design-system.service.gov.uk/styles/layout/)
We've made these changes because a user told us the previous wording was ambiguous.
=> Explain page content in notification banner guide

src/community/backlog/index.md.njk
Updated to reflect current community backlog. 
Summary of changes:
- updated status of Modal dialogue from 'in progress' to 'to do'
- updated Maps to 'in progress'
- renamed Quick exit to 'Hide this page'
- removed Service timeout as duplicate of Timeout
- added Freepost addresses
=> Update backlog on website

src/components/select/index.md.njk
Fixes [#1565](https://github.com/alphagov/govuk-design-system/issues/1565).
This PR updates our [select guidance](https://design-system.service.gov.uk/components/select/) with info about the difference between select's options and the options on [radios](https://design-system.service.gov.uk/components/radios/) and [checkboxes](https://design-system.service.gov.uk/components/checkboxes/).
We've added this info because of feedback from a user. It confused them that the select examples display pre-selected options, when the radios guidance advises against pre-selection.
=> Add preselected setting info to select guidance

src/components/cookie-banner/client-side-accepted/index.njk, src/components/cookie-banner/client-side-rejected/index.njk, src/components/cookie-banner/client-side/index.njk, src/components/cookie-banner/default/index.njk, src/components/cookie-banner/multiple-cookies/index.njk, src/components/cookie-banner/server-side-confirmation/index.njk, src/components/cookie-banner/server-side-multiple-messages-confirmation-visible/index.njk, src/components/cookie-banner/server-side-multiple-messages-question-visible/index.njk, src/components/cookie-banner/server-side/index.njk, views/partials/_cookie-banner.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/1886
Adds missing `govuk-body` classes to the design system cookie banner and the component examples.
Previously we were relying on default colour and margins for the text content within the cookie banner, when html was passed to the banner. In the yaml examples in govuk-frontend, we assume a user will add govuk-body classes to any html they pass in. However, this was missed when adding the cookie banner to the design system site and when implementing the examples shown in the cookie banner component guidance.
Adding the `govuk-body` class is an easy thing to miss because the cookie banner component adds some default text styling. We could remove this default styling to make it more obvious if a user forgets to add the …
=> Add missing `govuk-body` classes to cookie banner 

src/accessibility.md.njk, src/community/develop-a-component-or-pattern/index.md.njk
Fixes [#1798](https://github.com/alphagov/govuk-design-system/issues/1798).
This PR adds links from the Design System site to our [accessibility acceptance criteria doc](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/test-components-using-accessibility-acceptance-criteria.md).
Hopefully, these links will help contributors find the doc more easily.
We've also added some H3 headings to make the doc easier to scan.
=> Link Design System site to accessibility criteria

src/patterns/check-answers/default/index.njk
This PR replaces the word 'notification' with 'application' in the example on our [check answers page](https://design-system.service.gov.uk/patterns/check-answers/).
=> Fix wording in check answers pattern example

src/patterns/question-pages/explanatory-text/index.njk, src/patterns/question-pages/index.md.njk
New guidance to explain how to structure a question page when you need to explain the question in more depth than is appropriate for hint text. 
We've seen this come up as a discussion point on Slack a few times. We've also seen lots of examples of hint text that is too long to be read out by a screen reader every time a user focuses on the related input.
The example we used was from 'apply from teacher training'. It's quite a good one, although the explanatory text is arguably a bit on the short side. Could those sentences reasonably be hint text?
I think it's borderline. If anyone's found an example that might explain the approach better, please suggest one!
=> Add guidance on using longer supporting text for questions

src/patterns/question-pages/index.md.njk
Fixes [#1726](https://github.com/alphagov/govuk-design-system/issues/1726).
This PR adds content to our [question pages pattern](https://design-system.service.gov.uk/patterns/question-pages/).
We're adding this content because of a user-reported issue. The current wording suggests that, in contexts where a whole question is optional, users need to mark each label as ‘(optional)’. However, it's the legend they need to mark.
=> Add info about when to add 'optional' to legend

.github/workflows/ci.yaml
Use the built-in functionality provided by the setup-node GitHub Action[^1] to cache and restore dependencies.
This will enable quicker builds[^2] by caching the node_modules folder between builds, as long as the package-lock.json file hasn't changed (a hash of the file is used as part of the cache key).
[^1]: https://github.com/actions/setup-node#caching-packages-dependencies
[^2]: https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows
=> Cache npm dependencies between builds

.github/workflows/ci.yaml
We currently upload the build folder as an artifact as the last step of every successful build, so that we can use it in the deploy job.
However, the deploy job only happens if the build is running against the main branch.
We can therefore save some time for builds for pull requests and branches other than main [^1] by applying the same if condition to the step, so we only upload the build folder if we expect to be running the deploy job.
[^1]: a quick scan of the last few builds shows that uploading the artifact seems to take about 15-35 seconds, out of a total build time of 1m 30s - 2m 30s, so we'd expect to see a 15-20% reduction in build times.
=> Only save build folder as artifact if deploying

README.md
Partly addresses [#1692](https://github.com/alphagov/govuk-design-system/issues/1692).
This PR updates the [repo README](https://github.com/alphagov/govuk-design-system/blob/main/README.md) with info and link text for our [security policy](https://github.com/alphagov/govuk-design-system/security/policy).
Hopefully this will make the security policy more visible to researchers who want to report vulnerabilities.
=> Link Design System repo README to security policy

views/partials/_banner.njk
Part of https://github.com/alphagov/design-system-team-internal/issues/332.
We want it to be clear to users that when they visit v2--govuk-design-system-preview.netlify.com (or 'v3--' etc.) that what they are seeing is an old version of the Design System website.
This commit changes the phase banner for [Netlify branch deploys][1] to state that the website is an archive (rather than a preview).
Note that this applies to all branch deploys, so it might potentially cover branches that are for pull requests, but I think we only usually share branch deploys for old versions of the website.
[1]: https://docs.netlify.com/site-deploys/overview/
=> Add archive banner

package-lock.json, package.json
You can now use the `govuk-!-text-align-left`, `govuk-!-text-align-centre` and `govuk-!-text-align-right` CSS classes to set text alignment on elements.
This was added in [pull request #2368: Add `text-align` override classes](https://github.com/alphagov/govuk-frontend/pull/2368). Thanks to [Ed Horsford](https://github.com/edwardhorsford) for reporting this issue.
You can now pass the negative equivalent of a point from the spacing scale to the `govuk-spacing` function to get negative spacing.
For example, `govuk-spacing(1)` returns `5px`, and `govuk-spacing(-1)` returns `-5px`.
This was added in [pull request #2367: Allow `govuk-spacing` to output negative spacing](https://github.com/alphagov/govuk-frontend/pull/2367). Thanks to [Chris Hill-Scott](https://github.com/quis) for reporting …
=> Update to GOV.UK Frontend 3.14.0

src/styles/typography/index.md.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/1863
Add guidance for newly-added text override classes in Frontend: https://github.com/alphagov/govuk-frontend/pull/2339
Co-authored-by: @hannalaakso
=> Add guidance for text align override classes

src/components/panel/index.md.njk
Fixes [#1901](https://github.com/alphagov/govuk-design-system/issues/1901).
This PR adds content about heading text to our [Panel guidance](https://design-system.service.gov.uk/components/panel/).
We're adding this info to help users keep their heading text punchy. If they use long words, it could result in the text 'wrapping' to avoid overflowing its container.
=> Add heading text info to Panel guidance

views/partials/_whats-new.njk
Partly addresses [#2363](https://github.com/alphagov/govuk-frontend/issues/2363).
This PR updates the ['What's New' message on the Design System homepage](https://design-system.service.gov.uk/#:~:text=Get%20started-,What%E2%80%99s%20new).
It adds info about the contents of our v3.14.0 release of GOV.UK Frontend.
=> Update What's New message on DS homepage

src/components/date-input/default/index.njk, src/components/date-input/error/index.njk, src/components/date-input/without-heading/index.njk, src/components/error-message/default/index.njk
The "Dates" pattern gives specific guidance about giving user example dates: https://design-system.service.gov.uk/patterns/dates/#how-to-write-dates
However I noticed that the examples on the 'Date Input' component don't follow that guidance, so this PR updates the examples to match the guidance from the pattern.
=> Updating the hint text on the "Date Input" examples to match the "Dates" pattern guidance

src/community/roadmap/index.md.njk
This PR adds a link from [our roadmap](https://design-system.service.gov.uk/community/roadmap/) to the [most recent Frontend release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v3.14.0).
=> Add link for Frontend 3.14.0 release to roadmap

src/index.njk, src/stylesheets/components/_banner.scss, views/partials/_banner.njk
Pulls in changes to phase banner from main branch, so that the v2 deployment uses the new archive banner from https://github.com/alphagov/design-system-team-internal/issues/332.
=> Update phase banner for v2 deploy

.github/workflows/ci.yaml
We want to prevent against the GitHub Actions CI workflow being run in a circumstance that would result in old/stale/out-of-date code being deployed to production (such as happened with https://github.com/alphagov/design-system-team-internal/issues/527).
This commit adds a new job to the workflow that must complete before a deploy can take place. It contains a single step currently, which uses JavaScript to check the commit sha of the code that would be deployed against the most recent commit sha of the main branch. If this check fails, the user who started the workflow run will be notified of the failure, but we add a warning and a message explaining what has happened and asking them not to try re-running (otherwise they might end up trying to re-run it lots of times).
You can see what …
=> Add CI workflow step to prevent deployment of old code

src/components/error-message/index.md.njk, src/components/file-upload/index.md.njk, src/patterns/addresses/index.md.njk, src/patterns/bank-details/index.md.njk, src/patterns/confirm-an-email-address/index.md.njk, src/patterns/email-addresses/index.md.njk, src/patterns/national-insurance-numbers/index.md.njk, src/patterns/payment-card-details/index.md.njk, src/patterns/problem-with-the-service-pages/index.md.njk, src/patterns/service-unavailable-pages/index.md.njk, src/patterns/telephone-numbers/index.md.njk
Fixes [#1966](https://github.com/alphagov/govuk-design-system/issues/1966).
This PR will update several pages across our guidance to tell site-visitors:
- the guidance is for government teams building services
- they need to go to GOV.UK if they're looking for citizen-facing services
- Error message
- File upload
- Addresses
- Bank details
- Confirm email address
- Email addresses
- National insurance numbers
- Payment card details
- Problem with service
- Service unavailable
- Telephone numbers
[Some users have been ending up in the Design System when they want to find COVID-related services.](https://docs.google.com/presentation/d/1dIx0RQwxFovK6wAFxITZOwyn0PtgWAE_1eakodFWoxw/edit#slide=id.gf61b7945b0_0_183)
=> Tell users who guidance is for and link to GOV.UK

.github/workflows/deploy.yaml, .github/workflows/test.yaml
Split the `ci.yaml` workflow into two: `test.yaml` for pull request checks, and `deploy.yaml` for after merge to main. To reduce code duplication the deploy workflow calls the test workflow using the beta reusable workflow feature [[1]].
[1]: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
The advantage of splitting the workflows like this is that we can then give the entire deploy workflow a concurrency limit [[2]], without affecting test workflows. Having a concurrency limit is an alternative to the step which cancels any in-progress
deploys, which would have resulted in failed deployment messages.
This should make it easier to spot when a deployment fails for real, which should fix #1947.
[2]: https://github.blog/changelog/2021-04-19-github-actions-limit-workfl …
=> Refactor GitHub Actions workflows and add concurrency limit to deploys

src/components/back-link/index.md.njk
Fixes [#1231](https://github.com/alphagov/govuk-design-system/issues/1231).
This PR updates our [back link guidance](https://design-system.service.gov.uk/components/back-link/) to tell users when they should consider changing the default text ('Back')
=> Tell users when to change back link default text

README.md
Partly addresses [#2396](https://github.com/alphagov/govuk-frontend/issues/2396).
This PR updates the [govuk-design-system README](https://github.com/alphagov/govuk-design-system/blob/main/README.md), so users will know:
- the repo is open, and not monitored outside of office hours
- how to report inappropriate content
We're adding this info because of a [recent security-incident](https://docs.google.com/document/d/1-VZcvII1g9oKFi00JsiuvLE-Y0iAl-qmPeaYLzn6Fmg/edit#).
=> Tell users how to report inappropriate content

docs/logs.md
We mention the Reliability Engineering team in our Logit docs, but they're not
able to help with questions about how our data gets sent from the application through
to Logit.
For this, we should be able to ask the PaaS team who can answer our questions or
point us in the right direction.
This came up as part of investigating whether we needed to take action
for a Logit certification rotation https://github.com/alphagov/design-system-team-internal/issues/544
=> Mention PaaS in our Logit documentation

src/patterns/check-answers/index.md.njk
Fixes [#1574](https://github.com/alphagov/govuk-design-system/issues/1574).
This PR updates our check answers pattern to say that 'change' links contain hidden text. This means the links are accessible to screen reader users.
=> Tell users that change links have hidden text

views/layouts/_generic.njk
In the design system guidance for the cookie banner, we tell users to place the cookie banner before the skip to main content link using the `bodyStart` block.
However, we didn't follow our own guidance when adding the cookie banner to the design system website - the cookie banner is placed after the skip link.
We should follow our own guidance, and place the cookie banner before the skip link.
Initial research into positioning of the cookie banner: https://github.com/alphagov/govuk-frontend/issues/2096#issuecomment-767667620
=> Move cookie banner before skip link

src/stylesheets/components/_phase-banner.scss
On most pages (apart from the homepage), the parent div (`.app-pane`) is a flex container. We used to wrap the phase banner in a `div` but removed this in https://github.com/alphagov/govuk-design-system/pull/1983/commits/a04885bdca2d207d35bdaad2702970e7a4c92f9a as the class being applied to that `div` was only being used for tests.
Unfortunately, removing the `div` had the side effect of changing the positioning of the phase banner when it was inside the flex container - the phase banner appeared centred on the page.
I think this is happening because it's a child item of a flex container and it doesn't have any existing properties to say how much space it should take up, so it's only taking up the space it needs rather than the full width.
This commit sets `width: 100%;` on the phase …
=> Set phase banner width to 100% on desktop

src/styles/images/index.md.njk
Fixes [#1887](https://github.com/alphagov/govuk-design-system/issues/1887).
This PR updates our [Images guidance's section about alt text](https://design-system.service.gov.uk/styles/images/#alternative-text) to specify:
- who our guidance is for
- redirect users who want guidance about publishing mainstream content on GOV.UK
We've suggested these changes because our Images guidance did not mirror the [recently updated GDS guidance on alt text](https://www.gov.uk/guidance/content-design/images#alt-text)
=> Update Images guidance and example of alt text

src/components/summary-list/default/index.njk, src/components/summary-list/without-actions/index.njk, src/components/summary-list/without-borders/index.njk
At the minute we're using two very similar terms ('contact information' and 'contact details') to refer to two different things. This was previously flagged by DAC as confusing and failing WCAG 2.1 2.4.9: Link Purpose (Link Only) (because of the visually hidden text in the links – see #906).
This mirrors the change previously made to similar examples in the 'Help users check their answers' pattern as part of 36b3475 (#912).
=> Use 'Address' in summary list examples

src/styles/layout/index.md.njk
Big change, this one. 😛 Spotted a tiny inconsistency in the Layout guidance when I looked it up to help with reviewing a footer PR.
=> Add hyphen to mention of layout type

src/components/summary-list/index.md.njk
I've split the improvements to the summary list guidance by @calvin-lau-sig7 in #1990 out into a separate PR, so they can be reviewed separately and we can get these changes out before 4.0.
=> Improve summary list guidance

package-lock.json, package.json, src/components/character-count/threshold/index.njk, src/components/footer/full/index.njk, src/components/footer/with-navigation/index.njk, src/javascripts/govuk-frontend.js
Closes https://github.com/alphagov/govuk-design-system/issues/1851 
Updates the Design System to use v4.0.0.
**Note:** the current PR updates the Design System to use the v4.0.0 *pre-release*. This PR will need to be updated for the actual release, to point to the version of GOV.UK Frontend published on `npm`.
The Design System:
- **does not** use the `govuk-main-wrapper` or `govuk-main-wrapper--l` mixins
- **does not** use the `$govuk-border-width-form-element-error` variable
- **does not** individually import JavaScript files
- **does not** use HTML error messages
- **does not** use HTML hints
- **does not** use HTML skip link
- **does not** use `iff` Sass function
- **does not** use `govuk-tag--inactive` class
- **does not** import individual Sass files from `core` or `overrides`
- …
=> Update to GOV.UK Frontend v4.0.0

src/components/summary-list/index.md.njk, src/components/summary-list/mixed-actions/index.njk
**The guidance will not match the HTML in the example until updated to GOV.UK Frontend v4.0 with the changes from https://github.com/alphagov/govuk-frontend/pull/2323.** Do not merge until after the Design System has been updated to 4.0.
The example also takes into account changes to the other existing examples made in #1989, which has not yet been merged.
Closes #1948.
=> Add a summary list example where only some rows have actions

src/accessibility.md.njk
Fixes [#1823](https://github.com/alphagov/govuk-design-system/issues/1823).
This PR removes mention of an accordion-affecting [WCAG issue](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships) from the [non-compliance section of our accessibility statement](https://design-system.service.gov.uk/accessibility/#non-compliance-with-the-accessibility-regulations).
We've also removed some redundant text to avoid a clumsy repetition.
The iterated accordion component will fix the accessibility issue.
=> Delete accordion issue in accessibility statement

src/components/accordion/index.md.njk, src/components/details/index.md.njk, src/components/tabs/index.md.njk
This PR for the updated accordion guidance moves on from the [working Google Doc](https://docs.google.com/document/d/1lzOfwpwPKsfNqzO9gsu851sWPUTCeSwdTaOzi75faMc/edit?usp=sharing).
=> Update accordion guidance for v4.0.0

views/partials/_whats-new.njk
Partly fixes [#2331](https://github.com/alphagov/govuk-frontend/issues/2331).
This PR updates our landing page's 'What's new' message with info about the 4.0 additions (accordion iteration, footer fixes).
Please do not merge until we've done the release.
=> Update What's new message for v4.0

src/components/breadcrumbs/index.md.njk, src/styles/page-template/index.md.njk
Fixes [#1350](https://github.com/alphagov/govuk-design-system/issues/1350).
This PR updates our breadcrumbs guidance so users will know to place breadcrumbs at the top of a page, before the `<main>` element. This means the 'Skip to main content' link lets users skip all nav links (like breadcrumbs).
We're also adding a breadcrumbs link from the page template guidance.
=> Tell users where to put breadcrumbs on page

views/partials/_contact-panel.njk
Fixes [#1998](https://github.com/alphagov/govuk-design-system/issues/1998).
This PR rewords some link text that's on our component and pattern pages.
Several users have pointed out that the current link text ("share your research or feedback on GitHub") does not reflect why they visit the discussion pages.
=> Improve link text from Design System to GitHub

src/stylesheets/main.scss, views/layouts/layout-example-full-page-govuk.njk, views/layouts/layout-example-full-page.njk, views/layouts/layout-example.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/2008
- Update the `layout-example.njk` template to use the GOV.UK Frontend page template instead of hard coding it. This means we don't have to hardcode a link to the favicon (which is missing at the moment) and we also get other `<head>` tags automatically, e.g: social sharing image.
- Update other layouts to make sure they have the correct `assetUrl` set.
Anything using `layout-example` (for example, [tabs](https://design-system.service.gov.uk/components/tabs/default/index.html)) had a missing favicon and no social share image.
Anything using a layout with a missing `assetUrl` had a missing social share image as the asset could not be found (for example, [question pages](https://design-system.service.gov.uk/patterns/question-pa …
=> Fix missing favicon for component examples

src/components/accordion/index.md.njk
Partly addresses [#1443](https://github.com/alphagov/govuk-design-system/issues/1443).
This PR updates the accordion guidance about setting up whether the sections are open.
Some users said they were confused that the accordion had not retained their changes when they refreshed the page. However, the accordion only 'remembers' changes made within a single session, for example, when users nav back to the page via their browser.
=> Add session storage info to accordion guidance

src/patterns/task-list-pages/have-you-completed-this-section-error/index.njk, src/patterns/task-list-pages/have-you-completed-this-section/index.njk, src/patterns/task-list-pages/index.md.njk
This adds some guidance to the Task List pattern about how tasks can get marked as complete.
It recommends giving the user control over whether to mark the section as complete in a list of different scenarios, and suggests doing this via a Radio button question. Radios are recommended over checkboxes as they require a user to actively answer the question, preventing them from accidentally leaving the task as incomplete if they miss the question.
The guidance was developed by the Task List collaboration group.
=> Task list: Section on marking tasks as complete

src/design-system-team.md.njk
Owen Jones (me!) started with the design system team today. This adds my name to the [design system team](https://design-system.service.gov.uk/design-system-team/) page.
=> Add Owen Jones to the design system team page

src/components/character-count/index.md.njk
Fixes [#1969](https://github.com/alphagov/govuk-design-system/issues/1969).
Updates the character count guidance to tell users it counts emojis and accented characters as more than one character. 
This behaviour might confuse users, if they think an emoji or accented character = 1 character, and the count ends up higher than they expected.
=> Tell users about emoji and accent effect on count

src/patterns/task-list-pages/index.md.njk
Minor edit to pace full stops outside of single quotes, as they're not complete sentences (which would put the full stop inside the quotes).
Single quotes (') might need work to turn into 'curly quotes' (‘’), but I think they're changed automatically.
=> Place full stops outside of single quotes

__tests__/accessiblity_audit.test.js, __tests__/back-to-top.test.js, __tests__/component-options.test.js, __tests__/cookie-banner.test.js, __tests__/cookies-page.test.js, __tests__/example.test.js, __tests__/mobile-navigation.test.js, __tests__/search.test.js, __tests__/tabs.test.js, jest-puppeteer.config.js, lib/file-helper.js, lib/generate-sitemap.js, lib/get-macro-options/__tests__/index.js, lib/get-macro-options/index.js, lib/metalsmith-title-checker.js, lib/metalsmith.js, lib/modernizr-build.js, lib/navigation.js, lib/paths.js, tasks/serve.js, tasks/test-serve.js
This adds support for building, testing and running on Windows. Tested on Windows 11 (Windows Terminal with [nvm-windows](https://github.com/coreybutler/nvm-windows)) and Ubuntu, macOS test TBD.
The main change is replacing the requires for `config/paths.json` with `lib/paths.js` that returns a _path.normalize_'d version of the paths object. Replaced instances of `blah + '/'` or `blah + blah2` with `path.join(blah, blah2)` as `path` handles the OS support, meaning the correct joins are returned.
Tested:
- `npm install`
- `npm run lint`
- `npm run test`
- `npm run build`
- `npm start`
Related issues:
- https://github.com/alphagov/govuk-design-system/issues/694
- https://github.com/alphagov/govuk-design-system/issues/598
~Keeping in draft until tested on macOS, but making as a PR for others …
=> Initial Windows support

.github/workflows/test.yaml
We want to be able to support developers using Windows [[1]]. This commit adds a build matrix for PR checks that includes running tests on Windows as well as Linux, so that we can be more confident that any future changes won't break Windows support.
Note that we have to tweak the upload artifact step to only upload if running on Linux, to avoid uploading the artifact twice. We're not sure what would happen if we didn't change this, but we suspect that it wouldn't be good [[2]].
[1]: #598
[2]: https://github.com/actions/upload-artifact#uploading-to-the-same-artifact
---
Outstanding:
=> Run PR checks on Windows as well as Linux

.github/workflows/deploy.yaml
GitHub have now [made it possible to reference other workflows locally][1], rather than needing to specify the repo and version.
Update the deploy workflow, which 'uses' the test workflow, to adopt this new, simpler approach.
[1]: https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
=> Reference test workflow locally

src/components/radios/conditional-reveal-error/index.njk, src/components/radios/index.md.njk
Fixes [#863](https://github.com/alphagov/govuk-design-system/issues/863).
This PR updates our [radios guidance](https://design-system.service.gov.uk/components/radios/#error-messages) to tell users how to add an error message to a conditionally revealed question.
We're adding this content because users occasionally ask about this issue. For example, in the [radios discussion](https://github.com/alphagov/govuk-design-system-backlog/issues/59#issuecomment-485774915) and on the [original issue](https://github.com/alphagov/govuk-design-system/issues/863#issuecomment-723126530) itself.
=> Add guidance for conditional reveal error messages

src/patterns/addresses/index.md.njk, src/patterns/addresses/multiple/index.njk
Royal Mail states county is not required for delivering mail. The Royal Mail address finder provides a correct address to customers and this does not contain county https://www.royalmail.com/find-a-postcode
**Royal Mail states:**
- _“There is no need to include a county name, your letters and parcels will reach your intended recipient without one.”_ https://personal.help.royalmail.com/app/answers/detail/a_id/81/~/how-to-address-your-mail-%28clear-addressing%29
- _“The county is not required as part of a correct postal address.”_ https://www.poweredbypaf.com/wp-content/uploads/2015/02/Latest-Programmers_guide_Edition-7-Version-6.pdf
- _“County data was removed from the core PAF files over ten years ago, has not been actively maintained and is not needed for delivery purposes”_ (dated 2017) …
=> Removed county field

src/components/error-summary/default/code.njk, src/components/error-summary/full-page-example/code.njk, src/components/error-summary/full-page-example/index.njk, src/components/error-summary/index.md.njk, src/components/error-summary/linking-checkboxes-radios/code.njk, src/components/error-summary/linking-checkboxes-radios/index.njk, src/components/error-summary/linking-multiple-fields/code.njk, src/components/error-summary/linking-multiple-fields/index.njk, src/components/error-summary/linking/code.njk, src/components/error-summary/linking/index.njk, src/javascripts/govuk-frontend.js
Fixes https://github.com/alphagov/govuk-design-system/issues/1666
**Note: this PR uses a pre-release of GOV.UK Frontend. The first commit will need to be deleted before merging.**
Replaces the JavaScript override of the error summary `init` function with the new `disableAutoFocus` macro option instead.
Doing this means we have to introduce `code.njk` files for our error summary component examples, so that users viewing the HTML and Nunjucks code examples don't see the `disableAutoFocus` macro option/data attribute being set and accidentally copy that into their own service.
There should be no visual/behavioural changes as a result of this PR.
- The visual examples on the error summary page (or anywhere else they're used on the Design System website - I couldn't find any other uses) …
=> Remove error summary override `init` function

src/components/text-input/index.md.njk
Fixes [#1857](https://github.com/alphagov/govuk-design-system/issues/1857).
This PR updates our text input guidance.
The current guidance suggests certain characters are not allowed, which conflicts with our guidance elsewhere. Not allowing characters can be discriminatory.
=> Tell users to support necessary characters

src/patterns/create-a-username/index.md.njk
Fixes [#2055](https://github.com/alphagov/govuk-design-system/issues/2055).
This PR updates our 'Create a username' pattern.
=> Tell users to accept caseless input for usernames

lib/extract-page-headings/index.js, lib/get-macro-options/index.js, package-lock.json, package.json
[This dependabot bump](https://github.com/alphagov/govuk-design-system/pull/2020) is failing because we need to update some `require` statements, since `marked`'s default export was removed in 4.0.0.
https://github.com/markedjs/marked/releases/tag/v4.0.0
=> Bump marked to 4.0.10

src/stylesheets/components/_mobile-navigation.scss, src/stylesheets/components/_navigation.scss, src/stylesheets/components/_subnav.scss
Our ‘standard’ links turn darker blue on hover:
This CSS is currently overriding that behaviour so that the links _do not_ change colour on hover.
This was [discussed when we first introduced the new link styles to the Design System][1]. It seems like we were mainly looking to preserve the existing behaviour, but it’s not clear that this is desirable and nobody knew of any reason why the links shouldn’t get darker on hover.
Remove the overrides so that the navigation links are consistent with other links across the Design System.
| Navigation element | Before | After |
| -- | -- | -- |
| Top nav | ![Screenshot 2022-02-16 at 17 37 42](https://user-images.githubusercontent.com/121939/154324815-9acb75f7-87b5-4952-acf6-d3373d83409b.png) | ![Screenshot 2022-02-16 at 17 37 …
=> Make navigation links consistent with other links

src/patterns/telephone-numbers/index.md.njk
Fixes [#2022](https://github.com/alphagov/govuk-design-system/issues/2022).
Updates the ['links' section of our telephone numbers guidance](https://design-system.service.gov.uk/patterns/telephone-numbers/#do-not-display-telephone-numbers-as-links-on-devices-that-cannot-make-calls).
Current guidance says most:
- desktop machines do not support calls - this is untrue so we're changing it
- modern mobile browsers detect phone numbers and display them as links - as above
Also, when users click on linked numbers, it can trigger a Skype setup process or the like. So we're also adding a sentence to tell users to bear this in mind.
=> Remove errors from phone numbers guidance

src/components/text-input/index.md.njk
Fixes [#1734](https://github.com/alphagov/govuk-design-system/issues/1734).
Updates our [text input guidance](https://design-system.service.gov.uk/components/text-input/).
Current guidance under ['If the input uses characters that are not allowed and you do not know what the characters are'](https://design-system.service.gov.uk/components/text-input/#if-the-input-uses-characters-that-are-not-allowed-and-you-do-not-know-what-the-characters-are):
> Say ‘[whatever it is] must only include [list of allowed characters]’.
> For example, ‘Full name must only include letters a to z, hyphens, spaces and apostrophes’.
Users have reported that if they follow this advice, they will end up listing every character allowed, resulting in overlong UI text.
Change second sentence so that it reads:
> For …
=> Add guidance on error message for text input

src/community/index.md.njk
Fixes [#1546](https://github.com/alphagov/govuk-design-system/issues/1546).
Updates our [Community homepage](https://design-system.service.gov.uk/community/) to tell users:
- we like to thank them for their contributions
- we'll ask for permission before we thank them publicly
=> Tell users we ask for consent before we thank them

src/styles/typography/index.md.njk
Fixes [#2075](https://github.com/alphagov/govuk-design-system/issues/2075).
Updates our typography guidance to tell users why they should:
- usually left-align body copy
- avoid 'justifying' blocks of text so that it's aligned to both the left and right margins
=> Tell users to left align but not justify body copy

src/components/text-input/error/index.njk, src/components/text-input/input-hint-text/index.njk
Removes unneeded full stops from these examples within our text input guidance:
- [hint text](https://design-system.service.gov.uk/components/text-input/#hint-text)
- [error messages](https://design-system.service.gov.uk/components/text-input/#:~:text=Error%20messages%20should%20be%20styled%20like%20this%3A)
[A user on Slack pointed out an inconsistency](https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6/p1645710637156809) - the text ("The name you'll use on promotional material") in these examples has a full stop, whereas similar text elsewhere on this page does not.
=> Remove unneeded full stop from text input examples

src/patterns/telephone-numbers/index.md.njk
Explicitly set the language so that the syntax highlighting is applied correctly to the code block.
=> Fix syntax highlighting in telephone numbers pattern

src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk
Following on from f85db87 (#1891), we also need to add the `govuk-body` class to the paragraphs in the cookie banner in the ‘custom page template’ example.
Previously we were relying on default colour and margins for the text content within the cookie banner, when html was passed to the banner. In the yaml examples in govuk-frontend, we assume a user will add govuk-body classes to any html they pass in.
We then [went on to remove the default font styles from the cookie banner in 4.0.0][1], to make it more obvious when you have not added classes and styles to any custom HTML – but didn’t notice we had an example in the Design System which did just that!
[1]: https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md#style-any-custom-html-in-your-cookie-banner
=> Add missing class to cookie banner in page template

src/components/cookie-banner/index.md.njk
Fixes [#1849](https://github.com/alphagov/govuk-design-system/issues/1849).
Currently, [option 3 ('If you set non-essential cookies, but only on the client') of our cookie banner guidance](https://design-system.service.gov.uk/components/cookie-banner/#:~:text=When%20the%20page%20loads%2C%20include%20all%20the%20cookie%20banner%20messages%20that%20the%20user%20might%20see%2C%20but%20hide%20these%20with%20the%20hidden%20HTML%20attribute.) reads:
> When the page loads, include all the cookie banner messages that the user might see, but hide these with the hidden HTML attribute.
However, it wasn't clear to a user that both the component and the messages need to be hidden when the page loads. So this PR specifies what containers to hide.
=> Say what to hide when you set cookies client side

src/components/date-input/index.md.njk
Fixes [#1637](https://github.com/alphagov/govuk-design-system/issues/1637).
Updates the 'error messages' section of our date input guidance.
Our current guidance says, when information is missing from multiple fields, you should highlight all fields. This means, by implication, also highlighting fields the user has actually filled in.
This PR changes the guidance so that it now says to highlight only the fields the user needs to fill in.
=> Say what fields to highlight when info is missing

src/components/date-input/index.md.njk
Fixes [#2029](https://github.com/alphagov/govuk-design-system/issues/2029).
Updates the 'Error messages' section of our date input guidance.
A user asked if we could spell out that the year field requires 4 numbers. Otherwise, some people might enter only 2, and this could be confusing.
The guidance examples all use 4 numbers for the year. Might be good to recommend this in the guidance itself too.
=> Update error guidance to say years need 4 numbers

src/community/resources-and-tools/index.md.njk, src/index.njk
Fixes [#2109](https://github.com/alphagov/govuk-design-system/issues/2109).
[Support ticket analysis](https://docs.google.com/presentation/d/1TxZ17AJDMKI6djT1lEQj6wuH6U9edjZyRm2MfmGOar8/edit#slide=id.g119a61403dd_0_111) shows that some users have asked us for help with the Home Office Design System. Redirecting them to a [community-managed list of design systems](https://github.com/ctdesign/gov-design-systems-list) might prevent this from happening again.
=> Link Design System to list of other design systems

src/patterns/task-list-pages/index.md.njk
This aims to give people greater visibility over the work that is currently being done on this pattern and component.
Also updates the research section to add some additional known issues based on research gathered by the cross-government collaboration.
[Preview](https://deploy-preview-2105--govuk-design-system-preview.netlify.app/patterns/task-list-pages/)
=> Update Task List pattern to show it is being worked on

src/patterns/addresses/multiple/index.njk
This change did three things:
1. Stopped the second field label being invisible
2. Added 'optional' to second field label
3. Made the labels 'Address line 1' and 'Address line 2'
=> Changed field labels to 'Address line 1' and 'Address line 2'

src/components/fieldset/address-group/index.njk
We accidentally added a rogue ƒ in the last update to the fieldset page – this removes it.
=> Remove ƒ typo in fieldset example

src/patterns/addresses/index.md.njk, src/patterns/addresses/multiple/index.njk
This change updates the address pattern to:
* add the county field back in, after recently removing it (see https://github.com/alphagov/govuk-design-system-backlog/issues/31#issuecomment-1096919621)
* slightly switch the order of the different patterns, so 'multiple text fields' come first
We reordered the content based on a Slack conversation where a few members of the community felt that the 'multiple text fields' use case was more common than the others.
=> Put county field back in address pattern and update guidance

src/components/text-input/index.md.njk
Fixes [#2149](https://github.com/alphagov/govuk-design-system/issues/2149).
Updates our text input guidance to give more detail on why users should not use placeholder text.
=> Add placeholder text info to text input guidance

src/components/skip-link/index.md.njk
Fixes [#2131](https://github.com/alphagov/govuk-design-system/issues/2131).
Updates guidance to say where the skip link should sit.
The current guidance tells users to include a skip link in the header. Doing this makes axe flag it as a failure. As a result, some teams have been using workarounds like wrapping the skip link in `<nav>` tags.
=> Add implementation advice to skip link guidance

src/components/text-input/index.md.njk
Adds 2 subheadings to text input guidance:
- Avoid placeholder text
- If you're asking one question on the page
- 'Avoid placeholder text': we've had feedback that [some users have struggled to find the guidance on placeholder text](https://github.com/alphagov/govuk-design-system/pull/2152#issuecomment-1112467551)
- 'If you're asking one question on the page:' it feels like this subheading should exist to mirror the later subheading, 'If you’re asking more than one question on the page'
=> Add subheadings to text input guidance

src/components/fieldset/index.md.njk
Fixes [#2143](https://github.com/alphagov/govuk-design-system/issues/2143).
Current guidance:
> Include any general help text which is important for filling in the form and cannot be written as [hint text](https://design-system.service.gov.uk/components/text-input/#hint-text) in the legend, but try to keep it as concise as possible.
This sounds like we're saying users can make help text look like a heading. If that's right, then maybe we should add an example.
Also, the current wording is on the long side, so I had a go at rewriting it.
=> Make help text advice clearer in fieldset guidance

src/components/checkboxes/with-none-option-in-error/index.njk
A checkboxes example has double quotes around a mention of the 'No, I will not be travelling to any of these countries' option.
GOV.UK style guide says to only use double quotes in body text for direct quotations, and singles otherwise.
=> Replace double quotes with singles in example

src/patterns/national-insurance-numbers/index.md.njk
I was talking with @abbott567 about formats for screen readers with National Insurance numbers  - we've seen a few instances where it has been replayed with no spaces
I figured some explicit guidance on this might help clear it up.
Assumption was it probably lives in [How it works](https://design-system.service.gov.uk/patterns/national-insurance-numbers/#how-it-works) but happy to take feedback on location/content
```
When replaying the National Insurance number on something like [check your answers](/patterns/check-answers/) keep the format ‘QQ 12 34 56 C’ - the spaces will help break up the number for screen reader users.
```
=> Draft: National Insurance number formatting

src/styles/layout/index.md.njk
Fixes [#1900](https://github.com/alphagov/govuk-design-system/issues/1900).
The layout guidance currently uses 3 terms for the same thing:
- 'two-thirds and one-third'
- 'two-thirds / one-third'
- 'two-thirds to one-third'
This PR changes all mentions to 'two-thirds and one-third'.
=> Make layout name consistent throughout guidance

src/components/character-count/error/index.njk, src/components/character-count/index.md.njk
Make content changes for issue https://github.com/alphagov/govuk-design-system/issues/2155
=> Update character count guidance to match new implementation

src/components/character-count/index.md.njk
Fixes [#2140](https://github.com/alphagov/govuk-design-system/issues/2140).
The character count input only shows a red border when the character limit is exceeded. If there's been some other error, and the content is within the limit, it doesn't show this border.
Some users have reported being confused by this, so we're adding guidance to explain why.
=> Explain that red border depends on exceeding limit

src/patterns/email-addresses/index.md.njk
Fixes [#2189](https://github.com/alphagov/govuk-design-system/issues/2189).
Currently, the 'Ask users for email addresses' pattern says the character limit for the field is 256 characters.
This is untrue - it's actually 320 characters, with 64 chars max for the 'local-part' and 255 chars max for the 'domain' part.
=> Add accurate content for email field char limit

views/layouts/_generic.njk
The ‘back to top’ link takes users to the #top anchor point, which is currently before the navigation but after the ‘skip to main content’ link.
This means you can no longer skip past the navs etc (as per [WCAG 2.1 2.4.1 Bypass Blocks][1]) unless you know to press shift + tab to go backwards in the tab order.
Instead, we want the 'back to top' link to take the user to the very top of the page, so that the next tab will take them to ‘Skip to main content’ (or the cookie banner, if it’s not been dismissed).
We also [considered taking the user to the start of `#main`][2], bypassing all of the navigation, but opted instead to move the #top anchor to be the very first thing because:
1. The back to top link was introduced in #687, when we moved from the side navigation and the main content …
=> Move #top anchor to before the skip link

.github/workflows/test.yaml
actions/setup-node v2.5.0 and above support reading a .nvmrc file itself [[1]]. This lets us simplify our code.
[1]: https://github.com/actions/setup-node/releases/tag/v2.5.0
=> Use node-version-file input to specify node version in GitHub Actions

src/patterns/addresses/index.md.njk, src/patterns/national-insurance-numbers/index.md.njk, src/patterns/telephone-numbers/index.md.njk, src/patterns/validation/index.md.njk
Fixes [#2124](https://github.com/alphagov/govuk-design-system/issues/2124).
We've had user feedback that the various guidance pages touching on validation could be more consistent.
To try and fix this, this PR updates these patterns:
- Addresses
- National insurance numbers
- Recover from validation errors
- Telephone numbers
=> Make validation guidance language more consistent

views/partials/_contact-panel.njk
Update the contact panel on guidance pages, from 'Help improve this page' to 'Help improve this style/component/pattern'
I think 'Help improve this page' suggests that the section is about the page itself – things like reporting typos and bugs. I think it's more broadly about improving the component or pattern. That's why we link to the backlog discussion etc.
We discussed changing this on the team Slack a while ago, people were generally positive so thought I'd crack on and raise a PR!
Developer, content designer
The Nunjucks might need a look to see if it could be written more neatly or efficiently. 
A content designer should also probs check it still looks ok. I decided not to change the following paragraph, i.e. 'To help make sure that this page...' because I thought 'page' still made …
=>  Change contact panel headings to reflect the type of page they're on

src/styles/typography/link-no-underline/index.njk, src/styles/typography/link-no-visited-state/index.njk, src/styles/typography/link-on-dark-background/index.njk, src/styles/typography/link-opening-in-new-tab/index.njk, src/styles/typography/link/index.njk
A content designer colleague mentioned that it was confusing where the link text should go, as in the examples the same text is used in 2 places (link text and `class`). This aims to reduce this confusion by making the link text clearer.
"link text" is the phrase used [in the guidance](https://design-system.service.gov.uk/styles/typography/#links) so that seemed like the clearest text to use?
It might also be worth considering making the link in the first example embedded within a sentence, followed by a full stop, so that it is an example of the text before it:
> If your link is at the end of a sentence or paragraph, make sure that the linked text does not include the full stop.
(I've not done that in this pull request though)
=> Update link text in examples

src/components/cookie-banner/client-side-accepted/index.njk, src/components/cookie-banner/client-side-rejected/index.njk, src/components/cookie-banner/client-side/index.njk, src/components/cookie-banner/server-side-confirmation/index.njk, src/components/cookie-banner/server-side-multiple-messages-confirmation-visible/index.njk, src/components/cookie-banner/server-side-multiple-messages-question-visible/index.njk, views/partials/_cookie-banner.njk
Change cookie button text from 'Hide this message' to 'Hide cookie message' to provide context to any users using assistive tech navigating out of context.
This PR changes:
- the cookie banner for the design system website
- all cookie banner visual examples on the cookie banner component page
Note: this text is not hardcoded in the cookie banner component, so there is no corresponding release of `govuk-frontend` and services will need to make this change manually.
=> Update cookie hide button to be more descriptive

src/patterns/payment-card-details/index.md.njk
Remove last line on the Payment Card details page, which refers to the performance platform. This platform no longer exists.
=> Remove last line about performance platform

src/community/roadmap/index.md.njk, src/components/pagination/default/index.njk, src/components/pagination/ellipses/index.njk, src/components/pagination/first-page/index.njk, src/components/pagination/in-page/index.njk, src/components/pagination/index.md.njk, src/components/pagination/labels-2/index.njk, src/components/pagination/labels/index.njk, src/components/pagination/large-number-of-pages/index.njk, src/components/pagination/last-page/index.njk
Refine guidance for pagination component, based on design decisions and previous working group review.
Content improvements are mainly to:
- better explain the rules 'for large numbers of pages'
- structure the page to help users navigate the different patterns
Preview of page, with examples:
https://add-pagination--govuk-design-system-preview.netlify.app/components/pagination/
Other links:
- [Preview](https://add-pagination--govuk-design-system-preview.netlify.app/components/pagination/)
- [Draft doc](https://docs.google.com/document/d/1kccqRi89Z4oE1qS6te-p9a59yca_aCyjLmdk2qz4kGo/edit?usp=sharing) (no longer in use)
- [Design decisions](https://docs.google.com/document/d/1nyEiF4juIy3nGyAlSon1IVS_9DS32FdgOZQ7s4RGtvk/edit?usp=sharing)
Epic: [Publish pagination contribution …
=> Guidance for pagination component

src/styles/typography/link/index.njk
This link example does not include a wrapping element, meaning that some of the text is appearing as default serif text instead of in Transport in the Design System documentation.
As the text above this example states that it is regarding links at the end of sentences or paragraphs, the example code shouldn't be misleading by the inclusion of a paragraph.
=> Add paragraph element to link example

src/community/resources-and-tools/index.md.njk
I am no longer able to maintain govuk-react-jsx and therefore I think it should be removed from this list.
Thanks
Andy
=> Remove govuk-react-jsx which is no longer supported

__tests__/tabs.test.js, src/javascripts/components/options-table.js, src/javascripts/components/tabs.js, src/stylesheets/components/_tabs.scss, views/partials/_example.njk
Refactors the JavaScript associated with the tabbed interface used for code examples. 
It was felt that the existing code had become more difficult to understand and maintain over time; and did not align with how the Design System team now prefers to author JavaScript.
Also fixes #2042.
The JavaScript has been heavily refactored. It's a little more verbose and there is definitely some repetition that could be reduced (`getMobileTab` and `getDesktopTab` are almost identical functions), but it's hopefully a lot easier to understand now! (And it actually minifies to *less* code than the previous version. 3351 bytes for old vs. 2835 bytes for new, when piped through Uglify!)
Classes are no longer defined as variables at the top of the file. Many of these classes were only used once, and it …
=> Refactor JavaScript for tabs functionality

src/styles/images/index.md.njk
As flagged in https://github.com/alphagov/govuk-design-system-backlog/issues/70#issuecomment-1187335536:
> Mainstream is 2500 pages managed by GDS, but this guidance also applies to all content on www.gov.uk produced by depts, the half a million 'whitehall' pages.
Closes #2250
=> Remove ‘mainstream’ from images guidance

src/javascripts/components/options-table.js
I believe this dates from when the polyfill for the `<details>` element used to be applied in all browsers, and added extra ARIA attributes which always needed to be kept in sync when this script toggled the open state.
However, [since GOV.UK Frontend v3.1.0 the polyfill now does nothing in browsers that natively support the `<details>` elements][1].
This means that once these attributes are set on page load, unless the polyfill is running there is nothing to keep them in sync if the user toggles the details element:
- `aria-expanded` will always be `true`, potentially causing AT to announce the expanded state incorrectly
- `aria-hidden` will always be `false` – although this is likely not an issue as aria-hidden can't make things hidden using display:none 're-appear' in the accessibility …
=> Only toggle details ARIA attributes if already set

src/components/button/index.md.njk
Although unusual, there are a few valid circumstances where you might want to submit a form when pressing the start button. A situation that came up recently was we wanted to record analytics on when a user started a service by recording the time that a user presses the start button, without client-side JavaScript. The implementation for this involved using the Rails `button_to` helper which generates a form which POSTs to a route and includes a single `submit` button.
I think this is a valid use case of the start button, so I suggest changing the wording on this to be slightly more open to the idea of the start button not being a link.
See https://github.com/DFE-Digital/govuk-components/pull/343 and https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/174#discussion_r910 …
=> Allow start buttons to be forms

src/patterns/task-list-pages/index.md.njk
This file has changed location in recent changes to the Prototype Kit, this updates the URL to no longer 404.
=> Update link to task list Sass file

package-lock.json, package.json
One major version bump. Version 10:
- Uses PostCSS 8
- Removes support for Node.js 6, 8 and 11
- PostCSS is now a peerDependency
None of which affects our installation.
This change has been enabled by our update of @metalsmith/postcss and PostCSS.
=> Bump autoprefixer to 10.4.7

src/styles/page-template/index.md.njk
The ‘variables’ and ‘blocks’ tables were merged in #1311 but this link was missed.
=> Remove broken link in page template guidance

src/styles/spacing/index.md.njk
- Swap the small and large screen sizes
- Reverse the order of the table so that we go from smallest to largest size
- Remove redundant `govuk-table__head`, `govuk-table__body` and `govuk-table__row` classes that don't do anything – see https://github.com/alphagov/govuk-frontend/issues/2733
- Remove an extra `</tr>` that had snuck in, the sneaky little thing making our HTML all invalid
👉🏻 [Preview the change](https://deploy-preview-2274--govuk-design-system-preview.netlify.app/styles/spacing/)
It just makes more sense this way doesn't it?
=> Tweaks to spacing scale table in spacing guidance

src/styles/spacing/index.md.njk
Document the static spacing scale as part of the spacing guidance, as well as:
- improving the header structure of the page
- moving the section on overrides last, to try and encourage users who are writing their own CSS to use the helpers instead
- tweaking the guidance on helpers and overrides
Suggest reviewing commit-by-commit as some of the content has moved around – this will make it easier to see what's changed.
This does **not** include documenting the new static spacing override classes (#2244) – that will be done in a follow up PR. This means that these changes can go out before v4.3.0 is released.
Fixes #1210.
=> Document the static spacing scale and generally improve the spacing guidance

src/components/pagination/index.md.njk
When there's no empty line before the list the Markdown renderer is treating it like it's part of the preceding paragraph.
| Before | After |
| ------- | ------- |
| ![Screenshot from 2022-08-01 16-30-06](https://user-images.githubusercontent.com/128088/182185777-f37d3c40-bdfe-4caf-9b8f-a0173005c4be.png) | ![Screenshot from 2022-08-01 16-30-16](https://user-images.githubusercontent.com/128088/182185794-b3cd937d-b000-42c8-a688-80fa3f147fbb.png) |
=> Fix markdown lists on pagination component page

src/patterns/equality-information/index.md.njk
GSS appear to have moved to a new site - the link was pointing at the old (and out of date) archived standard.
See #2284 for more relevant conversation.
=> Change to more up to date link for Ethnicity harmonised standard

package-lock.json, package.json
Update the design system website to use the latest version govuk-frontend.
=> Update govuk-frontend to 4.3.0

src/styles/spacing/index.md.njk
Static spacing override classes are being introduced to GOV.UK Frontend (https://github.com/alphagov/govuk-frontend/pull/2672).
Document the new classes so that users know how they work, and how they compare to the existing responsive spacing override classes.
Closes #2244.
=> Document static spacing override classes

src/styles/page-template/index.md.njk
Document the new `opengraphImageUrl` page template option, added in https://github.com/alphagov/govuk-frontend/pull/2673.
Update the documentation for the `assetUrl` option to make it slightly more generic and remove the recommendation to override by adding another meta tag to the `head` block as users should use the new `opengraphImageUrl` instead.
=> Document `opengraphImageUrl` page template option

jest.setup.js
The "see no evil, hear no evil" approach. This does not address the flaky tests themselves, but sets `jest.retryTimes` to 3, rerunning failed tests and greatly increasing the likelihood of a CI test task passing.
This is speedier (and more automatic) than rerunning a full CI task again, so might be enough if the flakiness isn't easily addressable.
Before this change, my local `npm test` runs were consistently failing each time. After this I couldn't get 'em to fail after 20 attempts (very scientific, I know).
I think it might be worth merging this and seeing if it helps with the effect, then keeping #1957 open to deal with the cause.
=> Retry failed tests

lib/extract-page-headings/fixtures/src/example-with-aliases.md.njk, lib/extract-page-headings/index.js, lib/extract-page-headings/index.test.js, lib/metalsmith-lunr-index/fixtures/src/with-page-headings.md.njk, lib/metalsmith-lunr-index/index.js, lib/metalsmith-lunr-index/index.test.js, src/styles/typography/index.md.njk
I was building a page and wanted to have a styled `<hr>` so typed "Horizontal rule" and nothing came up in the search, I knew it was on the typography page from memory but I think other people may assume it doesnt exist.
This pull request enables aliases for headings, which aligns with top level aliases.
=> Add alias for section break

src/javascripts/components/navigation.js
IE 10/11 and Safari >= 5.1 < 14 support `window.matchMedia` but do not support `MediaQueryList.addEventListener`.
Instead we have to use the non-standard (and deprecated) [`MediaQueryList.addListener`][1], which only takes one argument which is the callback function to run when the media query status changes.
Test for the presence of the `MediaQueryList.addEventListener` method and then use whichever method is appropriate for the browser.
[1]: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
=> Fix matchMedia event listener in IE / Safari < 14

src/get-started/updating-your-code/index.md.njk
We now have a cookie banner component, so we should link to it from this guide.
=> Reference cookie banner in updating guidance

src/community/resources-and-tools/index.md.njk
Some Github confusion means we have a few PRs lying around for this change.
It's to add a new Mural link to the resources and tools page. I've reviewed it against our criteria, and it looks good.
Look here for more context: https://github.com/alphagov/govuk-design-system/pull/2281
Will close all the other PRs after this one's done.
=> Add in link to Mural file

lib/metalsmith.js
See individual commits for details.
=> Clean up marked config

src/stylesheets/components/_phase-banner.scss
We moved the banner when refactoring the nav in 2b6a27b.
Now that the banner is not between the header and the navigation, it makes sense to add the bottom border back to separate the banner from the page content.
Keep the `--no-border` modifier which we use on the homepage when the banner is followed immediately by the masthead.
=> Add border to 'preview' / 'archive' banner

src/components/text-input/index.md.njk, src/components/text-input/number-input/index.njk, src/patterns/bank-details/default/index.njk, src/patterns/bank-details/error/index.njk, src/patterns/confirm-a-phone-number/default/index.njk, src/patterns/confirm-a-phone-number/error-expired/index.njk, src/patterns/confirm-a-phone-number/error-incorrect/index.njk
We previously recommended using `pattern="[0-9]*"` on number inputs to prompt iOS to display the numeric keypad.
This has been unnecessary since Safari 12.2, when support for the standardised `inputmode` attribute was added to Safari.
We [stopped using the `pattern` attribute on the date input component][1] in v4.1.0 (released in May 2022) as the proportion of GOV.UK visitors using versions of iOS 12.x and below had fallen to 0.08% of total traffic.
[1]: https://github.com/alphagov/govuk-frontend/pull/2599
=> Stop recommending using `pattern="[0-9]*"` on number inputs

src/stylesheets/components/_footer.scss, src/stylesheets/components/_header.scss, src/stylesheets/components/_split-pane.scss, src/stylesheets/components/_subnav.scss
We need to use govuk-exports in GOV.UK Frontend as files can be imported multiple times but we only ever want the CSS to be outputted once.
As we're in control of how and where Sass in the Design System is imported, we don't need to worry about this and don't need to use the exports function.
Suggest [reviewing without whitespace](https://github.com/alphagov/govuk-design-system/pull/2328/files?diff=unified&w=1) to see the changes more clearly.
This branch is built on top of #2327 which needs to be merged first.
=> Remove use of `govuk-exports` in Design System Sass

src/get-started/updating-your-code/index.md.njk
I don't think there is a `%govuk-body` placeholder
to extend, or at least if I try to, I get an error
saying `The target selector was not found` and I
can't find any in the govuk-frontend repo'.
This copies the approach from the next pairing,
for `@include copy-14`, but with the `m` size, to
set the font-size to '19' rather than '14'.
=> Fix reference to `%govuk-body` placeholder

views/partials/_whats-new.njk
Remove Design System Day message from What's New panel to reflect the postponement. Removing quietly instead of announcing the change in line with national mourning period.
=> Edit What's new to remove Design System Day (for now)

src/components/text-input/index.md.njk, src/patterns/bank-details/index.md.njk
We stopped recommending using the `pattern` attribute on number inputs in #2323 but I missed this reference in the guidance for the text input component and the bank details pattern.
We still tell users to turn off HTML validation in [the broader 'validation' pattern](https://design-system.service.gov.uk/patterns/validation/#turn-off-html5-validation) – that hasn't changed – but now that we're not using the pattern attribute there's no need to call it out in these specific places.
=> Remove references to the `pattern` attribute in guidance

src/design-system-team.md.njk
The [list of team members](https://design-system.service.gov.uk/design-system-team/) is getting long, hard to read and does not help users understand what we do as a team.
This change to organise us into teams and squads works to help give a better idea of who we are.
=> Organise team page into teams and squads

src/community/blogs-talks-podcasts/index.md.njk, src/community/contribution-criteria/index.md.njk, src/community/design-system-working-group/index.md.njk, src/community/develop-a-component-or-pattern/index.md.njk, src/community/propose-a-component-or-pattern/index.md.njk, src/community/propose-a-content-change-using-github/index.md.njk, src/community/resources-and-tools/index.md.njk, src/community/roadmap/index.md.njk, src/community/upcoming-components-patterns/index.md.njk
This PR splits the pages in the 'Community' section into subsections, or 'themes', in a similar way to the [Patterns](https://design-system.service.gov.uk/patterns/) and [Get Started ](https://design-system.service.gov.uk/get-started/)sections of the website.
This change would make the pages easier to navigate when displayed on the left sidebar.
You can see what the new left sidebar looks like in preview:
**https://deploy-preview-2372--govuk-design-system-preview.netlify.app/community/**
Backlog (to be renamed in https://github.com/alphagov/govuk-design-system/issues/2310)
Roadmap
Discussions, events, co-design (could eventually we add an "alias link" that'd go back to community landing page in https://github.com/alphagov/govuk-design-system/pull/2356?)
Propose a content change using …
=> Organise 'community' pages into subsections (themes)

src/community/blogs-talks-podcasts/index.md.njk
Add 'How we prioritise additions to the GOV.UK Design System' blog post to the 'Blog posts, videos and podcasts' page
=> Add prioritisation blog post

views/partials/_whats-new.njk
Adds the new 'Upcoming components and patterns' page as the latest 'what's new' item and adds the blogpost about prioritisation into the Blogs page.
I think I've rebased this branch now so it should not conflict with #2372
=> Update What's new and blogs pages with 'prioritisation' work

src/community/backlog.md.njk, src/community/contribution-criteria/index.md.njk, src/community/develop-a-component-or-pattern/index.md.njk, src/community/index.md.njk, src/community/propose-a-component-or-pattern/index.md.njk, src/get-started/extending-and-modifying-components/index.md.njk, src/get-started/focus-states/index.md.njk, src/index.njk
After updating the backlog page in https://github.com/alphagov/govuk-design-system/pull/2354, there are still a few references to the community backlog that need updating. Hopefully this PR covers everything on the Design System website.
I've tried not to rewrite any descriptions of the contribution process, except where it's completely out of date or misleading. This should be done as part of a more comprehensive piece of work. The biggest change is where I removed step 3 from the 'Propose a component or pattern' page, because we don't review every new suggestion with the working group.
=> Tidy up references to the community backlog

views/partials/_whats-new.njk
Fixes the design system homepage.
Screenshot showing incorrect quotes and wrong link style:
=> Fix link style and smart quotes

docs/contributing/archiving-deleted-urls.md
Adds docs on how we archive pages on the design system website. This is something we do but don't have written down anywhere. Examples:
- https://github.com/alphagov/govuk-design-system/pull/1136
- https://github.com/alphagov/govuk-design-system/pull/2392
- https://github.com/alphagov/govuk-design-system/pull/1582
This doesn't include any guidance for how/if we "decay" archived pages aka: if and when we delete archived pages. Considering we currently don't have a redirect strategy based on any server config, I don't think this is worth worrying about now.
=> Add docs on archiving pages in the design system

.github/dependabot.yml
This PR enables Dependabot updates for npm and GitHub Actions
Previously only security-related updates were included
=> Update all dependencies using Dependabot 

src/components/back-link/index.md.njk, src/components/breadcrumbs/index.md.njk, src/components/button/index.md.njk, src/components/checkboxes/index.md.njk, src/components/date-input/index.md.njk, src/components/details/index.md.njk, src/components/error-summary/index.md.njk, src/components/file-upload/index.md.njk, src/components/index.md.njk, src/components/pagination/index.md.njk, src/components/panel/index.md.njk, src/components/phase-banner/index.md.njk, src/components/radios/index.md.njk, src/components/select/index.md.njk, src/components/skip-link/index.md.njk, src/components/summary-list/index.md.njk, src/components/table/index.md.njk, src/components/tabs/index.md.njk, src/components/tag/index.md.njk, src/components/text-input/index.md.njk, src/components/textarea/index.md.njk, src/components/warning-text/index.md.njk, src/design-system-team.md.njk, src/get-started/prototyping/index.md.njk, src/patterns/step-by-step-navigation/index.md.njk, src/patterns/task-list-pages/index.md.njk, src/styles/index.md.njk
The GOV.UK Protoype Kit website has moved to a service domain :tada:
This PR updates links to match. We also update the link to the install page, as the GOV.UK Prototype Kit version 13 is installed in a different way to previous versions, and the documentation has been changed to reflect that.
=> Update links to GOV.UK Prototype Kit website

lib/file-helper.js, lib/metalsmith.js, package-lock.json, package.json, src/accessibility.md.njk, src/community/contribution-criteria/index.md.njk, src/community/develop-a-component-or-pattern/index.md.njk, src/community/propose-a-content-change-using-github/index.md.njk, src/community/roadmap/index.md.njk, src/components/accordion/index.md.njk, src/components/cookie-banner/index.md.njk, src/components/footer/index.md.njk, src/components/notification-banner/index.md.njk, src/components/pagination/index.md.njk, src/components/radios/index.md.njk, src/components/tabs/index.md.njk, src/get-started/extending-and-modifying-components/index.md.njk, src/get-started/updating-your-code/index.md.njk, src/patterns/confirm-a-phone-number/index.md.njk, src/patterns/cookies-page/index.md.njk, src/patterns/dates/index.md.njk, src/patterns/question-pages/index.md.njk, src/patterns/start-using-a-service/index.md.njk, src/privacy-policy.md.njk, src/styles/colour/index.md.njk, src/styles/page-template/index.md.njk, src/styles/typography/index.md.njk, views/partials/_example.njk
We use `@metalsmith/in-place` to transform our source markdown and nunjucks files.
Under the hood, `@metalsmith/in-place` uses `jstransformer`, which in turn relies on `jstransformer-nunjucks` and `jstransformer-marked` to handle our Nunjucks and markdown code respectively.
Previously, we've been using `jstransformer-marked` v1.0.3, not realising that it was using an outdated version of `marked` (0.3.9), and not the direct dependency that we've specified. This means that if we try to update, we generate a lot of rendering errors (at one point I had a 100,000+ line diff) because of various bugs being ironed out in more recent versions of `marked`.
Previously, we've used [`pedantic` rules](https://marked.js.org/using_advanced#options), but some of our usage is incorrect, flying under the …
=> Update Marked and switch to Github Flavoured Markdown

src/community/roadmap/index.md.njk
- amended the 'last updated' date
- removed releases 4.1.0 and 4.2.0 from 'Recently shipped' as over 6 months ago
- removed Confirm a phone number from 'Recently shipped' as over 6 months ago
- added "hosted Design System Day 2022" to 'Recently shipped'
- added "publish an accessibility strategy for the GOV.UK Design System" to 'Working on now'
=> Update roadmap page

src/community/accessibility-strategy/index.md.njk
Now that the GOV.UK Design System accessibility strategy has gone through 3 drafts (team, internal, public), it's time to publish!
[Strategy preview page](https://deploy-preview-2445--govuk-design-system-preview.netlify.app/community/accessibility-strategy)
[Activity log draft](https://github.com/orgs/alphagov/projects/46)
[Public draft of the accessibility strategy](https://docs.google.com/document/d/1lIPb1X075bguXlVl34kND43V0QZ3SD2Iga4xZQissXo/edit?usp=sharing)
We need a more permanent home for the two portions of the accessibility strategy:
* the strategy portion
* the activity portion
They can't stay in Google Docs long-term, because many service teams and departments have difficulty accessing GSuite tools.
David, Claire, Calvin
Calvin, Claire, David, whole team
=> Adding the accessibility strategy

src/design-system-team.md.njk
When updating the [team page](https://design-system.service.gov.uk/design-system-team/), the most common review comment is that editors don't use the longer em dash between the team member name and that same team member's role. This is an attempt to mitigate the likelihood of that mistake.
=> Add comment on team page reminding editors to use em dashes

.github/dependabot.yml, package-lock.json
This PR configures Dependabot to only allow updates to [`direct` dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow)
See https://github.com/alphagov/govuk-frontend/pull/3132 for more info:
>We regularly receive Dependabot PRs for “dependencies of dependencies” **package-lock.json** changes. It's great for [**Dependabot security updates** via Settings](https://github.com/alphagov/govuk-frontend/settings/security_analysis) it's but too noisy for [**Dependabot version updates** via `dependabot.yml`](https://github.com/alphagov/govuk-frontend/blob/main/.github/dependabot.yml)
>
>For example updates to  [`indirect` dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version …
=> Configure Dependabot for direct updates only

lib/metalsmith.js
This line was added in #503, but it looks like the function `joinPaths` never actually made it into the merge, so this isn't referencing anything.
=> Remove unused Nunjucks global property

.github/workflows/test.yaml
In automated environments, it’s preferable to use `npm ci` over `npm install`.
It is ‘more strict than a regular install, which can help catch errors or inconsistencies’. Specifically, ‘[i]f dependencies in the package lock do not match those in `package.json`, `npm ci` will exit with an error, instead of updating the package lock.’ [1]
As far as I can tell, we do not have any optional dependencies, so I have also removed the `--no-optional` flag.
[1]: https://docs.npmjs.com/cli/v6/commands/npm-ci
=> Use npm ci to install GitHub Actions dependencies

src/index.njk, views/partials/_footer.njk
Update homepage to link to recently published and updated pages.
- Adds link to accessibility strategy
- Updates link to new community landing page (and call-to-action)
- Moves related resources out of the footer and into the homepage (also add style guide and content design guidance)
=> Update homepage links to recent updates

deploy/nginx.conf
[Running the Design System homepage through WebPageTest][1] flagged that we’re not currently compressing SVG or ICO files:
> FAILED - (17.7 KB, compressed = 2.3 KB - savings of 15.4 KB) - https://design-system.service.gov.uk/images/homepage-illustration.svg
> FAILED - (6.2 KB, compressed = 2.5 KB - savings of 3.7 KB) - https://design-system.service.gov.uk/assets/images/favicon.ico
We also have a number of SVGs on other pages – including the community page – where we’d see a benefit from enabling compression:
```
/patterns/check-a-service-is-suitable/check-a-service-is-suitable-new.svg
/images/homepage-illustration.svg
/community/images/dsday22-logo.svg
/community/images/discuss-and-give-feedback.svg
/community/images/propose-a-change-to-pages.svg …
```
=> Compress SVG and ICO files with gzip

docs/contributing/archiving-deleted-urls.md, src/community/blogs-talks-podcasts/index.md, src/community/resources-and-tools/index.md, views/partials/_contact-panel.njk
In #2519 we changed the file extensions for documentation pages from `.md.njk` to `.md`—however links to where these files were hosted on GitHub were not updated, leading to 404s. 
This PR fixes those broken links by removing the `.njk` part of the URL.
Additionally it updates our contributor documentation on archiving pages to use the new file extension format.
=> Fix links to renamed files 

src/patterns/task-list-pages/index.md
These got flagged on support - looks like a result of the changes for v13 of the Kit.
=> Fix broken links to task list code on the Prototype Kit repo

lib/generate-sitemap.js, lib/metalsmith.js, lib/modernizr-build.js, src/styles/page-template/block-areas/index.njk, src/styles/page-template/custom/index.njk, src/styles/page-template/default/index.njk, views/layouts/_generic.njk, views/layouts/layout-example-full-page-govuk.njk, views/layouts/layout-example-full-page.njk, views/layouts/layout-example.njk
This PR fixes a few issues split out from:
* https://github.com/alphagov/govuk-design-system/pull/2497
Including:
1. Write to `sitemap.xml` using metalsmith
2. Write to `modernizr.js` using metalsmith
3. Add `modernizr.js` fingerprint hashing
These changes replace `mkdir()` + `writeFile()` combos and enables asset fingerprinting as needed
=> Write to `sitemap.xml` + `modernizr.js` using metalsmith

.github/workflows/test.yaml
Checks on PRs are currently running twice on every push:
* 1x on `pull_request` event
* 1x on `push` event
This PR ensures we only run checks once on PRs (keeping pushes to branches with protection rules)
But also adds `workflow_dispatch` for manual runs as we do on [`govuk-frontend`](https://github.com/alphagov/govuk-frontend)
=> Prevent duplicate checks on GitHub Actions "Test" workflow

.github/dependabot.yml
Until we drop IE8 support, we need to pin to rollup v0.59.4 for compatibility.
=> Make dependabot ignore Rollup updates

src/components/select/index.md
Joe found an [additional issue](https://github.com/alphagov/govuk-design-system/pull/2467#discussion_r1085019703) that users struggle with about the select component.
=> add additional user struggle bullet to select component research guidance

lib/rollup/index.js
This resolves `npm start` (BrowserSync watch + rebuild) overwriting source files during development
Our Rollup plugin replaces [`config.input`](https://rollupjs.org/configuration-options/#input) (relative) with an absolute path:
```mjs
config.input = resolve(metalsmith.source(), file)
```
This means Rollup can correctly find our source input but it has some side effects:
**On initial build:** Metalsmith resolves config `file` path (relative) to `metalsmith.destination()`
**On watch + rebuild:** Metalsmith uses overwritten `file` path (absolute) to `metalsmith.source()`
Don't overwrite `config.input` and always use child paths for [Metalsmith `Files`](https://metalsmith.io/api/#Files)
=> Fix issue with Rollup `config.input` in watch mode

src/components/summary-list/card-with-actions/index.njk, src/components/summary-list/card-with-title/index.njk, src/components/summary-list/index.md, src/patterns/check-answers/index.md
Summary card is a variant of summary list contributed by @paulrobertlloyd. It's been approved by the working group and is ready for a final review. As well as adding new guidance and examples to the summary list page, it includes some new guidance on the 'check answers' pattern.
See Frontend code at https://github.com/alphagov/govuk-frontend/pull/2931
See more discussion at https://github.com/alphagov/govuk-design-system-backlog/issues/210
=> Summary card

src/index.njk, views/partials/_whats-new.njk
Update 'What's new' panel of the website homepage. Also fixes a typo in the link text to the accessibility strategy.
=> Update What's new for v4.5.0

src/community/roadmap/index.md
Updates the roadmap that moves up a couple of items, also adds things from v4.5.0 release.  Aim is to publish this alongside v4.5.0 release expected on 31 January 2022
=> Update roadmap for v4.5.0 release

src/stylesheets/components/_tabs.scss
Fixes a minor regression from:
* https://github.com/alphagov/govuk-design-system/pull/2242
=> Add missing `[hidden]` styling on tabs for IE8-10 compatibility

lib/metalsmith-browser-sync.js
Source map files are never found on-page so Browsersync triggers a full page reload (quite slow)
Since their related CSS or JS files will also update, Browsersync will continue to reload as expected. This is also a side effect of Metalsmith "replacing all the files" on rebuild versus per-file incremental changes
**Update:** Full page reloads still happen for the `*.html` changes but not for every `*.map` too
=> Prevent Browsersync full page reloads on `*.map` changes

lib/fingerprints/fixtures/src/example-xxx-123.js, lib/fingerprints/fixtures/src/example-xxx-456.map, lib/fingerprints/index.js, lib/fingerprints/index.test.js
We added hash fingerprints to source maps recently
But we assumed source maps would follow this pattern:
```mjs
const pathAsset = 'example.js'
const pathMap = `${pathAsset}.map`
```
Sadly we've hit this awkward combo in https://github.com/alphagov/govuk-design-system/pull/2572:
```
iframeResizer.contentWindow.min.js
iframeResizer.contentWindow.map
```
We now follow other libraries and grab the URL using regex:
```mjs
/# sourceMappingURL=(?<path>.*\.map)/g
```
=> Ensure mismatched source map URLs are still hashed

src/community/propose-a-component-or-pattern/index.md
When a user raises an issue in [govuk-design-system-backlog](https://github.com/alphagov/govuk-design-system-backlog), it needs to be manually added to the new [project board](https://github.com/orgs/alphagov/projects/43/views/1) we've created as a list of discussions.
This content change adds an instruction for the user to tell us when they've made a proposal so the team (usually whoever is on support) can do this.
This should solve situations such as this [user that could not see their proposed component](https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6/p1674734113489069?thread_ts=1674732951.858609&cid=C6DMEH5R6).
=> Ask users to tell us when they've made a proposal

src/community/resources-and-tools/index.md
The [boilerplate repo has been decommissioned](https://github.com/DFE-Digital/govuk-rails-boilerplate) and replaced by [the new Rails template](https://github.com/DFE-Digital/rails-template).
=> Replace the DfE Rails boilerplate with the new Rails template

src/components/checkboxes/index.md
A user [commented on Slack](https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6/p1675263749783979) that their team was confused whether to use single quotes or double quotes to refer to checkboxes in error messages.
On the checkboxes component, error messages are presented as quotes, which creates confusion when the error message itself contains a quote (quotes with quotes). Best practice (according to grammar and the style guide) is to use double quotes within single quotes, but the inconsistency is causing confusion.
This PR proposes using a quote block to avoid using quote marks.
=> Clarify error message in Checkboxes component

src/community/upcoming-components-patterns/index.md
We've released this as part of v4.5.0 so it can be removed from this page.
=> Remove summary card from what we're working on now

src/community/resources-and-tools/index.md
Add the template repository for GOV.UK Frontend Flask to the design system community resources. GOV.UK Frontend Flask is a complete Flask app template that implements the two Python port packages to integrate with GOV.UK Frontend.
This template app will replace the two current "demo" apps for the Jinja and WTForms packages respectively, serving as both the reference implementation of those packages and a best practice Flask app with sensible defaults to build upon.
=> Add GOV.UK Frontend Flask community resource

lib/file-helper.js, lib/marked-renderer.js, lib/metalsmith.js, src/get-started/focus-states/index.md, src/get-started/updating-your-code/index.md, views/partials/_example.njk
Line breaks in code blocks are back 🙌
All code blocks are now rendered in Markdown (not Nunjucks) to fix a rendering bug when line breaks are added.
=> Use Markdown to render all code blocks

lib/file-helper.js, lib/highlighter.js
This PR fixes various bugs and issues spotted with our code blocks
In commit https://github.com/alphagov/govuk-design-system/pull/2427/commits/1a615e755cda063d4fbf5598d3140fed81cee230 (via PR https://github.com/alphagov/govuk-design-system/pull/2427) we had to remove new lines to fix Markdown parsing. Turns out part of the issue was a default language not being set for code blocks.
The Accordion example “with summary section” was failing JavaScript detection and lacked code syntax highlighting. We no longer use `highlightAuto()` but instead tell `highlight.js` exactly what language to use
Removes `<label>` from the “inline” HTML list as the [previous “unformatted” fix](https://github.com/alphagov/govuk-design-system/commit/819a94e0783a24368f4b94f73c665e72140043f3) appears to have stopped …
=> Fix various code highlighting issues

src/stylesheets/main.scss
This PR adds "text wrapping by default" for code languages:
1. Plain text
2. Markdown
Otherwise we have lots of horizontal scrolling
=> Enable text wrapping in markdown/plaintext code

.github/workflows/test.yaml, .htmlvalidate.js, .htmlvalidateignore, package-lock.json, package.json, src/community/index.md, src/components/footer/index.md, src/cookies.njk, src/get-started/labels-legends-headings/legend-m-s/index.njk, src/patterns/confirm-a-phone-number/index.md, src/patterns/service-unavailable-pages/available-at-known-date/index.njk, src/patterns/service-unavailable-pages/default/index.njk, src/styles/colour/index.md, src/styles/page-template/index.md, views/layouts/_generic.njk, views/layouts/layout-example-full-page-govuk.njk, views/layouts/layout-example-full-page.njk, views/layouts/layout-example.njk, views/partials/_example.njk, views/partials/_image-card.njk, views/partials/_navigation.njk
We currently have no built-in way of ensuring our compiled HTML changes in the way we expect, and doesn't break.
This PR adds HTML linting using `html-validate`. There are quite a few commits, but they're all really small, promise!
There are some issues to consider:
- I've ignored a coupla "WCAG techniques" type rules which we might want to review as part of our accessibility work ([495be15](https://github.com/alphagov/govuk-design-system/pull/2569/commits/4bc4910b110dfe170bbce3d66f02037d47a451c1) and [d1dea99](https://github.com/alphagov/govuk-design-system/pull/2569/commits/d1dea99330909005c43473a4521434f8e70ef0b6))
- I've tried to avoid inline validation as far as possible, but sometimes this was the most targetted way
- We currently have status labels contained within `<h1>` tags, …
=> Lint compiled HTML

src/community/roadmap/index.md
We didn't do this in previous updates, whoops!
=> Update the date on the roadmap

.github/dependabot.yml
Reduces Dependabot updates frequency so it runs weekly on Monday (default) at 10:30 (some time in the day rather than before everyone is in, in the hopes to spread who picks these up a little more). 
This change of frequency shouldn't affect when Dependabot raises security updates (according to this [bit of Dependabot's documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#frequency-of-dependabot-pull-requests))
Closes [#3349](https://github.com/alphagov/govuk-frontend/issues/3349)
=> Reduce dependabot updates frequency to weekly

.github/workflows/test.yaml, lib/metalsmith.js, package-lock.json, package.json, src/community/blogs-talks-podcasts/index.md, src/components/error-summary/default/index.njk, src/components/footer/with-meta/index.njk, src/components/footer/with-navigation/index.njk, src/components/header/with-service-name-and-navigation/index.njk, src/components/skip-link/default/index.njk, src/get-started/extending-and-modifying-components/index.md, src/get-started/updating-your-code/index.md, src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk
Found a few broken anchor links whilst clicking around:
1. [**/community/**#community-principles](https://design-system.service.gov.uk/community/#community-principles)
2. [**/get-started/extending-and-modifying-components/**#avoid-overwriting-gov-uk-design-system-code](https://design-system.service.gov.uk/get-started/extending-and-modifying-components/#avoid-overwriting-gov-uk-design-system-code)
3. [**/styles/spacing/**#spacing-override-classes](https://design-system.service.gov.uk/styles/spacing/#spacing-override-classes)
4. [**/styles/spacing/**#spacing-on-custom-components](https://design-system.service.gov.uk/styles/spacing/#spacing-on-custom-components)
Realised our link checker wasn't checking anchors so switched to [hyperlink](https://www.npmjs.com/package/hyperlink) (used by …
=> Fix broken anchor links

src/patterns/addresses/index.md
The address lookup shown in the video example uses a Select (dropdown) component on the results page. The Select component's own page in the Design System says it should not be used except "as a last resort" and there are workable alternatives available (for example, a list of radios). 
The video causes confusion as it is widely understood to be "the GDS pattern" for address lookups: service teams then either build lookups that follow it or encounter the issues with Selects in their own testing and develop their own solutions from scratch, which may not be consistent with one another.
=> Remove video of address lookup that uses Selects

src/patterns/equality-information/index.md
Updates a broken link to the new URL for the GSS harmonisation standards.
=> Update link to GSS harmonised standards

src/index.njk, src/styles/index.md, views/partials/_masthead.njk
It’s not obvious that the design system is primarily intended for teams working on government services, which can cause problems. For example, a directory of parish councils adopted the design system wholesale which has lead to them receiving [multiple bad reviews](https://uk.trustpilot.com/review/parish.uk), and has caused their intended audience to label the directory a ‘scam’. 
These small changes should help address that. Once released, we can work towards iterating these messages to make it clearer, if necessary.
=> Make it clearer who the design system is aimed at

src/components/tabs/index.md
Added a new section under 'How it works' called "The current tab gets stored in the URL".
This new section explains how navigating to a tab results in a fragment being appended on the URL.
Why? So that developers know how the tabs component functions, and know that current / previous tab is stored and can be navigated to by using the browser's back button.
=> Add guidance on how tab values get stored in URL

src/javascripts/components/navigation.mjs
This PR partially reverts an unreleased change from https://github.com/alphagov/govuk-design-system/commit/cf8b7265ea5c8119089a6e1c54332aa8eec94b39#diff-77d636446b24955f10521d341aef15533905564e2ac413de8009562f3c9d0ce7R135
Browser testing in Safari 9.1 correctly spotted some recent MediaQueryList argument changes:
```js
var mql = window.matchMedia('(min-width: 48.0625em)')
mql.addEventListener('change', handler)
mql.addListener(handler) // Legacy IE and Safari
```
=> Fix argument count in deprecated `this.mql.addListener()`

src/design-system-team.md
Update the team page to:
- fix a text wrapping issue on the introductory 2 paragraphs
- make Romaric tech lead, and move me to cross-squad
- remove the prototype team
=> Updates to team page

src/community/roadmap/index.md
Move ‘iterate on alt text guidance for the images style page’ to recently shipped as it was completed in #2059.
List out the main changes coming in v5, including:
- updating ‘improve how JavaScript works in GOV.UK Frontend’ to ‘providing a clear JavaScript API for our components’ to give a better idea of what we’re trying to do
- moving ‘implement our proposal for reducing browser support’ from ‘Coming up next’ and reworded
Move ‘release the Hide this page’ component to ‘Coming up next’. Although this is still being actively worked on, it won’t be released until after v5.
Move ‘make sure the Design System meets WCAG 2.2’ from ‘Future plans’ to ‘Coming up next’.
Under future plans, add detail about dropping support for Ruby Sass and LibSass and make the migration to the Sass module system …
=> Update the roadmap

lib/metalsmith.js, package-lock.json, package.json
We make use of `metalsmith-env` to grab `process.env` variables and include them as Metalsmith metadata. This allows us to use these variables in templates (for instance, [using Netlify's environment variables to determine whether to display a "Preview" banner](https://github.com/alphagov/govuk-design-system/pull/138))
Metalsmith now has a built-in `env` method which we can use instead.
I've checked the local output of Metalsmith.metadata() before and after getting rid of `metalsmith-env` and they're identical. There's also no diff in compiled output.
Closes #2330
=> Use Metalsmith's built-in env() method

src/components/notification-banner/index.md
Very minor fix - just corrects an unnecessary space in `role="region"` ([It's valid](https://stackoverflow.com/questions/7064095/spaces-between-html-attributes-and-values), just inconsistent with the other examples)
=> Remove unneeded space in notification banner documentation

src/patterns/step-by-step-navigation/index.md
There is a broken Heroku link in the 'Step by step navigation' pattern guidance. I've sourced a new version of the link, and recommend we swap it in.
The broken link is in this section: https://design-system.service.gov.uk/patterns/step-by-step-navigation/#services-using-this-pattern
Old link: https://live-stuff.herokuapp.com/step-by-steps
New link: https://govuk-formats.herokuapp.com/
The new link was provided by Simon Hughesdon, via a Slack thread.
=> Fix broken link in 'step by step navigation' page

rollup.config.js
Aligns our Terser config with `govuk-frontend` and adds source map `{ includesources: true }`
This ensures web inspection and stack traces link back to original JavaScript lines, likely a regression from:
* https://github.com/alphagov/govuk-design-system/pull/2689
Found whilst testing:
* https://github.com/alphagov/govuk-design-system/pull/2740
=> Include sources content from `govuk-frontend` source maps

src/components/accordion/index.md
Updates the Accordion component's guidance to account for the upcoming introduction of the `rememberExpanded` option in 4.6.0.
Closes #2727.
- Adds a sentence stating that the session storage functionality can be turned off by setting `rememberExpanded: false` in the Nunjucks macro.
- Moves the "You can configure sections to start and stay open, but not stay closed." sentence to a separate paragraph, as it feels a bit more standalone now. 
- I've only given mention to the Nunjucks parameter, to the exclusion of the JavaScript configuration option and HTML data-* attribute. This is for consistency with other documentation on the Design System website, which tends to assume the user is using the Nunjucks macros.
=> Update Accordion guidance for `rememberExpanded`

src/components/text-input/code-sequence/index.njk, src/components/text-input/index.md, src/patterns/bank-details/default/index.njk, src/patterns/bank-details/error/index.njk, src/patterns/bank-details/international/index.njk, src/patterns/confirm-a-phone-number/default/index.njk, src/patterns/national-insurance-numbers/default/index.njk, src/patterns/national-insurance-numbers/error/index.njk
Preparing some documentation for one of the new features coming in the next release of GOV.UK Frontend. 
> **Note**: I've updated the code examples with the new class name, but the changes won't actually happen until the new version of Frontend has been released and the Design System has been updated to use it. 
Closes #2665.
- Adds a section to the Text Input component docs explaining when and how to use the new class.
- Adds an example of the Text Input component using the new class, using a 'company authentication code' from Companies House as an example.
- Updates examples on related patterns to use the new class. 
- Is the company authentication code example understandable? 
- I was trying to use something other than 2FA code, NI number or bank details, as we already have examples of …
=> Add documentation for `.govuk-input--extra-letter-spacing`

src/patterns/check-answers/default/index.njk
The guidance for check your answers mentions hiding sections that the user doesn't see but not optional questions. On discussion in cross-gov slack, teams do play back said fields but say "not provided". This may need to be added to guidance - view separate note - but also would be helpful to change the example
=> Add example for showing a field that was optional

src/components/summary-list/index.md
Adds a two-sentence explanation for why 'card actions' in summary cards get bolded, while 'row actions' do not.
It affects the ['Adding card actions' section of the 'Summary' list guidance page](https://design-system.service.gov.uk/components/summary-list/#adding-card-actions)
This guidance update is based off of a support thread that popped up from Mark McCormick, regarding why card actions get bolded.
=> Add 'card actions' bolding explanation to summary card content

src/accessibility.md
Related to issue 2666: https://github.com/alphagov/govuk-design-system/issues/2666
- Re-adds the section on non-accessible content
- Expands the statement to cover GOV.UK Frontend codebase
- Adds links to our accessibility statement
- Aligns content closer to the model accessibility statement
You can review this PR against the ['accessibility statement update 2023' drafting document (internal Google Doc)](https://docs.google.com/document/d/1nyWLKaSLhGPvG9qQ8RhuwzPvXBDiQmpCmRSv83fS_do/edit?usp=sharing).
The preview for this PR is here: https://deploy-preview-2752--govuk-design-system-preview.netlify.app/accessibility/
=> Expand and update accessibility statement

src/community/resources-and-tools/index.md
The Pensions Regulator is using the GOV.UK Design System in ASP.NET and Umbraco. We're open sourcing the code and publishing NuGet packages so that other organisations could choose to use our work.
=> Add govuk-frontend-aspnetcore-extensions for ASP.NET developers

src/components/text-input/code-sequence/index.njk, src/patterns/confirm-a-phone-number/error-expired/index.njk, src/patterns/confirm-a-phone-number/error-incorrect/index.njk
- Adds a default value to the example on the Text Input page, so the user doesn't need to manually interact with the input to see the differences in text appearance.
- Adds the class to two "Confirm a phone number" examples where it was accidentally omitted.
=> Fixup examples using `.govuk-input--extra-letter-spacing` class

src/styles/colour/index.md
This PR fixes a link that will break once we merge:
* https://github.com/alphagov/govuk-frontend/pull/3491
=> Fix broken link to GOV.UK Frontend departmental colours stylesheet

.github/dependabot.yml
We've decided to bump Dependabot's max open PR limit back to 10 and see how it goes, since we were falling a bit behind with the default limit of 5.
=> Increase Dependabot's open PR limit to 10

src/community/accessibility-strategy/index.md
These updates reflect the changes to our automated testing processes. These can be explored in detail in the PR: https://github.com/alphagov/govuk-frontend/pull/3522
- Added reference to @axe-core/puppeteer
- Removed notice about known limitations of our automated testing setup
- Added section explaining 4 of the recent updates we've made
=> Update automated testing section in the accessibility strategy

src/community/roadmap/index.md
We’ve decided to roll the typography changes out behind a feature flag as part of a future 5.x release, rather than trying to include them in v5.
We want to give ourselves a little more time to properly understand the impact of these changes.
We also think that putting the changes behind a feature flag will make them easier to roll out, before we then enable them by default, likely in v6.
=> Bump typography changes from v5 on roadmap

lib/get-macro-options/index.js, lib/marked-renderer.js, package-lock.json, package.json
[Dependabot previously attempted this](https://github.com/alphagov/govuk-design-system/pull/2766), but we got the following noisy deprecation warnings:
```
marked(): mangle parameter is deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-mangle.
marked(): headerIds and headerPrefix parameters are deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-gfm-heading-id.
```
I [attempted to address these](https://github.com/alphagov/govuk-design-system/pull/2766/commits/15d0bae56de67ccfb570a396d79aeba9c332fbe7) as recommended, but ran into a bug with the recommended plugin, so we decided to ignore the major version instead.
That bug …
=> Bump marked to v5.0.2

src/components/phase-banner/beta/index.njk, src/components/phase-banner/default/index.njk, src/components/tag/default/index.njk, src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk, views/partials/_banner.njk
The tag component [is being redesigned][1] as part of a wider piece of work on task lists, and the new design will be released as part of v5.0.
The changes include a change in case of tags from UPPERCASE to Sentence case. At the moment in some of our examples the tag text is lowercase in the HTML source, but this doesn’t matter as a CSS text-transform is applied.
We’re currently planning to include [a CSS adjustment][2] to try and sentence case existing tags, but it makes sense to update these examples to use sentence case anyway.
[1]: https://github.com/alphagov/govuk-frontend/pull/3502
[2]: https://github.com/alphagov/govuk-frontend/blob/188ad751fa9e9c1db5eaa62e556483adec2b2ff8/packages/govuk-frontend/src/govuk/components/tag/_index.scss#L36-L43
=> Capitalise tags in examples

src/community/blogs-talks-podcasts/index.md
Added a link to our recent contribution model blog post, in the 'contributing to the community' section of the page.
=> Add link to contribution model blog post

src/community/index.md, views/partials/_image-card.njk
This builds on top of the changes in #2813 to:
- make the `imageCard` macro callable, so we can avoid needing to pass HTML inside a double-quoted string (and therefore use double quotes for attributes consistently)
- consistently add full stop to the end of all sentences
- remove some commented out code
This shouldn't be merged until after #2813 is merged (at which point this PR should automagically 🪄  change to target main).
=> Minor community page improvements

src/community/blogs-talks-podcasts/index.md
Added a link to the accessibility strategy announcement blog from January, in the 'About the Design System' section of the page.
=> Add link to accessibility strategy blog post

src/components/details/index.md
It is now possible to force `<details>` elements to be forcibly opened prior to printing by using [the `beforeprint` event binding](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeprint_event). 
We don't do anything in Frontend to forcibly open `<details>` elements, but [past precedent on the accordion component](https://github.com/alphagov/govuk-frontend/issues/573#issuecomment-472465913) would imply that this lack of intervention is desirable, in order to only print what the user has chosen to show.
Given the overall statement is outdated, and we seemingly don't expect services to automatically expand `<details>` elements anyway, I propose that it is removed outright rather than being modified or reworded.
=> Remove outdated statement about printing `<details>` elements

__tests__/search.test.js, src/javascripts/components/search.mjs
This PR fixes a search results UI issue to show aliases for “begins with” matches
Since search queries match on “begins with” via `lunr.Query.wildcard.TRAILING` this change ensures aliases are always shown when relevant, not just when the alias “contains” the query
"**Upcoming components and patterns**" incorrectly matches "and" (via title)
* If the title "contains" the search query, hide all aliases
* If an alias "contains" the search query, show that alias
"**Upcoming components and patterns**" correctly matches "date" (via alias)
* If title words "begin with" the search query, hide all aliases
* If alias words "begin with" the search query, show that alias
=> Show search aliases for “begins with” matches

config/navigation.js, src/community/upcoming-components-patterns/index.md
1. Include all sections of the website in site search
2. Add aliases for upcoming work to the [Upcoming components and patterns](http://localhost:3000/community/upcoming-components-patterns/) page so searches for things on our roadmap will lead to that page
So that users looking for information on upcoming work have an easier experience finding out about this work.
=> Include 'Get started' and 'Community' pages in search

src/patterns/confirm-a-phone-number/index.md
We include lots of content that can’t be searched using the “telephone” keyword:
* Check your **phone**
* I do not have access to the **phone**
* …no longer have access to the **phone** used to sign up
* …partially show the user the **phone** number
This is now resolved
From a possibly-related-but-not comment https://github.com/alphagov/govuk-frontend/pull/3838#issuecomment-1602898777
=> Add alias “telephone number” to “Confirm a phone number” page

src/styles/colour/index.md
I have added in this change, as the problem with using the GOV.UK design system colours which are already on this page for charts is that, depending on what order the colours are presented in, they would not meet the adjacent colour contrast requirements.
The colours guidance I have linked was developed by a cross government working group led by the Department for Education. The colour palette in this guidance have been designed for use in standard line, bar and pie charts. When all the guidance is followed, the colours mentioned in the Analysis Function colour palette will create charts which are as accessible as possible. This  colour palette is used in the Whitehall publisher on GOV.UK.
=> Include a section on chart colours

src/patterns/step-by-step-navigation/index.md
The templates for prototyping step by steps [were moved into a plugin in GOV.UK Prototype Kit v13][1].
Once the plugin is installed, the step by step templates show up in the ‘Templates’ section of the ‘Manage Prototype’ screen.
There’s no obvious place to link users to for the Step by Step plugin itself, so instead point users to the generic instructions for installing a plugin.
[1]: https://github.com/alphagov/govuk-prototype-kit/releases/tag/v13.0.0
=> Point users to the ‘Step by Step’ Prototype Kit plugin rather than the old templates

src/components/exit-this-page/index.md, views/partials/_contact-panel.njk
Add the usage survey to components and pattern guidance pages.
This will allow services to tell us which components and patterns they're using, so that we can measure adoption of the design system.
Steve
Calvin, and one developer.
After chatting with @calvin-lau-sig7, we decided to add this to the 'Help improve this [element]' section on each guidance page. However, I've omitted it from Styles pages as it doesn't feel as useful there: most services needing to keep their look consistent with GOV.‌UK are required to use the styles, it's not really optional.
=> Add usage survey to contact panel partial

.github/workflows/deploy.yaml, .github/workflows/test.yaml
This change adds exact version numbers to all GitHub Actions
Dependabot will now raise PRs for minor/patch updates
=> Use exact GitHub Actions versions

src/patterns/step-by-step-navigation/index.md
We have had a few queries on our design system support about a link that no longer exists to step by step examples. The repos connected to this link were archived on June 13th.
=> Changing the broken link to step by step

src/components/error-summary/default/index.njk
It’s been flagged that [the example postcode may be hard to read by users with dyscalculia, dyslexia, dyspraxia or ADHD because the example repeats the same numbers and letters with the same shape so they ‘merge’ visually][1].
Additionally, [the examples of error states in the current pattern for ‘asking users for addresses’][2] is inconsistent with this and does not include an example postcode, only:
> Enter a real postcode
We can avoid both problems by not including an error that mentions postcodes in the error summary example.
Remove the postcode error and add a new error relating to the user’s name. Add the error for the user’s name to the top as this reflects the order the questions would likely be asked in.
We may want to revisit the example in ‘asking users for addresses’ in the …
=> Remove hard to read postcode from example

deploy/nginx.conf
In b16393df117a0b499b6288ea0041054093f94d58 We changed the MIME type for JavaScript from `application/javascript` to `text/javascript` in line with [IETF RFC 9239][1].
However we missed that the caching logic needed updating too, so we’ve not been sending `Expires` headers for our JS since. This means that the JS is not currently being cached by CloudFront or in browsers.
Update the mime type to match the mime type now being served.
[1]: https://www.rfc-editor.org/rfc/rfc9239
=> Fix missing Expires headers for JavaScript

src/components/pagination/index.md
- Changed 'For navigating been pages of items' to 'For navigating **between** pages of items'
=> Small typo fix in pagination component guidance

src/components/character-count/index.md, src/components/character-count/threshold/index.njk
Increases the amount of text in the Character Count's 'threshold' example, to better reflect the intended usage being fields with very high character limits that a user is unlikely to encounter naturally. 
Suggested by @davidc-gds on https://github.com/alphagov/govuk-frontend/issues/3689. 
I'm personally a little dubious as to the efficacy of this change, for a couple of reasons:
- It makes the HTML/Nunjucks examples harder to parse, as now a significant portion of them are taken up by the placeholder text.
- In my mind, a limit of 800 characters (as in David's suggestion) or 840 characters (as in this PR) is still much lower than the intended use for the threshold feature. 
- In my mind, the threshold feature is best used where the only limit to value length is technical, such as MySQL's …
=> Increase amount of text in character count threshold example

lib/metalsmith.js, views/partials/_banner.njk
The preview banner hasn't worked since:
* https://github.com/alphagov/govuk-design-system/pull/2942
Metalsmith and Nunjucks environment variables must be added manually, so we've restored:
* `BRANCH`
* `PULL_REQUEST`
* `REVIEW_ID`
=> Fix preview banner

src/components/summary-list/index.md
Removes a hard line break which gets converted to a `<br>` in the Design System, forcing the line to wrap prematurely
Before:
After:
=> Remove hard line break before "Name" in summary list documentation

views/partials/_banner.njk
Following on from the changes in #2979, we also need to fix the references to the BRANCH environment variable so that the banner renders correctly.
(You can see it in it's currently broken state on https://govuk-design-system-preview.netlify.app/)
Before:
```html
This is an archived version of the <a class="govuk-link" href="https://github.com/alphagov/govuk-design-system/tree/"></a> branch for the <a class="govuk-link" href="https://design-system.service.gov.uk">Design System</a>.
```
After:
```html
This is an archived version of the <a class="govuk-link" href="https://github.com/alphagov/govuk-design-system/tree/main">main</a> branch for the <a class="govuk-link" href="https://design-system.service.gov.uk">Design System</a>.
```
=> Fix missing branch and empty link text in banner

src/styles/page-template/index.md
This PR makes a separate documentation change to go along with:
* https://github.com/alphagov/govuk-design-system/pull/2961
Whilst the class `.js-enabled` is still added, the line for JavaScript behaviour needed updating
=> Preview v5: Replace `.js-enabled` with `.govuk-frontend-supported` in docs

src/javascripts/components/back-to-top.mjs, src/javascripts/components/cookie-banner.mjs, src/javascripts/components/cookies-page.mjs, src/javascripts/components/copy.mjs, src/javascripts/components/example-page.mjs, src/javascripts/components/example.mjs, src/javascripts/components/navigation.mjs, src/javascripts/components/search.mjs, src/javascripts/components/tabs.mjs, src/styles/page-template/index.md, src/stylesheets/components/_back-to-top.scss, src/stylesheets/components/_navigation.scss, src/stylesheets/components/_site-search.scss, src/stylesheets/main.scss
This PR updates `.js-enabled` to `.govuk-frontend-supported` as we did for:
* https://github.com/alphagov/govuk-frontend/pull/3801
Added separately to https://github.com/alphagov/govuk-design-system/pull/2958 as lots of functionality is broken until we preview v5
=> Preview v5: Skip initialisation when GOV.UK Frontend is not supported

views/partials/_example.njk
Updates the "Open this example in a new tab" link above examples to not have visually-hidden text in the middle of the link. This was making it difficult for voice control users to activate the links, as the visual text did not match what they needed to say.
This PR moves the visually hidden content to the end of the link instead.
Resolves #2853.
=> Update link text on component examples

src/components/file-upload/index.md
Adding the issue to the component page in favour of adding it to the accessibility statement. Similar issues with Select component and Step-by-step pattern have been put within their respective guidance pages.
=> Add usability issue to file upload component

src/components/file-upload/index.md
See the previous PR where this small content change was suggested: https://github.com/alphagov/govuk-design-system/pull/2996
Why? Because 'track our progress' is inaccurate. The Github issue will be closed without further action.
Before: For more detail, and to track our progress we have the GitHub issue...
After: More detail can be found in the GitHub issue...
=> Small language tweak for file upload guidance

src/components/exit-this-page/secondary-link/index.njk
As per https://github.com/alphagov/govuk-frontend/issues/3921, we don't want the Exit this Page functionality to expose information about the current webpage to the website being linked to. 
However, as we re-purpose the Skip Link component for the secondary link, users must apply the change manually through their Nunjucks include or in their HTML for this link. 
The change to the EtP button itself is here: https://github.com/alphagov/govuk-frontend/pull/4054
=> Add `rel` attribute to EtP secondary link example

src/components/radios/hint/index.njk
The example used for radio buttons with hint text references GOV.UK Verify, which has since been wound down.
This PR replaces the Verify reference with one to GOV.UK One Login, utilising the example hint text from [this One Login documentation page](https://www.sign-in.service.gov.uk/documentation/design-recommendations/save-progress#start-or-resume-a-report-or-application). 
Closes #986.
=> Update radio buttons with hints example

src/patterns/passwords/index.md
Related to this issue:
- #2795
=> Add guidance on show/hide password buttons

src/components/select/error/index.njk, src/components/select/index.md
Adds a brief section about error messages and an example of a Select component's error state to the Select component documentation, which was curiously absent.
Both the wording of the guidance and the error message itself is pulled from the [radio button guidance on error messages](https://design-system.service.gov.uk/components/radios/#error-messages), with the omission of multiple states, as the only invalid choice in a select tends to be the initial 'placeholder' option, if one is present. 
Closes #1049.
=> Add error message section and example to select component docs

src/patterns/step-by-step-navigation/index.md
There are two guidance changes needed to ensure users implement the Step-by-step pattern in accordance with WCAG 2.1
This closes the following issues:
- [Step-by-step navigation 'or' headings must be nested under their parent step headings #2794](https://github.com/alphagov/govuk-design-system/issues/2794)
- [Step-by-step navigation does not convey all of the information for screen reader users when viewing them as forms #3021](https://github.com/alphagov/govuk-design-system/issues/3021)
=> Step-by-step to meet WCAG 2.1

src/stylesheets/components/_example.scss
This fixes a flicker loading `<iframe>` examples with no custom height set
=> Fix typo affecting default iframe height

__tests__/tabs.test.js
Whilst running `jest --watch` locally, I've noticed that two `.click()` calls are sometimes debounced as one
Switching to `.click({ count: 2 })` like we do on GOV.UK Frontend fixes the issue
=> Fix Puppteeer tab link double click issue

deploy/nginx.conf
Modifies the nginx configuration so that the below URLs redirect to the Cabinet Office's centrally managed [security and responsible disclosure policies](https://vdp.cabinetoffice.gov.uk/.well-known/security.txt):
- https://design-system.service.gov.uk/security.txt
- https://design-system.service.gov.uk/.well-known/security.txt
More information is in the [security.txt repo](https://github.com/alphagov/security.txt). 
Related to #1678.
=> Set up redirects for security.txt file

deploy/nginx.conf
Follow up to #3025.
Places the new redirect rules above the rule that forbids access to files and directories starting with a `.`, as one security redirect involves the `.well-known` directory.
=> Re-prioritise security redirect rules

src/components/tabs/index.md
There is a guidance change needed to ensure users implement the Tabs pattern in accordance with WCAG 2.1
This closes the following issue:
- [Tab components should show visible headings for all sections on mobile screen sizes #2797](https://github.com/alphagov/govuk-design-system/issues/2797)
=> Tabs to meet WCAG 2.1

src/community/call-for-speakers-2023/index.md, src/community/design-system-day-2022/index.md, src/community/design-system-day/index.md
Here's the call for speakers on its own page, so that we can provide users with guidance on how to prepare a pitch. This means they'll be able to start preparing a pitch in a document, following the guidance, before opening the form to submit their pitch.
We can delete this page once the call for speakers is closed.
=> Add call for speakers

src/components/text-input/index.md
Adds a section to the Text input component documentation advising that users avoid using the `maxlength` attribute.
Questions about the attribute and its suitability (or lack of suitability) have come up on our support channels recently. 
Resolves #916.
=> Add guidance on avoiding using the `maxlength` attribute

src/styles/layout/index.md
Adds a section to the bottom of the Layout styles documenting the `govuk-visually-hidden` and `govuk-visually-hidden-focusable` utility classes. For (probably) one of the most relied upon classes in Frontend, it's a bit weird that there's no mention of it in the Design System. 
This is very much an MVP. This could definitely be added to, potentially adding a code example or guidance about what kind of content should be hidden — I think we generally only want plain text to be visually-hidden, rather than text containing links or other formatting. 
Related to #2739.
=> Add documentation for the `govuk-visually-hidden` utility classes

src/components/table/index.md, src/get-started/updating-your-code/index.md, src/styles/layout/index.md
Currently we have a `h2` ("Building your own layout") which appears to be acting as a section heading for the two subsequent `h2`s ("Page wrappers" and "Grid system"), which is an incorrect heading hierarchy. 
Normally we might move the child `h2`s to become `h3`s (and `h3`s to `h4`s, etc.), however the Design System website uses `h2`s to generate its table of contents and search index. As we want to preserve these sections in those locations, we're instead opting to remove the "Building your own layout" section and integrating its content into the subsequent sections.
=> Fix layout page heading hierarchy

.github/workflows/test.yaml
Temporarily prevent the Prettier formatting check from failing build/deploy
=> Enable `continue-on-error` for Prettier check

lib/get-macro-options/index.js, lib/metalsmith.js, src/stylesheets/components/_options.scss, views/partials/_example.njk
This PR lets macro option names wrap at full stops and capital letters
It includes:
1. Prefer `overflow-wrap` like we did in [**govuk-frontend**/pull/1185](https://github.com/alphagov/govuk-frontend/pull/1185)
2. Consistently use option `slug` so that `name` can contain HTML
3. Add line break opportunities using [`<wbr>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr)
By formatting option names with `<wbr>` they wrap without affecting copy & paste
<br>
<br>
<br>
Other long option names break in hard-to-read places, such as:
```
charactersAtLimitText
charactersOverLimitText
charactersUnderLimitText
hideAllSectionsText
hideSectionAriaLabelText
pressOneMoreTimeText
pressTwoMoreTimesText
preventDoubleClick
showAllSectionsText
showSectionAriaLabelText …
```
=> Allow macro options to wrap at full stops and capital letters

src/community/accessibility-strategy/index.md
Removes expected "Early 2023" date for the release of WCAG 2.2, keeps it simply to 2023
=> Update expected date for WCAG 2.2 release

.eslintrc.js, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/internal-story.md, README.md, docs/contributing/archiving-deleted-urls.md, lib/colours.js, lib/get-macro-options/index.js, lib/highlighter.js, package-lock.json, package.json, src/community/index.md, src/get-started/extending-and-modifying-components/index.md, src/get-started/updating-your-code/index.md, src/patterns/page-not-found-pages/index.md, src/patterns/problem-with-the-service-pages/index.md, src/patterns/service-unavailable-pages/index.md, src/styles/page-template/index.md, stylelint.config.js, views/partials/_example.njk
Some of our Sass Markdown blocks don't pass Stylelint checks
For example, CSS property order in [Small modifications to components](https://design-system.service.gov.uk/get-started/extending-and-modifying-components/#small-modifications-to-components):
````patch
--- a/src/get-started/extending-and-modifying-components/index.md
+++ b/src/get-started/extending-and-modifying-components/index.md
@@ -120,8 +120,8 @@ For example, if you wanted to override the button component you could do the fol
```css
.app-button--inverse {
-  background-color: govuk-colour("white");
color: govuk-colour("blue");
+  background-color: govuk-colour("white");
}
```
````
This PR brings over the following from GOV.UK Frontend:
* https://github.com/alphagov/govuk-frontend/pull/3698
=> Enable ESLint + Stylelint for code inside Markdown

src/styles/typography/index.md
There is a guidance change needed to ensure users implement links in accordance with WCAG 2.1
This closes the following issue:
- [Links to Welsh versions of content should be understandable even when out of context #2796](https://github.com/alphagov/govuk-design-system/issues/2796)
=> Links to meet WCAG 2.1

src/community/index.md
Minor edit on the Community landing page.
Removes link to Google Calendar link, explains we plan to survey the community. Further updated needed by autumn 2023.
=> Explain that Friday call is on pause

src/components/summary-list/index.md, src/components/summary-list/with-missing-information/index.njk
This shows how you can use the summary list when there is some missing information. There’s a few scenarios when this can occur:
* if a user returns to a partially-completed application
* if additional questions have been added since the user first completed the task (for example, in a case working system)
* optional questions
* where the summary list is shown before the user starts answering the questions. Digital Marketplace adopted this pattern, in order to make it clearer up-front what all the questions were, and because multiple users might collaborate on a single application.
One option for tackling this is to leave the `value` column blank, or with some placeholder text such as "Not entered", whilst keeping a "Change" link in the `actions` column. However "Change" makes sense sense …
=> Add example of summary list with missing information

src/community/roadmap/index.md
This should have been done at the start of the quarter, 6 weeks ago, but I was a bad product manager and didn't do it. I'll add a reminder to my calendar.
The roadmap has been updated with the latest epics we're working on and those coming up in the future. 
I've removed some pieces of work from the 'Recently shipped' section as they had been sat there for a few months, but if people feel I've culled the wrong items, please do add them back in.
=> Update the roadmap with current work and plans

lib/get-macro-options/index.js, lib/metalsmith.js, lib/nunjucks/filters.js, lib/nunjucks/filters.test.mjs, lib/nunjucks/globals.js, lib/nunjucks/index.js, package-lock.json, package.json, views/partials/_example.njk
This PR configures Nunjucks filters, globals and options from a single place
We previously had three ways to generate a slug, which was hard to follow:
1. [`slugger` npm package](https://www.npmjs.com/package/slugger)
2. [`kebabCase` Nunjucks filter](https://github.com/alphagov/govuk-design-system/blob/6cf12f37f28c0b9575d48e9e75af29669887e4f1/lib/metalsmith.js#L64-L66)
3. [`options.slug` for macro options](https://github.com/alphagov/govuk-design-system/blob/6cf12f37f28c0b9575d48e9e75af29669887e4f1/lib/get-macro-options/index.js#L17-L18)
This caused differences in output HTML, for example `formGroup` versus `form-group`
I've already consolidated 1) and 2) in https://github.com/alphagov/govuk-design-system/pull/2927, but now have a [single `slugify` filter to match GOV.UK …
=> Configure Nunjucks from `lib/nunjucks`, consolidate slugs

lib/get-macro-options/index.js, lib/nunjucks/filters.js, package-lock.json, package.json, src/components/accordion/default/index.njk, src/components/breadcrumbs/collapse-mobile/index.njk, src/components/error-summary/full-page-example/index.njk, src/components/error-summary/linking-multiple-fields/index.njk, src/components/error-summary/linking/index.njk, src/components/fieldset/address-group/index.njk, src/components/notification-banner/success/index.njk, src/components/notification-banner/whole-service/index.njk, src/components/summary-list/without-borders/index.njk, src/components/table/column-widths-custom-classes/index.njk, src/components/table/column-widths/index.njk, src/cookies.njk, src/patterns/addresses/multiple/index.njk, src/patterns/check-answers/default/index.njk, src/patterns/contact-a-department-or-service-team/expanding-contact-information/index.njk, src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk, views/layouts/_generic.njk, views/layouts/layout-example.njk, views/partials/_banner.njk, views/partials/_example.njk
This PR follows up on a Slack chat with @stevenjmesser
It adds "smart" typographic punctuation in lots more places
>SmartyPants can perform the following transformations:
>
>* Straight quotes ( " and ' ) into “curly” quote HTML entities
>* Backticks-style quotes (``like this'') into “curly” quote HTML entities
>* Dashes (“--” and “---”) into en- and em-dash entities
>* Three consecutive dots (“...”) into an ellipsis entity
It includes:
1. Automatic smart quotes in macro option descriptions
1. Automatic smart quotes in preview example titles
1. Automatic smart quotes in page `<title>` and meta tags
1. Automatic smart quotes in `*.njk` via `| smartypants` filter
1. Manual smart quotes in `*.njk` templates (not processed by Marked)
=> Apply “smart” punctuation to macro options, titles, meta tags

lib/get-macro-options/index.js, src/components/footer/index.md, views/partials/_example.njk
Closes https://github.com/alphagov/govuk-design-system/issues/2260
Includes two main changes:
1. Ensure each nested option `slug` is suffixed with its parent to make it unique
2. Ensures each nested option table caption is suffixed with its parent to make it unique
The following duplicate table captions have been renamed:
* Footer “items” → “meta items”
* Footer “items” → “navigation items”
But in GOV.UK Frontend v5 will also fix duplicate captions for:
* Summary list “actions” → “rows actions”
* Summary list “actions” for “card actions”
* Summary list "items" for “card actions items”
* Summary list “items” for “rows actions items”
The following duplicate table ID slugs have been renamed:
* Footer meta `items` → `meta-items`
* Footer navigation `items` → `navigation-items`
But in GOV.UK …
=> Fix duplicate macro options table captions and IDs

views/layouts/layout-pane.njk
When working on #3048, part of how I checked page titles for consistency was by scraping each page for the `title` and `h1` and comparing them, a task that was complicated by our component and guidance statuses being housed within the `h1` element.
As it turns out, [this is invalid HTML](https://github.com/alphagov/govuk-design-system/issues/2606), so I figured I'd whack it on the head while it's on my mind. 
Resolves #2606.
- Moves the status content outside of the `h1` element to directly below it.
- Adjusts the margin classes to maintain the existing spacing between elements.
- This includes a new if-block to override the `h1`'s bottom margin if a status is present.
- Changes the status container from a `div` to an `aside`. This seems potentially semantically appropriate if you …
=> Improvements to document statuses HTML

.prettierignore, config/navigation.js, lib/extract-page-headings/fixtures/src/example-with-aliases.md, lib/extract-page-headings/fixtures/src/example-with-page-nav.md, lib/extract-page-headings/fixtures/src/example-with-search.md, lib/extract-page-headings/index.js, lib/extract-page-headings/index.test.js, lib/metalsmith-lunr-index/fixtures/src/with-page-headings.md, lib/metalsmith-lunr-index/index.js, lib/metalsmith-lunr-index/index.test.js, src/styles/layout/index.md, src/styles/typography/index.md, views/partials/_subnav.njk
This is a quick supporting PR for:
* https://github.com/alphagov/govuk-design-system/pull/3106
I've extended page heading `aliases` to also include `url`, `ignoreInPageNav` and `ignoreInSearch`
Heading aliases were configurable
```yaml
headingAliases:
Section break: horizontal rule, hr
```
Headings can now be excluded from the side navigation, search, or given a custom URL fragment
```yaml
headings:
- text: Section break
aliases: horizontal rule, hr
- text: Section example
url: section-override
- text: Section link not indexed or shown
ignoreInPageNav: true
- text: Section link not indexed only
ignoreInSearch: true
```
=> Add options `ignoreInPageNav` and `ignoreInSearch` to headings

docs/contributing/adding-images-to-the-wesite.md
Adds guidance for adding images to the website, encouraging best practice when adding an image to mitigate risk of harming website performance. This is intended to be primarily internal facing content, but could be useful to anyone contributing to design system guidance.
This is intended as a small starting point for a wider piece of work to automate and generally improve the performance of "media" (images and videos) on the website.
=> Add guidance on adding images to website content

lib/get-macro-options/index.js
We didn't need to add parent prefixes in https://github.com/alphagov/govuk-design-system/pull/3107
Duplicate **Hints** and **Labels** are automatically removed from the page already
For these two components, this PR puts the original names back
You can see where this was already handled here:
https://github.com/alphagov/govuk-design-system/blob/6a3d9931ed141c8206d7bc1e3db89fa51d7c8a35/lib/get-macro-options/index.js#L119-L123
=> Remove parent prefix from nested component display names

src/components/panel/index.md
Update the panel guidance so that the paragraph on long words also covers "highlighted information" eg: reference numbers.
Co-authored with @calvin-lau-sig7 
Fixes https://github.com/alphagov/govuk-design-system/issues/2899. More information in the issue.
=> Extend panel guidance to advise not using long highlighted information

__tests__/cookies-page.test.js, src/components/cookie-banner/client-side-accepted/index.njk, src/components/cookie-banner/client-side-rejected/index.njk, src/components/cookie-banner/client-side/index.njk, src/components/cookie-banner/default/index.njk, src/components/cookie-banner/multiple-cookies/index.njk, src/components/cookie-banner/server-side-confirmation/index.njk, src/components/cookie-banner/server-side-multiple-messages-confirmation-visible/index.njk, src/components/cookie-banner/server-side-multiple-messages-question-visible/index.njk, src/components/cookie-banner/server-side/index.njk, src/cookies.njk, src/javascripts/components/cookies-page.mjs, src/patterns/cookies-page/cookies-form/index.njk, src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk, views/partials/_cookie-banner.njk
Follows on from https://github.com/alphagov/govuk-design-system/pull/3115 to fix a few things spotted by `html-validate`
1. Add button `type="button"` to **Hide cookie message** client-side buttons
1. Add button `type="submit"` to **Hide cookie message** server-side buttons
1. Remove button `href="#"` from **Hide cookie message** server-side buttons
1. Remove button `name` and `value` from various client-side examples
To solve a gotcha I've hit in the past too, the [Cookie banner](https://design-system.service.gov.uk/components/cookie-banner) and [Cookies page](https://design-system.service.gov.uk/patterns/cookies-page/) form fields now match
E.g. The same server-side middleware could respond to form submissions from either the banner or page
I've updated the [**Customised page template** …
=> Various fixes for `html-validate` (cookie banner buttons)

lib/get-macro-options/index.js, src/stylesheets/main.scss
Just splitting out some ideas from https://github.com/alphagov/govuk-design-system/pull/2892
This PR adds the nested option `type` to macro option table captions
* **Options for `example`** – Used for nested arrays, objects and components
* **Options for `example` object** – Used for nested objects
* **Options for `example` array** – Used for nested arrays (without params)
* **Options for `example` array objects** – Used for nested arrays (with params)
* **Options for `example` component** – Used for nested components
| Before  | After |
| ------- | ----- |
| <img width="782" alt="Table captions for nested options" src="https://github.com/alphagov/govuk-design-system/assets/415517/3023e100-4cab-4a8d-a4ad-c37aeba2daf0"> | <img width="780" alt="Table captions for nested options showing …
=> Show nested option type in table captions

src/community/resources-and-tools/index.md
This open source library is used within DfE and is built upon by https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions.
=> Add a link to GOV.UK Frontend ASP.NET Core library

__tests__/search.test.js
This PR fixes a bug that only affects local development builds
Consider the following:
* When running locally using `npm test` we **do** add hash fingerprints to generated assets
* When running locally using `npm start` we **do not** add hash fingerprints to generated assets
Since `npm test` overwrites a development build with a production build, we must run `npx jest` directly as shown
1. In Terminal 1, run `npm start`
1. In Terminal 2, run `npx jest --watch __tests__/search.test.js`
You'll see two failures because requests to `search-index.json` (without a hash fingerprint) are not mocked:
```console
● Site search › shows user a message that the index has failed to download
expect(received).resolves.toBe(expected) // Object.is equality
Expected: "Failed to load the search index" …
```
=> Fix local `search-index.json` test (no hash fingerprint)

.gitignore, package.json
We have a very flaky `npm run check-links` script at the moment
This PR partially fixes https://github.com/alphagov/govuk-design-system/issues/3113 and https://github.com/alphagov/govuk-frontend/issues/4223 makes the link checker stable by:
~1. Avoiding **sitemap.xml** parsing~
2. Remove flag `--source-maps`
~3. Remove flag `--recursive` (uses glob instead)~
~4. Replace reporter [`tap-mocha-reporter`](https://www.npmjs.com/package/tap-mocha-reporter) with [`tap-min`](https://www.npmjs.com/package/tap-min)~
5. Saving output to disk before piping to reporter
In the past we've [switched reporter](https://github.com/alphagov/govuk-frontend-docs/commit/3e3adb6e2f28aa14e7706fecce81b34b11f5d967) to increase stability but see https://github.com/Munter/hyperlink/issues/179#issuecomment-619537282. …
=> Fix flaky broken link checker

src/components/tag/all-colours/index.njk, src/components/tag/index.md
This updates the Tag component guidance to reflect [design changes made](https://github.com/alphagov/govuk-frontend/pull/3502):
Changes made:
* removes the guidance about not mixing "solid colours" and "tints", as all the tags use lighter background colours now
* added some content to the Research section about why the design changes were made
* adds the new "light blue" tag colour to the example showing all the colour options
➡️ [Preview of the changes](https://deploy-preview-2733--govuk-design-system-preview.netlify.app/components/tag/)
=> Tag component: updated guidance 

src/community/roadmap/index.md
I've set myself the task of reviewing and updating the roadmap each month, based on the latest plans.
In late August I accidentally removed task list from the plans, but our intention is very much to continue with it. So adding it back in to reflect that.
=> Update the roadmap to align with plans

src/community/share-research-findings/index.md
Draft of some guidance to help teams share useful research findings about things in the Design System
=> Draft: 'share user research' guidance

src/community/design-system-day/index.md
We're not going to issue tickets through Eventbrite any more, so removing the link. It should stop the support tickets about getting a ticket too.
=> Remove links to tickets

src/community/design-system-day/speaker-information.md
A few extra spaces have snuck into recent PRs. This is to let us do work on other parts of the website without being tripped up by our local testing.
=> Run prettier on speaker information

src/community/design-system-day/session-information.md
Some sessions have had to be cancelled at short notice. This commit marks them as having been cancelled, but keeps them in the schedule for people who may be looking for them.
=> Add warning to cancelled DSDay sessions

src/patterns/complete-multiple-tasks/index.md
We forgot to update this line when renaming the page... 🤦
=> Fix opening line on task list pattern page

.gitattributes
This PR prevents [**EditorConfig** check failures](https://github.com/alphagov/govuk-frontend/pull/2863/commits/dfe47a5fe0e95f4196a600fdfd4fc7142e5f11e9) on Windows
The change adds `* text=auto eol=lf` to **.gitattributes** copied from https://github.com/alphagov/govuk-frontend/pull/2863/commits/dfe47a5fe0e95f4196a600fdfd4fc7142e5f11e9
This was simpler than configuring [`core.autocrlf`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf) for every Windows developer
=> Ensure `git clone` uses LF line endings for EditorConfig

src/community/contribution-criteria/index.md, src/community/develop-a-component-or-pattern/index.md, src/community/resources-and-tools/index.md, src/components/accordion/index.md, src/components/cookie-banner/index.md, src/components/exit-this-page/index.md, src/components/notification-banner/index.md, src/components/tabs/index.md, src/patterns/bank-details/index.md, src/patterns/contact-a-department-or-service-team/index.md, src/patterns/cookies-page/index.md, src/patterns/exit-a-page-quickly/index.md, src/patterns/page-not-found-pages/index.md, src/patterns/problem-with-the-service-pages/index.md, src/patterns/service-unavailable-pages/index.md, src/patterns/telephone-numbers/index.md, src/styles/images/index.md
Removes the experimental status tag from all docs that use it, it's associated content and references to the experimental status in the tag component and the [develop a component or pattern guidance page](https://design-system.service.gov.uk/community/develop-a-component-or-pattern/).
Closes https://github.com/alphagov/govuk-design-system/issues/3194. More details in issue.
There's a reference to stuff being marked as experimental on the [contribution criteria page](https://design-system.service.gov.uk/community/contribution-criteria/):
>Components and patterns which are not proven usable can be published as experimental. But they must be clearly based on relevant user research from other organisations and best practice, and meet the other criteria.
Should we remove it?
Is removing the …
=> Remove experimental status tag and references to experimental status on website

src/community/share-research-findings/index.md
Change the wording of our template for sharing research findings with us to remove the word "key" from "key insights".
["Key" is a word to avoid as per the govuk styleguide](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#words-to-avoid)
Based on feedback from [this support ticket](https://govuk.zendesk.com/agent/tickets/5526787) (internal to DS team only)
=> Change wording of share research findings template

src/stylesheets/components/_example.scss, src/stylesheets/components/_tabs.scss
Reorganises border styling of the code example partial so that the outside border is now handled by `app-example-wrapper` and all blocks within an example ie: iframe, code block, tabs etc have a top border only.
Spotted during website testing work on https://github.com/alphagov/govuk-design-system/issues/2862
On mobile, instances of the code example where we only display the tabs and not the iframe, the top border of the example partial is missing. This is because we remove the top border from `app-tabs__heading` on the assumption that it'll be placed under an `app-example`, which has a full border.
=> Reorganise border cadence of example partials

src/community/index.md
A user on support has had difficulty accessing UK Government Digital slack today from the Community page link
=> Change the slack link to remove a backslash

src/stylesheets/components/_example.scss
Increase the font size of the "Open this example in a new tab" link as part of our example partials from 14 on the font scale 16. As we're removing 14 as an option in out font scale as part of https://github.com/alphagov/govuk-design-system/issues/2289, we should aim to not use it ourselves.
=> Increase font size of example new tab link to 16

src/community/index.md, src/community/share-research-findings/index.md
**From @Katrina-Birch:**
Can we change a link on the Community page? - so users go straight to here:
https://design-system.service.gov.uk/community/share-research-findings/
Under "Share your examples and research". The section will then do what it says on the tin. We want research findings on existing components, not just what we're working on. It will need a content tweak for the paragraph and a way to link to the what we're working on.
Also tweak the language to users rather than performance.
=> Update links to share findings page

src/community/accessibility-strategy/index.md
Update accessibility strategy with new dates now that WCAG 2.2 has been published
Clearer dates needed to acknowledge that WCAG 2.2 has been published, and monitoring will start.
=> Draft update of dates after WCAG 2.2 published

src/components/error-message/index.md, src/patterns/addresses/error-messages/index.njk
In a recent DAC audit they noted a usability issue with our error summary link text not matching the labels for inputs.
[This issue contains further detail on why we are making this change](https://github.com/alphagov/govuk-design-system/issues/3097).
=> New guidance on matching error message text to input label

lib/metalsmith.js, views/layouts/_generic.njk
This PR fixes a bug where only [Netlify `deploy-preview` and `dev` deploy contexts](https://docs.netlify.com/site-deploys/overview/#deploy-contexts) deny search engine indexing:
```html
<meta name="robots" content="noindex, nofollow">
```
We don't currently deny `branch-deploy` deploy context such as:
https://release-5-0--govuk-design-system-preview.netlify.app
This was spotted whilst catching up with https://github.com/alphagov/govuk-design-system/issues/3289
=> Prevent search engine indexing for Netlify branch deployments

views/partials/_banner.njk
Might as well use the same check as https://github.com/alphagov/govuk-design-system/pull/3307 to close https://github.com/alphagov/govuk-design-system/issues/3289
```njk
{#- Show banner for archive, preview and development builds only -#}
{% if ["branch-deploy", "deploy-preview", "dev"].includes(env("CONTEXT")) %}
```
=> Prevent banner on `main` Netlify deploys

deploy/nginx.conf, src/404.njk, src/errors/generic.njk, views/partials/_category-nav.njk, views/partials/_navigation.njk, views/partials/_subnav.njk
Another super quick one for Netlify support
Moves Nginx `/errors/404/index.html` to `/404.html` which also closes https://github.com/alphagov/govuk-design-system/issues/3281
Give it a try: https://deploy-preview-3309--govuk-design-system-preview.netlify.app/foo
=> Set up Netlify custom `404.html` page

src/components/select/error/index.njk, src/components/select/with-hint/index.njk
Fix incorrect indentation and `id` and `name` not relating to the examples being used.
=> Fix minor issues with select examples

src/community/resources-and-tools/index.md
Removes ~3~ 4 dead resources from our [resources and tools](https://design-system.service.gov.uk/community/resources-and-tools/) page:
- Govdown for R Markdown; the repo was archived April 2022
- GOV.UK Frontend Rails; the repo was archived in April 2023
- Atom snippets; github have discontinued Atom and the link now redirects to a github blog on their sunsetting plan (it was turned off December 2022)
- Adobe XD Wireframes; the repo hasn't been updated in 3 years and [Adobe have discontinued XD since purchasing figma](https://mondo.com/insights/adobe-xd-discontinued-implications-for-creatives-employers/)
There are several stale resources on that page but it's not clear if they should be removed. The inception for this PR was a user on support pointing out that the [Adobe XD …
=> Remove outdated resources and tools

src/patterns/complete-multiple-tasks/index.md, src/patterns/task-list-pages/index.md
Looks like we forgot to update the research section on the new task list pattern page (as we added the research to the new component page instead).
This updates the content.
=> Link "Complete multiple tasks" research to task list component

netlify.toml, src/form-success.html
A number of the examples in the Design System include `<form>` elements so that users copying the examples have something that requires relatively little tweaking to work out the box (in particular for Prototype Kit users, for example)
We have [some JavaScript to prevent those forms actually being submitted][1] but for users who don’t have JavaScript enabled (or who manage to interact with the form before the JS has run) it’s still possible to submit the form.
This adds the required Netlify config to handle that gracefully by redirecting to a page that explains what has happened and what the user needs to do next.
https://github.com/alphagov/govuk-design-system/assets/121939/ae293f18-fc10-47ae-bf95-104d7bcbb630
We’ve [previously tried to handle this by redirecting back to the referrer][2] …
=> Redirect form submissions somewhere sensible

package-lock.json.unit.test.mjs
We know some Dependabot `"optionalDependencies"` updates get incorrectly hoisted to `"dependencies"`
See our [Team Docs **Reviewing a PR from Dependabot**](https://govuk-design-system-team-docs.netlify.app/how-we-work/version-control/pull-requests#reviewing-a-pr-from-dependabot) for the manual checks we do
For safety, this PR adds a test for project-level `"dependencies"` to ensure we don't miss stray ones:
```patch
"license": "MIT",
"dependencies": {
+       "@types/node": "^20.10.5",
"accessible-autocomplete": "^2.0.4",
"clipboard": "^2.0.11",
"govuk-frontend": "^5.0.0",
```
For example, this test on PR https://github.com/alphagov/govuk-design-system/pull/3381 looks like:
=> Add test for incorrectly hoisted Dependabot updates

src/community/share-research-findings/index.md
This feels like an important topic to discuss but if raising a PR to do it isn't right, if we should instead start a community discussion (on GitHub, in a community call, or elsewhere), let me know what you think.
It can be hard to establish the importance of fixing a problem or making a design change based on some of the evidence we receive. It's not clear how confident in the evidence the team is, and therefore we can be hamstrung on whether to act on the reported problem or request. But better data and more context could lead to more robust decisions, and therefore better support for services.
A few times I've seen insights shared from research or testing where the evidence wasn't robust (in my opinion). The research had 6 participants and 1 person mentioned needing something, and this …
=> Add line about qual or quant study on sharing insights

src/community/design-system-day-2023/session-information.md
Add
- a link to the resources mentioned during the trauma informed panel discussion
- content advising users to contact the team if they want access to slide decks from day 2
=> Add further Design System Day 2023 content

views/partials/_example.njk
This PR takes adds a third flavour of nested component option:
1. Nested option
2. Nested option as `option.isComponent` with link to all component options
3. Nested option as `option.isComponent` with subset of options via `option.params`
For example **Checkboxes** and **Radios** `label` option only supports a subset of options:
* https://github.com/alphagov/govuk-frontend/issues/1779
This is also logged on our [Trello board (internal)](https://trello.com/c/RxuFrKQS/19-radio-and-checkbox-item-nested-label-components-list-options-that-cant-be-used)
Nested components can only link to their separate Design System guidance pages
Nested components with a subset of `option.params` get their own options table too
Now **Checkboxes** and **Radios** `label` option shows it supports only `classes` …
=> Add links to nested components with subset of options

src/styles/links/index.md, src/styles/lists/index.md
This PR adds links to the 'links' and 'lists' pages that take you to the typography discussion on GitHub.
A user raised on Slack that they were looking for some historic design context about links and couldn't find it from the links page.
We don't have specific pages for links, as the page was broken out from the typography page in https://github.com/alphagov/govuk-design-system/pull/3106. We had a short chat and decided to just link to the historic typography discussion for now, rather than try create a new issue in the backlog repo.
I've applied the same approach to lists, as it has the same problem.
Is it a problem that the link says to 'discuss links/lists on github' but actually goes to a page about typography? Is there a way around this?
=> Add links to GitHub discussions on links and lists pages

netlify.toml
Closes #3323 with `Cache-Control` headers only for known files with fingerprint hashes
We've chosen not to restore the [30 minute expiry times for images and videos](https://github.com/alphagov/govuk-design-system/pull/3402/commits/6a9681d83abe2ad96078ddebc120e74b343af50c#diff-402dd7ffa98c26c1269efd4ffd9a5048e88e20c306cb0df8e05306711e9fe781L92-L113) such as:
* [/images/homepage-illustration.svg](https://deploy-preview-3417--govuk-design-system-preview.netlify.app/images/homepage-illustration.svg)
* [/patterns/payment-card-details/enter-card-details.jpg](https://deploy-preview-3417--govuk-design-system-preview.netlify.app/patterns/payment-card-details/enter-card-details.jpg)
* [/patterns/payment-card-details/card-number.mp4](https://deploy-preview-3417--govuk-design-system-preview.netlify.a …
=> Configure Netlify `Cache-Control` headers

src/community/roadmap/index.md, views/partials/_whats-new.njk
This PR is to add comms changes to our website after publication of pull request [WCAG 2.2 guidance updates #3090](https://github.com/alphagov/govuk-design-system/pull/3090)
N.B. This will have broken links until the above PR is changed and merged.
=> WCAG 2.2 what's new and roadmap changes

src/stylesheets/components/_navigation.scss
This PR fixes the `$from: tablet` navigation menu width to occupy an extra 30px space
The extra available width is due to our `left: -15px` gutter offset, but we didn't use it
Menu item “Accessibility” doesn't fit at 768px width
Menu item “Accessibility” now fits at 768px width
=> Fix navigation `$from: tablet` gutter offset

src/accessibility/wcag-2.2/index.md, src/components/select/index.md, src/components/tag/index.md, src/patterns/confirm-an-email-address/index.md
Follows-up on few outstanding comments from #3090 
- changing links to Markdown (fixing a previous issue with brackets in link text, fixed by using `/` escape)
- add a missing overview criteria for 'Problem with a service' pages
=> WCAG 2.2 content follow-up

src/components/summary-list/index.md, src/patterns/passwords/index.md
This change adds 'or' to the statement to clarify the exception to the 'Target Size (Minimum) (Level AA)' guideline which states targets can be undersized if: "...are positioned so that if a 24 CSS pixel diameter circle is centered on the bounding box of each, the circles do not intersect another target or the circle for another undersized target;"
See comment: https://github.com/alphagov/govuk-design-system-backlog/issues/182#issuecomment-1887303500
=> Update WCAG 2.2 guidance on summary action links minimum size and spacing

src/community/blogs-talks-podcasts/index.md
Changed the 'Focus not obscured' workshop date from 18 July to 5 July.  Evidence of the correct date was found via the archived Eventbrite workshop page: https://www.eventbrite.co.uk/e/wcag-22-criteria-workshop-focus-not-obscured-tickets-665281102687
=> Correct date of 'focus not obscured' workshop

src/community/resources-and-tools/index.md
This was mentioned as being an additional link in the GitHub discussion [Add GOV.UK Mural template to community resources #250](https://github.com/alphagov/govuk-design-system-backlog/issues/250).
=> Add Mural template to 'Create prototypes and wireframes'

src/accessibility/wcag-2.2/index.md
This pull request changes the sentence:
> Revisit the [Government Digital Service (GDS) guidance](https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps) on accessibility is and why your service needs to invest in it
to 
> Revisit the [Government Digital Service (GDS) guidance](https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps) on what accessibility is and why your service needs to invest in it
=> Add 'what' into WCAG 2.2 page

views/layouts/layout-sitemap.njk
This changes the pattern to prefix 'also know as' to 'includes' to a list of aliases of design system pages that have them.
This should enable us to include more on the page content in search results. 
For example, information on hint text is given across multiple component and pattern pages. Our site search analytics data shows that it is third most likely result to return 'no result' over the past year (18 Jan 2023 - 18 Jan 2024).
Most reference to hint text is given within context so writing separate guidance for it might be equally hard to understand and/or find. 
This suggestion means that across the website we could alias included content to the pages we think are the most suitable.
=> Change 'also known as' to' includes' on the sitemap for aliases

src/stylesheets/main.scss
We got rid of this var and turned new link styles on by default in 5.0, so we don't need this variable anymore!
=> Remove $govuk-new-link-styles

src/styles/layout/grid-nested-annotate.scss, src/stylesheets/components/_example.scss, src/stylesheets/components/_navigation.scss, src/stylesheets/components/_page-navigation.scss, src/stylesheets/components/_site-search.scss, src/stylesheets/components/_subnav.scss, src/stylesheets/components/_tabs.scss, src/stylesheets/main.scss
Removes uses of `govuk-font` which are unnecessary, typically because typographic elements such as the font family are cascading from elsewhere and only a font size change may be necessary.
Similar to https://github.com/alphagov/govuk-frontend/pull/4267
Impact on CSS output is fairly minimal. Running `build` against this branch vs `main` shows that this branch's CSS is ~1 kilobyte~ 2 kilobyets lighter. I would still argue this is a useful change on the basis that it's ensuring we don't duplicate CSS unnecessarily.
Several removes of `govuk-font` are because that element's `typography-common` is being defined by `app-prose` and cascading down. In some cases this is convenient but not intentional eg: `app-tabs__item` only needing `govuk-typography-responsive` because `app-prose` is applying …
=> Remove unnecessary uses of govuk-font

views/partials/_subnav.njk
Does what it says on the tin. A minor enhancement to our subnav to make it easier for screen reader users to know where they are.
Only applied to the subnav as opposed to the top-level nav as it's harder from [the spec](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) to denote sections of a website.
=> Add `aria-current="page"` to subnav links

src/components/table/index.md, src/components/table/lots-of-data/index.njk
Add a section to the bottom of the tables page with instructions on how and when to use the small text from tablet modifier introduced in https://github.com/alphagov/govuk-frontend/pull/4630.
Closes https://github.com/alphagov/govuk-frontend/issues/3922
> [!IMPORTANT]
> This change can only be merged after the new typography scale is launched as part of https://github.com/alphagov/govuk-design-system/issues/3456
So that we are advertising that this feature exists to users as well as adding some light guidance on minimising data in a table where possible.
I need to make it clear that this is currently only tied to 5.2 if you turn the feature flag on. This could link to the new scale guide that now lives in https://github.com/alphagov/govuk-design-system/pull/3343.
=> Add guidance for tables with lots of data

src/community/roadmap/index.md, views/partials/_whats-new.njk
Updates the what's new section on the homepage and the roadmap page with 5.2.0 comms.
Also removes references to 5.0 and the crown releases from the roadmap and moves navigation work into the list of things we're doing now.
Closes https://github.com/alphagov/govuk-design-system/issues/3489
=> Update the What's new section and roadmap for 5.2.0

src/community/upcoming-components-patterns/index.md
We've updated on [the 'Roadmap' page](https://design-system.service.gov.uk/community/roadmap/) but @joelanman noticed that Navigation is still under ['Next priorities' on the 'Upcoming components and patterns'](https://design-system.service.gov.uk/community/upcoming-components-patterns/#next-priorities). 
This PR moves it into [the 'Working on now' section](https://deploy-preview-3593--govuk-design-system-preview.netlify.app/community/upcoming-components-patterns/#working-on-now).
=> Move navigation to 'Working on now' section

src/accessibility/wcag-2.2/index.md
On the 'Changes to meet WCAG 2.2' page, [we received feedback from a user](https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6/p1706258637961479) that they did not understand what the data in the 'Relevant WCAG 2.2 criteria' column of the table went. It's also possible they did not have context on WCAG and its criteria and how they related to accessibility, and the page does not explain this.
Alongside a hypothesis that it's common for users to overlook table headers (and therefore miss needed context to understand table data), there could be more context on this page of what WCAG success criteria are and how they work.
Still to decide, whether to:
- add a single link on the page
- add before each instance of the table
- add link in the table header "Relevant WCAG 2.2 criteria" (but …
=> Add more links that explain each WCAG 2.2 criteria

views/partials/_whats-new.njk
What it says on the tin.
From [skimming the history](https://github.com/alphagov/govuk-design-system/commits/main/views/partials/_whats-new.njk) I suspect this was added as part of the prototyping of the What's New section and we just forgot to scoop it out. We may want to reintroduce it as part of exploration into https://github.com/alphagov/govuk-design-system/issues/1974 but for now let's keep the partial nice and lean.
=> Remove redundant `govukButton` import from whats-new partial

src/components/password-input/default/index.njk, src/components/password-input/error/index.njk, src/components/password-input/index.md, src/patterns/passwords/index.md
WIP of some guidance for the password input component, transposing content from the "ask users for passwords" pattern guidance where it seems relevant.
Related to: 
- #3352
- #3353
Still needs examples.
=> Add guidance for password input component

src/components/password-input/index.md
Adds a direct link to our backlog issue summary on confirm password fields.
=> Add link to 'confirm password' backlog summary

src/components/password-input/index.md
Markdown isn’t parsed within HTML, so the backticks around `autocomplete` aren’t being converted to inline code.
Mark them up as HTML using the `<code>` element instead so it displays correctly.
=> Fix inline code in WCAG 2.2 callout

src/community/upcoming-components-patterns/index.md
Removes date from prioritisation list, as it's currently outdated for summer 2023.
We're also not sure whether we'll undergo the same process to review the list next time, so we're removing the date until we've decided the process for next time.
=> Remove date from prioritisation list

src/components/header/index.md
The transition period for rolling out the Tudor crown has ended. We can likely remove this guidance now.
=> Remove crown update guidance

src/patterns/start-using-a-service/index.md
Fixes a duplicate line in the Start page pattern, also strengthens the language a bit re: approval process.
=> Fix duplicate line in Start page pattern

src/components/accordion/index.md, src/styles/colour/index.md
Hello 👋
I've been on the [**Colour** styles page](https://design-system.service.gov.uk/styles/colour/) a bit recently and spotted a few hard line breaks affecting the layout
Most have been fixed already (e.g. https://github.com/alphagov/govuk-design-system/pull/2709/commits/41a5f1065a84d87f5f857ca737938b78ab00f91f, https://github.com/alphagov/govuk-design-system/pull/2991/commits/099bfd4fcfb7e3fa2d0a8149d57a14f2a6c2227a) but I found a few more
---
---
=> Fix hard breaks on Colours and Accordion pages

src/stylesheets/main.scss
Change `main.scss` to only import what the website is using so that we are serving less css to users. Part of https://github.com/alphagov/govuk-design-system/issues/3732.
This change reduces the built `main.css` by approximately 22kb.
There are a few things in here that are only relevant to full page examples because we are using the same asset set for full page examples and the website. We can investigate this later via https://github.com/alphagov/govuk-design-system/issues/3757 but for now we think this is still a useful gain.
What the website uses was discovered via post-processing analysis using rehype. You can see what we did in https://github.com/alphagov/govuk-design-system/tree/optimise-website-imports
=> Only use scss that the website is using

src/javascripts/application.mjs, views/partials/_header.njk
Updates `application.js` to only initialise the components that the website is using to optimise website performance. Part of https://github.com/alphagov/govuk-design-system/issues/3732.
This change reduces `application.js` by approximately 36kb.
This change imports the component js directly from the mjs in the component folders instead of importing directly from `govuk-frontend` via combined curly brackets as we'd expect our users to do. This is because we've noticed as part of this work that our tree shaking doesn't work when importing the "expected" way and only works when importing the components directly. See https://github.com/alphagov/govuk-frontend/issues/4957.
This was made possible by Romaric's work to figure out what `data-module`'s the website is using in …
=> Only import the js from GOV.UK Frontend that the website is using

package-lock.json, package.json, src/community/roadmap/index.md, views/partials/_whats-new.njk
- Updates the package version
- Update the "What's new" section on the homepage
- Update the 'Recently shipped' section on the 'Roadmap' page
=> Update to GOV.UK Frontend v5.4.0

src/javascripts/application.mjs, src/stylesheets/_example-init.scss, src/stylesheets/main.scss
Makes 3 changes across our sass and js importing and initialisation:
1. Removes the workaround to issues with our treeshaking introduced in https://github.com/alphagov/govuk-design-system/pull/3766 now that https://github.com/alphagov/govuk-frontend/issues/4957 is resolved and published
2. Uses the `createAll` method to initialise our js following it's introduction in https://github.com/alphagov/govuk-frontend/issues/4945
3. Removes `all` from the sass import paths as per the changes in https://github.com/alphagov/govuk-frontend/issues/4960
This is a redux of https://github.com/alphagov/govuk-design-system/issues/3732 following all the work done via https://github.com/alphagov/govuk-design-system/issues/3731 in the last cycle.
There are no changes in file size for compiled js and css …
=> Tidy up how our sass and js is imported

src/components/accordion/index.md
Add extra documentation for the 'id' attribute to the 'How It Works' section of the accordion component.
if a user is just using the HTML of the accordion component, then they might not encounter the additional documentation provided for the 'id' attribute. This addresses issue #1073.
=> Add documentation for 'id' to accordion component

src/components/phase-banner/beta/index.njk, src/components/phase-banner/default/index.njk, src/components/phase-banner/index.md
The link text in our examples isn’t very good. It’s just the word ‘feedback’ that’s linked, which is ambiguous and so it's unclear where the page takes you – it could be a way to view feedback that the service has received, for example.
Improve the link text by making more of the sentence part of the link, and also make it clear how the user will give feedback (by email, or in a form that opens in a new tab).
Restructure the sentence to put the link at the end of the sentence.
Also tweak the structure of the guidance to:
- Move ‘Use an alpha banner when your service is in alpha, and a beta banner if your service is in private or public beta.’ under ‘How it works’ as it’s more about how to use the component than when to use the component.
- Move the paragraph starting ‘There are 2 ways to …
=> Improve link text in phase banner examples and restructure guidance

src/styles/font-override-classes/index.md
The 'tabular numbers' section is nested beneath the 'font weight' heading, but tabular numbers are unrelated to font weight.
This PR bumps tabular numbers up to a second-level heading. This means that it will appear in the in-page navigation sidebar.
=> Fix heading level of tabular numbers override class

src/accessibility/index.md, src/accessibility/wcag-2.2/index.md
I noticed that the meta descriptions for these pages were either incorrect or holder copy, so I fixed them. I’m not precious about what I’ve written so feel free to rewrite both, @calvin-lau-sig7.
=> Fix a11y page descriptions

__tests__/cookie-functions.test.mjs, src/cookies.njk, src/javascripts/components/cookie-functions.mjs
Adds GA4 cookies to our cookie functions and updates our cookie policy, as per [GA4's cookie docs](https://support.google.com/analytics/answer/11397207?hl=en).
Part of https://github.com/alphagov/govuk-design-system/issues/3863
We've started migrating to GA4 and need to handle GA4's settings in our consent. This change reflects what GA4 is capturing and ensures we are deleting the correct cookies when a user withdraws consent after accepting.
GA4 appears to be stripping out UA cookies at initialisation, meaning that we in theory don't need to worry about UA anymore. I'm opting to play it safe though and maintain UA's consent management with a view to go back in and get rid of it after July 1st when our UA properties are due to be shut down.
=> Add GA4 cookies to our cookie functions

__tests__/cookie-functions.test.mjs, src/cookies.njk, src/javascripts/components/cookie-functions.mjs
A followup to https://github.com/alphagov/govuk-design-system/pull/3866 because we missed a few things:
- We're in fact still setting UA cookies so we should still list these in our cookie policy
- We should still set the `ga-disable` `window` property using GA4 monitoring IDs to be absolutely sure that GA doesn't erroneously track interactions after a user has opted out of tracking consent
=> Update GA4 cookie setup (again)

.github/ISSUE_TEMPLATE/cycle-brief.md
Adds a new template to the 'new issue' page in the Design System repo on Github.
It uses the format we've been using so far, but let me know if there are any tweaks that would make it clearer.
=> Add issue template for writing cycle briefs

__tests__/search.test.js, src/javascripts/components/search.tracking.mjs
Change the `site-search` event name to `site_search`.
To ensure that the event name for when a user searches is in keeping the GA4 Event Naming Rules which state that underscores should be used in event names.
=> Rename site-search to site_search

__tests__/cookie-functions.test.mjs, src/cookies.njk, src/javascripts/application.mjs, src/javascripts/components/cookie-functions.mjs
A followup of our migration to GA4 (https://github.com/alphagov/govuk-design-system/issues/3822)
We've finished moving our existing tags to GA4 and the old UA properties aren't collecting data and are in fact scheduled for deletion therefore we can get rid of our UA-specific code.
We still need to account for users who previously accepted UA cookies and GTM setting UA cookies still whilst our UA properties are waiting to be deleted, so we specifically target UA specific cookies for removal at the point they might be set and when we know a user has previously accepted marketing consent.
=> Remove references to UA from code

__tests__/search.test.js, src/javascripts/components/analytics.mjs, src/javascripts/components/search.tracking.mjs
Remove `ecommerce` field from `site-search` GA4 events. Add new `ecommerce` events that are fired upon `site-search` events also firing. 
In light of changes made in GA4, the site-search event structure has to be updated. Attributes have been renamed to be more in-line with events across GOV.UK. Ecommerce events have also been reworked to be compatible with GA4 ecommerce events.
Addresses https://github.com/alphagov/govuk-design-system/issues/3878
=> Update the site-search event structure

package.json
I found tests being prevented to run by linting errors that would be fixed on commit quite annoying during development,
as it forces you to fix formatting issue before getting feedback on whether your changes work OK from a functional standpoint.
Linting will run on commit and [CI (in parallel to tests there)](https://github.com/alphagov/govuk-design-system/blob/main/.github/workflows/test.yaml#L66-L88) to pick on formatting errors, so formatting issues will not slip through even if they are not checked by the `test` script.
=> Remove linting from 'test' npm script

.github/dependabot.yml
Similarly to [the GOV.UK Frontend repository](https://github.com/alphagov/govuk-frontend/pull/4999), make dependabot ignore eslint packages updates for now to avoid its process timing out and preventing the update of other packages.
=> Make dependabot ignore `eslint` and `eslint-*` dependencies

__tests__/accessibility-audit.test.js, __tests__/back-to-top.test.js, __tests__/component-options.test.js, __tests__/cookie-banner.test.js, __tests__/cookies-page.test.js, __tests__/example.test.js, __tests__/helpers/google-tag-manager.js, __tests__/helpers/puppeteer.js, __tests__/navigation.test.js, __tests__/search.test.js, __tests__/tabs.test.js, jest.config.mjs
Use Puppeteer's [request interception feature](https://pptr.dev/guides/network-interception) to isolate our tests from the actual Google Tag Manager (GTM) script, returning a mock script rather than the whole analytics script downloaded from Google.
This makes our tests no longer dependent to GTM having issues (either return 4XX response or errors in the script themselves), which make our tests fails as jest-puppeteer would exit the browser when uncaught errors occur.
The PR also add extra tests to the cookie-banner and cookie-page test suites, to verify that the script for GTM is actually loaded in the page when necessary and analytics immediately disabled when needs be. So far, we didn't have any tests for that, with the cookies-functions tests only checking [that `loadAnalytics` was …
=> Mock script injected to load Google Tag Manager

.husky/pre-commit
These lines of Husky setup code have been non-operational since Husky 9.0. It is now recommended to remove them, as they are likely to error with future releases of Husky.
- Removes the now deprecated code.
- Changes the npx command to replace [the deprecated `--no-install` flag](https://docs.npmjs.com/cli/v9/commands/npx?v=true#compatibility-with-older-npx-versions) with the replacement `--no` flag. 
- [Husky 9.0.0/9.0.1](https://github.com/typicode/husky/releases/tag/v9.0.1) removed the requirement to include shebang declarations and the Husky shell file in hook files. Husky still supported the code being present for backwards compatibility purposes, but silently ignored it. 
- [Husky 9.1.1](https://github.com/typicode/husky/releases/tag/v9.1.1) officially deprecated the lines and …
=> Remove deprecated Husky setup code

src/styles/font-override-classes/break-word/index.njk, src/styles/font-override-classes/index.md
We added a new typography override class (`govuk-!-text-break-word`) into govuk-frontend that breaks long words across multiple lines if the word would otherwise not fit into its parent container. https://github.com/alphagov/govuk-frontend/pull/5159
The most common example of this is probably long email addresses on narrow viewports, but it may also be an issue for the text in data tables, technical and scientific terms, or when localising content into languages with long compound words such as German.
This is a first pass at some guidance about the override class.
**[Quick link to the draft guidance.](https://deploy-preview-3968--govuk-design-system-preview.netlify.app/styles/font-override-classes/#breaking-up-long-words)**
> [!WARNING]
> This should not be merged until a version of …
=> Add guidance for break-word override class

src/styles/colour/index.md
As a companion piece to https://github.com/alphagov/govuk-frontend/pull/3407, it has been suggested we expound upon where we source the list of organisation colours from, as there is (semi-frequent) disagreement over what they're supposed to be.
> [!WARNING]
Don't merge this until https://github.com/alphagov/govuk-frontend/pull/3407 has been merged and released.
=> Add expanded information about organisation colours

.github/dependabot.yml
This should make Dependabot look at updating our own dependencies before the other groups.
=> Add group for our own dependencies in Dependabot config

src/stylesheets/components/_site-search.scss
Changes the search icon to be white if the user is using a dark forced colour mode (such as Windows High Contrast Mode). This aids in keeping the icon clearly visible in these modes. Resolves https://github.com/alphagov/govuk-design-system/issues/4016. 
- Add CSS to override the icon with a white coloured version if the user is has `forced-colors` active and the `color-scheme` is judged to be `dark`.
- These determinations are made by the browser and operating system. This means that there is still the possibility of a dark coloured icon appearing on a dark background or a light coloured icon on a light background, but this is largely out of our control.
- Refactors the icon SVG into a private Sass function to avoid repetition.
The Design System's search form is almost entirely generated …
=> Invert search icon colour in dark forced colour modes

views/layouts/layout-archived.njk
Whitespace inside the link was causing:
- a visible underlined space on Chrome
- the period to go to the next line on Firefox
=> Fix extra whitespace around link to National Archives

src/accessibility/index.md
Resolves cases of headings jumping straight from h1 to h3 on the accessibility landing page.
Partially resolves #4025.
- Bumps up the heading levels on the accessibility landing page from h3 → h2.
=> Fix non-sequential heading hierarchy on accessibility page

.browserslistrc, babel.config.js, package-lock.json, package.json, rollup.config.js, src/.eslintrc.js, src/javascripts/application.mjs, src/javascripts/components/back-to-top.mjs, src/javascripts/components/cookie-banner.mjs, src/javascripts/components/cookies-page.mjs, src/javascripts/components/copy.mjs, src/javascripts/components/example-frame.mjs, src/javascripts/components/example.mjs, src/javascripts/components/search.mjs, src/javascripts/components/tabs.mjs
As using `createAll` requires component to hold a static `moduleName` property, this PR updates the build process to add transpilation of the JavaScript with Babel (rather than relying on code being authored to match JavaScript features, linted by [es-x](https://eslint-community.github.io/eslint-plugin-es-x/)).
It then uses createAll to instantiate components that were previously looked up using `document.querySelector[All]` in `application.js`.
- `OptionsTable` works based on the hash, rather than specific elements on the page. It could actually be refactored as a function rather than a class.
- `Navigation` doesn't really have a 'root' element as it looks things up in the document. It could be broken down into two components with root elements, one for the menu itself and the other for …
=> Use `createAll` to initialise components in the Design System site

.github/dependabot.yml
It seems to have done it so far, but with the update popping up on the Design System site, better be safe than inadvertentnly use a GPL dependency which would make us have to change our licence as well
=> Make dependabot ignore major bumps for iframe-resizer

src/stylesheets/components/_header.scss, views/partials/_header.njk
GOV.UK Frontend 5.6.0 includes a new modifier class to make the Header's bottom border full width, negating the need for the Design System website to keep doing this with custom CSS.
Resolves https://github.com/alphagov/govuk-design-system/issues/4086.
- Adds the new modifier class to the sitewide header.
- Removes the custom CSS and classes previously being used to do this.
- Renames the remaining class name, used to alter the size of the logo container, so that it meets BEM conventions.
=> Update header to use full width border class

src/components/header/index.md, src/components/phase-banner/index.md, src/components/service-navigation/index.md, src/patterns/navigate-a-service/index.md
Resolves inconsistent guidance on Phase banners in the navigation pattern.
Also fixes some issues caught in proofreading in https://github.com/alphagov/govuk-design-system/issues/4089
=> Update phase banner guidance, plus fix typos

src/community/resources-and-tools/index.md
Hi,
Hope this is the right way to submit this. I've written a Vue component library called [GOV.UK Vue](https://govukvue.org). It supports almost every component in Frontend - the exception being 'Exit this page', as it's probably not an appropriate choice for the kinds of public-facing services that might use that component.
Generated markup is the same as Frontend, with the exception of `data-` attributes. GOV.UK Vue doesn't use Frontend's JS, so these aren't needed. This also means that GOV.UK Vue components can coexist on pages alongside server-rendered components that do use the Frontend JS, as the Vue components don't have `data-module` attributes and won't be picked up by Frontend. This is documented on [Differences between GOV.UK Vue and GOV.UK …
=> Add GOV.UK Vue to community resources

src/components/date-input/index.md
A user suggested:
> On this page: https://design-system.service.gov.uk/components/date-input/
> 
> You say: “You will not normally need to use the autocomplete attribute in prototypes, as users will not generally be using their own devices.”
> I’d like to suggest removing this because:
>
> * It might have been true once, but these days so much UR is done over video call
> * You’d particularly expect accessibility users to use their own devices with their own settings
> * Omitting this from prototypes might result in it also being missed out of final designs, as it means someone has to remember to put it back in
> 
> So would you consider deleting this?
I think that makes sense. I was thinking about rephrasing it, but there is no harm in removing it completely and more harm in having it …
=> Remove no need to use autocomplete in prototypes

lib/marked/renderer.js, src/javascripts/application.mjs, src/javascripts/components/scroll-container.mjs
The recent audit noted a usability issue for users who navigated using the <kbd>Tab</kbd> key, wherein they would be made to stop at every code block as they all have the `tabindex` attribute set. #4007
We set `tabindex` intentionally so that long lines of code can overflow the container and be scrolled by using the keyboard's arrow keys. We want to maintain this ability (removing it entirely would be a likely violation of [Success Criterion 2.1: Keyboard Accessible](https://www.w3.org/WAI/WCAG21/Understanding/keyboard-accessible)) but would like to limit it only to blocks that need to scroll.
- Adds a `data-module` attribute to code blocks processed by Markdown.
- Adds JavaScript to attach a ResizeObserver to each code block.
- When the page is initially loaded, or the elements are …
=> Add overflow checks to code blocks to dynamically remove `tabindex`

src/accessibility/wcag-2.2/index.md, src/components/accordion/index.md, src/design-system-team.md
Taking the instances of bad heading hierarchy found via https://github.com/alphagov/govuk-design-system/pull/2957 and publishing them.
=> Fix incorrect heading hierarchies

src/accessibility/accessibility-strategy/index.md
Replaces the tilde on the accessibility strategy page with 'around'.
Resolves https://github.com/alphagov/govuk-design-system/issues/4024
Following a discussion of [the remaining issues from the 2024 audit of the design system website](https://github.com/alphagov/govuk-design-system/labels/audit%20july%202024), we've decided that we'll fix this specific reported issue but won't be auditing the website for instances of special characters, in the same way we're auditing our link text for https://github.com/alphagov/govuk-design-system/issues/4023 and https://github.com/alphagov/govuk-design-system/issues/4013.
The reason for this is that special characters are the lowest priority issue for the accessible content audit we're carrying out in response to DAC's reported content issues and we're …
=> Remove tilde from accessibility strategy content

src/global.d.ts, src/javascripts/components/back-to-top.mjs, src/javascripts/components/cookie-banner.mjs, src/javascripts/components/cookies-page.mjs, src/javascripts/components/copy.mjs, src/javascripts/components/embed-card.mjs, src/javascripts/components/example-frame.mjs, src/javascripts/components/navigation.mjs, src/javascripts/components/scroll-container.mjs, src/javascripts/components/search.mjs, src/javascripts/components/tabs.mjs, src/tsconfig.json
As govuk-frontend provides no types, TypeScript will type its exports as `any` but be unable to acknowledge fields inherited from parent classes. This leads to errors when trying to assign or use them.
[TypeScript's shorthand ambient modules](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#shorthand-ambient-module-declarations) seem to also make inherited fields typed as `any`.
This "empty" module will override any other definition of the `govuk-frontend` module, either in another `.d.ts` file or in `@types/govuk-frontend`.
Issue was, our project was not configured to look up for `.ts` file, meaning any `global.d.ts` file was overlooked by TypeScript. Adding `**/*.d.ts` file to the `tsconfig.json` in `src` allows TypeScript to find the shorthand ambient …
=> Add shorthand ambient module definition for 'govuk-frontend'

src/community/roadmap/index.md, views/partials/_whats-new.njk
Because the changes are small, we're adding to the existing sections rather than replacing them, so there's still a visible mention of the update to the coat of arms.
=> Update "What's new" and "Recently shipped" sections for 5.7.1

src/community/roadmap/index.md, views/partials/_whats-new.njk
@calvin-lau-sig7 This came to mind after approving the updates to the Design System site content. I'm wondering if we could add a link to the Frontend Docs to get people to how you'd go and build your JavaScript component.
I've also clarified that what we're offering is only for building JavaScript components, not any components.
=> Add link to Frontend docs related to v5.7.0

src/global.d.ts, src/javascripts/application.mjs, src/javascripts/components/back-to-top.mjs, src/javascripts/components/cookie-banner.mjs, src/javascripts/components/cookies-page.mjs, src/javascripts/components/copy.mjs, src/javascripts/components/embed-card.mjs, src/javascripts/components/example-frame.mjs, src/javascripts/components/navigation.mjs, src/javascripts/components/scroll-container.mjs, src/javascripts/components/search.mjs, src/javascripts/components/tabs.mjs, src/tsconfig.json, views/layouts/_generic.njk
Make components in `govuk-design-system` extend `Component`. This means we can:
- Rename `this.$module` to `$this.$root` in a given component
- Remove initialisation checks that occur in `Component` in a given component
- Use `isSupported` function to check component support in a given component
In addition, changes were needed to `EmbedCard` and `Navigation` in light of changes to how components are now initialised.
In this PR, we also add configuration for Typescript to look up `.ts` files, which allows us to be able to add a shorthand ambient module definition for `govuk-frontend`. This means Typescript/JSDoc will not throw any errors when calling `this.$root` in a class that extends `Component`.
`Component` is now available as of `v5.7.0` of `govuk-frontend`. We also have made changes …
=> Update components to use `Component`

views/partials/_whats-new.njk
Spotted that the blue link colour was slightly off!
| Before | After |
| ------ | ----- |
| <img width="722" alt="Screenshot 2024-10-11 at 21 39 17" src="https://github.com/user-attachments/assets/479f5814-df9d-4282-8d3d-7c9e0c3e0dda"> | <img width="736" alt="Screenshot 2024-10-11 at 21 39 02" src="https://github.com/user-attachments/assets/b06e38e3-b9f1-49d5-b013-c1a3b3d6c1fb"> |
=> Add missing link class

src/styles/images/index.md
Remove content duplicated at the end of the image guidance page. Presumably it got there due to a merge conflict.
=> Remove duplicated image guidance 

src/components/character-count/index.md
Mention the updates made in 2022, and link out to ~~David's excellent blog post~~ a GitHub issue comment which has more detail. Clarify that previous research (mentioned in the wiki link) was from 2017.
=> Update research section on character count component

src/components/cookie-banner/index.md
Add clearer language to explain the different scenarios our cookie banner guidance covers.
Based on backlog comment from a user that found the current wording confusing: https://github.com/alphagov/govuk-design-system-backlog/issues/12#issuecomment-1898436250
=> Clarify cookie banner options

src/community/design-system-day-2024/index.md, src/community/design-system-day/index.md
- Update to [Design System Day 2024 page](https://design-system.service.gov.uk/community/design-system-day-2024/)
- Update to[ Design System Day Events page](https://design-system.service.gov.uk/community/design-system-day/)
=> Add information about upcoming Design System Hack Day to the website

src/stylesheets/components/_site-search.scss
Adds a visual cue to the site search so that users whre zoomed into the input know that there is a dialog below that they may be able to interact with. When a dialog is displayed, the input will be given 'bottomless' styling to remove it's bottom border, making it visually flow into the menu and drawing the eye down.
This applies _any time_ there's a visible drop down, so for any number of results and when the 'no results' dialog displays.
Fixes https://github.com/alphagov/govuk-design-system/issues/4015
| Scenario | Before | After |
| - | - | - |
| Input focused | <img width="314" alt="Focused site search without bottomless styling" src="https://github.com/user-attachments/assets/7ea69934-34a1-4cb4-8986-285607c663a8"> | <img width="313" alt="Focused site search with bottomless styling" …
=> Add styling for site search input 'flowing' into dropdown

src/stylesheets/components/_site-search.scss
Something we missed in #4220. We control how the separator is displayed via 2 accessible autocompelte states:
1. the input has `aria-expanded="true"`, indicating it has results
2. the input has `aria-expanded="false"` but also no `aria-describedby` attribute, indicating that the 'no results' dialog is visible
The 2nd state however is also true when a user has entered text into the input and clicked away, resulting in the border being visible when there's no dropdown:
This change uses `app-site-search__input--focused` as an additional hook for that state. We already do something similar for controlling the focus state of the input further down.
=> Only show the site search results separator when input is focused

src/components/task-list/index.md
We no longer need this njk suffix since metalsmith does the nunjucks processing for us. I susepct this just got missed between the task list being a long contribution and us making changes to the website in the mean time.
Also reformats the list in the task list page. I'm not totally sure where this came from, possibly VS code automating formatting when it became a fully fledged markdown file. Far from an issue.
=> Remove njk suffix from task list index

src/patterns/question-pages/index.md
On support today a user noticed the repetition of 'like' under the H4 `Hint `on the Question pages guidance.
=> User noticed typo fix

src/community/blogs-talks-podcasts/index.md
Changes all links on the [Blog posts, talks and podacasts](https://design-system.service.gov.uk/community/blogs-talks-podcasts/) page to include what the thing is in the link eg: `[How we built the martial arts pattern] (blog post)` becomes `[How we built the martial arts pattern (blog post)]`.
This more clearly communicates what the link is and where it goes to. Part of https://github.com/alphagov/govuk-design-system/issues/4267.
Note that these changes have been pre-reviewed via [our link audit worksheet](https://docs.google.com/spreadsheets/d/1skSCpONh9VnPwOkhCvJimwH_9Az6d91A4ZxK4pDOmw4/edit?pli=1&gid=1372295640#gid=1372295640&fvid=1932937816).
=> Update the links on the blogs, talks and podcasts page

views/partials/_example.njk
Updates the link text for the generated links in our examples partial, where a nunjucks macro option has it's own params and the link jumps to that option's own option table.
Part of https://github.com/alphagov/govuk-design-system/issues/4267. This change will resolve 64 identified links that need clearer link text.
The first variation on line 120, which is used when a sub option is referencing a component that _isn't_ the hint or label "components", doesn't have any instances across our library. This makes it hard to test. I was able to hard code it appearing by removing the label and hint condition. See the below screen shot of an example from the Text input options:
=> Update sub-table link text in nunjucks macros

src/accessibility-statement.md, src/get-started/focus-states/index.md, src/get-started/index.md, src/get-started/production/index.md, src/get-started/prototyping/index.md, src/index.njk, src/privacy-policy.md
Changes identified unclear links on the homepage, root pages and Get Started sections
This more clearly communicates what the link is and where it goes to. Part of #4267.
Note that these changes have mostly been pre-reviewed via our link audit worksheet. Some require input from a technical subject matter expert, which will be done before push to publish.
=> Update the links on homepage, root pages and Get Started sections

src/components/checkboxes/index.md, src/components/date-input/index.md, src/components/fieldset/index.md, src/components/password-input/index.md, src/components/phase-banner/index.md, src/components/radios/index.md, src/components/summary-list/index.md, src/components/text-input/index.md, src/patterns/dates/index.md, src/patterns/equality-information/index.md, src/patterns/exit-a-page-quickly/index.md, src/patterns/navigate-a-service/index.md, src/patterns/phone-numbers/index.md, src/patterns/problem-with-the-service-pages/index.md, src/patterns/validation/index.md
Changes identified unclear links on all WCAG-related links on the Design System.
This pull request covers the remaining links in component and pattern pages now captured by our other batch edits in #4267. 
This more clearly communicates what the link is and where it goes to. Part of https://github.com/alphagov/govuk-design-system/issues/4267.
=> Update remaining links on component and pattern edits from worksheet

lib/metalsmith-lunr-index/index.js, lib/metalsmith-lunr-index/index.test.js, src/stylesheets/components/_site-search.scss
Reformats the metadata aka the 'section info' of search results in the site search so that they are more verbose. Specifically:
- results that are pages will now say 'in [Section]' where before they just said '[Section]'
- results that are headings in pages will now say 'part of [Page] in [Section]' where before we generated a visual only chevron and the metadata read '[page] [chevron] [Section]'
Spelling out our search results is both better for screen reader users and more clearly communicates our info hierarchy. Part of https://github.com/alphagov/govuk-design-system/issues/4195
This doesn't outright close https://github.com/alphagov/govuk-design-system/issues/4195 as we still want to write up some extra thoughts and findings and potentially iterate this design, based on feedback from …
=> Reformat search results metadata to be more verbose

src/stylesheets/components/_site-search.scss
What it says on the tin.
A followup of https://github.com/alphagov/govuk-design-system/pull/4290. With the new search results, it's easier to read the more verbose results across fewer lines.
370px has been picked because it's the longest we can make it whilst still conforming to the breakpoints.
Co-designed with @hazalarpalikli so just needs dev review.
=> Increase site search input to 370px

src/community/resources-and-tools/index.md
This update adds a new Express.js frontend skeleton that incorporates GOV.UK styles and components. The changes include modifications to the resources and tools index.md to support this integration.
=> Update resouces and tools index.md

tsconfig.base.json
As we're running into the same type issues as on GOV.UK Frontend, where some of our dependencies code have type issues, implements the same fix as in https://github.com/alphagov/govuk-frontend/pull/5550. It turns on the `skibLibCheck` option of TypeScript, making it not check the code of our dependencies (but still check that we use them correctly).
=> Enable TypeScript's 'skipLibCheck' option

src/accessibility-statement.md
This updates the accessibility statement to:
* be up-to-date with latest audits
* refer to WCAG 2.2 instead of WCAG 2.1
* fix some links that were previously leading to GitHub labels that have since been renamed
* fix some stylistic issues:
* add a heading for the "GOV.UK Design System website" section under "Preparation of this accessibility statement"
* consistently use singular verb after "team"
* and some other minor changes
This will close https://github.com/alphagov/govuk-design-system/issues/4269.
Before this can be merged, two things need to happen:
=> Update accessibility statement

src/javascripts/components/cookie-banner.mjs
Make the cookie banner extends `ConfigurableComponent` which is now exported from the latest version of `govuk-frontend`. Remove redundant code and update references to the config. Use the `defaults` functionality of `ConfigurableComponent` and provide a `schema`.
Fixes https://github.com/alphagov/govuk-design-system/issues/4275
=> Cookie banner extends `ConfigurableComponent`

views/partials/_contact-panel.njk
This currently goes to an "unavailable" page. Remove it and reinstate if we decide to start this survey back up again.
=> Remove old usage survey link

src/components/error-summary/index.md
The guidance makes it clear that the errorSummary should be focused on page load, but doesn't mention that this should happen for free with the govuk-frontend javascript.
Hopefully this makes it clearer so teams don't spend time trying to re-impliment this.
See similar PR on the [NHS Service manual](https://github.com/nhsuk/nhsuk-service-manual/pull/1980)
Fixes #3818
=> Update index.md to mention that govuk-frontend javascript will auto-focus

.github/dependabot.yml
Following discussions, and adjustment of dependabot frequency on govuk-frontend, we're adjusting this to monthly updates and changing how we triage dependabot PRs.
=> Adjust dependabot frequency

views/partials/_cookie-banner.njk
Earlier in the code a default `category` is set if one is not sent:
```
{%- set category -%}
{%- if params.category -%}
{{ params.category }}
{%- else -%}
analytics
{%- endif -%}
{%- endset -%}
```
However later on the code refers to `params.category` - which could be null. If it is null the javascript breaks. This PR refers to `category` instead to make sure a value is present.
=> Make use of default category var

views/partials/_example.njk
Use the new `option.deprecated` field to flag when an option has been deprecated. Optionally (though most commonly), we can also flag the version it was deprecated in and link to the relevant release notes.
Here's what the [header](https://deploy-preview-4488--govuk-design-system-preview.netlify.app/components/header/) looks like:
We've considered and dismissed other placements of the deprecated tag:
* In the name field
* This is a table header cell, so will be read out often on screenreaders - it's better for it be succinct
* In the table caption
* We felt that it's too easy to gloss over the table caption and look straight at the options you want to check
* As a heading above all sub-tables which have been fully deprecated
* Another case of glossing over, and adds unnecessary code …
=> Add deprecation tag

src/community/resources-and-tools/index.md
Add an entry for Crispy Forms GDS, a template pack for Django Crispy Forms to generate forms and pages for the GOV.UK Frontend for Django based web sites.
=> Update index.md to add a tool for Django

lib/metalsmith.js, package-lock.json, package.json, src/components/cookie-banner/default/index.njk, src/components/cookie-banner/index.md, src/components/footer/default/index.njk, src/components/footer/index.md, src/components/header/default/index.njk, src/components/header/index.md, src/components/service-navigation/default/index.njk, src/components/service-navigation/index.md
- Adds a `rebrand` property to template frontmatter
- If this property is true, during build we create a duplicate of that file named `branded.njk`
- During build, we run metalsmith/in-place and metalsmith/layouts on the existing files as normal
- Then, we run each on the `branded` files, using a Nunjucks environment with the `govukRebranded` global
- Adds rebrand assets to build
=> Create branded versions of examples

src/components/accordion/index.md
Added content to explain how to make the sections open by default
=> Include how to make accordion open by default

src/community/design-system-day/index.md
Updates Design System Day page in Community section to 'archive' the event descriptions and phrase all dates into the past.
=> Update DSDay page to summarise 2025 events in the past

src/patterns/navigate-a-service/index.md
Updates the explanation that header with service name is already deprecated, which was done in v5.9.0
=> Update deprecation of service name

lib/metalsmith.js, package-lock.json, package.json, src/accessibility/wcag-2.2/index.md, src/components/back-link/index.md, src/components/breadcrumbs/index.md, src/components/cookie-banner/default/index.njk, src/components/cookie-banner/index.md, src/components/footer/default/index.njk, src/components/footer/index.md, src/components/header/default/index.njk, src/components/header/index.md, src/components/service-navigation/default/index.njk, src/components/service-navigation/index.md, src/styles/images/index.md, src/stylesheets/components/_callout.scss, src/stylesheets/main.scss, views/partials/_callout.njk, views/partials/_wcag-callout.njk, views/partials/_wcag-note.njk, views/partials/_whats-new.njk
- Remove WCAG callout/notes from affected components
- Adds a callout macro
- Updates rebranded components' guidance content
- Updates the What's new partial
=> Add rebrand MVP guidance

src/javascripts/application.mjs
As flagged in #4171, we're calling `createAll(CookiesPage)` twice.
=> Only initialise CookiesPage JS once

src/styles/page-template/index.md
We link to this page from our changelog/release notes, but we haven't updated it with the relevant information. This fixes that.
=> Add govukRebrand variable to template options table

.github/dependabot.yml, CODEOWNERS
Dependabot's `reviewers` option is being removed on 27th May, with its functionality being merged with the `CODEOWNERS` file, [as described on the GitHub blog](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/).
- Updates the `CODEOWNERS` file to include the **root** `package.json` and `package-lock.json` files explicitly, to match npm dependencies being protected by the `reviewers` option in Dependabot's config.
- Updates the `CODEOWNERS` file to include the `CODEOWNERS` file itself, requiring approval from codeowners to change it in future. [This is a recommended security practice.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners …
=> Remove deprecated `reviewers` option from Dependabot config

src/accessibility/index.md
Because alphagov/govuk-frontend#4661 removes content from the accessibility page, this adds more content referring to content that already exists.
This PR:
* adds a section and a link to the accessibility statement
* adds a section and a link to the accessibility section in the Service Manual
* removes some text from the introduction to avoid duplication
* adjusts the meta description
This depends on alphagov/govuk-frontend#4661 being merged first and will close https://github.com/alphagov/govuk-design-system/issues/4677.
=> Add more content to accessibility page

src/community/resources-and-tools/index.md
The `govuk-frontend-aspnetcore` repository has moved to the x-govuk org.
=> Update repository URL for ASP.NET Core integration library

src/community/roadmap/index.md, src/components/cookie-banner/index.md, src/components/footer/index.md, src/components/header/index.md, views/partials/_whats-new.njk
Updates the what's new section, roadmap page and brand callouts in components that reference the 5.10.x releases.
This follows the updates off of 4.10.0 in https://github.com/alphagov/govuk-design-system/pull/4706
=> Update website to reference 5.10.2

lib/nunjucks/globals.js, src/stylesheets/main.scss, views/layouts/_generic.njk, views/layouts/layout-pane.njk, views/partials/_breadcrumbs.njk
- Added breadcrumb component to the top of each guidance content page.
- This is intended to make upwards traversal through the hierarchy a bit easier.
- Breadcrumbs are not present on the homepage, 'meta' pages (like the privacy policy), 404 page, or archived content pages.
- Added a new global Nunjucks function, `getAncestorPages`, which is used to generate the breadcrumb navigation.
- Removed the theme name from above page titles (except for those in patterns) as they're now duplicating information in the breadcrumbs. 
Some lower level pages don't appear to work with the breadcrumbs (e.g. [speaker pages for DSDay events](https://design-system.service.gov.uk/community/design-system-day-2023/speaker-information/)). That's because these pages aren't included in the sitewide `navigation` …
=> Add breadcrumbs

src/stylesheets/components/_header.scss
As of [GOV.UK Frontend v5.10.2][1] the logo in the header only has padding applied to the right if the menu button is present.
As [discussed in #4668][2], this means that we can now remove this override from the Design System code.
[1]: https://github.com/alphagov/govuk-frontend/releases/tag/v5.10.2
[2]: https://github.com/alphagov/govuk-design-system/pull/4668#discussion_r2111217362
=> Remove padding override for logo

src/get-started/extending-and-modifying-components/index.md
As part of removing the WCAG 2.2 callouts we wanted to add some information that you generally need to check accessibility when you modify a component. This does that and will close #4667.
=> Add content about checking accessibility to 'modifying components' page

netlify.toml
As we've now left the Cabinet Office, the preference is to redirect to the generic top-level VDP instead.
This is based on advice from GC3 (Government Cyber Coordination Centre). The GC3 is a joint initiative between the Cabinet Office, National Cyber Security Centre, and GDS (by virtue of former CDDO).
=> Update security.txt redirection

package-lock.json, package.json
5.11.0-internal.0 adds new inverse service navigation styles.
=> [feature/rebrand] Bump govuk-frontend to 5.11.0-internal.0

src/components/header/index.md
Using the service name is now deprecated, so shouldn't appear in the description.
=> Remove mention of service name in description of Header page

lib/nunjucks/globals.js, src/stylesheets/main.scss, views/layouts/layout.njk, views/partials/_navigation.njk
Restyles the navigation on the homepage to blend in with the redesigned header and masthead. Part of #4734.
- Update to a preview branch of govuk-frontend, based on https://github.com/alphagov/govuk-frontend/pull/6015. 
- Add new styles to handle style changes to the accordion navigation that's bespoke to the Design System website.
- Adds a global `isHomepage` function to determine if the current page is the site homepage.
- Uses this function to determine if the inverse variant should be invoked or not.
- Refactors breadcrumbs to use this function.
The `isHomepage` function uses similar logic that breadcrumbs were previously using, that is, expecting an empty string for the `permalink` context item (which, as far as I know, only the homepage has). There is probably a nicer way of doing …
=> Restyle navigation to blend with header and masthead

src/privacy-policy.md
Updates information about the organisation and data protection contact points following GDS's move from the Cabinet Office to the Department for Science, Innovation and Technology (DSIT).
New information is mostly cribbed from [Notify's updated privacy policy](https://www.notifications.service.gov.uk/privacy), with the DSIT Data Protection Officer address taken from the ICO's Data Protection Public Register.
Mandatory "I am not a lawyer" disclaimer.
=> Update privacy policy following move to DSIT

package-lock.json, package.json
Update to [GOV.UK Frontend 5.11.1](https://github.com/alphagov/govuk-frontend/releases/tag/v5.11.1).
=> Update govuk-frontend to 5.11.1

src/community/roadmap/index.md, views/partials/_whats-new.njk
Update content of the "What's new" section of the homepage and the Roadmap page to announce the release of GOV.UK Frontend v5.11.1
=> Update "What's new" and "Roadmap"

src/patterns/question-pages/explanatory-text/index.njk
Raised via Zendesk ticket [#6197763](https://govuk.zendesk.com/agent/tickets/6197663)
=> Fix typo in 'Asking complex questions without using hint text' example

src/index.njk, views/partials/_whats-new.njk
Fix a couple of errant ‘straight’ quotes on the homepage.
In markdown, our markdown processor takes care of turning straight quotes into curly quotes with its ‘smart quotes’ plugin, but that doesn’t work where we write HTML 😢
=> Use curly quotes on homepage
