.travis.yml
bin/deploy-travis
manifest.yml

This sets Travis up to automatically deploy to the [PaaS](https://docs.cloud.service.gov.uk) (a CloudFoundry installation) whenever master changes.
By default when deploying to PaaS there is a [brief period of downtime](https://docs.cloud.service.gov.uk/#404s-after-commands-that-restart-the-app) when the old container is destroyed but the new one is not serving yet. We're using a plugin called [Autopilot](https://github.com/contraband/autopilot) to work around this by renaming apps and altering routes to provide a zero downtime deploy.
This means that we cannot use the 'built in' CloudFoundry Travis provider, and instead we need to use our own script. The config for this (api, org, space, username, password) is set using environment variables and the password is encrypted.

Add manifest and script to deploy to PaaS

---

source/layouts/layout.erb

Until this goes into public beta we don’t want it to appear in Google’s search results

Prevent robots indexing the design system

---

LICENSE

The Copyright is Crown Copyright; "Government Digital Service" should go in brackets – as per https://github.com/alphagov/styleguides/blob/master/licensing.md

Update copyright in license file

---

.gitignore
.travis.yml
README.md
config.rb
package-lock.json
package.json
source/index.html.erb
source/layouts/layout.erb
source/stylesheets/main.css.scss

* create package.json file where we install `@govuk-frontend` packages
* add `/node_modules`, `package-lock.json` and `.npmrc` file to `.gitignore`
* config application to load and import frontend packages from `node_modules`
* setup Travis to install private npm packages
* add npm token to the travis environment variables
* add documentation on how to install GOV.UK Frontend packages
[Trello card](https://trello.com/c/fHKlkwD6)

Enable Design System to use govuk-frontend private packages

---

.travis.yml
README.md
config/.sass-lint.yml
gulpfile.js
package-lock.json
package.json
source/stylesheets/main.css.scss

This adds the same Sass linter we use on govuk-frontend (gulp-sass-lint) and copies the config that we use so that we are linting to the same standard.
We should look at ways we can share this config between the two repos without duplication, as they are otherwise likely to drift apart.
It also configures Travis to run this as part of the automated checks, and fixes a warning that the linter identified where we used single quotes instead of double quotes which we prefer.

Add Sass linter

---

package-lock.json
package.json
source/stylesheets/main.css.scss

Updated GOV.Uk Frontend packages have been published so we need to update our dependencies.
This PR 
* updates dependency version of `@govuk-frontend/all`
* imports the "all" package instead of individual imports

Update frontend packages

---

source/components/_divider.erb
source/components/_masthead.erb
source/index.html.erb
source/layouts/layout.erb
source/stylesheets/components/_divider.scss
source/stylesheets/components/_masthead.scss
source/stylesheets/main.css.scss

Create masthead, three-blocks and divider components. Add grid styles, site
width container style and large screen breakpoint that will later move to FE.
I think the three grid blocks are unique enough to be a component but the single block ("Get in touch") isn't.
There are outstanding decisions on spacing and typography so these will need to
be reviewed again on the homepage at a later point.

Replicate DS homepage from DS prototype

---

source/layouts/layout.erb

Basic accessibility set up:
* A 'skip to main content' link appears on the first use of the tab key
* When activated by keyboard or mouse the skip to main content link shifts the focus to the content body, bypassing the navigation
* The focus state is highlighted using the standard GOV.UK style (yellow background)

Add skip-link and main content container

---

.travis.yml

This PR:
- updates Travis CI to use Node.js ~~v7~~ v8
- removes Ruby testing script `bundle exec rspec` as it's no longer relevant
- updates build script `npm run build`
- ensure use of latest npm version
**Note to reviewer:**
~~This PR fails as it depends on https://github.com/alphagov/govuk-design-system/pull/79 to be merged first.~~

Update Travis to use Node

---

views/layouts/layout-pane.njk
views/layouts/layout.njk

This PR removes the path when importing a partial file.
Partial files are [already included in the Nunjucks paths](https://github.com/alphagov/govuk-design-system/blob/master/lib/metalsmith.js#L17), so there's no need to specify the entire path.

Include partials without specifying the entire path

---

src/stylesheets/components/_highlight.scss
src/stylesheets/main.scss

This PR:
- 3b965cb adds styles to code blocks to highlight the syntax (uses GitHub highlight, we might want to change it to [Pygments](http://pygments.org/) if we want to be consistent with the GDS tech docs)
- cdb9cba limits the element (`<h*>`, `<p>`, `<ul>`, `<ol>`, `<img>`) inside `.app-c-content` (these can be placed inside `.prose` instead) in width (`38em`) for a better legibility
[Trello card](https://trello.com/c/ScbV1vsM)

Page styling

---

src/components/breadcrumbs/default.md.njk

At the minute you can click Home, load the Design System homepage, navigate to the breadcrumbs component, click Home, load the Design System homepage in the iframe, navigate to the breadcrumbs component, click Home, load the Design System homepage in the iframe's iframe, navigate to the breadcrumbs component…

Don't use 'real' links in breadcrumb example

---

src/Staticfile.auth

The authentication exists to ensure that users do not start using the Design System instead of the current resources - there is still a lot of work to do to get to a place where we’d want this to be happening.
There’s no need to keep the credentials ‘secret’ as they’re only there as a deterrent, which is why it’s OK to commit the encrypted htpasswd details to a public git repository.
https://trello.com/c/GVZduH2J/481-add-basic-authentication-to-the-production-design-system

Add basic auth for private beta

---

package-lock.json
package.json
src/components/breadcrumbs/default.md.njk
src/errors/404.html
src/errors/generic.html
src/index.njk
src/stylesheets/components/_example.scss
src/stylesheets/components/_footer.scss
src/stylesheets/components/_header.scss
src/stylesheets/components/_masthead.scss
src/stylesheets/components/_mobile-navigation.scss
src/stylesheets/components/_navigation.scss
src/stylesheets/components/_tabs.scss
src/stylesheets/components/_toc.scss
src/stylesheets/main.scss
views/layouts/_generic.njk
views/layouts/layout-example.njk
views/layouts/layout-pane.njk
views/partials/_footer.njk
views/partials/_masthead.njk
views/partials/_mobile-navigation.njk
views/partials/_navigation.njk

This PR updates the Design System to 0.19 with the following:
1. Build:
- Change `package.json` to use Frontend version 0.19-alpha
2. Styles:
- Remove references to `font-smoothing` and `font-stack` mixins and `govuk-u-font-smoothing` class as these are now included by `govuk-typography-common`.
- Add responsive margins to some components as 0.19 removes top margins from typography so this needs now to be accounted for in component styles.
- Halve `app-c-content` padding as 0.19 uses a 15px, not 30px gutter.
- Now use the spacing scale instead of the gutter spacing wherever possible - coupling spacing with gutters only makes sense in very layout-y classes.
3. Components/partials/layout:
- Remove `govuk-u-font-smoothing` classes as this is now handled by `govuk-typography-common`.
- Remove …

Update components, partials and scss to use Frontend 0.19

---

lib/metalsmith.js
views/partials/_example.njk

This was disabled when the examples work was done, but means that Frontend components do not behave as expected (`text` arguments not being escaped)
We can re-enable it, but we need to manually mark the code blocks for use within the examples as safe using the `safe` filter.

Enable autoescape option for Nunjucks

---

src/stylesheets/components/_example.scss
src/stylesheets/components/_tabs.scss
views/layouts/layout-pane.njk
views/partials/_example.njk

This PR adds `govuk-prose-scope` to the example pages:
- Add `.app-c-example--tabs` only when there are tabs below it to control bottom
margin. 
- Use Nunjucks Whitespace Control (`{%-`) to strip whitespaces to stop them being converted into blank paragraph tags.
- Add `.app-c-example-wrapper` around examples to control bottom margin. Move bottom
margin there from `.app-c-example`. Add top margin as requested by @dashouse.
- Reset `.govuk-prose-scope` styles that broke example tabs.
- Add `.govuk-prose-scope` to example page contents. There's no need for a
conditional for the class in `layout-pane` as the layouts (components/patterns)
using this page template are to be merged shortly.

Add prose scope style to example pages

---

src/index.njk

1. Add a link to the prototype kit site in the footer
1. Add a new section to the home page: 'Other design resources', with all the links from the footer. This is repetition, but the footer is easily overlooked, and I think these links are important.

link to prototype kit site

---

src/components/error-message/default.njk
src/components/error-message/index.md.njk
src/components/error-message/label.njk
src/components/error-message/legend.njk
src/components/error-summary/default.njk
src/components/error-summary/index.md.njk

Adds examples and pages for `error-summary` and `error-message`

Add error component pages

---

views/layouts/layout-example.njk

For some examples (at the minute specifically the layout examples) we need to add additional styling to add borders or backgrounds to highlight individual elements within the example.
At the minute this is being done by adding additional classes to the example (not yet committed), but this means that the app stylesheet is full of styles affecting only single examples, and the HTML and Nunjucks code includes extra classes which we would not want users to be copying into their own app.
By allowing users to include additional stylesheets, the additional styling can exist in the same directory as the example and included from there.
As an example, you might add the following to an example's frontmatter:
```
---
layout: layout-example.njk
stylesheets:
- annotate-layout.css
---
``` …

Allow for additional stylesheets per example

---

src/stylesheets/main.scss

This PR adds styling and responsiveness to images within `app-c-content`
- Adds border
- Adds padding (static)
- Makes image responsive
- Adds margin
**Known issue**
Currently images are rendered from markdown are inside a `<p>` tag. The margin in this update has been applied as if this `<p>` tag has been removed, so it's ready for that PR. That means this PR will look incorrect.
https://trello.com/c/kkrDD7G8/485-design-system-add-image-styling-and-responsive-sizing-to-the-design-system

Add image styling to Design System

---

src/stylesheets/components/_navigation.scss

Set the primary navigation to be displayed from tablet as the mobile menu button is being hidden from the same breakpoint.
The opther option is to move the breakpoint from `tablet` to `desktop` for both.
_Note: at the moment we don't have a primary navigation from `tablet` to `desktop`._

Sync primary navigation with mobile menu button

---

src/javascripts/components/tabs.js
src/javascripts/main.js
src/stylesheets/components/_tabs.scss
views/partials/_example.njk

This PR
- makes use of the `app-c-example-wrapper` container for isolating the examples
- allows an example to be used with/without the tabs opened on the same page
- handles padding if the code block does/doesn't have a close button (single/multiple tab case)
[Trello card](https://trello.com/c/ZcaEdfyq)

Update tabs on examples component

---

src/components/back-link/index.md.njk
src/components/breadcrumbs/index.md.njk
src/components/button/index.md.njk
src/components/date-input/index.md.njk
src/components/details/index.md.njk
src/components/error-message/index.md.njk
src/components/error-summary/index.md.njk
src/components/fieldset/index.md.njk
src/components/panel/index.md.njk
src/components/phase-banner/index.md.njk
src/components/skip-link/index.md.njk
src/components/table/index.md.njk
src/components/tag/index.md.njk
src/components/text-input/index.md.njk
src/components/textarea/index.md.njk
src/index.njk
src/patterns/addresses/index.md.njk
src/patterns/confirm-an-email-address/index.md.njk
src/patterns/create-a-username/index.md.njk
src/patterns/create-accounts/index.md.njk
src/patterns/dates/index.md.njk
src/patterns/email-addresses/index.md.njk
src/patterns/names/index.md.njk
src/patterns/national-insurance-numbers/index.md.njk
src/patterns/passwords/index.md.njk
src/patterns/question-pages/index.md.njk
src/stylesheets/components/_contact-panel.scss
src/stylesheets/main.scss
views/layouts/layout-pane.njk
views/partials/_contact-panel.njk

This creates the get in touch panel and adds it to the majority of pages.
This uses the correct contact email address but the current link to public cross-gov slack channel
As part of https://trello.com/c/2c3cDlyO/531-add-get-in-touch-panel-to-design-system

Add get in touch panel

---

package-lock.json
package.json
src/components/checkboxes/default.njk
src/components/radios/default.njk
src/get-in-touch.njk
views/partials/_header.njk

This adds the BETA phase banner with a simple `mailto:` link to our support email.
Couldn't use the macro with this one. I needed to add extra padding because we have a full width header and the macro isn't allowing classes to be passed to the parent container as par as I can see.
https://trello.com/c/YZaDRwVL/558-add-beta-banner-to-the-design-system

Add phase banner and get in touch page

---

lib/metalsmith.js
package.json
src/stylesheets/components/_tag.scss
src/stylesheets/main.scss
views/layouts/_generic.njk
views/partials/_banner.njk
views/partials/_header.njk

Use the build environment variables that Netlify give us to detect when a build happens as part of a PR preview, and clearly mark it as such by replacing the beta banner with a suitable summary.
https://trello.com/c/VzFEH5eR/549-review-apps-should-be-clearly-identified-as-previews

Indicate when built as a preview a of PR

---

package-lock.json
package.json
src/components/phase-banner/beta.njk
src/components/phase-banner/default.njk
src/get-in-touch.njk
src/index.njk
src/javascripts/components/copy.js
src/javascripts/components/tabs.js
src/patterns/task-list-pages/index.md.njk
src/styles/typography/link.njk
src/styles/typography/list.njk
src/stylesheets/components/_mobile-navigation.scss
src/stylesheets/components/_navigation.scss
src/stylesheets/components/_tabs.scss
src/stylesheets/main.scss
views/layouts/layout-pane.njk
views/partials/_banner.njk
views/partials/_contact-panel.njk
views/partials/_footer.njk
views/partials/_header.njk
views/partials/_mobile-navigation.njk
views/partials/_navigation.njk
views/partials/_subnav.njk
views/partials/_toc-styles.njk

This updates the DS to use the new version of FE 0.0.22-alpha with the following:
- Update `package.json` to use FE 0.0.22-alpha
- Update app markup to use the new `govuk-link` class
- Update tasklist fe-matter to use new `govuk-link`
- Update phase-banner HTML args to use `govuk-link`
- Update link and list examples to use `govuk-link`
- Update copy & close links in JS to new `govuk-link`
- Override `prose-scope` link styles for `app-c-link--copy` and `app-c-tabs__item`
- Set font styles in `app-c-link--copy`
- Reset font weight for nav & mobile nav links
Each of the above is a commit with some comments.
For "Reset font weight for nav & mobile nav links", I left a note in the commit about how the two components don't set their font styles consistently. We should probably review this but …

Update DS to use FE 0.0.22-alpha

---

src/stylesheets/components/_pane.scss

This will prevent us from going out to our private beta users with a bug that we know will be fixed by a new Google Chrome release.
Note: the layout will fallback on `flex`.

Temporary disable grid layout until the #130 is fixed

---

src/get-in-touch.njk
src/get-started.md.njk
src/index.njk
src/stylesheets/components/_divider.scss
src/stylesheets/components/_example.scss
src/stylesheets/main.scss
views/layouts/layout-single-page-prose.njk
views/layouts/layout-single-page.njk
views/layouts/layout.njk
views/partials/_masthead.njk

- Update home page content
- Add "Get started page"
- Create layout for pages that don't have sub-nav
- Create layout for pages that don't have sub-nav and written in markdown
- Move `@include govuk-font-regular-19;` to example component
As part of https://trello.com/c/0HJSd2q8/635-add-get-in-touch-page-and-update-home-page-content

Change home page content and add "Get started" page

---

src/patterns/start-pages/default.njk
src/patterns/start-pages/index.md.njk
src/patterns/start-pages/related-items.scss

This pull request adds:
- Start pages pattern guidance
- Start pages examples
- Related items SCSS from the Prototype Kit (beta)
SCSS for Related items styling isn't available in GOV.UK Frontend so is styled on the example only. 
It will still be styled for a user copying and pasting into the Prototype Kit (beta).

Add start page pattern

---

src/components/text-input/index.md.njk
src/components/text-input/input-width.njk

Raised by @joelanman - https://github.com/alphagov/govuk-design-system/issues/155
The Text input component has a section for "Use appropriately-sized text inputs" but has no connection to the width override classes.
In similar scenarios in the Design System we've re-use examples from other sections to explain something in that particular context.

Add width override class example to text input component page

---

views/partials/_example.njk

Adds ` data-track="tab-html"` and `  data-track="tab-nunjucks"` attributes to be used as selectors from Google Tag Manager which. This helps tracking users clicking on tabs.
_No Trello Card_

Add selectors for google tag manager

---

src/patterns/confirmation-pages/default.njk
src/patterns/question-pages/default.njk
src/patterns/question-pages/passport.njk
src/patterns/question-pages/postcode.njk

Realised during the research sessions that the page examples were inconsistent at including the wrapper classes.
This adds the width container to the examples, so page examples contain everything that you'd need to paste into your content block.

Update page examples to include the `govuk-o-width-container` class

---

src/components/textarea/default.njk

Swap apostrophe so it doesn't render as `&#39;` in HTML example

Update apostrophe in example

---

src/patterns/question-pages/default.njk
src/patterns/question-pages/passport.njk
src/patterns/question-pages/postcode.njk

`<form>` was left of from question page example.
This aligns the functionality of the question page in the DS and Prototype kit.

Add <form> to question page examples

---

views/partials/_example.njk

Adds a link to the table of arguments section for each component in the GOV.UK Frontend README file on Github.
Trello ticket: https://trello.com/c/peF3UoZd/718-add-links-from-the-component-examples-to-the-table-of-arguments-in-the-github-readme

Add link to the components' table of arguments

---

data/colours.json

These colours are not actually used in Frontend and their definitions are being removed in the next version. As the only colour left in this section is in fact a border, not a background, rename the section.
https://github.com/alphagov/govuk-frontend/pull/525

Remove panel, highlight and page colours

---

views/partials/_tracking-body.njk
views/partials/_tracking-head.njk

The GTM ID was accidentally changed to reference the ‘dev’ GTM environment in 6bbb1d62a03ff7589ffe33c3f53304fdfd732664 whilst testing using the tets-events-ga branch.
This reverts that change to re-instate the production GTM ID.

Revert changes to GTM ID

---

src/components/back-link/index.md.njk
src/components/breadcrumbs/index.md.njk
src/components/button/index.md.njk
src/components/checkboxes/index.md.njk
src/components/date-input/index.md.njk
src/components/details/index.md.njk
src/components/error-message/index.md.njk
src/components/error-summary/index.md.njk
src/components/file-upload/index.md.njk
src/components/panel/index.md.njk
src/components/phase-banner/index.md.njk
src/components/radios/index.md.njk
src/components/select/index.md.njk
src/components/skip-link/index.md.njk
src/components/table/index.md.njk
src/components/tag/index.md.njk
src/components/text-input/index.md.njk
src/components/textarea/index.md.njk
src/components/warning-text/index.md.njk
src/stylesheets/components/_tabs.scss
views/partials/_example.njk

- Adds link with tracking data- attribute to the table inside of each Nunjucks macro tab.
- Updates wording on each component page.
Trello ticket: https://trello.com/c/peF3UoZd/718-add-links-from-the-component-examples-to-the-table-of-arguments-in-the-github-readme

Add link to the table of arguments in GOV.UK Frontend readme

---

src/components/radios/default.njk

This fixes #189 
We tell people to copy and paste our examples, but in this case they would get a pre-checked radio, which we don't actually recommend people do.
This PR removes the checked state.

Remove checked state from radio example

---

src/components/textarea/index.md.njk
src/components/textarea/specifying-rows.njk

In user research we've seen participants wanting to know how to set the height of a textarea.
We have existing documentation that tells users they should set the height proportional to the expected content, but don't tell them they can use the rows attribute to do this.
This has not yet been reviewed by a content designer.

Document setting height of a textarea using rows

---

src/components/fieldset/address-group.njk
src/components/fieldset/index.md.njk
src/patterns/addresses/index.md.njk
src/patterns/addresses/multiple.njk

This PR updates the hardcoded HTML address examples to use macros.
It also fixes the visual issue with `govuk-o-form-group` not being added to these examples.

Update fieldsets to use macros

---

package-lock.json
package.json
src/stylesheets/components/_footer.scss
src/stylesheets/components/_header.scss
src/stylesheets/components/_pane.scss
src/stylesheets/components/_subnav.scss

- Update package.json to install latest GOV.UK Frontend
- Rename `exports` mixin to match naming in GOV.UK Frontend

Update to frontend 0.0.24 alpha

---

src/patterns/question-pages/default.njk
src/patterns/question-pages/passport.njk
src/patterns/question-pages/postcode.njk

This is the non-contentious (I hope!) change from #199 – removing the `form` classes from the forms in the examples.
https://trello.com/c/BVm3eKnt/805-remove-non-existent-form-classes-from-forms-in-question-page-examples

Remove non-existent form class from forms

---

views/partials/_tracking-body.njk
views/partials/_tracking-head.njk

This prevents making invalid requests to GTM when running the Design System locally.
This has been tested locally by running `GTM_ID="GTM-WVLM6KW" npm start` and verifying that both tracking scripts are present.

Only include GTM if GTM_TAG is set

---

src/stylesheets/components/_pane.scss

#130 was fixed after Google Chrome 64 release.
This was disabled in [PR146](https://github.com/alphagov/govuk-design-system/pull/146) to prevent private beta users running into this issue.
_Note: we might want to leave this PR pending for a few days so people will have time to update to the latest version of Chrome._

Enable grid layout

---

.travis.yml

Configure Travis to notify us by email when a build fails.
Improve the other documentation in the Travis config.

Broken build notifications; improve Travis docs

---

package-lock.json
package.json
src/stylesheets/components/_footer.scss

- Update package.json and package-lock.json to install latest GOV.UK Frontend
- Rename app footer `exports()` to avoid clashing with footer `exports()` from Frontend 
https://trello.com/c/gNYQwaAM/813-update-govuk-design-system-to-use-the-latest-release
Before exports renaming:

Update with frontend 0.0.26

---

src/javascripts/components/example.js
src/stylesheets/main.scss

This PR is fixing two bugs found by @ignaciaorellana while presenting the product on Friday.
- The position of the Resize label is `absolute` instead of `fixed`
- When clicking the `body` of the `iframe`d document the frame automatically resizes to fit height.

Fix iframe auto-resize and resize label position

---

data/colours.json
src/styles/colour/index.md.njk

Accidentally missed from #208.
Before
After (no difference in size or spacing, it's just the screen capture size being fit to the container)

Fix fuchsia colour name

---

src/stylesheets/components/_table.scss
src/stylesheets/main.scss
src/whats-changed.md.njk

This page maps classes and mixins from GOV.UK Elements / Frontend toolkit to GOV.UK Frontend.
This PR simply adds the page, it will not be findable without the URL until links are added to the 'Get Started' page.
Content needs to be reviewed by @amyhupe

Add what's changed page

---

tasks/serve.js

Enables you to make changes in the GOV.UK Frontend project and see it update
in the design system quickly.
As part of https://github.com/alphagov/govuk-frontend/pull/624

Ensure when npm-linking govuk-frontend browsersync picks up changes.

---

package-lock.json
package.json

Updated govuk-frontend to 0.0.28-alpha.
No additional changes to the Design System itself.

Update govuk-frontend to 0.0.28-alpha

---

src/stylesheets/components/_navigation.scss

Very small PR to change the padding on the nav from 20px to `govuk-spacing-scale-3`. The intent was the edge of the word "About" would line up with the secondary nav.
**Before**
**After**

Fix nav alignment

---

src/stylesheets/components/_mobile-navigation.scss
src/stylesheets/components/_subnav.scss

Requested by @timpaul 
Note - I have used a hard 19px unit on mobile as I do not want it to change to 16px on mobile.

Update theme styling to use lowercase, regular weight font

---

src/cookies.md.njk

Change 'Prototype Kit' to 'GOV.UK Design System' to correct an error.

Correct the product name in GA cookies table

---

src/cookies.md.njk

Missing the heading "Universal analytics"

Update cookies page to include missing heading

---

src/components/warning-text/index.md.njk

This PR is a fix and removes the [get in touch](Anchor link to Get in touch panel at bottom of page) link  which points to a 404 from the warning text page

Remove get in touch link which leads to 404

---

src/cookies.md.njk

- Fix link to guidance on managing cookies
- Moves 'Introductory message' out of Google Analytics section - it is not set by Google Analytics
- Rewords 'Introductory message' and 'welcome message' to more accurate 'cookie message'
- [Corrects the _gat cookie expiration time to 1 minute](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage#analyticsjs)

Fix cookie page

---

src/styles/layout/common-two-thirds.njk

- remove extra closing div tag from the layout example code

Fix typo in layout example code

---

src/stylesheets/components/_mobile-navigation.scss

Issue - https://github.com/alphagov/govuk-design-system/issues/260
This sets  `.app-mobile-nav` to `$from: tablet` rather than `$from: desktop`

Change media query on mobile nav to from:tablet

---

src/components/radios/stacked.njk

Add "name" to macro - currently has the same name as the other radios example

Fix radios example

---

lib/file-helper.js
package-lock.json
package.json

Based of @nickcolley’s initial work in d868d4d (https://github.com/alphagov/govuk-design-system/pull/259).
Trimming whitespace from the start and end of the HTML string is necessary to prevent the beautifier from doing strange things with the indentation of the first line.
Using [`js-beautify`](https://www.npmjs.com/package/js-beautify). because that’s what pretty used under the hood, and it gives us more control as we can change the config that gets passed to js-beautify (e.g. controlling the indentation).
https://trello.com/c/7wZdB2pn/766-prettify-html-in-code-examples

‘Beautify’ example HTML

---

src/components/button/disabled.njk
src/components/button/index.md.njk
src/components/button/primary.njk
src/components/button/start.njk

- Removes `input` example, input has some usability concerns since we cannot give extra touch area that we can for button and anchors, it is only required for IE6/7. We still support inputs being styled but should not recommend it's usage unless necessary. (See https://github.com/alphagov/govuk_elements/issues/545#event-1615721498 for details)
- Removes button 'start' button example, this is not how we expect this variant to be used, since this variant is intended for the start page of GOV.UK services.
Depends on: https://github.com/alphagov/govuk-frontend/pull/683
Trello: https://trello.com/c/gITiuXcS/765-use-button-by-default-for-buttons-rather-than-input-typebutton

Simplify button guidance

---

src/stylesheets/main.scss

By default static breakpoints is set to desktop and those media queries get rasterised.
For colour swatches we have a custom breakpoint that is higher than desktop so IE8 never gets those styles.
To fix, we check if `$govuk-is-ie8 == true` and if true we set the custom breakpoint to match desktop.
**Before**
**After**
Also fixes: https://github.com/alphagov/govuk-design-system/issues/126

Fix colour swatch styles for IE8

---

.travis.yml
bin/deploy-travis

We had a recent incident on 2018-05-21 between 11:00 and 11:30 that resulted in downtime for users.
As part of a review of the incident we decided to make two actions:
1. Investigate our deployment method with GOV.UK PaaS.
2. Ensure uptime robot was running against the website.
This pull request is the result of the first action.
We found that the Autopilot plugin we were using failed to execute in the manner it describes https://github.com/contraband/autopilot#method
Instead it first deleted the current running application and after this created a new instance of the application, this meant that when the upload failed the application was left in a broken state.
We have tested the plugin (which is [recommended by GOV.UK PaaS](https://docs.cloud.service.gov.uk/#404s-after-commands-that-rest …

Replace zero downtime Autopilot plugin with Blue/green deployment plugin

---

src/patterns/question-pages/index.md.njk

The captions example does not use Nunjucks, so it does not make sense to show it for this example.

Hide Nunjucks tab for ‘captions’ example

---

package-lock.json
package.json
src/stylesheets/components/_header.scss
src/stylesheets/components/_pane.scss
src/stylesheets/components/_subnav.scss

Update Design Sytem to use the latest version of govuk-frontend.
Because the SCSS are conflicting, `app-` prefix to the SCSS exports was added in this PR.

Update to frontend 0.0.30

---

deploy/nginx/conf/includes/form_handler.conf
src/patterns/page-not-found-pages/reason-not-known/index.njk
src/patterns/question-pages/default/index.njk
src/patterns/question-pages/passport/index.njk
src/patterns/question-pages/postcode/index.njk

Handle form submissions from examples that contain forms by redirecting them back to the referring example. This relies on updating the form examples within the design system to POST to `/form-handler`.
If for whatever reason there is no referrer, then redirect to the homepage instead.
Note that this will only work when deployed to CloudFoundry – Netlify does not use the nginx config at all.
Preview on PaaS: https://govuk-design-system-production-form-handler.cloudapps.digital/
https://trello.com/c/A2N92zjA/806-spike-how-to-handle-form-submissions-in-the-question-page-examples-in-the-design-system

Handle form submissions by redirecting to referrer

---

views/layouts/_generic.njk
views/partials/_tracking-body.njk
views/partials/_tracking-head.njk

Adds a guard around Google Tag Manager script to prevent it from initialising,
for users who have indicated they do not want to be tracked.
Also removes the `<noscript></noscript>` include as we can't guard this.
If we were server rendering the site, we could take advantage of the ['DoNotTrack' header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT).
https://trello.com/c/jHVUmpdx/957-do-not-track-users-with-donottrack-enabled

Do not track users who have enabled 'DoNotTrack'

---

src/styles/colour/index.md.njk
src/stylesheets/main.scss

- Fix tables not being identifiable 
by adding summary attribute
Before:
After:
- Fix being able to swipe through table in ios Voiceover
- replace `display:block` and `margin-bottom` on `tr` with `display: table-row` and transparent border
- remove visually hidden table head as it trapped swipe gestures with VoiceOver on iOS
Before video:
[before.zip](https://github.com/alphagov/govuk-design-system/files/2084029/before.zip)
After video:
[after.zip](https://github.com/alphagov/govuk-design-system/files/2084022/after.zip)
No visual change in browsers
- VoiceOver Mac
- VoiceOver iOS
- Jaws 17 in IE11
- Jaws 2018 in IE11
- NVDA 17.4 in Firefox 52
Trello ticket: https://trello.com/c/TN6qVBpf/1095-dac-audit-tables

Fix accessibility issues with tables on Colours page

---

lib/file-helper.js
lib/metalsmith.js
package-lock.json
package.json
src/stylesheets/components/_example.scss
src/stylesheets/main.scss
views/partials/_example.njk

- Remove CSS only text
- Give 'open in window' links more context
- Add title to iframes
- Refactors file helpers to use more robust parsing of files
Testing: https://deploy-preview-306--govuk-design-system-preview.netlify.com/components/button/
VO + Down, to select the frame: 'frame 0' 
VO + Down, to select the frame: 'Button frame' (reads the title attribute on the iframe)
JAWs key + down: 'Button - Example - GOV.UK Design System frame' (reads the <title> element inside the frame)
Tabbing onto iframe: 'Button - Example - GOV.UK Design System frame' (reads the <title> element inside the frame)
JAWs key + down: 'Button - Example - GOV.UK Design System frame' (reads the <title> element inside the frame)
Tabbing onto iframe: 'Button - Example - GOV.UK Design System frame' (reads the <title> …

Accessibility: improvements for examples

---

lib/metalsmith.js
package-lock.json
package.json
src/stylesheets/components/_pane.scss
views/layouts/_generic.njk
views/layouts/layout-pane.njk
views/layouts/layout-single-page.njk

Update to Frontend 0.0.31 and modify the templates to extend from the template provided by GOV.UK Frontend.
Required a little bit of tweaking to prevent the body from displaying weirdly on pages which did not use the split page layout, since the `<html>` element now has a grey background and that was bleeding through.
Also updated the ids on the `<main>` content elements to use the default target of the skip link as provided in Frontend's template.njk.

Update to Frontend 0.0.31

---

src/styles/layout/grid-annotate.scss
src/styles/layout/grid-nested-annotate.scss
src/stylesheets/components/_highlight.scss

Note: Not all the colours in our code highlighting stylesheet are currently used, in the examples below I modified the output to force certain colours to appear for the sake of this demo.
---
https://trello.com/c/u1fMUipK/1076-dac-audit-design-system-colour-contrast

Update code highlighting palette for WCAG Level AA contrast

---

src/stylesheets/components/_tabs.scss

I have fixed the most urgent issue with the copy button covering up the examples, however I think we could do much better with the general layout when zoomed in, so I'll leave the trello card as unfinished and we can make this better when Dave is back.
https://trello.com/c/0WMsHdZ9/1075-dac-audit-relative-sizing

Stop tabs from obstructing examples

---

config/navigation.json
src/design-system/community/backlog/index.md.njk
src/design-system/community/contribute/index.md.njk
src/design-system/community/index.md.njk
src/design-system/community/working-group/index.md.njk
src/design-system/index.njk

Trello card: https://trello.com/c/sFg6nov6/1117-add-a-new-community-section-to-the-design-system
This work:
- adds a Community section
- adds Community to the navigation
- adds a Community section to the homepage
**Known issue:**
The Community section left nav is in the wrong order. Ordering is currently only alphabetical in the Design System. I intend to do a further PR to add ordering functionality to the Design System.

Add community section

---

deploy/nginx/conf/includes/disable_absolute_redirects.conf

This fixes an issue where users who visit www.gov.uk/design-system would get an absolute redirect to our origin domain (govuk-design-system-production.cloudapps.digital/design-system/).
```
curl -I https://govuk-design-system-production.cloudapps.digital/design-system
HTTP/1.1 301 Moved Permanently
Content-Length: 178
Content-Type: text/html
Date: Thu, 14 Jun 2018 15:27:34 GMT
Location: http://govuk-design-system-production.cloudapps.digital/design-system/
Server: nginx
X-Vcap-Request-Id: 1d8e596c-4bf5-491d-7ace-8082dd601ebc
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```
```
curl -I https://govuk-design-system-production-redirect-test.cloudapps.digital/design-system
HTTP/1.1 301 Moved Permanently
Content-Length: 178
Content-Type: text/html
Date: Thu, 14 Jun …
```

Disable absolute redirects

---

src/design-system/patterns/check-a-service-is-suitable/index.md.njk
src/design-system/patterns/check-answers/index.md.njk
src/design-system/patterns/fill-in-a-form/index.md.njk
src/design-system/patterns/task-list-pages/index.md.njk

I feel having live demos of patterns may be a better way to do this than a literal explaination, but I hope this is better than before. We should consider including users with access needs in future rounds of research.
https://trello.com/c/uZiLJNxP/1068-dac-audit-provide-appropriate-text-alternatives-for-non-text-content

Update visual examples to include better alternative text

---

src/design-system/stylesheets/components/_tabs.scss
src/design-system/stylesheets/main.scss

Fixes https://github.com/alphagov/govuk-design-system/issues/299 which will be / is an issue in #322 
Also adds safe-guard for code blocks in example tabs.

Add max-width and bottom margin to block code blocks in prose-scope

---

.gitignore
.travis.yml

Since govuk-frontend is now public these are not needed.

Remove login credentials for npm

---

src/design-system/whats-changed.md.njk

Corrections
- Inset text no longer deprecated
- Correct modifier class for a bold label

Update "What's changed" page

---

src/components/text-input/default/index.njk

The current default example is for National Insurance numbers, but these should not be full width. This replaces it with the same example we use for the Email address pattern.

Update text input example

---

src/components/fieldset/address-group/index.njk
src/patterns/question-pages/postcode/index.njk

Fields that take short inputs of known length should be sized to reflect those inputs.

Make postcode field 10 characters wide

---

src/stylesheets/components/_subnav.scss

This PR reduces the excessive right padding on subnav items.

Fix subnav item padding

---

views/layouts/_generic.njk

Only its production (service domain) URL.
This excludes the examples which appear iframed in each page.
This is achieved by:
- checking if `travis_branch` variable exists or is not equal to 'master' and including the robots meta tag in those instances
Trello ticket: 
https://trello.com/c/GFmYbIAE/1065-allow-design-system-to-be-indexed

Allow the Design System to be indexed by search engines

---

src/patterns/telephone-numbers/default/index.njk
src/patterns/telephone-numbers/error-empty-field/index.njk
src/patterns/telephone-numbers/index.md.njk
src/patterns/telephone-numbers/international/index.njk

This pull request is to add a design pattern for telephone numbers. The guidance and examples were [approved by the working group on 26 April 2018](https://github.com/alphagov/govuk-design-system-backlog/issues/101#issuecomment-385634498).
This PR replaces: https://github.com/alphagov/govuk-design-system/pull/313

Add telephone numbers pattern

---

lib/metalsmith.js
package-lock.json
package.json
views/layouts/_generic.njk

We only want the canonical URL for each page (exluding example pages) indexed – we don't want the *.cloudapps.digital URL to appear in search results for example.
Utilising [metalsmith-canonical](https://github.com/saintedlama/metalsmith-canonical)
Trello ticket: https://trello.com/c/E7l2Q77P/1127-add-canonical-urls-to-the-design-system

Add canonical url 

---

src/patterns/start-pages/index.md.njk

Add links to Service Manual guidance from this page, to clarify that this pattern is just for prototyping.

update start page pattern guidance

---

manifest.yml

This is so that we can re-use the existing cloudapps.digital domain and redirect anyone that visits it to the service domain.

Change PaaS app name

---

lib/navigation.js
src/community/backlog/index.md.njk
src/community/contribution-criteria/index.md.njk
src/community/design-system-working-group/index.md.njk
src/community/how-you-can-contribute/index.md.njk

This adds ordering functionality, and orders the Community section.
The ordering works by adding `order: 1`  or other number to the 'frontmatter' of every page in a section.

Order community section

---

deploy/nginx/.htpasswd

Now that we've taken password off service domain, we still want to have basic auth on our cloud apps domain.

Update basic auth username and password

---

src/google921002f57f264802.html

The title needs to be specified to avoid tripping up on our own title checks.
https://deploy-preview-371--govuk-design-system-preview.netlify.com/google921002f57f264802.html

Add Google site verification

---

README.md
package-lock.json
package.json
src/components/header/default/index.njk
src/components/header/with-service-name-and-navigation/index.njk
src/components/header/with-service-name/index.njk
src/components/tabs/default/index.njk
src/components/tabs/index.md.njk
src/javascripts/govuk-frontend.js

This PR:
- updates the Design System to use [govuk-frontend 1.0.0](https://github.com/alphagov/govuk-frontend/releases/tag/v1.0.0) 🎉
- adds the tab component example and guidance
- removes the container class from the header examples (as now the container class is being added by default)
- removes the `npm login` instructions for the Design System
[Trello card](https://trello.com/c/noTIT53J)

Update to frontend 1.0.0

---

src/javascripts/components/cookie-banner.js
src/javascripts/main.js

If we also fix https://github.com/alphagov/govuk-design-system/issues/383 the Design System's JavaScript will work in IE8.

Fix old ie javascript

---

src/stylesheets/components/_footer.scss
src/stylesheets/components/_pane.scss

- Remove grid from the app layout
- Override the visually-hidden 'Support links' heading in the footer which fixes an issues with Safari scrolling past the end of the page.
Fixes #373 and #374 
Also fixes an issue where clicking one of the code tabs ('HTML' or 'Nunjucks') jumps you to the top of the page.

Fixes for Safari on macOS

---

src/get-started/updating/index.md.njk
src/styles/spacing/index.md.njk

Static spacing scale is no longer exposed as variables so wording of current content is confusing - this fixes it (consulted @dashouse). Also fixes two other typos.

Fix some words

---

src/components/index.md.njk
src/patterns/index.md.njk
src/styles/index.md.njk
src/stylesheets/components/_pane.scss
views/layouts/layout-pane.njk
views/partials/_in-page-subnav.njk

This PR duplicates the sub-navigation on the Styles, Components and Patterns landing pages for the mobile breakpoint.
Parts of this we'll want to clean up later...

Mobile in page nav

---

src/components/tabs/default/index.njk

This adds a margin-bottom override to the tabs component to keep it in line with our other components
Once this has been added to GOV.UK Frontend we can remove this class from the example in the Design System.
Issue on GOV.UK Frontend here:
https://github.com/alphagov/govuk-frontend/issues/820

Add bottom margin to tabs

---

src/get-started/updating-your-code/index.md.njk

GOV.UK Template used snake case; GOV.UK Frontend uses camel case. So this sentence is backwards.

Fix description of snake/camel case in template.

---

views/partials/_in-page-subnav.njk

This just moves the spacing override to the container div rather than putting it on the heading (only visible when page has themes)

Landing page mobile nav - move spacing override to container div

---

src/components/select/index.md.njk

I think that citizens is a problematic word because:
- the opposite of a citizen is someone who is stateless, which is not the distinction we’re trying to make here
- people who aren’t citizens sometimes need to use government services, for example those applying for asylum
I think ‘public’ is a better word – we are public servants, delivering public services.
***
The reason for making this distinction at all is because we design differently for people who use a service repeatedly. I don’t think that having a catch-all word for these users is realistic because there’s such a wide variety of them. In individual services it’s probably better to refer to them by the role or task they’re employed to do, for example case worker, solicitor, team leader. But ‘non-public’ works to
differentiate …

Refer to non-gov users as ‘public‘ not ‘citizens‘

---

src/get-started/updating-your-code/index.md.njk
views/layouts/layout-pane.njk
views/partials/_mobile-navigation.njk

- Close unclosed `<div class="app-pane__body">` in layout-pane
- Nest ‘theme’ navigation within a `<li>` list item, rather than directly inside the `<ul>`
- Remove `<p>` tags wrapping a `<pre>` which is not valid as both are block-level elements.

Fix invalid HTML

---

src/stylesheets/components/_pane.scss

Fixes #373 (again) - where in Safari it’s possible to scroll ‘past’ the end of the page.

Set overflow: hidden on app pane wrapper

---

config/modernizr.json

We don't use these feature detects, and we already bundle up a separate shiv in the IE8 javascript. This halves the size of the Modernizr javascript from a whopping 9.0KB (4.3KB gzipped) to 4.5KB (2.1KB gzipped)

Remove duplicated shiv and unnecessary feature detects from Modernizr

---

src/stylesheets/components/_header.scss

https://trello.com/c/z3VAUfeE/1202-remove-nav-toggle-button-when-javascript-is-disabled

Do not show header menu button if JavaScript is disabled

---

src/stylesheets/components/_mobile-navigation.scss

Fix duplicated nav on tablet for non-JS users

---

src/components/checkboxes/index.md.njk
src/components/date-input/index.md.njk
src/components/details/index.md.njk
src/components/error-message/index.md.njk
src/components/error-summary/index.md.njk
src/components/fieldset/index.md.njk
src/components/footer/index.md.njk
src/components/header/index.md.njk
src/components/inset-text/index.md.njk
src/components/panel/index.md.njk
src/components/radios/index.md.njk
src/components/table/index.md.njk
src/components/tabs/index.md.njk
src/components/text-input/index.md.njk
src/components/textarea/index.md.njk
src/patterns/addresses/index.md.njk
src/patterns/confirmation-pages/index.md.njk
src/patterns/dates/index.md.njk
src/patterns/email-addresses/index.md.njk
src/patterns/national-insurance-numbers/index.md.njk
src/patterns/page-not-found-pages/index.md.njk
src/patterns/problem-with-the-service-pages/index.md.njk
src/patterns/telephone-numbers/index.md.njk
src/styles/images/index.md.njk
src/styles/layout/index.md.njk
src/styles/page-template/index.md.njk
src/styles/spacing/index.md.njk
src/styles/typography/index.md.njk
src/stylesheets/components/_example.scss
views/partials/_example.njk

For users that have disabled JavaScript, or when JavaScript fails to execute, the iframe sizer will not work which means iframes will all be sized to 150px (the default size for an iframe) regardless of their content.
The iframes are resizable, but we can provide a better experience for these users by setting a better 'default' size for each example.
https://trello.com/c/3hKfCmwo/1201-use-sensible-default-example-size-when-javascript-is-disabled

Set sensible default iframe sizes for non-javascript users

---

src/components/error-summary/index.md.njk

This PR:
- clarifies the relationship between error summary and error message in the error summary guidance
- adds link to guidance on how to write good error messages from error summary how it works section
https://trello.com/c/rz1nYX2v/1225-clarify-intro-on-error-summary-component-page

Update error summary guidance

---

lib/navigation.js
src/components/back-link/index.md.njk
src/components/checkboxes/index.md.njk
src/components/details/index.md.njk
src/components/error-message/index.md.njk
src/components/fieldset/index.md.njk
src/components/inset-text/index.md.njk
src/components/panel/index.md.njk
src/components/phase-banner/index.md.njk
src/components/radios/index.md.njk
src/components/select/index.md.njk
src/components/skip-link/index.md.njk
src/components/tag/index.md.njk
src/components/text-input/index.md.njk
src/components/textarea/index.md.njk
src/components/warning-text/index.md.njk
src/sitemap.njk
src/styles/colour/index.md.njk
src/styles/layout/index.md.njk
src/styles/page-template/index.md.njk
views/layouts/layout-sitemap.njk
views/partials/_footer.njk

Adds a sitemap at `/sitemap` which lists out the contents of the Design System along with common aliases for some of the pages (for example, some users may refer to the Select component as a 'drop-down menu'.
These aliases will eventually be exposed as part of a client-side search feature, but this allows us to make this information available now, and may also eventually act as the 'fallback' for users without javascript enabled.
https://trello.com/c/UnL6P9mM/1193-develop-site-map-page-with-aliases

Add sitemap with alias support

---

lib/file-helper.js
src/patterns/confirmation-pages/default/index.njk
src/patterns/page-not-found-pages/default/index.njk
src/patterns/page-not-found-pages/reason-not-known/index.njk
src/patterns/page-not-found-pages/user-mistake/index.njk
src/patterns/problem-with-the-service-pages/default/index.njk
src/patterns/problem-with-the-service-pages/link-to-another-service/index.njk
src/patterns/problem-with-the-service-pages/offline-support/index.njk
src/patterns/question-pages/default/index.njk
src/patterns/question-pages/passport/index.njk
src/patterns/question-pages/postcode/index.njk
src/patterns/service-unavailable-pages/after-service-closes/index.njk
src/patterns/service-unavailable-pages/available-at-known-date/index.njk
src/patterns/service-unavailable-pages/before-service-opens/index.njk
src/patterns/service-unavailable-pages/default/index.njk
src/patterns/service-unavailable-pages/general/index.njk
src/patterns/service-unavailable-pages/link-to-another-service/index.njk
src/patterns/service-unavailable-pages/no-replacement-service/index.njk
src/patterns/service-unavailable-pages/service-replaced/index.njk
src/patterns/start-pages/default/index.njk
views/layouts/example-wrappers/full-page.njk
views/layouts/layout-example-full-page.njk

This is an alternative to #430 which tries to address some issues spotted whilst trying to move other pages to use full page examples:
- it uses `{% extends "foo.njk" %}` to allow us to define `beforeContent` and `content` blocks within examples – the approach in #430 which uses layouts does not allow us to do this because the page content is rendered to HTML _before_ it is injected into the layout, so the blocks are lost.
- It uses the `pageTitle` variable rather than defining `<title>` inside the `head` block, which means that the title ends up being set twice (once to the default value of "GOV.UK - The best place to find government services and information").
- It does not modify the non-full-page examples.
https://trello.com/c/cVyFXyRa/1180-resolve-inconsistencies-in-our-example-code

Update 'pages' examples to include the header and footer; use beforeContent and content blocks correctly

---

src/patterns/question-pages/passport/index.njk

- Adds missing day field to the date input
- Fixes #441

Update Question page 'Passport details' example

---

src/components/text-input/input-fixed-width/index.njk
src/components/text-input/input-fluid-width/index.njk

Remove headings in text-input example and replace label text to signpost
Additionally make examples unique
trello ticket: https://trello.com/c/zCTeHSEO/1231-rename-headings-on-text-input-example-in-ds

Replace headings with appropriate label text in text-input component examples

---

src/styles/page-template/index.md.njk

Variable is currently used on `<meta property="og:image"` tag where the URL to the assets needs to be absolute.
Fixes: #424

Document `assetUrl` variable in page template

---

src/patterns/addresses/index.md.njk
src/patterns/check-a-service-is-suitable/index.md.njk
src/patterns/check-answers/index.md.njk
src/patterns/confirm-an-email-address/index.md.njk
src/patterns/create-a-username/index.md.njk
src/patterns/create-accounts/index.md.njk
src/patterns/dates/index.md.njk
src/patterns/email-addresses/index.md.njk
src/patterns/gender-or-sex/index.md.njk
src/patterns/names/index.md.njk
src/patterns/national-insurance-numbers/index.md.njk
src/patterns/passwords/index.md.njk
src/patterns/question-pages/progress/index.njk
src/patterns/question-pages/section-headings/index.njk
src/patterns/telephone-numbers/index.md.njk
src/styles/typography/captions-inside/index.njk
src/styles/typography/captions/index.njk
src/styles/typography/index.md.njk
views/layouts/layout-pane.njk

In most cases, the caption is an orientation device and should not form part of the H1 of the page.
For example, in our ‘question pages’ the captions we use are ‘Question 3 of 9’ and ‘About you’ – including these in the H1 would make the page headings ‘Question 3 of 9 Your details’ and ‘About you What is your home adddress?’ – neither of which really make sense.
There will be some cases where including the caption in the H1 _does_ make sense (e.g. within some of the themes in our patterns section as outlined below), but we think these will be generally be an exception.
This PR:
- moves the caption outside of the H1 in existing examples on the typography page and within the 'Question pages' pattern
- adds a new example to the typography page showing the caption inside the H1
- updates the …

Move captions outside headings (where appropriate)

---

src/patterns/email-addresses/index.md.njk

The guide in the service manual used to say:
> Email addresses can be as long as 256 characters, so make sure users can type this many characters into the field. 
>
> The field itself should be wide enough for most users to see their address as they type it. Analyse your data to see how wide you'll need to make the field - but 30 characters is a good rule of thumb.
These two things got muddled when this guidance was transferred to the Design System, so we need to clarify it. There are two different things muddled together here which we can address separately:
The main drive here is that we want to help the user to double check their email address, so that they can make sure that it’s valid. For that reason, I think it makes sense to fold this into the section with the heading ‘Help users …

Clarify guidance around email lengths

---

package-lock.json
package.json
src/components/checkboxes/default/index.njk
src/components/checkboxes/hint/index.njk
src/components/checkboxes/index.md.njk
src/components/radios/conditional-reveal/index.njk
src/components/radios/divider/index.njk
src/components/radios/hint/index.njk
src/components/radios/index.md.njk
views/layouts/_generic.njk

- Update dependency
- Replace duplicate og:image meta tag declaration with new assetUrl variable definition
- Show examples of hint usage with [radios](https://deploy-preview-458--govuk-design-system-preview.netlify.com/components/radios#radio-items-with-hints) and [checkboxes](https://deploy-preview-458--govuk-design-system-preview.netlify.com/components/checkboxes#checkbox-items-with-hints)
- Show example of text divider usage in [radios](https://deploy-preview-458--govuk-design-system-preview.netlify.com/components/radios#radio-items-with-a-text-divider)
Trello ticket:
https://trello.com/c/aAlOAD9F/1269-update-design-system-with-v120-release
This PR doesnt include examples of how to add classes to labels in radio and checkbox items
Can we have eyes on the words @amyhupe?

Update GOV.UK Frontend to 1.2.0

---

src/components/radios/conditional-reveal/index.njk

Add "type" to email, telephone and text radio.
Radio buttons for this example all had a default "type" of text. This update makes these "type"s more reflective of actual content, and also better reflects the individual Patterns for Telephone Numbers and Email addresses.

Added type to Radio button conditional reveal example

---

src/components/checkboxes/conditional-reveal/index.njk

Checkboxes for this example all had a default "type" of text. This update makes these "type"s more reflective of actual content, and also better reflects the individual Patterns for Telephone Numbers and Email addresses.

Added type to checkbox conditional reveal example 

---

src/javascripts/components/copy.js
src/stylesheets/main.scss

No change to the visual design of the button
Update copy JS:
- to append a button rather than a link
- to use a more sensible class name (now that it is no longer a link)
- to set `innerText` rather than `text` when changing text from ‘Copy’ to ‘Copied’ and back.
Update styling of copy element:
- remove link pseudo-selectors
- remove prose scope link overrides which are no longer required
- increase ‘max-width’ from 58px to 80px to account for border-box box-sizing model (links use content-box model)
- add pointer cursor to match button component
- add focus state
https://trello.com/c/w7jE1qer/1288-make-copy-and-close-links-into-buttons

Make the copy button a button

---

lib/metalsmith.js
package-lock.json
package.json

Autoprefix CSS using postcss and autoprefixer. This will fix the display of the close button’s chevron in IE9 (which requires `-ms-transform`) and probably some other stuff too.
This uses the same browserlist as we have in GOV.UK Frontend.

Autoprefix generated CSS

---

src/javascripts/components/mobile-navigation.js
src/stylesheets/components/_mobile-navigation.scss
views/partials/_mobile-navigation.njk

- Allow 'current' section to be closed in mobile nav
- Set ARIA attributes correctly for subnavs
- Don't 'indent' the active page in the mobile nav
See individual commits for details.
https://trello.com/c/7T7mtpHD/1327-mobile-nav-tweaks

Tweaks to mobile nav

---

lib/metalsmith.js
package-lock.json
package.json

Fixes https://github.com/alphagov/govuk-design-system/issues/417 by minifying assets and generating a new sourcemap.
This has the side benefit of making the Design System faster, I will update this PR with the before and after.
https://govuk-design-system-preview.netlify.com/components/button/ vs https://deploy-preview-484--govuk-design-system-preview.netlify.com/components/button/
- Before: 554KB (179 KB gzipped)
- After: 470KB (94.9KB  gzipped)
Based on some quick lighthouse testing this seems to shave 100-200ms off time to first meaningful paint.

Fix iframer source map

---

__tests__/search.test.js
jest-puppeteer.config.js
lib/metalsmith-lunr-index/index.js
lib/metalsmith.js
package-lock.json
package.json
src/javascripts/components/search.js
src/javascripts/main.js
src/stylesheets/components/_header.scss
src/stylesheets/components/_site-search.scss
src/stylesheets/main.scss
views/partials/_header.njk

Enable users to search the Design System. 
Return search results from the generated search index based on user query
Utilising [Accessible autocomplete](https://github.com/alphagov/accessible-autocomplete) and [LunrJS](https://lunrjs.com/)
Trello ticket: https://trello.com/c/yqJxOj5e/1273-5-implement-client-side-search-interface
Thanks to Nick for added pair of hands.
<details>
<summary>AT testing</summary>
**JAWS 16,17 with IE11**
**EDIT: Jaws 15 announces the number of results, 16 and 17 don't
https://github.com/alphagov/accessible-autocomplete/issues/235**
1) tab to focus: _"Search design system edit combo. use arrow key or type in value"_ 
2) type "d": no number of results announced, selected item not announced
3) arrow down to select 2nw item:  _"list box details"_
**JAWS: 16 on …

Setup design system search

---

src/patterns/check-answers/index.md.njk
src/patterns/task-list-pages/index.md.njk

A couple of links just broke because we reorganised the templates in the kit

Fix prototype kit links

---

jest-puppeteer.config.js

We had very frequent failures to start the tests on Travis.
Extending the launchTimeout to 30s seems to have solved the issue.
Ran 3 consecutive builds on Travis and all completed OK. 
Tests still complete in roughly the same time as before
```
$ npm test -- --runInBand
> govuk_design_system@ test /home/travis/build/alphagov/govuk-design-system
> npm run lint && jest "--runInBand"
> govuk_design_system@ lint /home/travis/build/alphagov/govuk-design-system
> npm run lint:js && npm run lint:scss
> govuk_design_system@ lint:js /home/travis/build/alphagov/govuk-design-system
> standard
> govuk_design_system@ lint:scss /home/travis/build/alphagov/govuk-design-system
> gulp scss:lint
[12:26:11] Using gulpfile ~/build/alphagov/govuk-design-system/gulpfile.js
[12:26:11] Starting 'scss:lint'... …
```

Extend jest-puppeteer launchTimeout

---

src/stylesheets/components/_site-search.scss

Since we do not have a border on the menu anymore, we can have it fit properly.

Remove width logic needed for bordered menu

---

views/layouts/layout.njk

At the moment skip-link href is set to target `#main-content` which doesn't exist.

Update <main> element id to match skip-link target

---

lib/metalsmith-lunr-index/index.js
lib/metalsmith-lunr-index/index.test.js
src/javascripts/components/search.js
src/stylesheets/components/_site-search.scss

Store the section that a page is in as part of the document store, and present it as part of the search result in the interface.
We think this will help users to choose the most relevant match when presented with multiple results, and help them to understand the structure of the Design System.
https://trello.com/c/QN7zxxXi/1275-2-include-the-category-and-or-theme-when-presenting-search-results

Include section in search results

---

__tests__/search.test.js
deploy/nginx.conf
lib/metalsmith.js
src/javascripts/components/search.js
views/partials/_header.njk

Fingerprint the search index in the same way we fingerprint other assets (stylesheets, JavaScript), allowing us to cache it indefinitely.
Update the search JavaScript to read the current fingerprinted search index from a data attribute on the container (`data-search-index`)
This should mean that:
- the browser should only download the (same version of the) search index once
- when a new page is added to the Design System, deploying should cause browsers to load the new version of the search index on the next page load, preventing the search from returning out-of-date results

Fingerprint and cache the search index

---

__tests__/search.test.js
deploy/nginx.conf
lib/metalsmith.js
src/javascripts/components/search.js
views/partials/_header.njk

This change introduced some rendering issues of the page template page, so we want to revert it since trying to find a fix seems to be taking a while.
We believe it the issue is due to moving the hashAssets step, but are struggling to get lunr to work correctly when we move it. 
Reverts alphagov/govuk-design-system#489

Revert "Fingerprint and cache the search index"

---

src/styles/page-template/custom/index.njk

It's currently calling the wrong file and without the hash (see console log): https://design-system.service.gov.uk/styles/page-template/

Fix fingerprint in custom template example

---

lib/metalsmith.js
package-lock.json
package.json

metalsmith-layouts v2.0.0 started using jstransformers under the hood. This means we no longer need to specify the engine, as it will be inferred from the .njk file extension. We do however now need to pass the `views` array so that the layouts knows where to look to resolve templates from other places (partials, the template in Frontend) [1] – I have no idea how this worked before…
[1] This took WAY too long to debug – the error it was giving because it could not resolve the templates was “Error: Invalid result object from transform.” 🤦‍♂️ On the plus side, I learnt a lot about using Developer Tools to debug Node apps!

Update metalsmith-layouts to v2.1.0

---

lib/metalsmith-lunr-index/index.js
src/javascripts/components/search.js

Currently the search is configured so that every term (word) the user enters is required to match against a document for it to be returned as a result. This has the advantage that it only shows results which ‘perfectly’ match the entered terms – for example, searching for ‘date input’ will return only the date input component. This also means that entering additional terms will only ever refine the displayed results, ‘narrowing down’ the list.
The disadvantage of this approach is that users searching for something like ‘user accounts’ will never find the ‘Create accounts’ pattern, because that pattern does not include the word ‘user’ in any field that we currently index.
We _could_ work around this specific case by adding ‘user accounts’ as an alias, but we think that making each term …

Make search terms optional

---

lib/file-helper.js
lib/metalsmith.js
src/styles/page-template/block-areas/index.njk
src/styles/page-template/custom/index.njk
src/styles/page-template/default/index.njk
views/layouts/_generic.njk
views/layouts/layout-example-full-page.njk
views/layouts/layout-example.njk

Using a helper allows us to throw an error if the file is not found in the fingerprint array, making it harder to break the build without realising.

Use helper to lookup fingerprinted files

---

__tests__/search.test.js
deploy/nginx.conf
lib/metalsmith.js
src/javascripts/components/search.js
views/partials/_header.njk

_As per the [original pull request](https://github.com/alphagov/govuk-design-system/pull/489) with the difference of a separate hashing of the `search-index.json` file later the in the process._
> Fingerprint the search index in the same way we fingerprint other assets (stylesheets, JavaScript), allowing us to cache it indefinitely.
> 
> Update the search JavaScript to read the current fingerprinted search index from a data attribute on the container (data-search-index)
> 
> This should mean that:
> 
> the browser should only download the (same version of the) search index once
> when a new page is added to the Design System, deploying should cause browsers to load the new version of the search index on the next page load, preventing the search from returning out-of-date results

Reimplement fingerprint and search index caching

---

lib/file-helper.js
lib/metalsmith.js
src/styles/page-template/block-areas/index.njk
views/layouts/layout-example-full-page.njk
views/layouts/layout-example.njk

Update the config to fingerprint all CSS files, and use the fingerprint helper to include them.
Because we specify some asset paths using relative URLs (e.g. `../grid-nested-annotate.css`), but the fingerprint object has everything relative to the root, we need to ‘normalise’ all URLs using the path. Unfortunately that means we need to know the path of the page including the asset, and we don’t know that within metalsmith-in-place (because metalsmith-in-place runs before metalsmith-permalinks). This means we can call getFingerprint with relative URLs in layouts, but not in the source files themselves.
For that reason, the ‘block areas’ example has been updated to specify a path relative to the root.
https://trello.com/c/EHg1iVP5/1354-extra-css-for-examples-is-not-fingerprinted-but-is-cache …

Fingerprint all CSS files

---

src/components/text-input/default/index.njk

Change the default example for the text input component from an input asking for an email address to an example asking for someone’s full name.
As [raised in the backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/51#issuecomment-414986345), we are not currently using the correct `type=“email”`. We could fix this, but as users are likely to take this ‘default’ example and modify it to ask different questions, it makes sense to make it as generic as possible, avoiding using a type specific to a particular type of input.
Therefore changing to a more ‘generic’ question, such as full name, which does not require specific input types, makes more sense.

Use simpler default example for text inputs

---

__tests__/search.test.js
lib/metalsmith-lunr-index/fixtures/src/radios.html
lib/metalsmith-lunr-index/index.js
lib/metalsmith-lunr-index/index.test.js
src/javascripts/components/search.js
src/stylesheets/components/_site-search.scss

Include aliases ('reveal' for details) and common alternative spellings ('color' instead of colour) when searching.
We know that different users refer to the same component or pattern using different names. Allowing them to search for the component or pattern with other names increases the likelihood that they will find it.
Trello ticket: https://trello.com/c/1qzrKg00/1276-3-include-aliases-and-common-alternative-spellings-when-searching
Matches against the title carry a 10 times greater weight that matches agains the aliases.
When adding more characters to the query, if there are no matches in the title, results will contain matches in any of the item's aliases and show those aliases until there are no more matches.
Matches titles first, then aliases (for the select) and shows aliases …

Search aliases

---

views/layouts/layout-example-full-page.njk

The getFingerprint function returns a path that includes the leading slash already, so this currently evaluates to `//javascripts/govuk-frontend-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.js` which means the browser treats the URL as a protocol-less but absolute URL and tries to load `https://javascripts/govuk-frontend-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.js`.

Fix broken script include on full-page examples

---

src/javascripts/application.js
src/javascripts/components/copy.js
views/partials/_example.njk

- Removes jQuery dependency
- Followes GOV.UK Frontend convevtions
- Works in IE9+ (plugin does not support IE8)
Trello ticket: https://trello.com/c/J02wN45k/1326-update-copyjs-to-follow-frontend-conventions-and-remove-dependency-on-jquery
Ticket to build an ie8 bundle is here: https://trello.com/c/B6N3G2fS/1325-ensure-copy-to-clipboard-functionality-does-not-break-ie8-experience

Rewrite 'copy' functionality to remove jQuery dependency and follow GOV.UK Frontend conventions

---

src/javascripts/application.js
src/javascripts/components/example.js
views/partials/_example.njk

- Rewrite example.js
- Rewrite initialisation in application.js
- Initialise iframe with data-module attribute instead of a css class

Rewrite 'example' functionality to follow GOV.UK Frontend conventions

---

src/components/tabs/index.md.njk

We don't know if listing the devices/AT in the current manner on the Tabs page is the right approach.
We would like to research this with users but meanwhile we'll remove the "Browser testing" and "Testing with assistive technologies" sections to make Tabs consistent with the other component pages.

Remove "Browser testing" and "Testing with assistive technologies" from Tabs component page

---

src/javascripts/application.js
src/javascripts/components/search.js
views/partials/_header.njk

This PR modernises search javascript to follow GOV.UK Frontend conventions
- Use of data-module attribute to initialise the script
- Rewrite functions to match they way they're written in GOV.UK Frontend
Easier to review without whitespace: https://github.com/alphagov/govuk-design-system/pull/516/files?utf8=%E2%9C%93&diff=split&w=1

Rewrite "search" functionality to follow GOV.UK Frontend conventions

---

src/patterns/question-pages/default/index.njk
src/patterns/question-pages/passport/index.njk
src/patterns/question-pages/postcode/index.njk
views/layouts/layout-example.njk

Most modern browsers provide some sort of validation for fields that have explicit types (such as email, or telephone) or when a field is marked as required. The way that this validation works is inconsistent across browsers, and we have little control over the content or the style of the error messages that are used. This means that there are multiple ‘stages’ of validation going on, and there is no consistency between them.
_An example of browser validation kicking in in Firefox. Note the pink outline around the input and the tooltip._
For this reason, we have previously recommended disabling the browser’s native validation (though this doesn’t seem to be written down anywhere, yet) so we should do this in our own examples.
For full page examples that already have forms, it’s as simple …

Disable browser form validation in examples

---

src/components/panel/index.md.njk
src/patterns/confirmation-pages/index.md.njk

Added information about colour contrast and font size for the panel component. I put this on the component page and the confirmation page pattern page to make sure people see the information.
This used to be in the [colour section in Elements](http://govuk-elements.herokuapp.com/colour) and I think it was useful.

Colour contrast

---

package-lock.json
package.json
src/components/date-input/default/index.njk
src/components/date-input/error/index.njk
src/components/error-message/default/index.njk
src/components/panel/default/index.njk
src/components/text-input/input-fluid-width/index.njk
src/patterns/dates/default/index.njk
src/patterns/question-pages/default/index.njk
src/patterns/question-pages/passport/index.njk

Note: This pull request has been done using `npm link`, and will need to updated once GOV.UK Frontend 2.0.0 releases.

Update govuk frontend 2.0.0

---

src/stylesheets/components/_contact-panel.scss
src/stylesheets/components/_header.scss
src/stylesheets/components/_mobile-navigation.scss
src/stylesheets/components/_tabs.scss

Updates various focus styles in the design system website to be consistent with regular link styles.
Also ensure the navigation scales based on font size updates.
Fixes a regression due to prose scope styles leaking into the application specific tabs component.
---
---
---

Update focus styles, navigation font size

---

src/components/checkboxes/error/index.njk
src/components/checkboxes/index.md.njk
src/components/date-input/error/index.njk
src/components/date-input/index.md.njk
src/components/error-message/default/index.njk
src/components/error-message/index.md.njk
src/components/radios/error/index.njk
src/components/radios/hint/index.njk
src/components/radios/index.md.njk
src/components/text-input/error/index.njk
src/components/text-input/index.md.njk
src/components/textarea/error/index.njk
src/components/textarea/index.md.njk
src/patterns/addresses/error/index.njk
src/patterns/addresses/index.md.njk
src/patterns/dates/error/index.njk
src/patterns/dates/index.md.njk
src/patterns/email-addresses/error/index.njk
src/patterns/email-addresses/index.md.njk
src/patterns/names/error/index.njk
src/patterns/names/index.md.njk
src/patterns/national-insurance-numbers/error/index.njk
src/patterns/national-insurance-numbers/index.md.njk
src/patterns/telephone-numbers/index.md.njk

This pull request adds the error message examples and templates contributed by @stevenaproctor and [reviewed here by the Design System working group](https://github.com/alphagov/govuk-design-system-backlog/issues/47#issuecomment-418156705).
The following pages have had error message examples and templates added to them:
- src/components/checkboxes/index.md.njk
- src/components/date-input/index.md.njk
- src/components/error-message/index.md.njk
- src/components/radios/index.md.njk
- src/components/text-input/index.md.njk
- src/components/textarea/index.md.njk
- src/patterns/addresses/index.md.njk
- src/patterns/dates/index.md.njk
- src/patterns/email-addresses/index.md.njk
- src/patterns/names/index.md.njk
- src/patterns/national-insurance-numbers/index.md.njk
- …

Add error message examples to components and patterns

---

src/components/date-input/error/index.njk
src/components/error-message/default/index.njk
src/patterns/dates/error/index.njk

Add explicit width classes to date fields to support the 2.0 release of GOV.UK Frontend

Fix year field widths

---

src/stylesheets/main.scss

From https://github.com/necolas/normalize.css/issues/519#issuecomment-197131966
Major web browsers reduce the text size of elements whose `font-family` property is explicitly set to `monospace` to account for the greater width of many monospace typefaces in comparison to other fonts at the same text height ([citation](http://code.stephenmorley.org/html-and-css/fixing-browsers-broken-monospace-font-handling/)).
Browsers using **Blink**, **Gecko**, and **WebKit** reduce the size of `monospace`. Therefore, the `monospace,monospace` fix applies to **Android ≤ 6**, **Chrome ≤ 49**, **Firefox ≤ 45**, **iOS ≤ 9**, **Opera 15-35**, and **Safari 5-9**. The fix does not work for **Safari ≤ 4**.
Browsers using **Presto** and **Trident** treat `monospace` normally. Therefore, the …

Fix monospace font size

---

src/stylesheets/components/_header.scss
src/stylesheets/components/_site-search.scss

The Design System has a custom "Menu" button.
I have updated the style to look the same as the "Menu" button in the header component.
This also has a benefit of increasing the size of the search container and revealing the entire placeholder text at 320px.

Style the menu button to look the same as the standard header

---

src/patterns/service-unavailable-pages/after-service-closes/index.njk
src/patterns/service-unavailable-pages/available-at-known-date/index.njk
src/patterns/service-unavailable-pages/before-service-opens/index.njk
src/patterns/service-unavailable-pages/default/index.njk
src/patterns/service-unavailable-pages/general/index.njk
src/patterns/service-unavailable-pages/link-to-another-service/index.njk
src/patterns/service-unavailable-pages/no-replacement-service/index.njk
src/patterns/service-unavailable-pages/service-replaced/index.njk

This makes the examples meet what was discussed in the working group meeting. A couple of members questioned the use of lead paragraphs and these should have been removed sooner.

Removed lead paragraphs from examples

---

lib/extract-page-headings.js
lib/metalsmith.js
lib/navigation.js
src/styles/layout/index.md.njk
src/styles/spacing/index.md.njk
src/styles/typography/index.md.njk
src/stylesheets/components/_page-navigation.scss
src/stylesheets/components/_subnav.scss
src/stylesheets/main.scss
views/layouts/layout-pane.njk
views/partials/_subnav.njk

We have a plugin that extracts page headings from the markdown file and creates an array of heading objects in page metadata. Each heading object contains text, depth level (h1,h2,h3) and a generated url (which is the same as markedjs-generated heading id). 
We use this metadata to generate in-page and sidebar navigation.
In navigation.js I created a variable `subitem.link` which reads the url of the page and puts the label from the metadata at the end. If the url has that label the I ask it to show the contents of the json file, which are links that you to the appropriate place in the page. I added a loop in _subnav.njk that is looping through the metadata.headings array. Added styles for those links at _subnav.scss
https://trello.com/c/EOkrfNkF
**In page navigation Mobile view**
I have …

Add in page navigation 

---

src/stylesheets/components/_page-navigation.scss

Somewhere in the refactoring this code this spacing was removed.
Removes the browser default `<ul>` margin-top and adds margin-bottom so the list is equally spaced.
**CURRENT LIVE**
**AFTER**

In-page navigation - Remove default ul margin, add margin-bottom

---

__tests__/search.test.js

When adding different content that feeds search it flagged that tests were not set up correctly to match how the search matching logic works.
Updated tests in now test for words beginning with the query in the title (words) and then separately in the aliases, correctly accounting for the fact that there may not be aliases present.
Fault was identified in #476 and a temp fix was added there which needs to be removed once this is merged in

Make search test more robust

---

src/community/contribution-criteria/index.md.njk
src/community/develop-a-component-or-pattern/index.md.njk
src/community/propose-a-component-or-pattern/index.md.njk

This PR:
- fixes a typo in the contribution criteria 
- updates the timings for proposing a new component or pattern in line with process iteration
- updates working group decision options in line with process iteration

Update contribution guidance

---

src/styles/layout/index.md.njk

This is no longer needed as search will now return a result for 'grid' based on the page headings on the 'layout' page

Remove grid alias

---

data/colours.json

I have spoken to teams who have used focus colour for an active state since it stands out.
This updates the colours page to explicitly mention what it should be used for.
Tried to avoid using the technical terminology even though I think calling out ':focus' would be useful...
Closes #150

Add notes clarifying use of focus colour

---

src/styles/spacing/input-width/index.njk

Full width override class was added in Frontend 2.0 but wasn't added to the spacing section of the design system

Add full width override

---

src/patterns/service-unavailable-pages/after-service-closes/index.njk
src/patterns/service-unavailable-pages/available-at-known-date/index.njk
src/patterns/service-unavailable-pages/before-service-opens/index.njk
src/patterns/service-unavailable-pages/default/index.njk
src/patterns/service-unavailable-pages/general/index.njk
src/patterns/service-unavailable-pages/index.md.njk
src/patterns/service-unavailable-pages/link-to-another-service/index.njk
src/patterns/service-unavailable-pages/no-replacement-service/index.njk
src/patterns/service-unavailable-pages/service-replaced/index.njk

Updated the documentation and examples to include "sorry" in the `<title>` and `<h1>`.
This makes the examples meet the ['tone' section of Writing for user interfaces](https://www.gov.uk/service-manual/design/writing-for-user-interfaces#tone). From a user's point of view, "something serious has gone wrong" when a service is unavailable, even though it is unavailable on purpose.

Updated service unavailable page examples and documentation

---

src/get-in-touch.njk
views/partials/_contact-panel.njk

We already track the equivalent links on the homepage, this just applies the same data attributes to support links in the panel at the bottom of most pages and on the ‘Get in touch’ page.
This will help us to understand what channels users go to for support.
Also removes duplicated class attributes from links on the get in touch page.
https://trello.com/c/2lrSoUGg/1459-add-data-attributes-to-all-support-links

Add data attributes to track contact links

---

src/components/footer/full/index.njk

This relies on a change in GOV.UK Frontend 2.1.0 that introduced a new footer ‘meta’ area, designed for things like the ‘Built by GDS’ colophon. This aligns the footer example with the current design on GOV.UK.

Move colophon in footer example out of meta links

---

__tests__/tabs.test.js
src/javascripts/components/tabs.js
src/patterns/question-pages/index.md.njk
views/partials/_example.njk

Allows for a single tab to be present and toggle-able, depending on the parameters.
Also introduces a `hideTab` parameter.
When we have a single tab, want to have is expanded but not show the tab list item, set it to `true`
This page has the most diverse examples: https://deploy-preview-557--govuk-design-system-preview.netlify.com/patterns/question-pages/
To announce to screenreaders that the tab is expanded / collapsed we toggle `aria-expanded` on the trigger and `aria-hidden` on the content container.
Trello ticket: https://trello.com/c/wF6tmFc1/1321-iterate-example-code-block-tabs-2

 Update tabs component to allow for a single tab that can be toggled

---

src/components/text-input/input-hint-text/index.njk

'National Insurance' instead of 'National insurance'.

Changed capitalisation in example

---

src/patterns/question-pages/index.md.njk

This PR adds a link from the How it works section of the Question pages pattern to the Service Manual guide on Designing good questions

Link to service manual designing questions guide from question pages

---

__tests__/search.test.js
src/javascripts/components/search.js
src/javascripts/components/search.tracking.js

This implements events fired to Google Tag Manager via the data layer.
This article was really useful to set this up: https://www.analyticsmania.com/post/google-tag-manager-custom-event-trigger/
1. Set up a 'trigger' that matches the 'event' property in our data layer events.
2. Setup three new variables that can reference the eventDetails properties, (this screenshot shows one example) (This wont need to be done again if a similar approach is taken in the future)
2. Setup a 'tag' that references the variables set.
-  mocks the normal timeout for the tracking functionality to avoid very slow tests
- includes an explicit cut off point to stop any search JavaScript executing in browsers that can not run the Accessible Autocomplete, this allows us to use any features available in IE9+

Add events for search tracking

---

src/javascripts/components/search.js

Compare search query and recorded aliases in lower case so that returned matches are more consistent.
Fixes: #580

Tweak search alias matching

---

src/community/backlog/index.md.njk

Remove 'Character count' and 'Payment details' from backlog as these have now been published.

Remove published items from backlog

---

src/patterns/payment-card-details/index.md.njk

This PR adds guidance to the Payment card details pattern saying not to assume that the name on a user's card will be the same as they enter elsewhere in the service.
This addition came from the Credit card details file on Dropbox Paper which has been archived as part of the migration work.

Add guidance on asking for names

---

src/components/tabs/index.md.njk

This PR adds information explaining how tabs behave when JavaScript is not available.
This update is follows a review of the Tabs file in Dropbox Paper, which has now been archived.

Add info on how component behaves without JS

---

config/paths.json
lib/metalsmith.js
package-lock.json
package.json
src/javascripts/application-ie8.js
src/javascripts/head-ie8.js
src/styles/page-template/block-areas/index.njk
src/styles/page-template/custom/index.njk
src/styles/page-template/default/index.njk
views/layouts/_generic.njk
views/layouts/layout-example-full-page.njk
views/layouts/layout-example.njk

Fixes issues that stopped the Design System JavaScript behaviour from working in IE8.
- Google Tag Manager fails in IE8
- Uglify needs to be configured to work in IE8
- Copy and Search both rely on dependencies that fail on runtime
Clipboard.js and Accessible Autocomplete cannot bypassed by runtime feature detection and must not be loaded instead, this is why I have opted for a separate IE8 bundle.
I have raised an issue on the accessible autocomplete to make this easier for others: https://github.com/alphagov/accessible-autocomplete/issues/306
https://trello.com/c/B6N3G2fS/1325-ensure-copy-to-clipboard-functionality-does-not-break-ie8-experience

Fix javascript errors in ie8

---

src/components/error-message/label/index.njk
src/patterns/email-addresses/error/index.njk
src/patterns/email-addresses/index.md.njk
src/patterns/national-insurance-numbers/error/index.njk
src/patterns/national-insurance-numbers/index.md.njk
src/patterns/telephone-numbers/index.md.njk

After a discussion with other designers, we thought "right format" maybe misinterpreted by some users and thought saying "correct format" was more accessible.

Change right format to correct format

---

package.json
views/partials/_tracking-head.njk

I think this started failing when we published the Google Tag Manager updates.
Since we are only testing that our events are added to the data layer, and the data layer is a simple object on the window, we can force Google Tag Manager not to load which'll ensure our tests won't get polluted.

Prevent Google Tag Manager from updating the dataLayer

---

src/javascripts/application.js
src/javascripts/components/mobile-navigation.js
src/javascripts/components/search.js

Rewrites the mobile navigation JavaScript to avoid using jQuery
Worth reading this commit by commit since I needed to refactor the structure of this before rewriting it to jQuery.
https://trello.com/c/IqK2orrv/1328-update-mobile-navigationjs-to-follow-frontend-conventions-and-remove-dependency-on-jquery

Remove jquery from mobile navigation

---

__tests__/mobile-navigation.test.js
__tests__/search.test.js
__tests__/tabs.test.js
package.json
views/partials/_tracking-head.njk

We need to inject a global variable at runtime since we do not want to create additional builds as this would cause our tests to run too slowly.
Uses [evalutateOnNewDocument](https://github.com/GoogleChrome/puppeteer/blob/v1.9.0/docs/api.md#pageevaluateonnewdocumentpagefunction-args) to ensure we inject this variable before any of our code is run.
> The function is invoked after the document was created but before any of its scripts were run. This is useful to amend the JavaScript environment, e.g. to seed Math.random.
Reverts the previous attempt since while it could be useful it might confuse someone in the future since it does not actually do anything in our build pipeline.

Prevent google tag manager running in tests

---

src/javascripts/application-ie8.js
src/javascripts/application.js
src/javascripts/components/tabs.js
src/stylesheets/components/_tabs.scss
views/partials/_example.njk

Rewrites the Tabs JavaScript to avoid using jQuery
Trello ticket: https://trello.com/c/kUIcctm7/1352-update-tabsjs-to-avoid-using-jquery-3

Remove jQuery from Tabs

---

views/layouts/_generic.njk

Resolves #415.
Some questions:
* Do we want to port this change to the alphagov/govuk-frontend template?
* Do we want to include the "- GOV UK Design System" in the open graph description?
Hope this helps :)

Added open-graph title and description using existing elements

---

src/stylesheets/components/_pane.scss

Until we do proper 3-pane scrollable layout we can address the scrollbar issue for Edge / IE11 when scrollbar is invisible when scrolling.
This work makes the scrollbar appear when hovered over the section or section is in focus.
Otherwise scrollbar disappears, same as it does in other browsers.
Addresses: #468
Before:
After:

Show scrollbars for Edge / IE11 when page is interacted with

---

package-lock.json
package.json

Latest released version. 
Release notes here: https://github.com/alphagov/govuk-frontend/releases/tag/v2.3.0

Update GOV.UK Frontend to v2.3.0

---

src/patterns/step-by-step-navigation/index.md.njk

It was pointing to the start page issue

Fix 'Discuss' link so it points to new 'step by step' issue

---

__tests__/component-options.test.js
lib/file-helper.js
lib/metalsmith.js
package-lock.json
package.json
src/components/text-input/index.md.njk
src/components/textarea/index.md.njk
src/javascripts/application-ie8.js
src/javascripts/application.js
src/javascripts/components/copy.js
src/javascripts/components/options-table.js
src/stylesheets/components/_options.scss
src/stylesheets/main.scss
views/layouts/_generic.njk
views/partials/_example.njk

Co-authored with @hannalaakso 
This PR:
- Formats `macro-options.json` for rendering within component pages by grouping it by tables, adding heading data and linking to other components.
- Places the tables markup inside a Details component within each Nunjucks tab.
- Renders any nested items within options as their own table and links to the table from the primary options.
- Renders Hint and Label component options as their own tables in the options of the component using them.
- Marks up any markdown in `description` fields using marked.js
- Adds the warning about using HTML with Nunjucks macros in production from the component README's above the table (we have a separate card to look at how we talk about HTML and Nunjucks).
- Visually hides the "Primary options" table caption as the …

Render component options as tables

---

views/partials/_example.njk

This should have been in https://github.com/alphagov/govuk-design-system/pull/518.
Google Tag Manager looks for the innermost element as the source of clicks so the tag needs to be inside the summary.

Move GTM tag to innermost <span> in options <details>

---

src/components/radios/index.md.njk

This pull request adds guidance to the radios component page explaining that combining conditional reveals with inline radios is not recommended or supported.

add-guidance-for-conditional-reveal-with-horizontal-radios

---

src/components/error-summary/index.md.njk
src/components/error-summary/linking-checkboxes-radios/index.njk
src/components/error-summary/linking-multiple-fields/index.njk
src/components/error-summary/linking/index.njk

This introduces guidance to help service teams link from the error summary to the corresponding questions in an accessible way.
👉You can preview this change here: https://deploy-preview-634--govuk-design-system-preview.netlify.com/components/error-summary/
Our approach mirrors the [recommended approach from WebAIM][1], linking to the input in all cases.
This does mean that the input would natively be focussed at the top of the viewport, which means the associated label or legend would not be visible to the user. There is a [corresponding change to Frontend][2] to manually manage the focus and scroll state, allowing us to target and focus the input whilst scrolling to the label or legend.
To understand how to do this in an accessible way, we carried out research using a [simplified test …

Add guidance on linking from the error summary

---

manifest.yml

According to PaaS’ docs, “for a production app, you should always run more than one instance.”
https://docs.cloud.service.gov.uk/managing_apps.html#increasing-instances
Also updated another out of date link to their docs.

Run two instances rather than one

---

__tests__/example.test.js
lib/metalsmith.js
src/javascripts/example.js
views/layouts/layout-example-full-page.njk
views/layouts/layout-example.njk

This work creates a new `example.js` file entry point that is imported in example layout views and it includes a function that prevents form submission.
This is needed as users can either view the example in an iframe or a separate page. On those pages we don't import `application.js`, only 'frontend.js`.
`Example.js` is rolled-up, hashed and minified in the metalsmith build process.
Example page: https://deploy-preview-621--govuk-design-system-preview.netlify.com/patterns/question-pages/
Tested in:
Trello ticket: https://trello.com/c/i3DlCyU3/1369-form-examples-in-the-design-system-load-the-system-into-the-iframe-on-submission-timebox-05-days

Prevent forms in examples from submitting

---

package-lock.json
package.json
src/javascripts/govuk-frontend.js

Overrides the init function to avoid the autofocus behaviour, we should remove this when the component has this option itself.

Update GOV.UK Frontend and enable error summary

---

src/javascripts/components/tabs.js

We fix the dependency import in GOV.UK Frontend in v2.4.0, so there is no more need to import it here.
Fixes: #637 
Tabs looking lovely in IE8 after removal

Remove Element polyfill import in tabs.js

---

__tests__/tabs.test.js
views/partials/_example.njk

If the example has both html and nunjucks set to false we don't want to render the tabs list items.
This fixes the current issue, where on [styles/images](https://design-system.service.gov.uk/styles/images/) there is an empty tab list item, even though html is set to false.
Fixes: #622

Conditional render of tab list items

---

config/modernizr.json
src/stylesheets/components/_pane.scss

Fixes: #624 
Based on ideas from
https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size
Browser visual check:
Safari
Chrome:
Firefox:
Edge: 
IE 11: 
IE 10: 
IE 9: 
IE 8:
to note: ie8 footer is still fubar is it is on live, partly issue with the use of HTML5 footer element

Fix Safari layout display bug

---

deploy/nginx.conf
manifest.yml

This upgrades nginx from 1.13.11 to 1.15.6.
Relevant breaking changes in v1.0.0 of the buildpack:
- Change {{.Port}} to {{ port }} for nginx config templating
- Apps no longer need to set pid to /tmp/nginx.pid because the default now just works
Tested by deploying to CloudFoundry using `cf push`.
https://trello.com/c/DRa9ngrl/1536-update-nginx-buildpack

Update nginx buildpack to v1.0.3

---

src/components/character-count/index.md.njk
src/patterns/payment-card-details/index.md.njk
src/patterns/task-list-pages/index.md.njk

This PR updates the "Services using this pattern" markup from an `<h4>` to `<strong>` and `<br>`'s
This fixes https://github.com/alphagov/govuk-design-system/issues/604

Update "Services using this pattern"

---

src/patterns/telephone-numbers/index.md.njk

The link to the GOV.UK Style guide is - `https://via.hypothes.is/https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#telephone-numbers`
This PR removes hypothesis from the link

Remove link to hypothesis on Telephone numbers pattern

---

src/components/date-input/error/index.njk
src/components/date-input/index.md.njk
src/components/error-message/default/index.njk
src/components/error-summary/linking-multiple-fields/index.njk

Added a new error message template following a conversation in Slack with Wayne from DVLA.
I added the error message border to the day and month fields in the date input error example and the date of birth example in error message. This is because the entire date is wrong, not just the year.
I have updated the example in the error summary to fit more with the new documentation too.

Updated date input error messages and example

---

views/layouts/layout-example-full-page.njk

This PR adds 'Service name' to our full page examples in the design system.
This is one step related to an issue of services about to go live with no service name  https://trello.com/c/Ufu0Y7KE/1631-make-it-clear-which-template-govuk-services-should-be-using

Add generic 'service name' to all full page examples

---

src/get-started/labels-legends-headings/label-h1/index.njk
src/get-started/labels-legends-headings/label-m-s/index.njk

Noticed that the checkboxes issue also applies to the label examples
https://github.com/alphagov/govuk-design-system/pull/662

Fix label association for label examples

---

src/components/table/column-widths-custom-classes/column-width-custom-classes.scss
src/components/table/column-widths-custom-classes/index.njk
src/components/table/column-widths/index.njk
src/components/table/index.md.njk

Provide an example of how table column widths can be set using the available 'classes' parameter in the Nunjucks macro.
Addresses https://github.com/alphagov/govuk-frontend/issues/887 with an example  here.
Also part of https://trello.com/c/2A9eFRgu/1546-add-missing-documentation-to-the-design-system

Showcase custom classes on tables

---

src/components/back-link/index.md.njk
src/patterns/question-pages/index.md.njk

Following a review of the back link guidance in Dropbox Paper (which has now been removed), this pull request:
- updates the Question pages guidance to say do not disable the browser back button.
- updates the back link guidance to say hide the back link if it relies on JavaScript and JavaScript is not available

Update back link guidance

---

src/patterns/problem-with-the-service-pages/index.md.njk

Updated the bullets under 'How it works' to include the correct page title and h1.

Updated There is a problem with the service pages documentation

---

src/components/accordion/default/index.njk
src/components/accordion/index.md.njk
src/components/accordion/with-summary-section/index.njk
src/javascripts/govuk-frontend.js

_Note for reviewers:_
Please leave any comments pertaining to the guidance/documentation or the content used for the accordion on this PR.
Please leave any comments for the accordion component itself (design, code) on https://github.com/alphagov/govuk-frontend/pull/958.

Add accordion component

---

src/components/summary-list/default/index.njk
src/components/summary-list/index.md.njk
src/components/summary-list/without-actions/index.njk
src/components/summary-list/without-borders/index.njk

https://github.com/alphagov/govuk-frontend/pull/1065
https://trello.com/c/kh2atSrd/1612-add-summary-list-component-to-govuk-frontend-pair
We probably should have some guidance on how to use the `visuallyHiddenText` option.
This is blocked on https://github.com/alphagov/govuk-design-system/pull/667
See https://github.com/alphagov/govuk-frontend/pull/1097 for an example of the two new features for check answers

Add summary list component

---

src/patterns/confirmation-pages/default/index.njk

Changed h3 to h2 to avoid skipping a heading level.

Updated heading level in example

---

src/community/backlog/index.md.njk

This PR updates the Backlog page by removing the Accordion component from the list of backlog work, because it's now been published.

Remove Accordion from backlog page as now published

---

data/colours.json
lib/colours.js
src/styles/colour/index.md.njk

Replace reference to `govuk-colour("blue")` in the 'main colours' section with a reference to `$govuk-brand-colour`.
Add guidance to discourage people from using the palette when there is a variable that meets their use case, and also from using the semantic variables for unrelated purposes.
Move the guidance about using sass variables into the ‘main colours’ section.
Add undocumented colours (`$govuk-input-border-colour`, `$govuk-link-active-colour`, `$govuk-focus-text-colour`)
Refactor the colour library code – primarily to avoid having to define the palette again.
Hopefully this should help to clear up some of the confusion discussed in https://github.com/alphagov/govuk-frontend/issues/920
👉[Preview change](https://deploy-preview-717--govuk-design-system-preview.netlify.com/styles/colou …

Update colours page

---

__tests__/back-to-top.test.js
src/javascripts/application.js
src/javascripts/components/back-to-top.js
src/stylesheets/components/_back-to-top.scss
src/stylesheets/components/_banner.scss
src/stylesheets/components/_cookie-banner.scss
src/stylesheets/components/_footer.scss
src/stylesheets/components/_header.scss
src/stylesheets/components/_navigation.scss
src/stylesheets/components/_pane.scss
src/stylesheets/components/_subnav.scss
src/stylesheets/main.scss
views/layouts/layout-pane.njk
views/layouts/layout.njk
views/partials/_back-to-top.njk
views/partials/_banner.njk
views/partials/_cookie-banner.njk
views/partials/_footer.njk
views/partials/_header.njk
views/partials/_navigation.njk

In a previous audit we had reports of issues with the sticky and independently scrollable parts of our original design.
We also need to meet the new guidance in WCAG 2.1 which means that the design system reflows well when zoomed: https://www.w3.org/TR/WCAG21/#reflow
This change turns the design system into a static layout with a maximum width, which means there is more vertical space for reading, and reflows better without causing obstructions.
Additionally this change makes the design system less 'special' and more like the services that our users build. It also allows us to present the examples in the design system (For example, a component) at a width which is closer to how they will actually be used in a service.
We have created a new back to top component that will return you to the …

Remove fixed layout, introduce back to top component

---

src/styles/layout/index.md.njk

This change updates the description to meet our style guide which says that 'Two-thirds/One-third' should be written in sentence case instead of title case.

Update layouts styles page to meet our style guide

---

src/styles/colour/index.md.njk

Make sure that the contrast ratio of text and interactive elements in the service meets [level AA of the Web Content Accessibility Guidelines
Colour contrast needs to be updated from WCAG.2.0 to WCAG 2.1

Colour contrast needs to be updated from WCAG.2.0 to WCAG 2.1

---

src/styles/page-template/index.md.njk

Changed bullet "favicon, and other related theme icons" to start with "the" so that the sentence is clearer.

Made bullet clearer

---

src/styles/layout/index.md.njk

Remove reference to "modifier" in under Understanding the grid system, as it is not following the BEM syntax

Remove reference to modifier for width

---

src/patterns/page-not-found-pages/index.md.njk

'Humorous' is how the Guardian style guide recommends spelling it, and GDS defers to this when there's no guidance in our style guide.

Corrected spelling of 'humourous' to 'humorous'

---

src/components/phase-banner/index.md.njk

"Service Manual" changes to "GOV.UK Service Manual".

Fix reference to service manual in phase banner

---

src/components/summary-list/index.md.njk

CHANGE:
You can use it to display metadata like ‘Last updated’ with a date like ‘22 June 2018’. Or to summarise a user’s responses at the end of a form like the [check answers](/patterns/check-answers) pattern.
TO:
You can use it to display metadata like ‘Last updated’ with a date like ‘22 June 2018’, or to summarise a user’s responses at the end of a form like the [check answers](/patterns/check-answers) pattern.
REASON:
Incorrect grammar.

Fix grammar error in when to use this component

---

src/components/phase-banner/index.md.njk

A user researcher got in touch with GDS to ask how to get the feedback banner at the top of their page within their service. This additional alias should help users find this component in the future.

Add "feedback banner" to aliases for phase banner

---

src/javascripts/components/copy.js
src/stylesheets/components/_tabs.scss
src/stylesheets/main.scss

This PR adds extra space to the top of the code block to stop the copy button clashing with the code referenced in https://github.com/alphagov/govuk-design-system/issues/704
In addition I have changed the content of the button to "Copy code" and "Code copied" to add some context to the button to help with the feedback below. I have also changed the text to sentence case and adjusted the padding accordingly.
> The ‘copy’ link is not descriptive to users that rely on audio feedback and navigate out of
> the context of the page.
This does not add the context of the particular code block the user is copying but is a good start.

Update copy button content and position

---

src/javascripts/components/tabs.js

As the functionality was removed in #670 this function is no longer used and can be removed

Remove redundant clickCloseContainer function

---

src/components/checkboxes/index.md.njk
src/components/radios/index.md.njk

As part of the Dropbox Paper migration work, this PR:
- adds guidance explaining that you should order checkboxes alphabetically by default, and from most-to-least common if applicable
- makes a small change to shorten a sentence length in the radios guidance
More information about this work can be found in the [checkboxes issue in the community backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/37#issuecomment-460603249)

Update radios and checkboxes guidance on ordering options

---

src/community/index.md.njk

Add community principles to the landing page of the Community section.
These principles were co-created with 35 members of our community of users and contributors.

Add community principles

---

src/components/date-input/date-of-birth/index.njk
src/components/date-input/default/index.njk
src/components/date-input/error/index.njk
src/components/date-input/index.md.njk
src/components/error-message/default/index.njk
src/components/error-summary/default/index.njk
src/components/error-summary/linking-multiple-fields/index.njk
src/components/text-input/index.md.njk
src/components/text-input/input-autocomplete-attribute/index.njk
src/patterns/addresses/index.md.njk
src/patterns/addresses/textarea/index.njk
src/patterns/dates/default/index.njk
src/patterns/dates/error/index.njk
src/patterns/dates/index.md.njk
src/patterns/dates/memorable-date/index.njk
src/patterns/email-addresses/default/index.njk
src/patterns/email-addresses/error/index.njk
src/patterns/email-addresses/index.md.njk
src/patterns/names/default/index.njk
src/patterns/names/error/index.njk
src/patterns/names/index.md.njk
src/patterns/telephone-numbers/default/index.njk
src/patterns/telephone-numbers/error-empty-field/index.njk
src/patterns/telephone-numbers/index.md.njk
src/patterns/telephone-numbers/international/index.njk

We now allow textarea, input and date input components to accept an option to render `autocomplete` attribute. 
This helps to surface the new WCAG 2.1 guidelines for "Identify Input Purpose" - see https://github.com/alphagov/govuk-design-system/issues/696
This PR:
- Adds guidance and examples of using `autocomplete` for the above components.
- Changes the default examples for date-input, error-message and error-summary to use a different question (not date of birth) for their default example. This is to avoid adding `autocomplete` attributes to default examples as these could be copy pasted for use in other contexts than date of birth.
- Is doing the minimum to add guidance for the components that now explicitly accept `autocomplete`. There are probably other examples in the Design System …

Add examples and guidance for `autocomplete` attribute 

---

src/community/index.md.njk

This pull request adds a missing word to the community principles section. Thanks @rpowis for the spot!

Fix typo in community principles

---

src/components/text-input/index.md.njk
src/stylesheets/components/_tabs.scss
views/partials/_example.njk

This PR adds the option to remove the rendered example from the example / codeblock.
This means we can present both HTML / Nunjucks tabs when we want to talk specifically about the HTML / Nunjucks (e.g. attributes) and a rendered example would have no purpose.

Example component update

---

src/patterns/confirmation-pages/index.md.njk

Adds this research gathered from Dropbox paper audit
**Known gaps**
Research is needed on the best way to confirm transactions that are part of a wider user task. For example, where you might need to emphasise next steps more than completion of that particular transaction.

Add research to confirmation page from dropbox paper

---

package-lock.json
src/components/checkboxes/conditional-reveal/index.njk
src/components/radios/conditional-reveal/index.njk
src/components/text-input/default/index.njk
src/components/text-input/error/index.njk
src/components/text-input/index.md.njk
src/components/text-input/input-hint-text/index.njk
src/components/text-input/input-spellcheck-disabled/index.njk
src/patterns/email-addresses/default/index.njk
src/patterns/email-addresses/error/index.njk
src/patterns/email-addresses/index.md.njk
src/patterns/names/default/index.njk
src/patterns/names/error/index.njk
src/patterns/names/index.md.njk
src/patterns/national-insurance-numbers/default/index.njk
src/patterns/national-insurance-numbers/error/index.njk
src/patterns/national-insurance-numbers/index.md.njk

Add examples and guidance on disabling spell check for form inputs such as email addresses and reference numbers.
As discussed in https://github.com/alphagov/govuk-frontend/issues/1129#issuecomment-455584260, Safari can correct user input without user approval and Chrome on Android can offer "corrections" even when user types in their email address. Spell checking is also unnecessary and potentially confusing when collecting user input like reference numbers.
Fixes https://github.com/alphagov/govuk-frontend/issues/1129
We could also consider changing the text input component in GOV.UK Frontend so that when `type="email"`, `spellcheck="false"` is added.

Add guidance and examples for `spellcheck="false"`

---

src/stylesheets/components/_site-search.scss

When the page first loads the GOV.UK banner is 33px high. 
When Javascript kicks in and search field is rendered it takes up 1px more space than is available, causing the GOV.UK banner to increase in height to accommodate the search.
This causes a 1px jump of the whole page on every page load, because the header pushes down all content below it:
This commit adds some negative margin to the search field to make it take up less space, meaning the GOV.UK banner doesn’t need to grow to accommodate it.
***
I haven’t tested this fix locally, and maybe negative margin isn’t the best way of achieving this, but I figured a PR is more useful than an issue…

Make GOV.UK banner same height with/without search

---

src/patterns/confirm-an-email-address/index.md.njk

Removes a duplicated word that was reported by a member of the community.

Remove duplicated word

---

src/components/text-input/input-fluid-width/index.njk
src/styles/spacing/input-width/index.njk

As reported by @edwardhorsford in https://github.com/alphagov/govuk-design-system/issues/804, the labels having width override classes as well as the inputs could be misleading outside of the context of the examples.
This PR removes the override classes from the labels on the Styles > Spacing page and the Text input page.

Remove label width overrides on Spacing and Text Input page

---

src/styles/page-template/index.md.njk

Clarify what the main block overrides so that it also includes 'content' and 'beforeContent' block, which aims to resolve some of the confusion around how the diagram relates to this block.
Fixes #802

Clarify wording for the main block in the page template

---

src/components/text-input/index.md.njk

placeholders disappear on typing, not click

update placeholder guidance

---

src/patterns/names/index.md.njk

"Full legal name" doesn’t seem to have a clear and unambiguous meaning (for instance it implies that everyone has a single legal name, when they may use both a married and maiden name in different contexts).  Instead it may be better to refer to a name matching that used on government issued documents such as passports and driving licences.
It is also possibly to have an additional name noted on a passport in the observations page.
See:
* [Change your name by deed poll](https://www.gov.uk/change-name-deed-poll)
* [Recording Changes of Forename(s) and Surname(s) in Scotland
](https://www.nrscotland.gov.uk/registration/recording-change-of-forename-and-surname-in-scotland)
* [Annex A: use of names in passports](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachm …

Clarify what is meant by 'full legal name'

---

__tests__/accessiblity_audit.test.js
__tests__/back-to-top.test.js
__tests__/component-options.test.js
__tests__/example.test.js
__tests__/mobile-navigation.test.js
__tests__/search.test.js
__tests__/tabs.test.js
lib/jest-utilities.js

This refactor tests to that they all have the same setup
so that we can't accidentally ommit the logic that ensure the analytics are not run.

Avoid tests from running Google Tag Manager analytics code

---

src/community/index.md.njk
src/get-started/index.md.njk

We need to include a (mobile only) sub nav on these pages so that if JS has failed on a mobile device the user can still access the pages in the section (as the main menu will not be usable for accessing sub pages)

Show sub nav on community and get started pages

---

src/get-started/extending-and-modifying-components/index.md.njk

On `Avoid overwriting GOV.UK Design System code` the automated conversion generates a `-` between GOV and UK which is missing from a reference

Fix broken link

---

views/partials/_in-page-subnav.njk
views/partials/_navigation.njk

Ensure navigation shows correct active state

---

src/styles/layout/common-two-thirds-one-third/index.njk

Looks like this came in by mistake in #784:
https://github.com/alphagov/govuk-design-system/pull/784/files#diff-7883ebc5245f0aeaea5ee02bb00d6d56L23

Fix mismatched <h2> </h3> in layout example

---

src/patterns/passwords/index.md.njk

The old link redirected to the new NCSC home page, so I've updated the link to point to the new home for password research. Many thanks to @joelgsamuel for the tip off.

Update link to NCSC password research

---

src/stylesheets/main.scss

This PR adds some contextual spacing adjustments to the heading when they immediately follow a `<pre>` element.
This was raised by @fofr more generally (https://github.com/alphagov/govuk-design-system/issues/838) but until we have a better idea on how we handle the spacing of non-text content within large blocks of text I have only updated the design system itself.
**Before**
**After**
**After (switching to an H2)**

Add contextual adjustment for headings after pre elements

---

src/patterns/dates/memorable-date/index.njk

Input size on the "year" for memorable dates is 2 characters, should be 4

Dates pattern: Fix input size on year

---

src/components/button/index.md.njk
src/components/button/secondary-combo/index.njk
src/components/button/secondary/index.njk
src/components/button/warning/index.njk

This pull request makes the following additions to the button component page:
- examples and guidance for [new button styles](https://github.com/alphagov/govuk-frontend/pull/1207)—secondary buttons, warning buttons
- a default button example and guidance 
👉 https://deploy-preview-865--govuk-design-system-preview.netlify.com/components/button/

Add guidance for secondary and warning buttons

---

src/patterns/check-a-service-is-suitable/index.md.njk

We had a discussion about this example and are not confident that it is useful so instead of resolving the issue short term we want to remove it and raise an issue to investigate it to give us more time.

Temporarily remove link to broken example

---

src/patterns/dates/default/index.njk
src/patterns/dates/error/index.njk
src/patterns/dates/index.md.njk

Day and month fields should accept input with and without leading zeros
The example month number should illustrate a leading zero isn't mandatory i.e in the range 1 to 9.
The example day number should illustrate it's day before month rather then month before day i.e. in the range 13 to 31
Squashed version of the original work here: https://github.com/alphagov/govuk-design-system/pull/858

Clarified leading zero on date

---

src/get-started/updating-your-code/index.md.njk

This PR updates the ["Updating from GOV.UK Elements and Frontend Toolkit" page](https://deploy-preview-883--govuk-design-system-preview.netlify.com/get-started/updating-your-code/) to:
- Update extend example in Shims section to reference a placeholder selector
- ~~Remove Internet Explorer section (as the mixins were removed in #631)~~ Update Internet Explorer section to expose current mixin (`govuk-if-ie8`)
Update: it seems like this is fixing #875

Update "Updating your code" page

---

lib/colours.js
package-lock.json
package.json
src/styles/layout/layout-wrappers-annotate.scss
src/styles/page-template/block-areas/block-areas-annotate.scss
src/stylesheets/components/_example.scss
src/stylesheets/components/_mobile-navigation.scss
src/stylesheets/components/_site-search.scss
src/stylesheets/components/_subnav.scss
src/stylesheets/components/_tabs.scss
src/stylesheets/main.scss

Changes:
- Updates the design systems v3 branch to use govuk-frontend pre-release.
- Minor fixes to get the service up and running
Issues:
- a11y tests likely to break because of the contrast difference as a result of the colour palette changes

Update Design System to use Pre-release

---

src/components/error-summary/full-page-example/index.njk
src/components/error-summary/index.md.njk

Add full page example to error summary component to help users understand where it should be positioned and what size column it should be in.
Relates to issues:
https://github.com/alphagov/govuk-design-system/issues/851
https://github.com/alphagov/govuk-design-system/issues/860
This example has placeholder content. @amyhupe can we talk about how we might include "component context" in the content pattern as it feels like we might need to do this more often.
For other observers, this is currently low priority. No need to look at it w/c 13/05/19.

Add full page example to error summary component

---

src/styles/page-template/index.md.njk

The block is put just before the closing body tag:
https://github.com/alphagov/govuk-frontend/blob/b52474c4c1c98c9886b48caafa3746bf7782859d/package/template.njk#L58
Previous text was ambiguous.

Fix help text for bodyEnd block

---

src/patterns/check-answers/default/index.njk

In #912 we updated a key from 'contact information' to 'address' but did not update the visually hidden text at the same time.

Update visually hidden text in check your answers

---

src/community/develop-a-component-or-pattern/index.md.njk
src/get-in-touch.njk
src/index.njk
views/partials/_contact-panel.njk

Updates the existing Slack links to use Slack's 'deep link' redirect. These will try to open the channel in the user's Slack app if it's installed, whilst providing links to download the app and to open in browser to help users if it's not.
This allows us to remove the 'open in app' links which were flagged as part of a recent audit as it does not make sense out of context.
> “As I navigated out of context, I discovered a link which read to me as “Open in app.” It was not immediately clear to me while situated out of context which app the link related to as this was not obvious within the link text. Although I could establish the purpose of the link in context in a testing environment some users might not be aware of which app is intended to open. Including the app name within the link …

Improve links to Slack channels

---

views/partials/_back-to-top.njk

This was flagged in a recent accessibility audit:
> An ‘svg’ image has been used to present the ‘back to top’ arrow which is currently receiving focus for keyboard only users in Internet Explorer. When selected this took the user to the top of the page. This is a known bug in Internet Explorer, and can be overcome using focusable="false" on the SVG.
I’ve also added `role=“presentation”` as the link includes the text ‘Back to top’ and the arrow is just an additional affordance. This is consistent with what we do with the crown in the header.
Closes #900

Prevent back to top arrow SVG from being focusable

---

src/patterns/addresses/index.md.njk

This pull request suggests the following changes to PR #893 
- move guidance into How address lookups work section
- add anchor link to guidance from How multiple text inputs section
- change heading to match corresponding guidance on the telephone numbers pattern
- collapses list into sentence to be consistent with corresponding guidance on the telephone numbers pattern
- rearranged order of content to lead with rationale

Suggested update to PR #893

---

lib/metalsmith-title-checker.js
src/components/character-count/error/index.njk
src/components/character-count/label-page-heading/index.njk
src/components/character-count/threshold/index.njk
src/components/character-count/word-count/index.njk
src/components/error-summary/full-page-example/index.njk
src/components/file-upload/error/index.njk
src/components/summary-list/without-actions/index.njk
src/components/summary-list/without-borders/index.njk
src/components/table/column-widths-custom-classes/index.njk
src/components/table/column-widths/index.njk
src/get-started/labels-legends-headings/label-h1/index.njk
src/get-started/labels-legends-headings/label-m-s/index.njk
src/get-started/labels-legends-headings/legend-h1/index.njk
src/get-started/labels-legends-headings/legend-m-s/index.njk
src/patterns/dates/error/index.njk
src/patterns/problem-with-the-service-pages/link-to-another-service/index.njk
src/patterns/question-pages/date-of-birth/index.njk
src/patterns/service-unavailable-pages/link-to-another-service/index.njk
src/styles/layout/common-two-thirds-one-third/index.njk
src/styles/layout/common-two-thirds-two-thirds-one-third/index.njk
src/styles/layout/common-two-thirds/index.njk
src/styles/typography/captions-inside/index.njk

By making sure our titles are unique we ensure the examples can be navigated to independently.
I've also added a check to the title checker that ensures duplicate titles fail our builds which should hopefully avoid this in the future.
Through doing this I've noticed our titles are really inconsistent in formatting, and in some cases are not very well done, this could make it harder to understand what an example is about.
I have made the minimum changes to ensure the titles are unique but I think we should raise another issue to review the titles from a style perspective and improve them, but I think how / if we do that is up to @amyhupe and @m-green...
Fixes #901

Fix duplicate iframe titles

---

src/stylesheets/components/_back-to-top.scss
views/partials/_back-to-top.njk

Make sure you can tab to the back to top link even when it's invisible, this is consistent with how the skip link works.
Closes #899

Make back to top link focusable

---

views/partials/_mobile-navigation.njk
views/partials/_navigation.njk
views/partials/_subnav.njk

The links in the navigation currently omit the trailing slash. For example, the 'Components' link links to `/components`.
If you try to visit this URL you get a 301 to `/components/`.
By adding the trailing slashes to the links in the navigation, we save a round trip to the server to get the 301 response.
Fixes #816

Avoid unnecessary 301 redirects

---

src/styles/colour/index.md.njk

This link was broken when we namespaced GOV.UK Frontend as part of the currently unreleased 3.0.
Fixes #934

Fix broken link to organisation colours

---

src/components/radios/hint/index.njk
src/components/text-input/error/index.njk
src/components/text-input/input-hint-text/index.njk
src/errors/404.njk

This commit replaces several straight quotes with their curly
equivalents, to match the rest of the design system documentation.
Straight quotes have been retained when they have been in a technical
context, such as code comments or as string delimiters.
This follows the guidance set out by this 2015 blog post:
https://designnotes.blog.gov.uk/2015/09/16/tips-for-creating-good-typography/
For more information, see https://practicaltypography.com
This commit ignores that of Markdown for the reasons given at:
https://github.com/alphagov/govuk-design-system/pull/952#issuecomment-509230660
cf. #952

Replace straight quotes in curly quotes

---

bin/deploy-travis
bin/smoke-test
deploy/nginx.conf
src/__canary__.html

This creates a new HTML page which will be built and deployed to `/__canary__/index.html` containing nothing but the words ‘Tweet tweet’ (following [the pattern set by GOV.UK][1])
It adds a smoke-test script which verifies the existence and content of that file, returning an error exit code if is not present.
Finally, it tells the Blue/Green deploy script that we use to use that smoke test, which means if e.g. nginx fails to start the deploy will not continue, and the existing container and route will be maintained.
This should hopefully give us more confidence when rolling out changes to the CloudFoundry / nginx configuration.
[1]: https://www.gov.uk/__canary__

Add smoke tests for CloudFoundry deploys

---

manifest.yml

When the blue green deploy plugin runs, it’s picking `design-system.service.gov.uk` as the first route and using that to generate the fully qualified domain name used for smoke tests.
This means that smoke tests are running against `govuk-design-system-origin-new.design-system.service.gov.uk` which is not valid.
Specifying the routes in the manifest (and, importantly, putting the `cloudapps.digital` domain first) should fix this.
This behaviour was not seen in testing as we were not testing against an instance with a cdn-route.

Add explicit routes to the manifest file

---

manifest.yml

This effectively just updates nginx from v1.15.6 to v1.17.1.
Tested by manually pushing an app to the PaaS:
Existing app:
```
$ curl -sI https://govuk-design-system-origin.cloudapps.digital/ | grep Server
Server: nginx/1.15.6
```
App with this change:
```
$ curl -sI https://design-system-buildpack-14.cloudapps.digital/ | grep Server
Server: nginx/1.17.1
```

Update nginx buildpack to v1.0.14

---

src/community/propose-a-content-change-using-github/index.md.njk

Updated to:
- make it clearer that pull requests are publicly visible on GitHub, and so can be seen by other people
- remove 'changing the information here will not change the original description, but will send it in addition' as it's not clear to the user what the difference between those two things is; why they should care or what they should do about it.
- try and remove some overlap with step 6 (the Design System team being notified of the PR)

Revise guidance on creating pull requests

---

src/styles/page-template/index.md.njk

Following what we'll advise users to do in https://github.com/alphagov/govuk-frontend/blob/master/CHANGELOG.md#if-youre-using-nunjucks they shouldn't need to load the `/components` directory as this would hide the path in their files. Instead, they would do the following:
```
{% from "govuk/components/breadcrumbs/macro.njk" import govukBreadcrumbs %}
```

Update template page Nunjucks config

---

src/javascripts/govuk-frontend.js

Implement the changes to how JS is initialised in v3 components:
- Initialise GOV.UK Frontend button and details components using `data-module`
- Initialise all instances of button since the Design System contains a page with two buttons
- Namespace `data-module` value of other GOV.UK Frontend components which use Javascript

Initialise Javascript of v3 GOV.UK Frontend components

---

src/stylesheets/components/_example.scss
src/stylesheets/components/_options.scss
src/stylesheets/components/_tabs.scss
src/stylesheets/main.scss
views/partials/_example.njk

This includes:
- the focus state of the 'open in new link' window
- the tabs interface used on desktop breakpoints
- the accordion interface used on mobile and tablet breakpoints
Closes #960 
<details>
<summary>Screenshots - Desktop</summary>
</details>
<details>
<summary>Screenshots - Desktop (custom colours)</summary>
</details>
<details>
<summary>Screenshots - Mobile</summary>
</details>

Update examples to use new design and focus states

---

src/stylesheets/components/_header.scss
src/stylesheets/components/_pane.scss
src/stylesheets/components/_site-search.scss
views/layouts/_generic.njk
views/partials/_header.njk

Updates the header to:
- use the new focus style for the menu button
- use most of the header markup and CSS from GOV.UK Frontend, with some targeted overrides where required
- align the search within the header, align the text within the search input correctly, and update its focus state
<details>
<summary>Screenshots</summary>
</details>
This covers #961 and part of the work to remove baseline adjustments from the Design System (#957)

Update the header

---

src/javascripts/components/mobile-navigation.js
src/stylesheets/components/_mobile-navigation.scss
src/stylesheets/components/_navigation.scss
src/stylesheets/components/_subnav.scss
views/partials/_mobile-navigation.njk
views/partials/_navigation.njk
views/partials/_subnav.njk

Update navigation focus styles to be inline with GOV.UK Frontend 3.0.0
This work also includes some refactoring to use BEM, which was necessary for the mobile navigation but a nice to have everywhere else.
Closes #958

Update navigation focus styles

---

package-lock.json
package.json

This updates the release to as close to what we will ship to users.

Update GOV.UK Frontend 3.0.0 pre-release

---

src/patterns/confirmation-pages/index.md.njk

As the panel colour in GOV.UK Frontend v3.0 has been updated, it now meets contrast ratio requirements at any font size.
We removed the guidance from the panel component in 22bad33, but didn’t notice it was in here as well.

Remove contrast ratio note from confirmation pages

---

src/community/backlog/index.md.njk

This has now been released as the [Ethnic groups pattern](https://design-system.service.gov.uk/patterns/ethnic-group/).

Remove 'Ethnicity' from the backlog

---

src/stylesheets/components/_navigation.scss
src/stylesheets/main.scss

- Prevent the hover state on unvisited nav links
- Reduce the height of the navigation to 50px
- Tweak the copy button to closer align it with the focus and active styles for secondary buttons

Design tweaks

---

src/accessibility.md.njk

Remove references to known issues and the upcoming GOV.UK Frontend release, as when this is published v3 will be available.
Update to provide details about the latest audit, including links to the issues raised from the audit.
Closes #840 
👉 [See preview of the revised accessibility page](https://deploy-preview-994--govuk-design-system-preview.netlify.com/accessibility/)

Update accessibility page

---

src/styles/layout/index.md.njk

Move the documentation for `govuk-main-wrapper--l` up with the documentation for `govuk-main-wrapper` rather than as part of the ‘exploded view’.
Add guidance around the `govuk-main-wrapper—auto-spacing` modifier.

Improve documentation of main-wrapper modifiers

---

src/accessibility.md.njk

This PR:
- removes future-tense references to v3 release, which has now been done
- adds information on how to get in touch with the team for help
- removes instances of "we" in line with the [Design System team style guide](https://ukgovernmentdigital.slack.com/app_redirect?channel=govuk-design-system)

Update for v3 release

---

src/stylesheets/components/_cookie-banner.scss

Since the colours changed the colour function transforms no longer result in the correct colour.
Instead of bringing back the colour by adjusting the transforms we've decided to go with white which is consistent with GOV.UK Publishing's cookie banner.
Closes https://github.com/alphagov/govuk-design-system/issues/995

Set cookie banner background to white

---

src/styles/colour/index.md.njk

Update WCAG link for contrast from WCAG 2.0 to WCAG 2.1
My linter also seem to have removed a space on save, can put it back if it was intended.

Update WCAG link for contrast

---

src/stylesheets/components/_navigation.scss

Box shadow disappears when changing colours in your browser, for example Firefox

Improve current nav when changed colours

---

src/stylesheets/components/_site-search.scss

We've had reports that the button style can be confusing when it disappears.
To try and make this interaction simpler we keep the icon at all times but allow it to be pressed to focus the input.
By doing this I re-introduced the hint text appearing, which I'm not sure if was intentionally hidden before. This seems to make changed colours interaction more confusing, so not sure if we should hide this or not.
This mirrors a similar style on GOV.UK Publishing.
| Before | After |
| ------ | ------ |
| ![](https://user-images.githubusercontent.com/2445413/62132164-72c78500-b2d4-11e9-9fba-d14750a324eb.gif) | ![](https://user-images.githubusercontent.com/2445413/62132159-722eee80-b2d4-11e9-81a1-57bc46ed9b69.gif) |
| Before | After |
| ------ | ------ |
| …

Adjust site search so that icon is always visible

---

src/stylesheets/components/_contact-panel.scss
src/stylesheets/components/_mobile-navigation.scss
src/stylesheets/components/_navigation.scss
src/stylesheets/components/_pane.scss
views/layouts/_generic.njk

This makes it easier to access the navigation for users that use screen readers as the menu button is closer to the menu itself.
Many users of screen readers also use high magnification which brings up the mobile style layout.
I've also refactored some unneeded wrapper code.
Fixes https://github.com/alphagov/govuk-design-system/issues/939

Move beta banner below mobile navigation

---

src/javascripts/components/search.js

Since the input is now always 100% width we don't need to account for this case.
Thanks to @kr8n3r for pointing this out.

Remove unneeded search focus logic

---

src/styles/spacing/index.md.njk

Based on feedback from a user on Slack:
> "Is it easy to add search terms to the design system search? I can never find the margin and padding override classes - but have learnt that ‘width’ gets me to the page I want"

Add margin and padding as aliases of spacing

---

views/partials/_example.njk

For users using assistive technologies, the link has more detail, for
other users we simplify it to just 'example' relying on the visual
location of the link giving the context without the additional detail.
Fixes https://github.com/alphagov/govuk-design-system/issues/959

Ensure open in new window link is not too verbose

---

.github/issue_template.md
.github/pull_request_template.md

Between 13-26 August, the GOV.UK Design System team is assisting with urgent and critical Brexit-related work being undertaken by GDS and will not be able to respond to support requests.

Create issue and pull request templates

---

src/components/fieldset/index.md.njk

This issue https://github.com/alphagov/govuk-design-system/issues/1022 highlights a confusion between "form group" being an alias of `<fieldset>` and the class `govuk-form-group` which wraps all form components.
I suggest we remove the alias from the search to avoid this.

Remove "form group" search alias from fieldset

---

views/partials/_example.njk

For longer pages this prevents all examples being loaded even if they're not in view.
I have tried loading the [layout page with lazy loading](https://deploy-preview-1012--govuk-design-system-preview.netlify.com/styles/layout/) and the [layout page without lazy loading](https://govuk-design-system-preview.netlify.com/styles/layout/) and recorded the results under simulated slow 3G.
| Metric | Current | With lazy loading |
| ----- | ------- | ------------ |
| HTTP Requests | 130 | 37 |
| Data Transferred | 1.3 MB | 502 KB |
| Resources used | 5.1 MB | 1.6 MB |
| Time to DOMContentLoaded | 5.58s | 5.60s |
| Time to finish | 37.22s |  17.65s |
| Time to fully load | 34.80s | 17.65s |
This is only available in Chromium browsers so far such as Chrome 76 stable, see …

Add lazy loading for examples

---

src/components/character-count/error/index.njk
src/components/character-count/index.md.njk
src/components/error-message/index.md.njk
src/components/text-input/index.md.njk
src/components/textarea/index.md.njk

Sorry in advance: this must have been discussed before.
It is inaccurate to say "less" of a number of discrete items. [Plain Words](https://en.wikipedia.org/wiki/The_Complete_Plain_Words):
> _Less_ appertains to degree, quantity or extent; _fewer_ to number. Thus, _less_ outlay, _fewer_ expenses, _less_ help, _fewer_ helpers; _less_ milk, _fewer_ eggs.
This PR changes "less" to "fewer" in that context.
EDIT: correct spelling of “innacurate”

Replace 'less' with 'fewer' for countable nouns

---

deploy/nginx.conf

Override charset_types to include text/css.
The default value for charset_types is:
```nginx
charset_types text/html text/xml text/plain text/vnd.wap.wml application/javascript application/rss+xml;
```
We don’t serve any text/vnd.wap.wml (!) so we can omit that, and we can add text/css.
This change means that CSS files are served with `charset=utf8` as part of the Content-Type header:
```
Content-Type: text/css; charset=utf-8
```
I am hoping this will fix encoding issues like those seen in #1023.
```bash
➜ curl -I https://govuk-design-system-origin.cloudapps.digital/stylesheets/main-43960fd538bd98817b7759e86cdfde51.css
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=315360000
Content-Length: 124472
Content-Type: text/css
Date: Tue, 27 Aug 2019 12:09:15 GMT
Etag: …
```

Serve CSS with explicit UTF8 charset

---

src/styles/spacing/index.md.njk

If you search for 'width' you find the guidance in Styles. This shows the generic width override classes, but we have specific guidance on that (that uses character width, not % width), so this PR adds a link. The words might not be right :)

Add link to text input width guidance

---

src/stylesheets/components/_highlight.scss
src/stylesheets/main.scss

This pull request replaces colours in the Design System code blocks, in order to meet constrast (4.5) against the background ```#f3f2f1```.
The updated colours are``` #dd1144```, ```#007f80```, ```#99998``` and ```#000080```,
they have been replaced with ```#d13118``` (4.51), ```#00703c```(5.5), ```#0b0c0c```(17.5)  and ```#003078```(11.09) respectively. These changes also update inline code snippets.
This solution creates the least amount of visual difference, whilst using most of the colours from the GOV.UK colour palette. 
Fixes #1032

Update colours in code blocks to improve contrast

---

src/styles/layout/combinations/index.njk
src/styles/layout/index.md.njk
src/styles/layout/three-quarters/index.njk

This PR adds an example of the **3/4** column and adds a **1/4** / **3/4** and **3/4** / **1/4** examples to the combinations section.
This PR fixes https://github.com/alphagov/govuk-design-system/issues/1047

Document `govuk-grid-column-three-quarters`

---

src/styles/page-template/index.md.njk

The order of items in the section "Changing template content" appears to be the order in which they appear on the pages created with template, so have followed this.
See https://github.com/alphagov/govuk-frontend/pull/1576 for the change in Frontend

Add guidance for pageTitleLang and mainLang

---

views/partials/_contact-panel.njk

I noticed that some of the proposal links were broken.
["There is a problem with the service pages"](https://https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/) page, since we were relying on the title always being the same as the path.
This pull request uses `path` instead which points to the right place, I have also done some refactoring / reformatting of this file since it was a pain to update.
Check out the commits to see the fix and then the reformatting separately.

Fix propose link

---

src/patterns/passwords/index.md.njk

Change based on NCSC guidance:
"If using account lockout, we recommend you allow between 5 and 10 login attempts before the account is frozen" (https://www.ncsc.gov.uk/collection/passwords/updating-your-approach)

Change the recommended number of max failed login attempts before locking the user out

---

__tests__/component-options.test.js
lib/metalsmith.js
src/javascripts/components/options-table.js
views/partials/_example.njk

We fixed issues with ID's not being unique which changed how the first example's ID is generated.
Now it contains the component name instead of a generic 'default' id.
This means when linking between components the macro options behaviour is currently broken.
You can see this by going to the textarea component macro options and press 'errorMessage', it will load the page but not show the macro options for the Error Message component.
Fixes https://github.com/alphagov/govuk-design-system/issues/1008
I'll need to update all the component READMEs in GOV.UK Frontend also.

Fix options table links

---

src/patterns/confirmation-pages/index.md.njk

Searches for "GDS done page" take users to this page rather than the relevant page in the Service Manual.
DIT had this problem today and couldn't find the right information.
I've also proposed that the Service Manual page is updated to include the still-used term "done page".

Adding a user journey to the feedback page guide

---

src/javascripts/application.js
src/javascripts/components/back-to-top.js
src/stylesheets/components/_back-to-top.scss
src/stylesheets/components/_contact-panel.scss
src/stylesheets/components/_subnav.scss
src/stylesheets/main.scss
views/layouts/layout-pane.njk
views/partials/_back-to-top.njk
views/partials/_contact-panel.njk
views/partials/_in-page-subnav.njk

This resolves the majority of issues raised by the recent accessibility audit relating to the back to top link, with only an investigation into NVDA's anchor link remaining.
Fixes https://github.com/alphagov/govuk-design-system/issues/899
This means that anyone using a keyboard can access the back to top link
if they're navigating to the bottom, whereas perviously the link was
just after the navigation.
Moving this forces us to have to change our approach having the back to top link follow the user.
We cannot use `position: sticky`, so have to make more use of
intersection observers and implement the desired behaviour ourself.
- mirrors the source order better
- users with motor impairments this may be easier to access as it's
closer to the bottom of the page.
- fallback for older …

Back to top link improvements

---

src/patterns/addresses/index.md.njk
src/patterns/payment-card-details/index.md.njk
src/stylesheets/main.scss

We used to have an invisible label for users of assistive technologies that explained the video was complementary and did not have any audio.
We've moved this onto the page for everyone to see based on @selfthinker 's recommendations since this will make it useful for people that are using other assistive technologies such as magnification tools.
I have used `aria-labelledby` to associate this label with the video to keep the existing behaviour.
Thanks to @amyhupe  for improving the content for the label.
I think this was one of the only thing we've forgot to add a focus style to that follows the new guidelines.
Fixes https://github.com/alphagov/govuk-design-system/issues/904

Improve video alternative text

---

views/layouts/layout-example.njk

This makes sure that any accidental personally identifiable information
is not stored in logs as using the GET method means that these are put
into the URL.
This approach is consistent with how the other examples are setup.
Fixes https://github.com/alphagov/govuk-design-system/issues/1066

Ensure all wrapper forms submit via POST

---

src/__canary__.html

We use the `/__canary__` route to check instance health when deploying before we make the new site live, but we don’t want it to be indexed and it definitely doesn’t need to be included in the sitemap (which it currently is).

Exclude the canary from the sitemap 🐤🚫

---

src/styles/page-template/custom/code.njk
src/styles/page-template/custom/index.njk
src/styles/page-template/index.md.njk

Blocked until https://github.com/alphagov/govuk-frontend/pull/1623 is released

Document how to add an attribute to template <body>

---

src/components/button/index.md.njk

Mentioning 'on a GOV.UK page' here:
> Use the button component to help users carry out an action on a GOV.UK page like starting an application or saving their information.
...seems confusing to me. It’s not clear whether that includes services using a `*.service.gov.uk` domain or not. End-users might perceive everything to be "GOV.UK" but within government it seems common to refer to GOV.UK as being the content platform only, not the services.
I think it might be clearer to drop this reference, which would also be more consistent with other component descriptions.

Remove reference to 'GOV.UK page'

---

src/javascripts/components/back-to-top.js

Entries only appear when an element that is being observed enters or leaves the viewport.
This means that we cannot rely on the subNav entry being avaliable to check it's intersectionRatio.
This change to the logic caches the ratio outside of the observer so it's always up-to-date with the last time an entry for the subNav is avaliable.
This has no impact on users that I can tell fortunately.
Fixes https://github.com/alphagov/govuk-design-system/issues/1088

Fix sticky navigation logic erroring on some pages

---

src/stylesheets/components/_site-search.scss

I was helping Amy get some screenshots of the website with colours changed and noticed some issues with the search that can be improved.
- remove background on inputs so in Firefox the input renders correctly, move the icon image to the input itself
- update the placeholder text to the same colour as the icon (should we consider doing this in GOV.UK Frontend?)
- add a transparent outline for selected items
| Before input | After input |
| - | - |
| ![](https://user-images.githubusercontent.com/2445413/69645547-3fb4b880-105e-11ea-853f-75019c6f6136.png) | ![](https://user-images.githubusercontent.com/2445413/69645569-45120300-105e-11ea-8716-4095f0a6e0da.png) |
| Before highlights | After highlights |
| - | - |
| ![](https://user-images.githubusercontent.com/2445413/69645458-1c8a0900-105e-11e …

Fix search on updated colours

---

src/about.md.njk
src/design-system-team.md.njk
src/index.njk
views/partials/_footer.njk

Add an about page with who we are, and link to it from the footer.
We want to have an official list we can point to for who is on the team.
I considered including our GitHub handles but as long as we have our real names on GitHub you can still cross reference this list.
I've added our job title roles to mirror what we do in internal weeknotes, this is to help people understand what we do on the team.
I've also added a summary of who we are, where we're based, what we're trying to do (based on our mission statement) and how to contact us.
For now I've put this page at `/about` with a title of `about` but we might want to change this.

Add about page for the team

---

src/index.njk
src/styles/page-template/custom/code.njk
src/styles/page-template/custom/index.njk
src/stylesheets/main.scss
views/layouts/layout-pane.njk
views/layouts/layout-single-page.njk
views/partials/_banner.njk
views/partials/_cookie-banner.njk
views/partials/_footer.njk
views/partials/_header.njk
views/partials/_masthead.njk
views/partials/_navigation.njk

By introducing an application specific width container we make sure the examples within the Design System are the default width.
This commit also tidies up some unused class names.
Fixes https://github.com/alphagov/govuk-design-system/issues/798

Fix examples width being too wide

---

manifest.yml

Since we create new applications when we deploy using blue/green deployment, we need to specifiy the service that sends logs so it's applied on deployment.

Add logit-ssl-drain service to PaaS manifest

---

src/design-system-team.md.njk

Amy left GDS on 19 December so removing her from the team page.

Remove Amy

---

src/styles/page-template/index.md.njk

This adds a minor bit of clarification to the description of the `assetUrl` variable in Page template, as suggested by a 2ier.

Amend assetURL description with 2i fix

---

src/patterns/start-pages/default/related-items.scss

Update borders to match current start page design

---

views/partials/_toc-styles.njk

This file was introduced in 88269ad but has not been used since 402c5c4. When _toc-components.njk and _toc-patterns.njk were removed, this should have been removed as well.

Discard unused partial

---

src/patterns/addresses/error/index.njk
src/patterns/addresses/multiple/index.njk

I have avoided adding an autocomplete for county as the specification talks about 'post towns', and county is an optional field.
> The broadest administrative level in the address, i.e. the province within which the locality is found; for example, in the US, this would be the state; in Switzerland it would be the canton; in the UK, the post town.
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-address-level1
This is based on research done by the community:
https://github.com/alphagov/govuk-design-system/issues/1090#issuecomment-557045858
I'm not sure if there's any content changes to support this, for example we talk about these values here and there might be some tweaks needed: 
https://design-system.service.gov.uk/patterns/addresses/#use-the-a …

Add autocomplete values for address fields

---

manifest.yml

This effectively just updates nginx from v1.17.5 to v1.17.7.
Tested by manually pushing an app to the PaaS.

Update nginx buildpack to v1.1.3

---

src/styles/page-template/block-areas/index.njk
src/stylesheets/components/_example.scss
src/stylesheets/main.scss
views/layouts/layout-example-full-page.njk
views/partials/_example.njk

Update the 'Open in new window' link so that it sits within its own 'toolbar', rather than overlapping the example.
This allows us to remove the padding from full-page examples without the open in new window link overlapping the header, and simplifies things like the focus state.
It also updates the 'canvas' behind the example (seen only when resizing the example) to a 'checkerboard' design.

Update 'Open in new window' design

---

src/javascripts/example.js

I'm unclear how this wasn't picked up by CI in #1116 but we removed the `app-example-page` class from full page examples, which this Javascript relies on to prevent form submissions within examples.
As this is only included in full page examples, we can just initialise on the whole document.

Fix example form submission prevention

---

src/patterns/contact-a-department-or-service-team/all-contact-information/index.njk

Update the address in the pattern to use a simpler paragraph rather than an nested list.
Thanks to [@adamliptrot-oc](https://github.com/adamliptrot-oc) for proposing this change.
Also update the Twitter credentials as a list with one item is not necessary.
Closes https://github.com/alphagov/govuk-design-system/issues/1104

Simplify contact a department or service team pattern markup

---

src/__canary__.html
src/patterns/step-by-step-navigation/index.md.njk
src/styles/page-template/block-areas/index.njk
src/styles/page-template/custom/code.njk
src/styles/page-template/custom/index.njk
src/styles/page-template/default/code.njk
src/styles/page-template/default/index.njk

We're currently inconsistent as to whether we self-close void elements or not.
The self-closing / has no effect on the start tags of void elements in HTML5.[1]
For this reason, we should standardise on omitting them.
[1]: https://html.spec.whatwg.org/dev/syntax.html#start-tags

Don't unneccesarily self-close tags

---

src/styles/typography/index.md.njk

This has come up a number of times since the design system was launched, it would be good to clarify that using a different size heading class is ok and is down to the designer.
This is very much a draft and isn't nesassarily the solution, just wanted to get it in before I remove my GitHub credentials and do one more PR :)

Add guidance about different heading size usage

---

src/stylesheets/components/_navigation.scss

We're using app-width-container on a `<ul>` here, which isn't something we generally expect people to do.
We were relying on the top and bottom margins being reset by app-width-container - since v3.5.0 this doesn't happen so the space above the navigation is now bigger.
Adding an explicit top and bottom margin to the app-navigation__list class fixes this.

Fix navigation top and bottom margins

---

src/community/how-you-can-contribute.md.njk
src/cookies.md.njk
views/layouts/layout-redirect.njk

Simpler approach to solve: https://github.com/alphagov/govuk-design-system/pull/1135
We decided against:
- updating the nginx configuration as we're worried it could break the live site and don't have a staging environment
- using meta refresh or JavaScript to automatically redirect the page as we're not sure the impact it could have on people using assistive technologies.
Content tries to mirror the [Page not found pattern](https://design-system.service.gov.uk/patterns/page-not-found-pages/)
Closes https://github.com/alphagov/govuk-design-system/pull/1135
Closes https://github.com/alphagov/govuk-design-system/issues/536

Add pages to redirect users from removed pages

---

src/components/text-input/index.md.njk
src/components/text-input/number-input/index.njk
src/patterns/bank-details/default/index.njk
src/patterns/bank-details/error/index.njk

This PR:
- Adds guidance on asking users for numbers
- Adds a code example
- Updates the bank details pattern to use the [new number input API](https://github.com/alphagov/govuk-frontend/pull/1527)
Fixes https://github.com/alphagov/govuk-design-system/issues/1128

Add guidance on how to ask users for numbers

---

src/get-started/index.md.njk

Adds information the help users understand:
- the difference between published styles, components and patterns vs ideas in GitHub discussions
- that GitHub discussions are open - so the views expressed aren't "official" in any sense
Closes https://github.com/alphagov/design-system-team-internal/issues/211

Add information on using the design system

---

src/styles/typography/index.md.njk

Part of the work on [link styles](https://github.com/alphagov/govuk-design-system/issues/1159).
We’ve never really acknowledged that we have non-underlined links all over GOV.UK, or given people a rationale for when to do that. We think that by formalising and publishing this rationale, we will see clearer and more consistent use of link styles on GOV.UK and elsewhere.
I spoke with designers on GOV.UK and the GDS graphic design community to get their opinions and summarised the discussions.
Underline:
- By default.
- Inline links that are part of a block of text. For example, within paragraphs or when part of a list.
- Links on their own. For example, back buttons.
- Breadcrumbs (does this contradict the point about being obviously navigational?)
Do not underline:
- Links that are part of …

Add guidance on when to remove link underlines

---

views/partials/_contact-panel.njk

Remove full stop on email line of contact panel

---

src/components/tag/all-colours/index.njk
src/components/tag/coloured-tags/index.njk
src/components/tag/index.md.njk
src/components/tag/multiple-tags/index.njk

First stab at guidance for the additional Tag colours as explained here:
https://github.com/alphagov/govuk-frontend/pull/1711

Guidance for the additional colours for the Tag component

---

docs/deployment/production.md

We don't want to replicate PaaS's documentation on signing in and deploying apps so would expect team members to consult PaaS docs to do those things. Useful to have a link to it here. 
Also made the naming a bit clearer since "Platform as a Service" is a computing concept by itself so wanted to clarify that we're talking about the GOV.UK service.

Update deployment docs

---

src/styles/page-template/custom/index.njk

The footer is missing the app-width-container container class which means the footer is using a different width to the rest of the page.
Add the missing container class, which means it now displays correctly.

Fix footer width on custom page example

---

src/get-in-touch.njk
views/partials/_contact-panel.njk

We're seeing an increased number of members of the public use the Design System support email address for enquiries about other government services like universal credit.
We think that this is because they are searching for e.g. 'government email address' or 'government phone number' and finding our patterns relating to asking for email addresses or asking for phone numbers.
Remove the email address from the bottom of every page, instead routing users to the existing 'get in touch' page.
Add warning text to the 'get in touch' page that explains the purpose of the support email address, and direct users to the GOV.UK contact form for other enquiries.
This is based on wording used by Notify, who have implemented something similar. (https://www.notifications.service.gov.uk/support/public)

Route to get in touch page, add notice for public

---

src/index.njk
src/patterns/understand-the-impact-of-an-emergency/index.md.njk

The accent colour of the GOV.UK global coronavirus banner has changed (and may change again). This PR updates the GOV.UK Design System to reflect that.

Update references to global banner colour

---

src/privacy-policy.md.njk

We have [dropped IP addresses from our logs entirely](https://github.com/alphagov/govuk-design-system/pull/1158) so we can update the privacy policy to reflect this
Closes https://github.com/alphagov/design-system-team-internal/issues/269

Remove IP addresses in logs from data collected

---

src/get-started/production/index.md.njk
src/styles/page-template/custom/code.njk
src/styles/page-template/default/code.njk
src/styles/page-template/index.md.njk

This updates relevant links in the Design System so that they point to the Tech Docs Template domain rather than the Frontend docs repo.

Change Frontend docs links to TDT

---

src/get-started/updating-your-code/index.md.njk

When we publish the migration guidance, this PS updates the 'Updating from GOV.UK Elements and Frontend Toolkit' page to:
- change the title to better reflect the content, and so it doesn't 'compete' with the main migration guidance
- add a link to the main migration guidance
- remove anything that's better covered in the main migration guide
Do not merge until:

Update 'updating from old frameworks' guidance to work with new migration guide

---

src/components/checkboxes/index.md.njk
src/components/radios/index.md.njk

This is consistent with the active voice used in the following sentences, and makes it explicitly instructional rather than making it sound like this is automatic behaviour that checkboxes and radios provide.

Use active voice for guidance on grouping controls

---

src/components/radios/index.md.njk

This PR clarifies some of the error messages on the radio button component page.
Should probably be reviewed by @christopherthomasdesign

Clarify radio error message examples

---

src/components/date-input/index.md.njk

This updates the example under 'If the date entered can’t be correct' in [Date input](https://design-system.service.gov.uk/components/date-input/), so that it works in a wider range of contexts, and better matches other examples on the page.

Update 'not a real date' example

---

src/components/table/column-widths-custom-classes/index.njk
src/components/table/column-widths/index.njk

Spotted that two of the examples had missing pound signs, I added them in.

Make table examples consistent

---

src/patterns/understand-the-impact-of-an-emergency/index.md.njk

This change is being made based on feedback from the working group, and is consistent with how we use 'For example' elsewhere in the Design System.
Closes #1242

Use 'For example:' not 'For example -'

---

src/patterns/passwords/index.md.njk

> It's fairly common to say whitelisting and blacklisting to describe desirable and undesirable things in cyber security. For instance, when talking about which applications you will allow or deny on your corporate network; or deciding which bad passwords you want your users not to be able to use.
> 
> However, there's an issue with the terminology. It only makes sense if you equate white with 'good, permitted, safe' and black with 'bad, dangerous, forbidden'. There are some obvious problems with this.
>
> – https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white
Closes #736

Avoid exclusionary language in Passwords pattern

---

src/get-started/production/index.md.njk

This adds link from the [Get started > Production](https://design-system.service.gov.uk/get-started/production/#option-1-install-using-npm) page to the importing docs in Frontend, as we've had feedback that users on this page could not find how to selectively include CSS and JavaScript for individual components.

Add links to importing docs

---

views/partials/_header.njk

The markup for the header was changed in https://github.com/alphagov/govuk-frontend/pull/1724:
> role="none"/"presentational" does not do enough to hide the child fallback image used in older browsers.
>
> We have found that Chrome's new "Get image descriptions from Google" feature will notice this fallback image.
>
> This means when screenreaders such as NVDA visit the logo, it'll announce "Unlabelled graphic, To get missing image descriptions, open the context menu." for this fallback image.
>
> By using aria-hidden="true" we can ensure that the SVG and it's children are all hidden from the accessibility tree, which I have confirmed in NVDA + Chrome.
This change went out as part of GOV.UK Frontend v3.6.0. It was missed when updating the Design System to use v3.6.0 in #1187 (it's a …

Update header to use latest markup

---

views/partials/_contact-panel.njk

We try to interpolate the current page title within the 'Help improve this page' section to make it clear what we're asking for, but it doesn't always work – especially with patterns:
> To help make sure the There is a problem with the service pages page is useful, relevant and up to date, you can:
>
> - share research or feedback about the There is a problem with the service pages pattern on GitHub
> - propose a change to this page – read more about how to propose changes in GitHub
Simplify it to be more generic – where there is a linked backlog it will now say:
> To help make sure that this page is useful, relevant and up to date, you can:
>
> - share your research or feedback on GitHub
> - propose a change – read more about how to propose changes in GitHub
Where there is no associated …

Simplify 'Help improve this page' section

---

src/get-started/labels-legends-headings/label-h1/index.njk
src/get-started/labels-legends-headings/legend-h1/index.njk

This is to fix an error made in #1201 
The [Making labels and legends headings](https://design-system.service.gov.uk/get-started/labels-legends-headings/) page is currently showing duplicated examples:
I've removed the second example in each:
Before #1201, the examples included both a `l` and `xl` size. However, I think since we're changing our default heading size to `l` now, I think showing the `xl` example here again could be confusing and inconsistent with our other guidance. Happy to add back in if others feel strongly about keeping it though.

Fix duplicated examples on label and legend headings page

---

manifest.yml

This effectively just updates nginx from v1.17.7 to v1.17.10.
Tested by manually pushing an app to the PaaS.

Update nginx buildpack to v1.1.9

---

manifest.yml

The build is currently failing with:
> Could not push new version - Error reading manifest file:
> The following manifest fields cannot be used with legacy push: buildpacks
This reverts commit a7b6920f1d4dba2560d856d61eb6f4c57785cca7.

Revert "Use 'buildpacks' instead of deprecated 'buildpack'"

---

src/components/breadcrumbs/default/index.njk
src/components/breadcrumbs/index.md.njk

Remove guidance about adding the current page title (and update examples), to be consistent with how breadcrumbs work on GOV.UK pages.
Fixes #1228

Remove current page from breadcrumbs

---

src/styles/typography/index.md.njk
src/styles/typography/list-spaced/index.njk

This PR adds guidance for and an example of the new `govuk-list--spaced` modifier class.
Fixes: https://github.com/alphagov/govuk-frontend/issues/1272
[Preview the new guidance here](https://deploy-preview-1209--govuk-design-system-preview.netlify.com/styles/typography/#spaced-lists)

Add list spacing

---

src/patterns/dates/index.md.njk

There is more than one way to ask for a date, and that using a date input is only one of the possible approaches, so position the date input example closer to the use case to make this clearer.
This also helps to differentiate the 'asking for dates' pattern from the date input component.

Move date pattern example further down the page

---

src/components/error-message/index.md.njk

Remove a broken link to error messages in the 'asking for dates' pattern – the guidance on error messages in this pattern was removed in 651ac78 as it duplicated the guidance in the date input component.

Remove link to 'dates' error messages

---

src/components/text-input/decimal-input/index.njk
src/components/text-input/index.md.njk

When asking for numbers with decimal places, it's important to use `inputtype="decimal"` as `inputtype="number"` may trigger a keyboard that does not include a period key.
The `pattern` attribute is not required for numbers with decimals – it's used to trigger the numeric keypad on iOS < 12.2, but as far as we can tell there's no equivalent to trigger the keyboard for decimal numbers. On these devices it'll fall back to displaying the full alphanumeric keypad.
Closes #1212

Add guidance on asking for numbers with decimals

---

src/components/radios/hint/index.njk
src/patterns/ethnic-group/default/index.njk
src/patterns/ethnic-group/error/index.njk

Removing the `govuk-label--s` class on labels on radios with hint text, to make them consistent with how we use hint text elsewhere. For example:
Closes #1150, relates to https://github.com/alphagov/govuk-design-system/issues/1222

Remove bold labels on radio examples with hint text

---

src/components/text-input/default/index.njk
src/components/text-input/error/index.njk
src/components/text-input/input-hint-text/index.njk
src/components/text-input/number-input/index.njk
src/components/textarea/default/index.njk
src/components/textarea/error/index.njk
src/components/textarea/specifying-rows/index.njk

Default to labels/legends as headings in component examples. As a principle, we should make examples follow our 'one thing per page' guidance unless there's good reason not to. This PR should close #1021 and relates to https://github.com/alphagov/govuk-design-system/issues/1222
This covers just text input and textarea as far as I'm aware:
Still have a couple of questions at this point:
1. Do we need to update any of the guidance on these page? In particular the lines `If you’re asking just one question per page as recommended, you can set the contents of the <label> as the page heading.` which feels a bit off if the component is set to that as standard. Might just be a subtle change of wording needed.
2. Am I right about it just being these two components? What about file upload?
3. …

Default to labels or legends as headings in component examples

---

src/community/resources/index.md.njk

Following on from the conversation in alphagov/govuk-design-system#1293 this PR contains some tweaks to the Ruby section of the Community Resources page, namely:
* update the URL for `govuk-frontend-rails` so it points at the newer, maintained project. Also make its description more accurate
* add the word 'complete' to the DfE Boilerplate project description to indicate that it contains an _entire_ template app and not a generator/engine etc
* rename the section from 'Ruby' to 'Ruby on Rails' as all the linked projects are Rails-specific

Reword Ruby resources section and fix govuk-frontend-rails project URL

---

src/components/text-input/index.md.njk
src/patterns/bank-details/index.md.njk

We include the `pattern` attribute on the [text input component for numbers](https://design-system.service.gov.uk/components/text-input/#numbers). This PR is a very rough attempt at drafting some guidance to explain that this requires [turning off HTML5 validation](https://design-system.service.gov.uk/patterns/validation/#turn-off-html5-validation).
We already expect teams to turn off HTML5 validation for [visual and accessibility reasons](https://design-system.service.gov.uk/patterns/validation/#turn-off-html5-validation). The guidance in this PR acts as an additional signpost from the text input for numbers component and the bank details pattern.
We have an [open issue](https://github.com/alphagov/govuk-frontend/issues/1701) for removing the `pattern` attribute from the number input …

Add guidance for turning off HTML5 validation for number inputs

---

src/patterns/question-pages/index.md.njk

Some small updates to the question pages pattern. Related to https://github.com/alphagov/govuk-design-system/issues/1222.
What's changed:
- moved the multiple questions example further down the page so that the default is clearly 'one thing per page'
- added guidance on when to group multiple questions on a page, and how to style labels and legends to make the page easier to scan
Questions worth considering:
- what about using headings rather than labels to group related fields? e.g. having a `h2` saying 'contact details' with a text input for email and phone number below
- not directly related to this work but the 'Asking users questions' section at the bottom of this page feels quite high level and possibly too foundational to be at the bottom of the page like it is?

Clarify guidance on asking multiple questions on a page

---

src/index.njk

Following chat with Mark (we're adding aliases to the relevant pattern, so people who search will still find it)

Remove section about coronavirus

---

src/patterns/understand-the-impact-of-an-emergency/index.md.njk

Suggestion from Mark, before we remove the coronavirus section from the home page

Add coronavirus aliases

---

src/components/date-input/index.md.njk
src/components/error-message/index.md.njk

This PR will make a couple of changes to guidance on:
- date inputs
- error messages
In [issue 1820 in Frontend](https://github.com/alphagov/govuk-frontend/issues/1820) we're proposing changing the border width on inputs with errors to 2px. This is to resolve the problem of fields with errors not having enough contrast with their focused states (both being 4px wide and without enough colour contrast between them).
This will mean that inputs with errors will be less visually prominent than before. This could cause problems with grouped inputs, such as for dates. This guidance tries to make it clear that in these cases, the error message MUST directly reference the field it's referring to.

Update guidance on error styling and messages

---

src/components/checkboxes/conditional-reveal/index.njk
src/components/radios/conditional-reveal/index.njk
src/components/text-input/decimal-input/index.njk
src/components/text-input/input-spellcheck-disabled/index.njk
src/components/text-input/number-input/index.njk
src/patterns/bank-details/default/index.njk
src/patterns/bank-details/error/index.njk
src/patterns/bank-details/international/index.njk
src/patterns/email-addresses/default/index.njk
src/patterns/email-addresses/error/index.njk
src/patterns/names/default/index.njk
src/patterns/names/error/index.njk
src/patterns/national-insurance-numbers/default/index.njk
src/patterns/national-insurance-numbers/error/index.njk

Depends on: https://github.com/alphagov/govuk-design-system/issues/1309
Relates to: https://github.com/alphagov/govuk-frontend/issues/1832
Update any documentation around enabling/disabling spellcheck for input and textarea components in the design system to use the new spellcheck attribute
The spellcheck attribute was added for the input and textarea components in this PR: https://github.com/alphagov/govuk-frontend/pull/1859 . We should replace the old way of doing things with the new way, so that we're consistent.

Update documentation on using spellcheck attribute

---

src/patterns/email-addresses/index.md.njk

Unfortunately there is [no way to disable auto-linking in marked without overriding the renderer's `link` function][1].
Prevent the auto-linker from working by including an empty `<i>` tag within the email address, which is [consistent with how we've done it elsewhere, in the typography styles page][2].
Fixes #1316.
[1]: https://github.com/markedjs/marked/issues/882
[2]: https://github.com/alphagov/govuk-design-system/blob/d25b2f6407f86a8f4c168ea6604f935ae51cfe0c/src/styles/typography/index.md.njk#L86

Do not autolink email address in emails pattern

---

src/components/summary-list/index.md.njk

I needed a summary list without a bottom border - the design system has a useful class for this, but it's not mentioned.
My use case is a summary list appearing inside of another block - in this case the bottom border is redundant.

Document row-no-border class

---

src/get-started/production/index.md.njk
src/styles/page-template/index.md.njk

As part of [Improving guidance for using Nunjucks docs](https://github.com/alphagov/govuk-design-system/issues/1281), this improves the Nunjucks guidance in the Design System to: 
- remove the Nunjucks guidance from [Get Started > Production](https://design-system.service.gov.uk/get-started/production/) and link to the [new improved Frontend docs on Nunjucks](https://github.com/alphagov/govuk-frontend-docs/pull/67)
- link to the same new docs from [page template](https://design-system.service.gov.uk/styles/page-template/)
- improve the page template-specific Nunjucks guidance so we talk about `set` and `block` as alternate ways of passing in the same options rather than 2 different types of option
- combined the 'variable' and 'block' tables, and put the combined table in alphabetical …

Update Nunjucks guidance and link to new docs

---

src/components/fieldset/index.md.njk

The heading was renamed from 'Using hint text' to 'Hint text' in fbe0c47.
Fixes #1326.

Fix broken anchor link

---

manifest.yml

When we set the Design System up, PaaS did not support the nginx buildpack, so we had to reference the buildpack using its GitHub URL, pinning to a specific version.
PaaS now provide an nginx buildpack, so we can now use that instead. This means whenever PaaS update their buildpacks we'll automatically use the latest version when we next deploy.
The current version of the buildpack is 1.1.14, so this effectively bumps the buildpack version from 1.1.9 to 1.1.14, and the nginx version from v1.17.10 to v1.19.2 (verified by deploying a test app to the sandbox).

Use PaaS-supplied nginx buildpack

---

src/accessibility.md.njk

We're doing an overall accessibility audit of our Tech Docs Template technical documentation across GDS.
Following the [audit and improvements](https://github.com/alphagov/govuk-frontend-docs/issues/65) to the Frontend docs July, we now need to publish accessibility content as part of the Design System accessibility statement.
I've made clarifications in the statement so it's clear when we're talking about the Design System website and when we're talking about the Frontend docs.

Add content about accessibility of Frontend docs

---

src/components/text-input/decimal-input/index.njk
src/components/text-input/index.md.njk
src/components/text-input/input-prefix-suffix-error/index.njk
src/components/text-input/input-prefix-suffix/index.njk
src/components/text-input/input-prefix/index.njk
src/components/text-input/input-suffix/index.njk

Adds prefix and suffix elements to the input component.
A number of local and departmental design systems ([GOV.UK Publishing Components](https://components.publishing.service.gov.uk/component-guide/input/with_prefix_and_suffix), [HMRC](https://design.tax.service.gov.uk/hmrc-design-patterns/currency-input/), [MOJ](https://moj-design-system.herokuapp.com/components/currency-input) and [ONS](https://ons-design-system.netlify.app/patterns/numeric-values/)) are using prefixes and suffixes to indicate currencies and measurements.
```html
<div class="govuk-form-group">
<label class="govuk-label" for="cost">
Cost, in pounds
</label>
<div class="govuk-input__wrapper">
<span class="govuk-input__prefix" aria-hidden="true">£</span>
<input class="govuk-input govuk-input--width-10" id="cost" …
```

Add input prefix and suffix

---

src/stylesheets/components/_example.scss
src/stylesheets/components/_tabs.scss
views/partials/_example.njk

Allow the code blocks to be scrolled using the keyboard by including them in the tab order and giving them a visible focus state.
This allows the user to tab to the code blocks, then use the arrow keys to scroll left to right.
Fixes #1343

Make code blocks scrollable using the keyboard

---

src/stylesheets/components/_tabs.scss

Fixes https://github.com/alphagov/govuk-design-system/issues/1356

Switch code block focus from box-shadow to border

---

src/components/checkboxes/conditional-reveal/index.njk
src/components/radios/conditional-reveal/index.njk

The conditional reveals example for the checkboxes component uses an ID of `citizenship-conditional` but the question is about contact preferences – suspect this is either a copy and paste error or an error introduced when the content in the example was updated. Update it to use ‘contact’ as a prefix instead.
Update the corresponding example in the radios component to be consistent rather than the current more verbose `how-contacted-conditional`.

Update ID and name for conditional reveal examples

---

src/community/backlog/index.md.njk

'Callout text' is covered by [inset text](https://design-system.service.gov.uk/components/inset-text/)

removing 'Form input prefixes and suffixes' and 'Callout text'

---

package-lock.json

Dependabot flagged a [high severity security issue for `object-path`](https://github.com/alphagov/govuk-design-system/network/alert/package-lock.json/object-path/open). `object-path` is a dependency of browser-sync - bumping browser-sync seems to remove `object-path` completely.
This also fixes another [high-severity security issue for `http-proxy`](https://github.com/alphagov/govuk-design-system/network/alert/package-lock.json/http-proxy/open) in any versions below 1.18.1.

Bump browser-sync from 2.26.7 to 2.26.13 to fix security issues

---

src/components/button/index.md.njk

In response to this query in the backlog: https://github.com/alphagov/govuk-design-system-backlog/issues/34#issuecomment-399995390

Explain why start buttons are output as HTML links, not buttons

---

src/components/date-input/index.md.njk

Add the following sentence to the guidance for Date input:
_Make sure that any example dates you use in hint text are valid for the question being asked._ 
This came up in our support channels and is particularly relevant when the date you are asking for must fall with in a range relative to the current date (eg. 'within the last 2 weeks'). In cases like this example dates in hints would need to be programatically generated, to make sure they don't keep falling outside of the permissable date range.

Add guidance about using example dates in hint text

---

src/stylesheets/components/_highlight.scss

Change the colour of ‘meta’ syntax highlighting from `#999999` to `#545555` (a 30% tint of `#0b0c0c`), improving the colour contrast against the background (`#f3f2f1`) from 2.55:1 (which fails [WCAG 2.1 1.4.3 Contrast (Minimum)](https://www.w3.org/TR/WCAG21/#contrast-minimum)) to 6.68:1 (which passes as it meets the minimum 4.5:1 ratio)
The ‘meta’ syntax highlighting is only used in a couple of places (the doctype definition in the page template and an `!important` rule in a code example from the ‘Extending and modifying components in production’ guidance.
| Before | After |
| -- | -- |
| ![Screenshot 2020-10-27 at 13 50 53](https://user-images.githubusercontent.com/121939/97310825-9b358a80-185b-11eb-9066-40b0333f93a8.png) | ![Screenshot 2020-10-27 at 13 51 …

Improve colour contrast of 'meta' syntax highlighting, and make comments look more like comments

---

src/patterns/understand-the-impact-of-an-emergency/index.md.njk

Archive the ‘Help users to understand the impact of an emergency on your service’ pattern.
This pattern is being replaced by the guidance in the notification banner component.
Closes https://github.com/alphagov/design-system-team-internal/issues/364

Archive the ‘Understand the impact of an emergency’ pattern

---

src/components/notification-banner/index.md.njk

Adds a new alias 'flash message' to the search that routes users to the notification banner:
Raised by @edwardhorsford on Slack

Add 'flash message' alias to notification banner

---

src/components/checkboxes/index.md.njk
src/components/radios/index.md.njk

Simplify the guidance for radios so that it matches the language used for conditional reveals for checkboxes. You don’t ‘use a component’ to add conditionally revealing content to radios – radios _are_ the component.
Also break the equivalent guidance in the checkboxes guidance over two paragraphs to improve readability.

Simplify language used in conditional reveals guidance

---

views/layouts/layout-archived.njk

This builds on top of #1400 as it's just something I was playing with on Friday, and I'm not sure whether we actually want to do it or not.
Allow users to check the UK Government Web Archive (from The National Archives) for previous versions of archived pages.
Affected pages:
👉🏻  &nbsp; [Cookies](https://deploy-preview-1401--govuk-design-system-preview.netlify.app/cookies/)
👉🏻  &nbsp; [How you can contribute](https://deploy-preview-1401--govuk-design-system-preview.netlify.app/community/how-you-can-contribute/)

Link to UK Gov Web Archive from archived pages

---

src/components/error-message/index.md.njk

Make it clearer that the error message pattern is for highlighting problems with information the user provides rather than problems with the service.

Clarify when not to use error messages

---

src/community/resources-and-tools/index.md.njk

Since the release of the fixtures in govuk-frontend@3.9.x the govuk-frontend-diff tool is no longer necessary - I have moved away from using it on my own repository and marked it as deprecated on the readme. I'll leave the repository up of course, but it wouldn't be my first choice for testing now that the fixtures are available.

Removing deprecated govuk-frontend-diff tool

---

src/styles/colour/index.md.njk
src/stylesheets/main.scss

They are snippets of code, so semantically it makes sense to treat them as code.
This also has the benefit of styling them as code, which makes the individual digits easier to distinguish.
I’ve overridden the red text colour and grey background so they are styled the same as the colours’ variable names.
Before | After 
---|---

Treat hexadecimal colours codes as code

---

src/community/resources-and-tools/index.md.njk

Adds a link to a Miro version of the GOV.UK Design System Flow Diagrams by @dashouse

Link to a Miro version of GOVUK Design System Flow

---

src/accessibility.md.njk

Updated the date for fixing the Tech Docs Template accessibility issues in from “end of December 2020” to “end of March 2021”. As a result of resourcing pressures and re-prioritisation this year, it’s taking longer than we hoped to arrange developer and designer resources to fix the accessibility issues.
(This only relates to https://github.com/alphagov/govuk-frontend-docs/, not the main Design System site).

Update date for govuk-frontend-docs part of accessibility statement

---

src/stylesheets/components/_site-search.scss

Prompted by discussions with the NHS Frontend team (https://github.com/nhsuk/nhsuk-frontend/issues/679), improve the visibility of the focus state for the search box by adding a black (#0b0c0c) border between the white text input and the yellow focus outline.
Without this change, the only part of the focus indicator that meets colour contrast is the outermost 1px which change from black to white as the input ‘grows’ – the other 2px of the 3px outline change from white to black.
After this change, the entire 7px comprised of the border, box shadow and outline meet contrast, as the border changes from a 2px white to a 4px (2px border + 2px box-shadow) black (19.58), and the 3px outline causes a change from black to yellow (14.54).
This change also improves the visibility of the focus state …

Improve visibility of focus state for search box

---

src/styles/images/index.md.njk

The following two lines under the "Do not" heading are mutually contradictory:
- repeat information from the page
- include extra information not on the page
What you should say is, don't include extra info that is **not in the image**

Clarify guidance on image alt text

---

src/components/character-count/default/index.njk
src/components/character-count/error/index.njk
src/components/character-count/index.md.njk
src/components/character-count/threshold/index.njk
src/components/character-count/without-heading/index.njk
src/components/character-count/word-count/index.njk
src/components/checkboxes/index.md.njk
src/components/checkboxes/without-heading/index.njk
src/components/date-input/index.md.njk
src/components/date-input/without-heading/index.njk
src/components/radios/index.md.njk
src/components/radios/without-heading/index.njk
src/components/text-input/index.md.njk
src/components/text-input/without-heading/index.njk
src/components/textarea/index.md.njk
src/components/textarea/without-heading/index.njk
src/get-started/labels-legends-headings/index.md.njk

This PR updates components with labels or legends to include examples without headings. It aims to solve #1364 and apply the same principle to other relevant components.
It updates content and examples for the following components:
- Character count
- Checkboxes
- Date input
- Radios
- Text input 
- Text area
Would be good to get a review from @StephenGill – I went off your suggestion for the checkbox page and have tried to apply the same approach elsewhere. Should probs also have a developer make sure I haven't done anything wrong with the new examples.

Update components with labels or legends to include examples without headings

---

src/get-started/index.md.njk

This is to correct lowercase instance of 'design system.'

Fix capitalisation in Get Started doc

---

src/components/character-count/index.md.njk
src/components/checkboxes/index.md.njk
src/components/date-input/index.md.njk
src/components/radios/index.md.njk
src/components/text-input/index.md.njk
src/components/textarea/index.md.njk
src/patterns/question-pages/index.md.njk

Adds clearer link text for anchor links to the 'Asking multiple questions on a page' section of the 'Question pages' page.

Add clearer anchor link text to questions

---

src/components/button/button-group/index.njk
src/components/button/index.md.njk

Add guidance about [button groups](https://github.com/alphagov/govuk-frontend/pull/2114) to the button component guidance.
Includes two examples:
- the current example of two buttons together, moved from the 'secondary buttons' section and updated to use the button group object rather than a margin override
- a new example that includes a button and a link together
👉🏻 &nbsp;[View preview](https://deploy-preview-1472--govuk-design-system-preview.netlify.app/components/button/#grouping-buttons)
Closes #1471

Add guidance for button groups

---

src/components/table/caption-l/index.njk
src/components/table/column-widths-custom-classes/index.njk
src/components/table/column-widths/index.njk
src/components/table/index.md.njk
src/components/table/numbers/index.njk

This is some additional guidance to support the changes to table caption styles https://github.com/alphagov/govuk-frontend/commit/a20ffa8954820f5507715cb9ef676318d0cce3af

add updated caption styles to table component

---

src/patterns/cookies-page/cookies-updated/code.njk
src/patterns/cookies-page/index.md.njk

Stop the notification banner used in the example from stealing focus when the iframe loads.
This is consistent with the approach used in other auto-focusing components in the Design System – for example, the ‘success’ example in the notification banner component guidance.

Disable cookie page notification banner autofocus

---

src/styles/page-template/custom/code.njk
src/styles/page-template/custom/index.njk

Add the default cookie banner to the customised page template example as discussed in https://github.com/alphagov/govuk-design-system/issues/1475#issuecomment-775053243.
Partially fixes https://github.com/alphagov/govuk-design-system/issues/1475

Add cookie banner code example to page template

---

data/colours.json

This PR is proposing we expose the `$govuk-success-colour` variable to be used for success messages [1][2], as we do for [error messages](https://design-system.service.gov.uk/styles/colour/).
[1] https://design-system.service.gov.uk/components/notification-banner/#reacting-to-something-the-user-has-done
[2] https://design-system.service.gov.uk/patterns/confirmation-pages/
I appreciate the timing of this PR might not be ideal and we might want to proceed with this at a more appropriate moment, but I personally find it valuable as it promotes a level of abstraction (on top of the raw `govuk-colour("green")`) that could prove to be beneficial on the long run.

Add success colour

---

.github/workflows/ci.yaml

Occasionally the webhook does not fire when a PR is merged to master – for example, if GitHub is having a partial outage.
Adding workflow_dispatch to the list of triggers [allows us to trigger this workflow manually from the Actions tab][1].
[1]: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually

Make it possible to manually trigger a deploy

---

src/components/cookie-banner/index.md.njk

(Curly quotation marks are invalid for HTML attributes)

Minor: use straight quote marks in HTML fragments

---

src/components/cookie-banner/index.md.njk

The fact that we've put the word 'partner' or 'partners' in quotes has led at least one person to think we want them to use that term in banner text. That's not the intent behind the guidance, so I've updated it to sound less prescriptive.

Avoid implying we want people to use 'partner'

---

views/partials/_contact-panel.njk

Add an `id` to the heading of the 'contact panel' shown at the bottom of guidance pages:
I wanted to send a link for this section to a user on support earlier. Also seems a bit inconsistent with the other headings on the pages.
The `id` content is hard coded cos the headings are the same on every page, happy to hear suggestions of better ways to do it if you think this would be a problem though.

Add id to contact panel heading

---

src/patterns/names/index.md.njk

Addressing #1354 at the request of @timpaul.
This makes clearer how to label middle names.
It does not address the issue I've seen frequently that the `Full name` field induces users to provide full legal names including middle name, when many services don't actually want this.

Add more detailed guidance about middle names

---

src/components/cookie-banner/multiple-cookies/index.njk

Single word change to avoid implying that analytics cookies track an individual user.
Checked with Stephen Gill for privacy concerns and it's fine.

Update multiple cookies example to be clearer

---

src/components/cookie-banner/index.md.njk

Add legal disclaimer text, as requested by privacy advisor, to make it clear this component does not automatically make services compliant with regulations.

Add cookie banner legal disclaimer text

---

src/components/notification-banner/success/code.njk

Updating one of the examples in the notification banner component so that the heading within the banner uses a `h3` instead of a `p`. 
I think that was our original intent, and reflects the hierarchy of the content more accurately. Let me know there's a reason it is the way it is!

Update notification banner example to use correct markup

---

src/components/notification-banner/index.md.njk

This guidance is to provide clarity on how to use headings `<h3> `and upwards in the Notification Banner. 
The challenge is to ensure users know not to use a heading if they have no body or paragraph content to follow it.
Closes #1516

Adding guidance to support the updated heading example

---

src/components/cookie-banner/index.md.njk

Reworked research section of the Cookie banner component page based on user feedback:
https://github.com/alphagov/govuk-design-system/issues/1502
User feedback 1 (example text)
> "I shared it with the designers...earlier today and it’s resulted in some interesting discussions, one in particular around the content in the banner. We wonder if “…understand how you use the service…” is potentially misleading, as analytics shouldn’t be able to track one user. Maybe something like “We’d also like to store cookies to track visits and find out how people use the website, so we can make improvements.” would be a better option?"

Improve cookie banner research explanation

---

src/components/button/index.md.njk

Based on this comment in the backlog: https://github.com/alphagov/govuk-design-system-backlog/issues/34#issuecomment-699537400

Add research section to button page

---

src/community/resources-and-tools/index.md.njk

The [govuk-components](https://github.com/dfe-digital/govuk-components) gem is a lightweight alternative to the [govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components) library and provides all of the non-form components from the GOV.UK Design System.
Version 1.0.0 has recently been released and it's now used across several DfE projects.
It uses [GitHub's ViewComponent framework](https://viewcomponent.org/).
This supersedes #1430 where the forked repository fell victim to my spring clean.

Add the DfE's govuk-components to resources list

---

src/components/tag/default/index.njk
src/components/tag/index.md.njk

Just added an example here because there wasn't one there before, which is inconsistent with other components.
I used 'completed' as the example, taken from the task list pattern.

Add example to top of tag component

---

src/community/resources-and-tools/index.md.njk

Adding WTForms Widget package to generate GOV.UK compliant forms. Works in conjunction with the existing GOV.UK Frontend Jinja package.

Add GOV.UK Frontend WTForms package

---

lib/get-macro-options/index.js

Make sure any additional components in the macro options are converted to markdown before displaying.
Issue raised by @EoinShaughnessy . We weren't converting all macro option descriptions to markdown, which meant some descriptions were displaying the backticks to highlight code rather than rendering as actual inline code blocks.

Render additional component descriptions as markdown

---

views/layouts/layout-example-full-page.njk

We regularly get support requests from users who are having difficulty signing in to Universal Credit.
According to Google Search Console, on 1 Feb we saw a particularly high peak of 5,034 clicks from Google search results of which 2,349 related to Universal Credit. 2,633 clicks were to the ‘Service unavailable’ pattern, and another 1,223 clicks were to the ‘Problem with the service’ pattern.
These patterns both include full page examples which contain text that might appear in a service. They also contain the names of real-life services or concepts, including ‘tax credits’ and ‘Universal Credit’.
[Unlike partial examples][1], full page examples do not include a robots meta tag preventing indexing from search engines.
Prevent full page examples from being indexed by search engines by …

Prevent full page examples from being indexed

---

src/community/blogs-talks-podcasts/index.md.njk
src/community/index.md.njk
src/index.njk

This pull request adds a blog posts, talks, and podcasts page to the community section of the Design System website.
This closes #1470

Add blogs, talks and podcasts to community pages

---

src/components/accordion/index.md.njk
src/components/checkboxes/index.md.njk
src/components/radios/index.md.njk

In #1549 we updated the date we plan to fix the 2 known accessibility issues from March 2021 to June 2021. However, the March dates also appear in the guidance for the affected components (radios, checkboxes, accordion) and these were missed.
Update the dates in the guidance to keep them in sync with the dates in the accessibility statement.

Update expected fix dates in guidance

---

src/components/cookie-banner/index.md.njk

The `Research on this component` section is missing an "is", and is not clearly readable without it.

Add missing "is" to `Research on this component`

---

src/styles/typography/captions-inside/index.njk
src/styles/typography/captions/index.njk
src/styles/typography/headings-xl/index.njk
src/styles/typography/headings/index.njk
src/styles/typography/index.md.njk

In #1201 the default heading size was changed to `govuk-heading-l` - however the typography page still gives the impression that `govuk-heading-xl` should be the default.
It says in words that the heading size should depend on the content - but all the examples continue to use `xl`.
Additionally the primary example showing the different heading classes also changes the heading level with each class. This gives the *very strong* impression that `govuk-heading-xl` is for `h1`, `govuk-heading-l` is for `h2`, etc.
I've spoken with several teams across gov (both new starters and people who have worked with the design system for some time), and universally every one took the main example (screenshot above) as indicating a correlation between class and heading level - which is not at all …

Make it clear that the heading class does not relate to the heading level

---

src/patterns/equality-information/asian/index.njk
src/patterns/equality-information/black/index.njk
src/patterns/equality-information/date-of-birth/index.njk
src/patterns/equality-information/disability-impact/index.njk
src/patterns/equality-information/disability/index.njk
src/patterns/equality-information/error-date-of-birth/index.njk
src/patterns/equality-information/error-ethnicity/index.njk
src/patterns/equality-information/ethnic-group/index.njk
src/patterns/equality-information/explainer-screen/index.njk
src/patterns/equality-information/index.md.njk
src/patterns/equality-information/marriage-status/index.njk
src/patterns/equality-information/multiple/index.njk
src/patterns/equality-information/other/index.njk
src/patterns/equality-information/religion/index.njk
src/patterns/equality-information/sex-gender/index.njk
src/patterns/equality-information/sexual-orientation/index.njk
src/patterns/equality-information/white/index.njk

Closes https://github.com/alphagov/govuk-design-system/issues/1540
Publish the equality information pattern, based on the [harmonised standards developed by the Government Statistical Service](https://gss.civilservice.gov.uk/guidances/harmonised-standards-guidance/).
Draft doc: https://docs.google.com/document/d/1Het6wUdA3a8al-Z27g-fqJOOQpwxysa3IT95QkN7TjY/edit
**Note: there is a question about the legend for the first example, which may need updating. I'm following up with Stephen on this.**

Add new equality information pattern

---

src/community/backlog/index.md.njk

Removes protected characteristics 'to do' line, as it's replaced by the Equality information pattern
https://github.com/alphagov/govuk-design-system/issues/1545

Remove protected characteristics item

---

src/patterns/equality-information/index.md.njk

'Discrimination' is mis-spelled in opening sentence

Correct typo

---

src/accessibility.md.njk

Fixes [#1569](https://github.com/alphagov/govuk-design-system/issues/1569) (Remove references to accessibility issues in Frontend Docs from accessibility statement [before 31 March]).
The [most recent update to the Tech Docs Template](https://github.com/alphagov/govuk-frontend-docs/pull/109) has fixed some accessibility issues. For example, users of assistive tech will now no longer be able to focus elements that should remain hidden on pages. So, we now need to update our accessibility statement to say that our Frontend docs site is fully compliant with the WCAG 2.1 AA standard.
This PR also contains:
- an updated review date for the accessibility statement
- deletions of outdated information (about WCAG only being partly met because of issues with the Template)

Update accessibility statement after TDT fixes

---

src/patterns/ethnic-group/index.md.njk

The ‘asking users for ethnic groups’ pattern was archived in #1582 and redirected to the new ‘asking users for equality information’ pattern.
However, the Design System currently relies on the `ignore_in_sitemap` flag in the frontmatter when deciding whether the page should appear in the sitemap and the site navigation.
This means that the pattern is still appearing in the sitemap, and also at the very bottom of the Patterns navigation.
Add the `ignore_in_sitemap` flag to the archived page to remove it from both places.
Fixes #1592.

Exclude ethnic group pattern from sitemap and nav

---

src/community/contribution-criteria/index.md.njk
src/components/button/index.md.njk
src/components/date-input/index.md.njk
src/components/notification-banner/index.md.njk
src/components/radios/index.md.njk
src/components/tag/index.md.njk
src/patterns/cookies-page/index.md.njk
src/patterns/equality-information/index.md.njk
src/patterns/gender-or-sex/index.md.njk
src/patterns/payment-card-details/index.md.njk
src/patterns/step-by-step-navigation/index.md.njk
src/patterns/task-list-pages/index.md.njk
src/patterns/validation/index.md.njk
src/styles/typography/index.md.njk

The GOV.UK style guide says that some users find negative contractions hard to read, or else misread them.
So, we should write "have not" instead of "haven't," and so on.
This PR replaces the negative contractions I've found in our components guidance.

Replace negative contractions in guidance

---

src/community/resources-and-tools/index.md.njk

This pull request closes #1533 
Adding a Figma resource to the tools and resources page of the community section.
Some of our users use Figma to prototype their work. This resource will allow them to use Design System styles and components.

add figma resources to community resources and tools page

---

src/design-system-team.md.njk

- Replace dashes with en-dashes
- Replace non-breaking spaces with spaces

Fix typos on team page

---

src/community/contribution-criteria/index.md.njk

Adds suggested message so community resources cannot be mistaken for official parts of the Design System.
Fixes https://github.com/alphagov/design-system-team-internal/issues/430

Add criteria for community resources

---

src/patterns/step-by-step-navigation/index.md.njk

This PR fixes an unclear expression in the [guidance page for our step by step navigation pattern](https://design-system.service.gov.uk/patterns/step-by-step-navigation/).

Fix grammar in step by step navigation pattern

---

src/components/footer/full/index.njk

Set [`lang`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) and [`hreflang`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-hreflang) attributes on the ‘Rhestr o Wasanaethau Cymraeg’ (‘List of Welsh Language Services’) link in the [Footer with secondary navigation and links to meta information](https://design-system.service.gov.uk/components/footer/#footer-with-secondary-navigation-and-links-to-meta-information) example:
```html
<a class="govuk-footer__link" href="#" lang="cy" hreflang="cy">
Rhestr o Wasanaethau Cymraeg
</a>
```
This matches the current HTML used in the footer on GOV.UK:
```html
<a class="govuk-link" href="/cymraeg" lang="cy" hreflang="cy">Rhestr o Wasanaethau Cymraeg</a>
```
Fixes #1631

Specify lang attributes on Welsh link in footer

---

README.md

The link in the readme to sass-lint was pointing to a similar but different tool, gulp-scss-lint. This commit fixes the link so that it points to the tool we are actually using according to the package maniftests.

Fix URL in link to sass-lint

---

src/accessibility.md.njk

Fixes [#1654](https://github.com/alphagov/govuk-design-system/issues/1654) (Update accessibility statement to say that mobile tabs are not in a tablist).
This PR is to tell users of our [Accessibility Statement](https://design-system.service.gov.uk/accessibility/) about an issue that fails [WCAG 2.1 success criterion 1.3.1 (Info and Relationships)](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html).
On mobile, our guidance's HTML and Nunjucks tabs are not contained in a `tablist`.
This means that assistive tech might interpret the tabs as plain text, instead of as the 'control' we've built them to be.
This PR also redisplays the accessibility issues in numerical order of WCAG fail.

Add mobile tabs issue to Accessibility Statement

---

src/stylesheets/components/_mobile-navigation.scss
src/stylesheets/components/_navigation.scss
src/stylesheets/components/_subnav.scss
src/stylesheets/components/_tabs.scss
src/stylesheets/main.scss
views/partials/_mobile-navigation.njk
views/partials/_navigation.njk
views/partials/_subnav.njk

The new link and hover styles due to be published in GOV.UK Frontend v3.12.0 will be opt-in until the next major release. However, we'd like the Design System website itself to take advantage of the new styles in order to showcase the most up-to-date version of GOV.UK Frontend, and to have an example we can show users of making custom link styles compatible with the new styles.
This PR:
- opts into the new styles
- makes the navigation, mobile navigation, subnav and tabs compatible with the new styles by using the `govuk-link-style-no-underline` mixin which will handle the text decoration and use the new hover styles.
As the new link styles don't support IE8, the current navigation item will have a double underline. The navigation is still functional.
~Optionally, I've had a go at making …

Implement the new link and hover styles in the Design System website

---

src/patterns/equality-information/sexual-orientation/index.njk

Addresses [#1624](https://github.com/alphagov/govuk-design-system/issues/1624).
This PR changes an example question in the [Equality information pattern](https://design-system.service.gov.uk/patterns/equality-information/) from:
> Which of the following options best describes how you think of yourself?
to
> Which of the following best describes your sexual orientation?
This change is because of an issue raised by a designer at the Office of National Statistics (ONS). The original question was inaccessible - when screen readers read it out, what was being asked was unclear to users.
The revised wording is in line with what was asked in the Census and signed off by the ONS.

Make Equality Info example question accessible

---

src/components/text-input/index.md.njk

Addresses [#1671](https://github.com/alphagov/govuk-design-system/issues/1671).
This PR updates our [hint text guidance](https://design-system.service.gov.uk/components/text-input/#hint-text) to:
- explain why users should not use hint text for long paragraphs and lists
- suggest an alternative way to display complex questions

Add correct usage to hint text guidance

---

package-lock.json

Bumps [browser-sync](https://www.npmjs.com/package/browser-sync):
- [Release notes](https://github.com/BrowserSync/browser-sync/releases/tag/v2.26.14)
- [Commits](https://github.com/BrowserSync/browser-sync/compare/v2.26.13...v2.26.14)

Bump browser-sync from 2.6.13 to 2.6.14

---

package-lock.json

This PR bumps a number of indirect dependencies using `npm audit
--fix`.
Bumps [lodash](lodash.com) to 4.17.21:
- [Changelog](https://github.com/lodash/lodash/wiki/Changelog)
Bumps [kind-of](https://github.com/jonschlinkert/kind-of) to 6.0.3:
- [Changelog](https://github.com/jonschlinkert/kind-of/blob/master/CHANGELOG.md)
Bumps [acorn](https://github.com/acornjs/acorn) to 6.4.2:
- [Release notes](https://github.com/acornjs/acorn/releases/tag/6.4.2)
Bumps [extract-zip](https://github.com/maxogden/extract-zip) to 1.7.0:
- [Release notes](https://github.com/maxogden/extract-zip/releases/tag/v1.7.0)
Bumps [fd-slicer](https://github.com/andrewrk/node-fd-slicer#readme) from 1.0.1 to 1.1.0:
- [Changelog](https://github.com/andrewrk/node-fd-slicer/blob/master/CHANGELOG.md)
- …

Bump dependencies using npm audit

---

package-lock.json
package.json

You can now use ES6 constructs such as `const` in JavaScript files.
Bumps [metalsmith-uglify](https://github.com/borisovg/metalsmith-uglify#readme) from 2.3.2 to 2.4.0:
- [Commits](https://github.com/borisovg/metalsmith-uglify/compare/b882ee733be0a6a0c3d36ef5c09990fe606630a0...54d8f83dfe78d1b45f6f648645c088ff3ec0ece2)

Bump metalsmith-uglify from 2.3.2 to 2.4.0

---

src/patterns/step-by-step-navigation/index.md.njk

Partly addresses [#1426](https://github.com/alphagov/govuk-design-system/issues/1426).
This PR updates the [guidance for the step by step navigation pattern](https://design-system.service.gov.uk/patterns/step-by-step-navigation/) to make it clear that:
- the pattern is only for use on GOV.UK 
- the pattern is only included in the Prototype Kit so users can prototype their journeys
- we do not actually provide the code for the pattern (unlike most of our other components and patterns)

Add content about using step-by-step only on GOVUK

---

.babelrc.json
__tests__/cookie-functions.test.js
package-lock.json
package.json
src/javascripts/cookie-functions.js

Closes #1614.
This PR adds copies of the [cookie consent functions from digitalmarketplace-govuk-frontend](https://github.com/alphagov/digitalmarketplace-govuk-frontend/tree/d24e7f1dc6e94fb9f173aebf46aed5f1051af59c/src/digitalmarketplace/helpers/cookie), and refactors them slightly.
---
We wanted a cookie module to provide the following functionality:
- accept and reject cookies
- save consent in a cookie, with an expiry of 1 year
- delete cookies when a user changes their preference to reject
- look up a user's consent
- be able to map a cookie name to it's category, e.g: `_ga` -> `analytics`
I reviewed existing code in other alphagov projects and found the Digital Marketplace GOV.UK Frontend code fit all of our needs and was the best fit for our existing codebase. See issue #1615 for …

Add cookie consent functions

---

src/components/phase-banner/index.md.njk

Minor update to clarify that a service needs to complete a live assessment before they can remove a phase banner.
In response to a support query from Head of Service Assessments in CDDO.
https://govuk.zendesk.com/agent/tickets/4587581

Clarify when a service needs a phase banner

---

src/components/error-summary/default/index.njk
src/components/error-summary/linking-checkboxes-radios/index.njk
src/components/error-summary/linking/index.njk

We’ve had feedback that the IDs used in these examples might suggest that the links should go to the error message rather than the input.
To make this clearer, avoid suffixing the link targets with the word ‘error’, and use `input` where it’d be realistic a user might do so, like for simple text inputs.
In the case of date inputs, the date input component uses the field name as a suffix, so it’s likely the field ID will end with e.g. ‘-day’, so don’t add a further suffix there.
For the checkbox example, simplify the code as use the auto-generated ID for the first checkbox will be ‘nationality’ anyway, so we don’t need to set it explicitly.
Closes #1696

Avoid confusing IDs in error summary examples

---

src/javascripts/components/back-to-top.js

Fixes JavaScript error `Unable to get property 'classList' of undefined or null reference` in IE11 on the few pages we have that don't have a back to top link.

Check for Back to top link before initialising it
