alphagov/govuk-design-system

source/components/_header.erb, source/stylesheets/components/_header.scss
This adopts the correct BEM notation which I got totally wrong in my previous PR. 😱
As spotted by @alex-ju in #72
=> Update the class names in the header

source/errors/404.html.erb, source/errors/generic.html.erb
This PR:
- Updates 404 error page
- Updates generic error page
- (Hopefully?) a 404 appears when a url is entered that cannot be found
[Trello card](https://trello.com/c/Evgmg8Ay)
=> Update 404 and generic error pages

views/layouts/_generic.njk, views/partials/_tracking-body.njk, views/partials/_tracking-head.njk
This adds google tag manager code. It uses the same file naming as the Prototype Kit and Elements.
=> Add google tag manager

package-lock.json, package.json
See individual commits for details.
=> Update metalsmith-sass, marked dependencies

.editorconfig
Added latest version of the GDS Way .editorconfig
=> Add latest version of the GDS Way .editorconfig

src/components/table/default.njk, src/components/table/index.md.njk, src/components/table/numbers.njk
Add table page and two examples
=> Add table page and examples

.gitignore
Useful for contributors who do not have global git configurations
=> Ensure more common files cannot accidentally be checked in

src/components/index.md.njk, src/patterns/index.md.njk, src/styles/index.md.njk
This adds content to the Styles page and amends the Components and Patterns pages to be more in-line with the current build.
=> Update content on landing pages

src/index.njk, views/partials/_masthead.njk
This PR updates the content of the home page.
=> Update home page content

data/colours.json, lib/colours.js, lib/metalsmith.js, package-lock.json, package.json, src/styles/colour/index.md.njk, src/stylesheets/main.scss
- add a JSON file to store the colours in the right order, in groups, with notes
- process that file with the SCSS to add the correct hex values
- add a page with the colours and guidance
@hannalaakso I split the colours code out into a separate file, good call
https://trello.com/c/oDwp8XZH/450-make-colour-page-in-ds
=> Add colour page

README.md
Update README.md to reflect the automated deployment works for PR review and branch publish.
Part of this [Trello card](https://trello.com/c/BzuTM2kl)
=> Add automated deployment documentation

src/components/warning-text/default.njk, src/components/warning-text/index.md.njk
Adds warning text component and example
=> Add warning text component

lib/metalsmith.js
=> Remove errant semicolon

src/patterns/gender-and-sex/default.njk, src/patterns/gender-and-sex/index.md.njk
Added gender and sex pattern including:
- guidance
- example
=> add gender and sex pattern

src/patterns/gender-and-sex/default.njk, src/patterns/gender-and-sex/index.md.njk
Updated two mentions of 'Nonbinary' to say 'Non-binary' to be consistent with other government services.
=> Updated gender sex pattern

src/styles/layout/index.md.njk
=> Remove duplicated 'need to'

src/stylesheets/components/_divider.scss, src/stylesheets/components/_pane.scss, src/stylesheets/main.scss
This PR fixes SCSS linting errors based on `.sass-lint` config file
=> Fix SCSS linting errors based on .sass-lint config

lib/colours.js, lib/metalsmith.js, lib/modernizr-build.js, package-lock.json, package.json, src/javascripts/components/copy.js, src/javascripts/main.js
This PR: 
- adds standard as a dev dependency
- runs standard on build
=> Add standard js

views/partials/_example.njk
More considerations about the language needed.
=> Revert "Add link to table of arguments in the readme"

package-lock.json, package.json, src/stylesheets/components/_footer.scss
- Update to version 0.0.23-alpha
- Add footer specific variables which were removed from GOV.UK Frontend into the footer partial
=> Update Design System to use GOV.UK Frontend 0.0.23-alpha

views/partials/_banner.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/193
Master
Pull request
=> Change the preview banner message if master netlify preview

src/patterns/question-pages/default.njk, src/patterns/question-pages/postcode.njk
This adds closing divs to two examples on the question page pattern
=> Fix question page examples

src/javascripts/components/copy.js, src/stylesheets/main.scss
Give users feedback that code has been copied.
Add aria-live attribute to announce action taken.
Set minimum width.
Set length of text display for 2 seconds.
Fixes #149
=> Update copy button text on copy action

package-lock.json, package.json
- Update package.json and package-lock.json to install latest GOV.UK Frontend
https://trello.com/c/20K7VJz5/800-update-ds-to-use-the-new-release
=> Update with version 0.0.25-alpha of GOV.UK Frontend

src/index.njk, views/partials/_navigation.njk
Adds tracking attributes to 
- top navigation items
- links in Get started, Support and Contribute sections
Trello ticket: https://trello.com/c/rVZn0Cxv/786-2-implement-tracking-code-data-atributte-top-nav-shortcuts-in-the-design-system
=> Add top nav and homepage section link data-tracking attributes

src/components/button/index.md.njk
Changed start button heading from H2 to H3.
=> Fixed start button heading

src/styles/typography/index.md.njk, src/styles/typography/link-no-visited-state.njk
https://trello.com/c/BF3hYuXJ/622-add-link-variant-for-links-with-no-visited-state
=> Document 'no visited state' link variant

src/stylesheets/components/_footer.scss, views/partials/_footer.njk
With full-width and app-specific overrides
https://trello.com/c/6nDwS8bk/836-update-ds-to-use-footer-from-govuk-frontend
@dashouse can you have a look what've missed, not done?
=> Update DS to use footer from GOV.UK Frontend

src/stylesheets/components/_example.scss
This trick with 3d transform seems to fix the overflow issue.
=> Force hardware acceleration to stop overflow issue

lib/metalsmith.js, package-lock.json, package.json, views/layouts/_generic.njk
With the latest change in app styles we had instances of absent styles to do browser caching.
This adds a plugin to add a hash to app assets and removes old (non hashed file from public)
=> Add asset hashing (cache busting)

src/patterns/national-insurance-numbers/default.njk
Fix the length of the field so that it's more appropriate for the input that it requires.
=> Use a fixed field length

src/index.njk, src/stylesheets/components/_divider.scss, src/stylesheets/main.scss, views/partials/_divider.njk
This PR removes some of the app specific styles and overrides and utilises more GOV.UK Frontend classes.
=> Update homepage layout

src/stylesheets/components/_mobile-navigation.scss, views/partials/_mobile-navigation.njk
Update mobile navigation to be open on current page
Thanks @alex-ju (who did the code for this PR on my machine)
Issue:
https://github.com/alphagov/govuk-design-system/issues/230
=> Update mobile navigation to be open on current page

lib/metalsmith.js, src/cookies.md.njk, src/javascripts/components/cookie-banner.js, src/privacy-policy.md.njk, src/stylesheets/components/_cookie-banner.scss, src/stylesheets/main.scss, views/layouts/_generic.njk, views/layouts/layout-single-page.njk, views/partials/_cookie-banner.njk, views/partials/_footer.njk
- Add Cookies page
- Add Privacy policy page
- Add links to both in the footer
- Add Cookie banner to the DS (SCSS, JS and Generic layout)
- Amend single page layout to use large wrapper variant
=> Add cookies and privacy policy pages

src/privacy-policy.md.njk
This was supposed to be an `h2`
=> Add heading level to "Your rights" section

src/styles/layout/common-two-thirds.njk
- remove extra closing div tag from the layout example code
=> [Do not merge] [Raising to trigger CI for external contributor] Fix typo in layout code

src/get-started.md.njk
Replaces [previous pull request](https://github.com/alphagov/govuk-design-system/pull/264)
=> Add link to Frontend to Get started

src/patterns/gender-or-sex/index.md.njk
Adds gender or sex pattern back into the Design System
=> Add gender or sex pattern

src/styles/typography/index.md.njk, src/styles/typography/section-break.njk
Adds section break guidance and example.
https://trello.com/c/94hzjG0S/796-add-govuk-section-break-to-the-design-system
Requires a review by @amyhupe
=> Add section break to typography page

lib/metalsmith.js, package-lock.json, package.json, src/javascripts/govuk-frontend.js, tasks/serve.js, views/layouts/layout-example.njk
https://trello.com/c/UiikJpQn/1005-javascript-consumption-in-the-design-system
=> Enable javascript from govuk frontend

src/components/checkboxes/conditional-reveal.njk, src/components/checkboxes/index.md.njk, src/components/radios/conditional-reveal.njk, src/components/radios/index.md.njk, src/javascripts/components/example.js
Content written by @amyhupe
Trello Ticket
https://trello.com/c/jMwX1j2q/937-update-design-system-with-conditional-reveal
=> Add checkboxes and radios conditional reveal examples

src/components/inset-text/default/index.njk, src/components/inset-text/index.md.njk
=> Add inset text component example and guidance

src/components/header/index.md.njk, src/components/header/with-navigation/index.njk
Adds a more meaningful example to test.
=> Add header with navigation example

src/components/date-input/error/index.njk, src/components/error-message/default/index.njk, src/components/error-message/index.md.njk, src/components/error-message/label/index.njk, src/components/error-message/legend/index.njk, src/components/error-summary/default/index.njk, src/components/error-summary/index.md.njk
This PR is updating error message guidance.
The guidance for this component was updated after [Error messages: add guidance on how to write good ones](https://github.com/alphagov/govuk-design-system-backlog/issues/128) has gone through the review session.
Authors: @stevenaproctor, @amyhupe, @timpaul 
[Preview changes](https://deploy-preview-290--govuk-design-system-preview.netlify.com)
=> Update error message

src/errors/404.html, src/errors/generic.html
As per https://govuk-design-system-production.cloudapps.digital/patterns/page-not-found-pages/
=> Follow our own 404 page pattern

lib/metalsmith.js, package-lock.json, package.json, src/components/error-message/index.md.njk
This PR:
- fixes a broken link on the error-message page
- tests markdown output for broken internal links or missing assets on build, returning 1 if fails
```
/Users/alexandrujurubita/Documents/GitHub/govuk-design-system/tasks/build.js:5
if (err) { throw err }
^
Error: You have 1 broken links:
components/breadcrumbs/index.html >>> href: "/wrong-path", text: "Breadcrumbs"
```
```
Error: You have 1 broken links:
patterns/addresses/index.html >>> href: "passports-address-lookup-2_.gif", text: "Address lookup"
```
[Trello card](https://trello.com/c/mUZt1yNP)
=> Check broken links before start and build

.travis.yml, __tests__/mobile-navigation.test.js, __tests__/tabs.test.js, config/paths.json, jest-puppeteer.config.js, package-lock.json, package.json
This PR:
- sets up Jest and Puppeteer for integration tests
- add basic render tests for home page
- add tests for mobile navigation
- add tests for tabs
[Trello card](https://trello.com/c/mUZt1yNP)
=> Add integration tests

src/get-started.md.njk, src/whats-changed.md.njk
https://trello.com/c/29ylXFhE/1086-dac-audit-acronyms-and-abbreviations
I've also done a search of the codebase for anything that looks like an acronym (that's not GOV or UK - to avoid matching GOV.UK - it didn't work perfectly, it's picked up some within URLs etc):
```
Results for "(?!GOV|UK)(\b[A-Z]{2,}\b)" in "src/**/*.njk"
/src/get-started.md.njk:
13:  install [GOV.UK Frontend on GitHub](https://github.com/alphagov/govuk-frontend/blob/master/➡️README⬅️.md). 
34:  The Design System provides lots of new ➡️CSS⬅️ classes for styling content, meaning you shouldn’t need to write as much of your own Sass or ➡️CSS⬅️.
36:  class names follow the ["Block, Element, Modifier" (➡️BEM⬅️) naming convention](https://en.bem.info/methodology
80:  There are 2 ways to use components in the Design System. …
```
=> Expand BEM acronym on Get Started page

lib/metalsmith.js
The `metalsmith-permalinks` plugin by default [duplicates assets across folders to try and preserve relative links (!?)](https://github.com/segmentio/metalsmith-permalinks#relative-files).
> When this plugin rewrites your files to be permalinked properly, it will also duplicate sibling files so that relative links like /images/cat.gif will be preserved nicely.
This disables that feature because it’s causing all sorts of duplication within the build directory (for example, `favicon.ico` ends up in 13 different places including `/cookies/favicon.ico`, `/cookies/assets/favicon.ico`,  `/get-in-touch/favicon.ico` and `/get-in-touch/assets/favicon.ico`.
This PR reduces the number of directories and files in the build output from 299 directories, 595 files to 158 directories, 222 files.
``` …
```
=> Stop metalsmith-permalinks from duplicating files in build output

src/design-system/patterns/service-unavailable-pages/after-service-closes/index.njk, src/design-system/patterns/service-unavailable-pages/available-at-known-date/index.njk, src/design-system/patterns/service-unavailable-pages/before-service-opens/index.njk, src/design-system/patterns/service-unavailable-pages/default/index.njk, src/design-system/patterns/service-unavailable-pages/general/index.njk, src/design-system/patterns/service-unavailable-pages/index.md.njk, src/design-system/patterns/service-unavailable-pages/link-to-another-service/index.njk, src/design-system/patterns/service-unavailable-pages/no-replacement-service/index.njk, src/design-system/patterns/service-unavailable-pages/service-replaced/index.njk
This pattern was contributed by Steven Proctor
https://trello.com/c/i0DMj2OZ/1019-get-error-message-guidance-contribution-ready-to-publish
=> Add service unavailable page pattern

src/design-system/components/fieldset/address-wrapper/index.scss, src/design-system/patterns/addresses/multiple/address-wrapper.scss, src/design-system/patterns/start-pages/default/related-items.scss, src/design-system/styles/layout/grid-annotate.scss, src/design-system/styles/layout/grid-nested-annotate.scss, src/design-system/styles/layout/layout-wrappers-annotate.scss, src/design-system/styles/spacing/spacing-scale-padding/spacing-scale.scss, src/design-system/stylesheets/_example-init.scss
Consistently import only the required layers (settings, helpers and tools) whilst correct setting the assets path so that the font is loaded correctly.
This fixes an issue where the browser makes an unnecceary request for fonts at /assets/fonts (which 404s) and removes core styles being outputted  unneccesarily in additional example stylesheets.
It also fixes unparsed function calls to the `govuk-spacing` function in `design-system/styles/layout/layout-wrappers-annotate.css` and design-system/patterns/start-pages/default/related-items.css (which were previously not importing the helpers layer)
```diff
diff -r public-master/design-system/patterns/start-pages/default/related-items.css public/design-system/patterns/start-pages/default/related-items.css
1c1
< …
```
=> Fix assets path and bloat in example CSS

src/design-system/community/backlog/index.md.njk, src/design-system/community/contribute/index.md.njk, src/design-system/community/working-group/index.md.njk, src/design-system/index.njk
This PR updates the community pages and the community section for the homepage. Content has already been reviewed and approved.
=> Update community section

src/design-system/index.njk, src/design-system/roadmap.md.njk
Adds a roadmap page and links to it from the home page. Content has already been reviewed and approved.
=> Add roadmap

src/patterns/page-not-found-pages/default/index.njk, src/patterns/problem-with-the-service-pages/offline-support/index.njk, src/patterns/service-unavailable-pages/no-replacement-service/index.njk
rewrite the page not found, problem and service unavailable pages to use `<br>`'s so the phone number is part of the same paragraph as it's title.
**From:**
```
<p class="govuk-body govuk-!-margin-bottom-0">Telephone:</p>
<p class="govuk-body govuk-!-font-weight-bold">0808 157 3900</p>
```
**To:**
```
<p class="govuk-body">Telephone:><br>
<strong class="govuk-!-font-weight-bold">0808 157 3900</strong>
</p>
```
=> Update telephone number examples to use <br>s

src/components/back-link/index.md.njk, src/components/breadcrumbs/index.md.njk, src/components/button/index.md.njk, src/components/checkboxes/index.md.njk, src/components/date-input/index.md.njk, src/components/details/index.md.njk, src/components/fieldset/index.md.njk, src/components/file-upload/index.md.njk, src/components/index.md.njk, src/components/panel/index.md.njk, src/components/phase-banner/index.md.njk, src/components/radios/index.md.njk, src/components/select/index.md.njk, src/components/skip-link/index.md.njk, src/components/table/index.md.njk, src/components/tag/index.md.njk, src/components/text-input/index.md.njk, src/components/textarea/index.md.njk, src/components/warning-text/index.md.njk, src/patterns/addresses/index.md.njk, src/patterns/dates/index.md.njk, src/patterns/task-list-pages/index.md.njk, src/styles/layout/index.md.njk
- Made inline component and pattern names lower case throughout design sentence
- Fixed textarea typo in addresses pattern
=> Fix component and pattern names

src/community/backlog/index.md.njk
=> Remove inset text from the backlog

src/components/back-link/index.md.njk, src/components/breadcrumbs/index.md.njk, src/components/button/index.md.njk, src/components/checkboxes/index.md.njk, src/components/date-input/index.md.njk, src/components/details/index.md.njk, src/components/error-summary/index.md.njk, src/components/file-upload/index.md.njk, src/components/index.md.njk, src/components/panel/index.md.njk, src/components/phase-banner/index.md.njk, src/components/radios/index.md.njk, src/components/select/index.md.njk, src/components/skip-link/index.md.njk, src/components/table/index.md.njk, src/components/tag/index.md.njk, src/components/text-input/index.md.njk, src/components/textarea/index.md.njk, src/components/warning-text/index.md.njk, src/get-started/prototyping/index.md.njk, src/styles/index.md.njk
This depends on us deploying the private beta site to the public URL.
=> Update GOV.UK Prototype Kit links to point at public website

src/get-started/production/index.md.njk, src/get-started/prototyping/index.md.njk, src/get-started/updating/index.md.njk
New order:
Prototyping with the Design System
Using the Design System in production
Updating your code
=> Re-order Get Started section

src/components/date-input/default/index.njk, src/components/date-input/error/index.njk, src/components/error-message/default/index.njk, src/components/error-message/label/index.njk, src/components/panel/default/index.njk, src/components/tag/default/index.njk, src/components/warning-text/default/index.njk
Closes https://github.com/alphagov/govuk-design-system/issues/151
=> Align Macro syntax consistently

src/community/backlog/index.md.njk
=> Update Backlog page

src/community/index.md.njk, src/index.njk
=> Fix typos on homepage and community page

src/stylesheets/components/_example.scss, src/stylesheets/components/_tabs.scss, views/partials/_example.njk
=> Fix example tabs on mobile viewport

src/community/backlog/index.md.njk
=> Update status of Autocomplete component

src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk, src/styles/page-template/index.md.njk
This PR updates the custom template to use English instead of French to avoid disruption.
=> Update custom template

src/get-started/updating-your-code/index.md.njk
Simple documentation change to the "Updating your code" page.
=> Fix mq documentation from $to to $until

data/colours.json, src/styles/colour/index.md.njk
Added the white swatch to the greyscale colours.
=> Add white to the greyscale colours

src/components/text-input/input-fixed-width/index.njk
Exposes fixed width 5,4,3,2 characters in the Text input example
=> Add new fixed with classes to example

src/components/error-message/index.md.njk, src/components/error-summary/index.md.njk
Trello ticket: https://trello.com/c/4DlcEYwh/1088-dac-audit-fix-typos
=> Remove redundant indefinite article from component descriptions

package-lock.json, package.json, src/components/tabs/default/index.njk
- Updates dependency version number
- Removes fix that added margin to table component as the margin is now part of the component CSS
=> Update frontend to 1.1.1

src/components/skip-link/default/index.njk
Recommendation from the Accessibility audit
Trello ticket: https://trello.com/c/pfegkMNj/1098-dac-audit-change-wording-for-skip-link-to-be-clearer
=> Update instruction on how to access the skip link component example

__tests__/tabs.test.js, src/javascripts/components/tabs.js, src/stylesheets/components/_tabs.scss, src/stylesheets/main.scss
https://trello.com/c/w7jE1qer/1288-make-copy-and-close-links-into-buttons
=> Make close link a button

src/community/contribution-criteria/index.md.njk
Updated the Consistent criteria description based on feedback from @stevenaproctor 
The update aims to clarify that code is not a requirement for all patterns.
=> Updated Consistent criteria

package-lock.json, package.json
Update dependency following the latest release
=> Update GOV.UK Frontend to 1.3.0

src/patterns/question-pages/section-headings/index.njk
This corrects a typo at Patterns page,
"What is your Home address"
=> Correct address question is patterns

jest-puppeteer.config.js, views/partials/_header.njk
Remove the check for the search flag, thus enabling search for everyone 🎉
=> Enable the search feature

src/patterns/page-not-found-pages/default/index.njk, src/patterns/start-pages/default/index.njk
Fix for "Start page" and "Page not found page" which contain un-styled links.
=> Fix link styles

src/get-started/updating-your-code/index.md.njk
Closes https://github.com/alphagov/govuk-design-system/issues/431
=> Add gutter variable guidance to updating your code guide

src/roadmap.md.njk
=> Remove "add search" from roadmap

src/components/checkboxes/index.md.njk, src/components/date-input/index.md.njk, src/components/radios/index.md.njk, src/components/text-input/index.md.njk, src/components/textarea/index.md.njk, src/patterns/dates/index.md.njk, src/patterns/names/index.md.njk, src/patterns/national-insurance-numbers/index.md.njk, src/patterns/telephone-numbers/index.md.njk
Changed quotation marks in error message template to be “” not "" and added full stops after examples.
=> Updated error message templates

lib/metalsmith.js
=> Use https in sitemap and canonical URLs

src/components/details/index.md.njk
=> Adding "show and hide" Details component alias

src/patterns/service-unavailable-pages/before-service-opens/index.njk
Updated one of the service unavailable examples to include the word 'to'.
=> Updated example

src/components/checkboxes/index.md.njk, src/components/date-input/index.md.njk, src/components/radios/index.md.njk, src/components/text-input/index.md.njk, src/patterns/national-insurance-numbers/index.md.njk, src/patterns/page-not-found-pages/index.md.njk, src/patterns/problem-with-the-service-pages/index.md.njk, src/patterns/service-unavailable-pages/index.md.njk, src/patterns/telephone-numbers/index.md.njk
All the double quotation marks on these screens are not direct quotes so they should use single quotes.
=> Change double quotation marks to single where suitable

src/patterns/task-list-pages/index.md.njk
@amyhupe and I updated the task list research section to:
- include important updates shared in the community backlog discussion on GitHub 
- validate a new approach to formatting the research sections based on what users told us they wanted to see there
=> Task list research update

package-lock.json, package.json
=> Update GOV.UK Frontend dependency

src/components/character-count/default/index.njk, src/components/character-count/error/index.njk, src/components/character-count/index.md.njk, src/components/character-count/label-page-heading/index.njk, src/components/character-count/threshold/index.njk, src/components/character-count/word-count/index.njk, src/javascripts/govuk-frontend.js
This PR adds a newly released character-count component and associated guidance.
Guidance written by @amyhupe
=> Add character count component

.travis.yml, __tests__/mobile-navigation.test.js, __tests__/search.test.js, __tests__/tabs.test.js, config/paths.json, jest-puppeteer.config.js, package-lock.json, package.json, tasks/test-serve.js
Only perform one build on CI, avoid using Browserstack as a test server, and run it on a separate port.
See individual commits for details.
https://trello.com/c/21Tx1s3m/1510-address-flakey-tests-in-govuk-design-system
=> Improvements to the way we run tests on CI (and locally)

src/components/character-count/index.md.njk
Clarify our position on server-side character limits. This change addresses the issue raised here: https://github.com/alphagov/govuk-design-system-backlog/issues/67#issuecomment-428938065
=> Clarify guidance on server-side character limits

src/errors/404.njk
=> Add reference to the 404 page pattern from the 404 page

src/patterns/telephone-numbers/index.md.njk
=> Add an alias based on user feedback

src/patterns/passwords/index.md.njk
This PR adds a point to the research section on whether inline password validation is helpful for users creating passwords.
This update follows a review of the Passwords file in Dropbox Paper, which has since been archives.
You can [see full details of the review here](https://github.com/alphagov/govuk-design-system-backlog/issues/56#issuecomment-429848531)
=> Say research is needed on using inline validation for password creation

package-lock.json, package.json
👋 
Trello ticket: https://trello.com/c/ukkbjoSy/1330-remove-jquery-dependency
=> Remove jQuery from dependencies

src/components/character-count/default/index.njk, src/components/character-count/index.md.njk
This is following the Design System Working Group and a conversation with @amyhupe.
=> Updates to character count documentation

src/styles/images/index.md.njk
Which is the correct as alt is not a tag.
Fixes: #507
=> Replace 'alt tag' with 'alt text'

src/patterns/step-by-step-navigation/index.md.njk
We incorrectly attributed a service, as helpfully pointed out here: https://twitter.com/timpaul/status/1058095739820302338
=> Change DVLA to DVSA

src/patterns/dates/index.md.njk
Closes #606 
https://trello.com/c/9HKr8Ea8/1627-add-link-to-date-of-birth-blog-post-to-the-asking-for-dates-pattern
=> Add link to ‘asking for a date of birth’ blog post

README.md
Reverts alphagov/govuk-design-system#649
We have got enough results that we've decided to stop promoting this.
https://trello.com/c/aGO2estC/1630-remove-survey-promotion-from-repositories
=> Revert "Add note about frontend survey README"

src/get-started/labels-legends-headings/legend-h1/index.njk, src/get-started/labels-legends-headings/legend-m-s/index.njk
Added suggested changes by @nickcolley and changed id and name values. 
Fixes #661
=> Fix example checkboxes

src/components/date-input/index.md.njk
This relates to https://github.com/alphagov/govuk-design-system/pull/641/files
The new messages have been published but the original message is still on the screen. This PR removes the duplicated information.
=> Date input: error message

src/community/backlog/index.md.njk
We've created a new issue for Ethnicity - this PR adds the item and updates the 'Protected characteristics' URL
=> Update the backlog

src/components/error-message/index.md.njk, src/components/file-upload/error/index.njk, src/components/file-upload/index.md.njk, src/components/textarea/index.md.njk, src/patterns/email-addresses/index.md.njk
Worked with @Emilyallinson to come up with standard error message templates for file upload. Reviewed with @adamsilver to make sure it met HMCTS needs.
=> File upload error message templates

src/components/summary-list/index.md.njk
I'm not very happy with how I tried to explain this, would be good to catch up with someone and try and make this clearer.
=> Add explaination for visuallyHiddenText in Summary List guidance

src/patterns/payment-card-details/index.md.njk
=> Add a link to the GOV.UK Pay page on GOV.UK Performance

src/components/date-input/index.md.njk
Changed capital 'D' in 'Date input' to lower case in one instance.
=> Changed cap 'D' in 'Date input' to lower case

src/components/details/index.md.njk
Add this as part of an exercise.
=> Added more information about details, accordions and tabs.

src/styles/page-template/index.md.njk
Added corrections to line 23 in lines 24 and 25. Created two sentences from the one long sentence that had two separate points.
=> Page template styles page contains sentence that can be simplified

src/components/button/index.md.njk, src/components/button/preventDoubleClick/index.njk
This PR:
- adds guidance on `preventDoubleClick` feature
=> Add preventdoubleclick guidance

src/components/error-message/custom-prefix/index.njk, src/components/error-message/index.md.njk
Do not merge until the Design System has been updated to GOV.UK Frontend 2.8.0.
=> Add guidance on error message visually hidden text

src/get-started/extending-and-modifying-components/index.md.njk, views/partials/_mobile-navigation.njk, views/partials/_subnav.njk
See the fully rendered page here: https://deploy-preview-829--govuk-design-system-preview.netlify.com/get-started/extending-and-modifying-components/
Resolves https://github.com/alphagov/govuk-design-system/issues/810
=> Add guidance for extending and modifying components

src/components/table/column-widths-custom-classes/column-width-custom-classes.scss, src/components/table/column-widths-custom-classes/index.njk, src/components/table/index.md.njk
=> Align custom class example with new guidance

src/components/header/with-service-name-and-navigation/index.njk, src/components/header/with-service-name/index.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/836
The larger issue is reported here: https://github.com/alphagov/govuk-design-system/issues/848
=> Fix broken in-page anchor for header component

src/accessibility.md.njk, views/partials/_footer.njk
Adds an Accessibility page with messaging about WCAG 2.1
=> Add accessibility page

src/patterns/check-answers/default/index.njk
This PR fixes issue #906 from the DAC report
=> Update example text in Check answers pattern

src/accessibility.md.njk
This PR updates the date for the release of V3 from June to July 2019 to reflect our current estimate.
=> Update date for v3 release

src/index.njk, src/roadmap.md.njk
We now link directly to the roadmap on GitHub.
=> Update Roadmap section

src/styles/spacing/spacing-scale-margin/index.njk
Adds the margin override level to examples.
=> Demonstrate the margin level applied to examples

src/components/panel/index.md.njk, src/patterns/confirmation-pages/index.md.njk
Add aliases to make the pattern and component easier to find
=> Make confirmation pages and the panel component easier to find

bin/deploy-travis
=> Fix path to smoke-test script

src/components/back-link/index.md.njk, src/components/breadcrumbs/index.md.njk, src/components/button/index.md.njk, src/components/date-input/index.md.njk, src/components/details/index.md.njk, src/components/error-summary/index.md.njk, src/components/fieldset/index.md.njk, src/components/footer/index.md.njk, src/components/header/index.md.njk, src/components/inset-text/index.md.njk, src/components/panel/index.md.njk, src/components/phase-banner/index.md.njk, src/components/skip-link/index.md.njk, src/components/table/index.md.njk, src/components/tag/index.md.njk, src/components/text-input/index.md.njk, src/components/textarea/index.md.njk, src/components/warning-text/index.md.njk, src/patterns/addresses/index.md.njk, src/patterns/confirm-an-email-address/index.md.njk, src/patterns/create-a-username/index.md.njk, src/patterns/create-accounts/index.md.njk, src/patterns/email-addresses/index.md.njk, src/patterns/national-insurance-numbers/index.md.njk, src/patterns/question-pages/index.md.njk, src/patterns/start-pages/index.md.njk, src/stylesheets/components/_contact-panel.scss, views/layouts/layout-pane.njk, views/partials/_contact-panel.njk
This PR:
- adds guidance on how to propose content changes (open PRs) using GitHub to the Community section
- includes a new design of the "Get in touch" panel at the bottom of the pages in the Design System
- adds a "Help improve this page" section to the bottom of style, component and pattern changes with links to the backlog, the markdown file and the new guide on proposing changes
- removes empty research sections from component and pattern pages
=> Update contact panel

src/community/propose-a-content-change-using-github/index.md.njk
This pull request updates guidance on how to write a commit message and description to make clearer that the commit should convey the intent behind a PR, rather than describing the change itself.
=> Clarify guidance on writing commits

package-lock.json, package.json
We'll need this to implement the focus style updates correctly.
=> Update to the most recent GOV.UK Frontend pre-release

src/components/accordion/index.md.njk
The hover colour issue will no longer be applicable with v3 version of component
=> Remove redundant point from accordion docs

src/styles/page-template/index.md.njk
=> Specify language to improve syntax highlighting

package-lock.json, package.json
We have been running the pre-release to make it easier to deploy.
=> Update website to GOV.UK Frontend 3.0.0 stable

src/styles/typography/list-bullet/index.njk
Per #1013, add a lead-in line to the example.
Closes #1013
=> Add lead in line

.github/issue_template.md, .github/pull_request_template.md
Reverts alphagov/govuk-design-system#1020
=> Remove issue and pull request templates

src/components/date-input/date-of-birth/index.njk
=> Use correct width for year in dob example

package-lock.json, package.json
=> Update to use accessible-autocomplete v2.0.0

src/components/details/index.md.njk
https://twitter.com/hashtag/showyhideything
=> Add 'ShowyHideyThing' as an alias for 'details' component

src/accessibility.md.njk
This PR adds the accessibility statement to the accessibility page in the Design System
=> Add accessibility statement

src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk, src/styles/page-template/index.md.njk
We'll probably need to tweak the wording here but I've taken an initial stab at it.
Fixes https://github.com/alphagov/govuk-frontend/issues/1289
=> Document how to overwrite the Open Graph image path

src/community/backlog/index.md.njk
These are both currently being worked on
=> Update backlog status of Contact a department and Modal

package-lock.json, package.json
=> Update to GOV.UK Frontend v3.4.0

src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk, src/styles/page-template/index.md.njk
Co-authored with @m-green 
Blocked until https://github.com/alphagov/govuk-frontend/pull/1626 is released
Fixes https://github.com/alphagov/govuk-design-system/issues/1075
=> Document how to add a class to the template container

src/index.njk
Thanks to Joe L for spotting this.
=> Fix typo linking to the team page

src/components/error-summary/full-page-example/index.njk, src/components/error-summary/linking-multiple-fields/index.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/1061
=> Fix error summary date input example using incorrect name

src/patterns/contact-a-department-or-service-team/expanding-contact-information/index.njk, src/patterns/contact-a-department-or-service-team/index.md.njk, src/patterns/contact-a-department-or-service-team/inset-contact-information/index.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/1102
Thanks Colin O. for letting me know about this.
=> Fix contact a department or service team nunjucks tab

src/design-system-team.md.njk
=> Update team page

src/patterns/step-by-step-navigation/index.md.njk
Update step by step guidance as per [issue #1132](https://github.com/alphagov/govuk-design-system/issues/1132)
=> Update step by step pattern

package-lock.json, package.json
=> Update to GOV.UK Frontend v3.5.0

package-lock.json, package.json
v2.0.2 fixes a bug that can affect the way users can click results in the dropdown.
Fixes #1148.
=> Update to accessible-autocomplete v2.0.2

src/design-system-team.md.njk
=> Add Chris to team

docs/logs.md
While we think that fingerprinting the IP addresses deidentified them, we don't have a strong need for this data so we want to remove them entirely to remove any risk of storing personal information.
To do this I have:
1. Stopped assigning the matched IP address to a variable `x_forwarded_for:\"%{IP:[access][user_ip]}, %{IP}, %{IP}\"` -> `x_forwarded_for:\"%{IP}, %{IP}, %{IP}\"`
2. Removed the fingerprinting as there is no IP to fingerprint.
If this is accepted I will update this filter in Logit.io and merge when I've confirmed it's working.
=> Drop IP addresses from kibana output entirely

src/components/text-input/index.md.njk
Added link to @hannalaakso's blog post about input type for numbers.
Fixes https://github.com/alphagov/govuk-design-system/issues/1177
=> Add link to blog post about numbers

__tests__/search.test.js, docs/logs.md, lib/colours.js
I ran a typo checker through the codebase & spotted 3 little typos in comments. 
This updates them to what I think they should be :)
=> Correcting 3 typos

src/components/error-message/index.md.njk, src/components/error-summary/index.md.njk, src/patterns/validation/index.md.njk
This PR creates the new validation pattern and makes minor changes to two linked pages
=> Create new validation pattern

src/styles/page-template/custom/code.njk, src/styles/page-template/custom/index.njk
I think this was referencing a class that was removed.
=> Fix custom template example width container class

src/design-system-team.md.njk
=> Update Design System team page

src/components/table/index.md.njk
=> Minor typo fix

src/errors/404.njk
As discussed in https://github.com/alphagov/govuk-frontend-docs/pull/33#discussion_r409660120, "404" in the title is pretty jargony.
=> Improve 404 page title

src/components/tag/index.md.njk
The examples given (urgent, finished, waiting on, sent) are all adjectives or adjectival phrases, not nouns
=> Describe words used in tags as adjectives, not nouns

src/components/text-input/index.md.njk
Relates to https://github.com/alphagov/govuk-design-system/pull/1217/files
=> Fix incorrect error message examples

src/styles/typography/index.md.njk, src/styles/typography/link-opening-in-new-tab/index.njk, views/partials/_example.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/935.
=> Add guidance on external links and opening links in a new tab

src/styles/typography/index.md.njk
Tidy up text, including removing a negative contraction
=> Tidy up text on opening links in a new tab

package-lock.json, package.json
=> Update to GOV.UK Frontend v3.7.0

src/design-system-team.md.njk
Resolves https://github.com/alphagov/govuk-design-system/issues/1300
=> Add Vanita to team members list

src/styles/layout/index.md.njk
=> Document display override classes

src/community/backlog/index.md.njk, src/community/contribution-criteria/index.md.njk, src/community/design-system-working-group/index.md.njk, src/community/develop-a-component-or-pattern/index.md.njk, src/community/index.md.njk, src/community/propose-a-component-or-pattern/index.md.njk, src/community/propose-a-content-change-using-github/index.md.njk, src/community/resources-and-tools/index.md.njk
Closes: https://github.com/alphagov/govuk-design-system/issues/1282
=> Add community resources page

package-lock.json, package.json
=> Update GOV.UK Frontend to v3.8.0

package-lock.json, package.json
=> Update GOV.UK Frontend to v3.8.1

src/patterns/gender-or-sex/index.md.njk
Hi 👋 - Just a tiny change I'd suggest to clarify, as a deed poll is not required to change title, as any common non-protected title can be used freely by anyone. These aren't part of a person's name, and people can freely switch between them at will or use any title they wish - with or without including them on a deed poll. 
P.S. thank you for including this important info on gov.uk, seeing this page made me feel included! ✨
=> Added Mx, removed title deed poll

package-lock.json, package.json
Closes https://github.com/alphagov/govuk-design-system/issues/1347
=> Update GOV.UK Frontend to 3.9.0

src/community/resources-and-tools/index.md.njk
Contribution from @camnomis: https://github.com/alphagov/govuk-design-system/pull/1312
=> Add Adobe XD wireframes

src/design-system-team.md.njk
Have removed Mark's name and added my own.
=> Update team page to say Eoin is now tech writer

src/patterns/bank-details/index.md.njk
Based on feedback from user and guidance here: slashes are valid: https://identityandfraud.uk.experian.com/documentation/bank-wizard-api-guide-j12f/subsystems/default/country_details/roll_number_validation.htm
=> Update error message for bank details pattern

package-lock.json, package.json
Update `govuk-frontend` to `3.10.0`
=> Update govuk-frontend to 3.10.0

package-lock.json, package.json
Closes https://github.com/alphagov/govuk-design-system/issues/1416
=> Update the design system to GOVUK Frontend v3.10.1

src/components/notification-banner/success/code.njk, src/components/notification-banner/success/index.njk
I've 'hopefully' added a two line success example to the guidance to answer [this open issue](https://github.com/alphagov/govuk-design-system/issues/1407)
=> Add success example with body copy to the guidance

src/components/text-input/index.md.njk
Brilliant addition! Hope you don't mind a small suggestion from a big fan ;)
This PR tweaks the copy to acknowledge that not all screen reader users are blind or visually-impaired and so _may_ see the input prefix or suffix.
=> Remove screen reader use assumption

src/accessibility.md.njk
Changes date to merge date of last PR that changed Accessibility page.
We forgot to change the "last updated/reviewed" date at that time.
=> Update review date for DS Accessibility Statement

src/design-system-team.md.njk
Adding in Imran and his role into the team page.
=> Adding Imran to the Design System page

src/design-system-team.md.njk
Added myself Calvin to the team member list.
=> Update Design System team page to add Calvin Lau

src/patterns/validation/index.md.njk
Original wording was unclear that you always validate server side.
=> Update validation wording

src/styles/page-template/index.md.njk
Also corrected typo ('contain' -> 'container').
Please do not merge till we've released cookie banner.
=> Update page template to mention cookie banner

src/patterns/step-by-step-navigation/index.md.njk
Style guide says to avoid negative contractions.
Many users find them hard to read.
=> Fix negative contraction in Patterns content

src/components/back-link/index.md.njk, src/components/button/index.md.njk, src/components/text-input/index.md.njk
Style guide advice: use single quotes unless quoting direct speech.
=> Fix punctuation in Components guidance

src/patterns/validation/index.md.njk
Made some small tweaks to:
- clarify the text about useful error messages
- avoid using parentheses within parentheses
=> Fix minor content issues in validation pattern

src/components/cookie-banner/index.md.njk, src/patterns/cookies-page/index.md.njk
=> Add search aliases for cookie banner, cookie page

src/components/text-input/index.md.njk
This explanation was provided in the backlog, but is not in the guidance.
=> Explain why prefixes and suffixes are outside inputs

src/components/notification-banner/index.md.njk
This corrects a wording change I missed in the last merged pull request.
=> fix: change 'to' to 'in'

src/community/design-system-working-group/index.md.njk
To test on preview page and for content review.
=> Update to Working group page to recruit new members

src/components/text-input/index.md.njk
Based on backlog conversation here: https://github.com/alphagov/govuk-design-system-backlog/issues/51#issuecomment-496411901
=> Explain how fixed widths are calculated

src/components/details/index.md.njk
Based on a review of the backlog
=> Add research section to the details component

src/community/design-system-working-group/index.md.njk
To publish on 5pm on 5 March 2021
=> End of working group recruitment

src/community/blogs-talks-podcasts/index.md.njk
1. Link to video on "Designing the service behind the GOV.UK Design System"
2. Link to video about 'Building Community Behind GOV.UK Design System"
=> Add 2 links to videos

src/community/resources-and-tools/index.md.njk
Walkthrough for importing GDS component library into .NET project
Instructions on how to compile the sass at runtime using gulp
=> Add guide for importing GDS into .NET Project

package-lock.json, package.json
=> Update GOV.UK Frontend to v3.12.0

src/styles/typography/index.md.njk, src/styles/typography/inverse.scss, src/styles/typography/link-no-underline/index.njk, src/styles/typography/link-on-dark-background/index.njk
Fixes https://github.com/alphagov/govuk-design-system/issues/1603
=> Updates to guidance for new link modifiers

src/privacy-policy.md.njk, views/partials/_footer.njk
Replaces entire privacy policy with new version, as instructed by GDS privacy advisor.
=> Update privacy policy in line with advisor

package-lock.json, package.json
Bumps [metalsmith-in-place](https://github.com/metalsmith/metalsmith-in-place)
- [Changelog](https://github.com/metalsmith/metalsmith-in-place/blob/master/CHANGELOG.md)
- [Commits](https://github.com/metalsmith/metalsmith-in-place/compare/v4.4.0...v4.4.2)
=> Bump metalsmith-in-place from 4.4.0 to 4.4.2

src/design-system-team.md.njk
=> Add new team member

docs/deployment/production.md
=> Fix a typo in deployment docs

__tests__/cookie-functions.test.js, src/javascripts/application.js, src/javascripts/components/analytics.js, src/javascripts/cookie-functions.js
Closes https://github.com/alphagov/govuk-design-system/issues/1616
Adds GTM snippet to the design system site. This should only run once a user has consented to cookies, so it's safe to merge and deploy now as we don't give users a way of doing this yet.
=> Add GTM snippet

src/design-system-team.md.njk
Change hyphen to en dash before Content Designer
=> Fix punctuation mark error

README.md
Following [agreed comms](https://docs.google.com/document/d/1DiKycAgLAjeab8ThjIlhZkUISQ2qZ8w1tcZ6jVCyIzE/edit?ts=60c35c5f#heading=h.85wz5jtozgbc).
=> Add government frontend survey notice to README

src/patterns/validation/index.md.njk
Resolves #1450 – more information on the issue. 
Added guidance with a slightly wider scope, in response to the comments on the issue.
- Check the new guidance covers the points raised in the issue
- Check it doesn't duplicate content elsewhere on the page
- Check it's in the right place on the page
- Check style – first draft feels a bit verbose
=> Add guidance on when to ignore whitespace in form inputs

src/patterns/cookies-page/index.md.njk
Linked to 'button' rather than 'cookie banner'
=> Fix incorrect link

src/privacy-policy.md.njk
Minor update to privacy policy, as requested by GDS privacy team.
=> Minor update from privacy team

src/community/resources-and-tools/index.md.njk
The sketch kit has moved to DWP's repo
=> Update sketch kit link

src/accessibility.md.njk
This PR updates our [accessibility statement](https://design-system.service.gov.uk/accessibility/) with the new date for fixing our accordion issue ([see issue for iteration details](https://github.com/alphagov/govuk-design-system/issues/1706)).
=> Add accordion fix date to accessibility statement

src/styles/spacing/index.md.njk, src/stylesheets/main.scss
=> Tidy spacing guidance, and document how to do negative spacing.

__tests__/accessiblity_audit.test.js, src/stylesheets/components/_tag.scss, src/stylesheets/main.scss, views/partials/_banner.njk
Because the GOV.UK Design System is now officially LIVE
=> Remove beta phase banner from production

src/community/blogs-talks-podcasts/index.md.njk
Adds 2 blog posts to the Blog posts, videos and podcasts page.
=> Add blog posts on none checkbox and conditional reveals

src/components/accordion/index.md.njk
Add link to backlog post in Accordion guidance.
=> Add link to backlog summary comment

README.md
Fixes [#1287](https://github.com/alphagov/govuk-design-system/issues/1287).
PR raised because [users have pointed out that the Readme currently lacks info about the repo's purpose](https://github.com/alphagov/govuk-frontend/issues/1833#issuecomment-642681664).
=> Update Readme to say what repo contains

src/design-system-team.md.njk
David Cox has joined the team! This is my first pull request for this repo.
=> Add David Cox to the design system team page

src/design-system-team.md.njk
Have updated the list of team members to include our new team member Katrina
=> Add Katrina to the team page on Design System website

src/design-system-team.md.njk
Thanks to @vanitabarrett for pointing me towards this.
It's lovely to be part of the team.
=> Added Natalie to the team list.

docs/deployment/production.md
The GitHub Actions were refactored in 6f04855, when `ci.yaml` was split into `test.yaml` and `deploy.yaml`.
We also switched to using a concurrency group (rather than cancelling existing deploys) in 336a93c.
Update the deployment docs to reflect these changes and the current state of our GitHub Actions workflows.
=> Update deployment docs

src/design-system-team.md.njk
Add Ciandelle Scollan as an interaction designer in the design system team
=> added Ciandelle Scollan to list

src/design-system-team.md.njk
=> Added Kimberly Grey to the team list

src/components/button/index.md.njk
=> Update links to start using a service pattern

src/community/blogs-talks-podcasts/index.md.njk
Adds latest blog posts from Design System team and community members
=> Add latest blog posts April 2022

src/patterns/national-insurance-numbers/index.md.njk
following on from https://github.com/alphagov/govuk-design-system/pull/2175 being closed additional text added.
cc @calvin-lau-sig7
=> adding format guidance for National Insurance number

src/patterns/validation/index.md.njk
Fixes [#1557](https://github.com/alphagov/govuk-design-system/issues/1557).
Updates our 'Recover from validations error' pattern.
Some users have reported that the current guidance lacks this info.
=> Explain issues with client side validation

src/community/roadmap/index.md.njk, views/partials/_whats-new.njk
Includes changes to:
- What's New section
- Roadmap page
=> Update Design System website for v4.1.0

src/components/footer/index.md.njk
This proposed update:
- adds links to relevant information on privacy notices, cookie pages and accessibility statements
- clarifies copyright and licensing information
Related issues:
https://github.com/alphagov/govuk-design-system/issues/1225
https://github.com/alphagov/govuk-design-system/issues/1306
=> Update guidance on footer component

package-lock.json, src/components/select/index.md.njk, src/components/select/with-hint/index.njk
=> add a hint to the select to help users understand the options

src/community/roadmap/index.md.njk, views/partials/_whats-new.njk
I've removed some earlier stuff in the "recently shipped" section, because we're quite a few releases away from that now.
Not sure if we need to make any other roadmap changes?
=> Update what's new and roadmap for 4.2.0

src/design-system-team.md.njk
=> Update team member

src/styles/images/index.md.njk
Minor change to reduce the linked text to improve readability and usability.
=> Adjust link text to GOV.UK image guidance

src/components/error-message/index.md.njk
The ethnic groups pattern was archived in #1582.
=> Remove link to archived ethnic groups pattern

src/community/blogs-talks-podcasts/index.md.njk
Allows more options to access it as I've made it into a blog post too.
=> Update link to my talk for more accessible blog

package-lock.json, package.json
=> Update to GOV.UK Frontend v4.3.1

views/layouts/layout-sitemap.njk
Raised by AJ on Cross GOV Slack.
=> Improve heading hierarchy on sitemap page.

package-lock.json, package.json
=> Update to use govuk-frontend 4.4.0

src/get-started/updating-your-code/index.md.njk
Updating these links to send users to the issue template page.
=> Update links to Github issue creation

src/community/index.md.njk
Makes 2 minor corrections that got missed before we published the community landing page.
=> Correct typo and update on DSDay

src/patterns/bank-details/index.md.njk
Pay does not offer direct debits
=> Remove reference to GOV.UK Pay's direct debit

src/community/blogs-talks-podcasts/index.md.njk, src/styles/typography/index.md.njk
Add links to promote the recently-published Typography blog post.
=> Add links to typography blog

package-lock.json, package.json
Fixes https://github.com/alphagov/govuk-design-system/issues/2487
=> Update govuk-frontend to v4.4.1

package-lock.json
Somehow I missed bumping these in #2503.
This is the result of running `npm install` on the `main` branch.
=> [Fix] Update package-lock

src/components/select/index.md
Adding additional content to research section of the 'select' page to clarify the issues with selects [#2447](https://github.com/alphagov/govuk-design-system/issues/2447)
=> Add to research section to help clarify the issues with selects

src/components/checkboxes/index.md
Fixes https://github.com/alphagov/govuk-design-system/issues/2604
=> Correct issue link in research section of checkboxes page

src/community/roadmap/index.md
=> Update link to sprint board on roadmap page

package-lock.json, package.json
Update the Design System website to use `govuk-frontend@4.6.0`
=> Update to `govuk-frontend@4.6.0`

src/patterns/check-answers/index.md
This may need further review because ideally we don't ask optional fields - and for some multiple input fields like addresses it doesn't make sense to playback the empty fields - but it would be good to have standard
=> Add guidance about optional questions

src/community/index.md
Adds link to the YouTube playlist for the 2 DSDay 2022 videos on the Community section of the website
=> Add links to DSDay 2022 YouTube videos

src/components/exit-this-page/default/index.njk, src/components/exit-this-page/index.md, src/components/exit-this-page/secondary-link/index.njk, src/patterns/exit-a-page-quickly/index.md, src/patterns/exit-a-page-quickly/safety-content-example/index.njk
Pull request to add guidance for Exit this page. Currently being used to show a Netlify preview to share with the community for consultation.
=> Add guidance for Exit this page component and pattern

src/community/design-system-day-2022/index.md, src/community/design-system-day/index.md
Run prettier on the new DS day pages to fix some tiny styling issues
=> Fix styling issues in community pages

src/patterns/passwords/index.md
Fixes a spacing issue from https://github.com/alphagov/govuk-design-system/pull/2861 to unblock the deployment
=> Run `prettier --write` on “Passwords” pattern page

src/community/design-system-day/index.md
The agenda is almost complete, we're just waiting to confirm the last few speakers. But we can still share what talks and sessions will be happening, to whet people's appetite.
=> Add a taster of the things to come

src/community/design-system-day/index.md
Have added the draft agenda to the page on the design system site.
=> Add agenda and timings

src/community/share-research-findings/index.md
I noticed that this one wasn't marked up properly, so this is a wee PR to fix it.
=> Little fix of an unordered list

src/community/design-system-day/index.md, src/community/design-system-day/session-information.md, src/community/design-system-day/speaker-information.md, src/community/resources-and-tools/index.md, src/community/share-research-findings/index.md
This PR is a quick `prettier --write` run to unblock `npm run lint` again locally
To automatically fix files manually you can run:
```console
npm run lint:prettier -- --write
```
We temporarily ignored [failing Prettier checks](https://github.com/alphagov/govuk-design-system/actions/runs/6406668262/job/17391808898) in https://github.com/alphagov/govuk-design-system/pull/3070 until we pick up:
* https://github.com/alphagov/govuk-design-system/issues/3047
=> Run `prettier --write` to format Markdown etc

src/community/design-system-day/speaker-information.md
Content has been reviewed outside of PR
=> Add missing DS Day 23 speaker bios

src/community/design-system-day/session-information.md
This talk has been rescheduled to 11:45am to 12:30pm.
=> Fix Vicky Teinaki day 2 talk time

src/community/design-system-day/session-information.md
This session has been cancelled at short notice as the presenter is no longer available.
=> Cancel "Leading the system" session

lib/metalsmith.js, src/styles/page-template/custom/code.njk, src/styles/page-template/default/code.njk, src/stylesheets/example.scss, src/stylesheets/main.scss, views/layouts/layout-example.njk
Closes: https://github.com/alphagov/govuk-design-system/issues/3172
=> Update examples with `govuk-frontend.min.css`

src/community/design-system-day-2023/index.md
Add content about day 1 video recordings now being available.
=> Add content about day 1 videos

src/community/design-system-day-2023/session-information.md
Add video recordings of each session on day 1 of Design System Day
=> Add day 1 videos

src/design-system-team.md
Recognise some recent important changes to the team on the team page 🎉
=> Update the team page

netlify.toml
Closes #1678 and partially addresses #3322.
=> Proxy requests for security.txt

src/community/roadmap/index.md, views/partials/_whats-new.njk
Preview:
👉🏻 [What's New (Homepage)](https://deploy-preview-3358--govuk-design-system-preview.netlify.app/)
👉🏻 [Roadmap](https://deploy-preview-3358--govuk-design-system-preview.netlify.app/community/roadmap/)
=> Update what's new and roadmap for v5.0.0

src/community/blogs-talks-podcasts/index.md
Adds 2 new entries to the Blog posts, videos and podcasts page.
- WCAG 2.2 launch
- Franki's task list collab
=> Update blogs page for Jan 2024

src/community/index.md
Update the community landing page to reflect the new monthly call.
=> Update website for monthly catch-up call

src/design-system-team.md
=> Remove Steve from the team page 😢

src/components/text-input/index.md
Raised to try and address comments in the #3436 issue.
=> Link to asking complex questions

src/components/index.md
Making some minor content changes to the introduction of the components section.
=> Update Components introduction

src/styles/links/index.md
As pointed out by [this comment](https://github.com/alphagov/govuk-design-system/pull/3722#issuecomment-2032556456)
=> Use correct link on links page

src/design-system-team.md
Add 'Patrick Cartlidge - Frontend Developer' to `design-system-team.md`.
Patrick Cartlidge (me) has recently joined the team. Addresses issue #3728.
=> Add 'Patrick Cartlidge' to 'design-system-team.md'

config/navigation.js, config/tsconfig.json, tsconfig.json
See individual commits for details 👀
=> Allow config files to be type-checked and tidy up outdated config

src/styles/font-override-classes/index.md
Draft some guidance around what tabular numbers are and what uses they're suited for, using the context of a new override class. 
Aiming to resolve https://github.com/alphagov/govuk-design-system/issues/1233. 
I didn't add a live example as it would need to be fairly different from the other examples on the page to effectively demonstrate how tabular numbers look and work. That remains an option, but I opted not to sink that time in if we don't think it's a good idea. 
I also considered linking to components that already make use of tabular numbers (Table and Character Count) in place of an inline example, but figured this could be too much of a distraction.
=> Add tabular number override class guidance

src/accessibility/accessibility-strategy/index.md
Reported by a user. The old URL now 404s.
=> Fix link in accessibility strategy to 7 principals of design

src/components/password-input/index.md
Made a clearer description of how to write labels and toggles when showing one or more password inputs.
=> Update 'how it works' for Password input

src/community/design-system-day-2024/index.md, src/community/design-system-day-2024/session-information.md, src/community/design-system-day-2024/speaker-information.md
=> amended bios and session info

src/community/design-system-day-2024/index.md, src/community/design-system-day-2024/session-information.md, src/community/design-system-day-2024/speaker-information.md
can I get you both to cast an eye over this please - it's holding information only at the moment until we have something more concrete
=> Dsday24 speakers

package-lock.json, src/accessibility/wcag-2.2/index.md, src/components/footer/index.md, src/components/header/index.md, src/components/service-navigation/index.md, src/components/service-navigation/with-service-name-and-navigation/index.njk, src/components/service-navigation/with-service-name/index.njk, src/patterns/navigate-a-service/index.md
This is the updated guidance for the 'agile version' of our Navigation contribution
=> Navigation contribution Sept 2024

src/community/roadmap/index.md, views/partials/_whats-new.njk
Adds comms to the guidance website
=> Add navigation comms to roadmap and whats new

src/community/design-system-day-2024/index.md
Add details of face to face event, and plans for next event.
=> Update Design System Day 2024 page

src/patterns/exit-a-page-quickly/index.md
Updated link as current link goes to quite a bad 404 page
=> chore: remove deep link on exit a page quickly pattern for cmg

views/partials/_contact-panel.njk
One minor change to our pre-footer, part of #4267
=> Update link to 'propose change' in the pre-footer

src/patterns/gender-or-sex/index.md
This PR will resolve [Edit 'Gender or sex' pattern to avoid discouraging services to ask their users for equality information](https://github.com/alphagov/govuk-design-system/issues/4289)
=> Add Equality Act 2010 reason to collect gender or sex data

src/patterns/dates/default/index.njk
Suggested by a user on support 10 Dec 2024
=> Make the date example more recent

.github/workflows/test.yaml
We're having some issues with Ubuntu 24, so fixing to 22 while we figure 'em out
=> Fix runner to Ubuntu 22

package-lock.json, package.json, src/community/roadmap/index.md, views/partials/_whats-new.njk
- Update What's New section
- Update Roadmap
=> Update site for GOV.UK Frontend 5.8.0

.github/ISSUE_TEMPLATE/cycle-brief.md
- update name of template
- remove tasklist codeblocks
- remove roles and add 'Squad'
=> Update cycle brief template

src/components/cookie-banner/index.md
=> Fix stray backticks in cookie banner guidance

src/components/cookie-banner/index.md, src/components/footer/index.md, src/components/header/index.md, src/components/service-navigation/index.md, src/get-started/index.md, src/styles/page-template/index.md
Includes content changes being worked on across https://github.com/alphagov/govuk-design-system/issues/4729.
=> Brand website updates for 25 June

src/design-system-team.md
=> Remove Ciandelle from the team page 😢

package-lock.json, package.json
=> Bump govuk-frontend to 5.11.2
